FAForever/fa

changelog.md, units/XSA0202/XSA0202_unit.bp
T2 Sera Bomber was missing BOMBER category. Adding this enables hotkeys to
distinguish between fighters and fighterbombers.
=> Add BOMBER category to Notha

changelog.md, effects/cartographic.fx
Before this, if a map file doesn't contain cartographic colours, the preview
will not be generated.
Since the shaders are not being passed the water height level, the cartographic
preview cannot include the water level of the map, however.
There's a discussion thread on the forums about patching the engine for this
[here](http://forums.faforever.com/forums/viewtopic.php?f=45&t=9141).
=> Always generate cartographic view

lua/ui/lobby/lobby.lua
This stops "random" being a skin after the game has started, causing you to get the proper factional UI for the faction you actually ended up being.
This also obviates the need to import a ton more resources to fix the whole default/uef skin problem.
=> Switch in-game skin to the real factional skin on game start

changelog.md, lua/ui/dialogs/hotstats.lua, lua/ui/dialogs/score.lua, lua/ui/game/gameresult.lua
Fixes the gist of what #302 was about:
```
- Score viewing:
- Score button no longer exits the game forcefully
- Viewing of score screen when scores were set to off is re-enabled, but the
statistics are not particularly useful
```
=> Improve score UI

lua/ui/lobby/lobby.lua
Fixes this error from #315 
warning: Error running DataReceived script in CScriptObject at 11024960: ...ged alliance\gamedata\mohodata.scd\lua\maui\text.lua(170): bad argument #1 to gfind' (string expected, got table) stack traceback: [C]: in functiongfind'
...ged alliance\gamedata\mohodata.scd\lua\maui\text.lua(170): in function WrapText' ...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(3999): in functionAddChatText'
...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(1400): in function SendSystemMessage' ...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(2259): in functionHostTryAddObserver'
...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(2124): in function `HostTryAddPlayer'
...ta\faforever\gamedata\lua.nx2\lua\ui\lobby\lobby.lua(4385): in function …
=> Don't send table to function expecting string

lua/ui/controls/radiobutton.lua, lua/ui/game/chat.lua, lua/ui/lobby/ModsManager.lua, lua/ui/lobby/lobby.lua, lua/ui/uiutil.lua
Some GPG code we're not currently modifying was failing to create checkboxes because it was relying on the old naming convention.
The old convention named checkboxes "radio", which seems irritating. Here, we neatly dodge this problem by entirely ignoring the parameter GPG's calls to CreateCheckboxStd gives us. They always want to create a checkbox with the default textures, so let's rename our fancy checkbox-creating method to something else and turn the one GPG's untouched code uses into a single-argument default-checkboxes-only one.
=> Bring back vanishing checkboxes

lua/ui/game/gamemain.lua
Prefetch is currently only used for UI textures, these should be loaded as fast as possible to prevent stutter. Currently the prefetcher pauses for 3 seconds every time there is disk load (which is constantly due to replay / log saving).
This patch makes the asset load much faster into memory.
The prefetcher never release memory anyway so this won't change total memory usage, it just makes sure the textures end up faster into memory.
=> Making UI prefetch more aggressive

lua/ui/uiutil.lua
An exact rehash of 351eb17c64e0ecdd0f105d2b0c4f394f06e3054c.
These functions are unused in our code and GPG's code. The old commit was backed out due to concerns about breaking mods.
I have since downloaded the entire mod database and grepped it for the names of each of these functions. No results were found.
Since these functions are both unused and represent obsolete, suboptimal ways of doing what they do (such as making an ItemList into a textbox, instead of just using an actual textbox), I am confident it is now safe to remove them.
=> Delete unused UIUtil functions

lua/EnhancedLobby.lua, lua/system/utils.lua, lua/ui/dialogs/mapselect.lua, lua/ui/lobby/lobby.lua
The random map button in the lobby used to take about 3 seconds to do its job, as it would load the "game options" menu and click the button...
Here, we make that less insane. A random map is selected that has enough slots to hold the players currently in the game, in a sensible amount of time.
The random map button in the game options menu is simplified to simply select a random element from the current map list.
The logic for filtering maps is refactored to use a functional filter pattern, for noticeable performance win.
=> Simplify random map logic

lua/ui/lobby/lobby.lua
A feeble attempt at reducing some lobby lag 
* Only send game rules to the joining player
* Send benchmark results in one batch
* Support for sending multiple game options 
* Support for sending multiple player options
* Cache result of CPU benchmark
Some more info in the commit messages
=> Lobby speedup

lua/sim/Unit.lua, lua/sim/tasks/EnhanceTask.lua
Fixed a bug with engineers workitem not resetting when an upgrade unit
finished.  Also some cleanup and protection against recursive calls to
UpdateAssisters()
Fixes #521
=> Consumption bugfix

lua/ScenarioFramework.lua, lua/sim/Unit.lua
Seems like the first attempt to fix pose errors didn't work.
More testing of the error reveals that it's due to some form of
garbage collection of wrecks. When there's been enough of unit deaths on
the field it starts to remove random wrecks.
This results in wrecks sometimes getting removed in the same tick as they are
created. This causes the error with TryCopyPose() when it tries to set a
pose of a deleted wreck.
It's unnecessary to copy pose of units that didn't animate at death so
this fix at least reduce the amount of spam in log
I've not found out a way to raise the bar of the garbage collect. ~~Maybe we
should implement our own GC of wrecks and delete the oldest ones instead,
this would prevent newly created wrecks to insta-disappear~~ (see below)
=> Fix garbage collection of wrecks

lua/defaultunits.lua
Fixes personal shield ACUs not playing the damage warning. Damage is passed from unit.lua's OnDamage() directly to ApplyDamage for personal shields. shield.lua's OnDamage is now unused in most cases.
=> Tell ACU shield not to go through unused OnDamage

lua/ui/uiutil.lua
This should be seen as a quickfix to getting legacy checkbox code to work
(diplomacy / debug window etc).
We should probably decide on a naming convention for the UI-textures, at
the moment the modded FAF ones differ from original.
Fixes #669
=> Fix to make legacy checkbox code work

changelog.md, lua/sim/Unit.lua
When assisting a damaged unit the current engine behavior is to prioritize
repair, for instance repairing the ACU instead of helping it build a pd.
With this change, if you want to repair a unit over assisting a builder you
need to give explicit repair command.
There are known minor quirks with this fix so the engineers don't behave
exactly as if they assisted an undamaged builder (if not in build range they
walk near the building before starting to assist). Still way better than the current behavior.
*Got this idea while messing around with the "Prevent assist on upgrading factories" #640  (which is unsolved for the moment)*
=> Prioritize assisting buildings over repair

lua/defaultunits.lua
Seems like GetUnitBeingBuilt() function isn't defined for mobile construction units.
Until we a better inheritance chain, let's just use self.UnitBeingBuilt
Fixes #809
=> Use self.UnitBeingBuilt instead of getter

lua/defaultunits.lua
Stops the unit currently being built from persisting when reclaiming or
transferring a factory. OnDestroy is a much better location for these things, as it's called in more situations than OnKilled. It's also called in the same code path as OnKilled.
Fixes tarmac on buildings lasting forever if the building is reclaimed.
=> Fix factory unit not being destroyed

lua/ui/dialogs/mapselect.lua
When the map list changed, e.g. when switching from normal FAF to Coop,
resulting in the previously selected map not being available anymore, the
missing check for scenarioInfo being set caused the UI to bug out.
- Check for scenarioInfo being set
=> Make mapselect not spaz out after changing mods

lua/sim/DamageArea.lua
A bit of an ugly hack, but this is working in my tests. Basically, anything you can see gets the new behaviour, and anything you can't gets the old, but nothing gets hit by both.
=> Deal with the new nuke setup not hitting unscouted enemies

lua/ui/lobby/UnitsRestrictions.lua
Fixed #1224 by including gateway structures to `No T3 restriction preset` and T3 factories which cannot be upgraded to T4 so they are useless when `No T3 restriction preset `is enabled
=> Minor fix in restriction presets

lua/ui/controls/resmappreview.lua
slight oversight there from long, long ago. Possibly a small
memory leak.
=> Remember to delete the wreckage icon pool

lua/aibrain.lua
the old IF ELSE statement was playing the nuke warning for non observers x-times (for every player sync one warning). This was making the sound verry loud.
New If Else only play the nuke warning once, also if you are an observer the sound will only played once (for player index 1 only)
=> Bugfix Play nuke VO for observers

units/UAA0103/UAA0103_unit.bp, units/UEA0103/UEA0103_unit.bp, units/URA0103/URA0103_unit.bp, units/XSA0103/XSA0103_unit.bp
Increase the time T1 bombers take to circle over their target as they
attack.
=> Increase T1 bomber BreakOffDistance to 24

lua/ui/lobby/lobby.lua
Issue #1436
This change is for compatibility from FAF with vanilla and steam game
version. FAF is using more colors inside the Lobby then vanilla and steam can handle, so
we use a own variable now for it.
=> BugFix lobbycolor incompatible with vanilla and steam

units/UEA0203/UEA0203_script.lua
The only way this can occur is if they are carried in by the UEF T2 Gunship (Normal transports cannot enter carriers). So on Gunship loading, disable carried unit weapons.
Fixes https://github.com/FAForever/fa/issues/1457
=> Stop LABs firing from carriers

lua/ui/game/gamemain.lua, units/XSL0101/XSL0101_script.lua, units/XSL0101/XSL0101_unit.bp
Unit spawns with the toggle off. It behaves as a normal scout/LAB, no special abilities.
Toggle the unit's ability on, and it will drop to low selection priority and enable the stealth system, which is back to being motion-based.
=> Change the way the Selen toggle works

lua/victory.lua
Issue #1294
Replaced the function GetCurrentUnits() with a new one. Now units are
counted accurate and the game will end in all gamemodes like expected.
=> Bugfix Game don't end in Assassination or Supremacy mode

lua/ui/game/controlgroups.lua
Controlgroups don't have global icon support, and can't display Icons from Modded units:
=> Global Icon support for control groups

units/UAA0104/UAA0104_script.lua, units/UAA0104/UAA0104_unit.bp
Reopened PR #1337
More Info: #1336 
I added a Weapon with 0 damage to the Aeon Transporter to guide the weaponfire from loaded units.
=> Adding a 0 Damage Weapon to Guide Weaponfire of LABs

lua/ui/game/construction.lua
In case we don't find an icon from the other faction return the old icon
instead of "false"
=> Bugfix for All Race templates

lua/ui/game/unitviewDetail.lua
issue #1514
Preset Subcommanders are named like `ual0301_Engineer`
So we need to removed the extension` _Engineer` to get a proper blueprint name and the corresponding enhancements.
=> BugFix preset SCUs' enhancements have no description

units/UEL0301/UEL0301_unit.bp
well i dunno who is responsible but this should be a crime imo. anyway
when you add 2 and remove -4 then add 2 again you get 0 aoe so if you
try to get the upgrade, remove, and get it again it no longer works.
great.
now that's fixed, and also NewMaxRadius was missing in here, lukily it
was called with (bp.NewMaxRadius or 25) so it wasn't so terrible, but
still
enjoy your game knowing it had balance terrorists working on it )
=> fix uef scu aoe upgrade removal incorrect numbers

effects/emitters/seraphim_chronotron_cannon_projectile_fxtrail_01_emit.bp, effects/emitters/seraphim_chronotron_cannon_projectile_fxtrail_02_emit.bp, effects/emitters/seraphim_chronotron_cannon_projectile_fxtrail_03_emit.bp
Optimizing a change in https://github.com/FAForever/fa/commit/8a987da5fab49c61409a5b9b71b82abff32381e4
The LODCutoff for the weaponemitter of the Serapim ACU was set to 1200.
But the ACU Unit itself has a LODCutoff of 175.
This will lead to show the weapopntrail while full zoomed out without showing the ACU unit.
So i reduced the visibilty of the weapon to the same zoom level as the unit.
seraphim_chronotron_cannon_projectile_fxtrail_01_emit.bp
Changed from 1200 to 175 (was 100 in vanilla)
seraphim_chronotron_cannon_projectile_fxtrail_02_emit.bp
Changed from 1200 to 175 (was 100 in vanilla)
seraphim_chronotron_cannon_projectile_fxtrail_03_emit.bp
Changed from 1200 to 175 (was 100 in vanilla)
=> Fix LODCutoff for Seraphim ACU weapon trail

units/URS0202/URS0202_unit.bp
While was changed toggle weapon to equilibrium style was copypast AA
target priority also to ground fire weapon. This fix it to naval
standards.
#BalanceTerroristsInvadingYourCode
=> Siren ground fire target priority fix

lua/SimCallbacks.lua
Moving the race-lookup table outside the callback, like Crotalus said.
Should make less garbage to declare the table only once.
=> Optimize Callbacks.CapMex - moving race-table out of callback

lua/SimPing.lua, lua/ui/game/reclaim.lua
Ok, there is one place where armyIndex-1 needs to be set, when creating an entity with spec table the Owner field is actually armyIndex-1.  In this case it's for the zoomed in ping entity that's spawned when pinging.
I will add the reclaim label bugfix here when I manage to see what's wrong so wait to merge this PR until it's added here.
=> Hotfixes for 3660 (ping / reclaim labels)

lua/ui/lobby/lobbyOptions.lua
Surprisingly enough the engine only accepts, 5, 10, 20. Must be hard-coded somewhere
Fixes #1618
=> Remove non-working 15, 30 NoRush options

changelog.md, lua/sim/Unit.lua, lua/version.lua, mod_info.lua
This happens in the no power state. Having no power cycles through
all of the intel types, not just the ones you should be able to use.
This accidentally triggers the cloak FX function. Checking that the
unit was meant to have cloak fixes it.
Note - This fix won't work with cloakfield units (The FX didn't anyway)
Will need to find a solution for BlackOps and other mods who use that
broken function...
=> Stop cloak FX flickering on all intel units. Fixes #1674

units/UAL0304/UAL0304_unit.bp
it doesnt deploy. so it doesnt need to have this ability. its pretty
misleading. no gameplay changes, this is only a ui mistake.
=> Remove Deploy ability from aeon t3 arty

lua/aibrain.lua, lua/sim/ScenarioUtilities.lua
The intel system gets slower with more players in a game so instead of waiting 1 second for civs to reveal we use a trigger in OnIntelChange to get information when a player actually sees the civilians.
Fixes #1667
=> Fix bug with civs not always revealing

lua/ScenarioFramework.lua, lua/SimObjectives.lua, lua/SimUtils.lua, lua/scenariotriggers.lua, lua/sim/Unit.lua
fixes FAForever/fa-coop#47 (speed2 told me to PR it here)
I created a UnitCallback that is called each time a player gives that unit to a different Player.
Each specific unit used in an objective receives a trigger for it. The 'new' unit now has to replace the old unit in the Objective: replace in the Targets list, reassign triggers, reapply marks and arrows.
=> Players giving objective units doesn't break the objective anymore

lua/ui/lobby/lobby.lua
fixes:
1) close - spawn mex is changed to close when "options" is clicked without changing the map
2) clients not showing closed spots
=> fix bugs with "close - spawn mex"

lua/UserSync.lua, lua/sim/Prop.lua, lua/ui/game/reclaim.lua
This is a first attempt to follow the reclaim logic view through and try to identify the fault. I believe I identified one potential vulnerability: When a prop was destroyed, if it happened such that self.MaxMassReclaim had already been cleaned up, it would return nil and skip the creation of the data block to be synced, leading to the label never being called for destruction.
=> Attempt to address 'ghost' reclaim labels: #1628

lua/defaultunits.lua, lua/game.lua
We could make this a gameplay option also per player basis. What's needed then is a SimCallback which provide the default firestate at start of game / whenever player changes that option.
=> Set ground fire as default for mobile units

lua/options/options.lua
Should we deploy this? Or should we increase the default, eg. to 1000 or 2000? I think 1000 run still run very smoothly for most players.
=> Fix #1743 reclaim label default value

mod_info.lua
so some uplords working on a git patcher and since faf wants to have
schook defined, this is it happening. no other changes bscly, cannot possible fail right?
=> include hook directory in mod_info.lua

lua/ui/lobby/lobby.lua
This way the default map can be easily changed, without complicated
hooking, for mods like coop, tutorials or any mod that doesn't use
skirmish maps.
=> Use default scenario from uiutil if map is missing

lua/ui/lobby/lobby.lua
So apparantly random and balance functions couldn't handle uneven teams.
Not sure about their balancing performance in these cases, but atleast they don't crash anymore.
=> Lobby: Autobalance functions don't crash on uneven teams anymore

lua/ScenarioFramework.lua
Fixes #1789 
Yotha doesn't spawn energy storm when given
Ignores unit restrictions, since this function is used only in missions.
=> Improve GiveUnitToArmy

lua/ui/lobby/lobby.lua
Remove SetPlayerOptions which should only be used for local slots or hosts.
Every player will do SetPlayerOption for himself so not everyone else should do it for others anyway.
=> Lobby: remove unnecessary and harmfull SetPlayerOption

lua/sim/Unit.lua, lua/ui/lobby/lobby.lua
That warning message uses `key `and `val` variables, so need a for loop to get them from the table.
=> Fix Warning message

lua/ui/lobby/lobby.lua
Faction selector didn't disably when you become observer as non-host, so yeah, need to update it.
This should fix all the issues that non-host has with faction selector.
=> Lobby: Update factionselector when becoming observer as non-host

lua/ui/lobby/lobby.lua
To remove the ability of people to spam chat with the observer button.
As reported here:
http://forums.faforever.com/viewtopic.php?f=2&t=14090
=> Only send NoUnitsAvailable message to spot requesting observer

lua/SimCallbacks.lua, lua/sim/tasks/AttackMove.lua, lua/ui/controls/worldview.lua, lua/ui/game/commandmode.lua, lua/ui/game/orders.lua
- Clean up whitespace, dead function and some other code niggles
- alt-rmb, when clicked, not only places the order, it spawns a blue "Going here" flash with a downward arrow. The new command should also do this
- The new command turns into a new cursor. alt-rmb should have this cursor while mousing over blank map space
=> Improve the new Attack Move Button

lua/ui/controls/worldview.lua
Like the title says: Factories also have the attackmove cursor when you hold alt even though they can't use the button itself. 
(factory AggressiveMove works different somehow so we don't know how to make it work with a button at the moment)
=> Give Factories AttackMove cursor when pressing alt.

modules/hotkeylabels.lua, modules/hotkeylabelsUI.lua
Needed to change some extra things because current version didn't support labels with strings longer than 2.
=> Add Alt+RMB label to attack move

run_lua_tests.sh
We don't (really) care about the lua files in `engine/` and `testmaps/` being syntax-checked
=> Ignore non-live lua folders

lua/ui/lobby/lobby.lua
Players currently broadcast their CPUbenchmark upon join, but i'm guessing this happens before anyone except the host is connected to that player, so only the host gets this information.
So i tried to use the host to indirectly communicate this CPUbenchmark to the other players aswell.
(I thought why not just send everything so everybody has the same data even if something got lost)
fixes #1798
=> Fix invisible CPU of recently joined players bug

units/XEA0002/XEA0002_script.lua
No longer errors out for directly satellites spawned without a building.
=> Fix satellite's death with no assigned building

lua/EffectUtilities.lua
fixes #1904
the adjecency lines are now created between the buildings, even when they are under water. This is primarily relevant for under water crazyrush mexes.
=> fix/ underwater adjecency lines on water surface

lua/aeonunits.lua
Fixes #1902
As the open animations don't exists, this can be removed so the code can get tocreating the rotators (as I dont expect anyone to make the open animations).
It got broken by this commit https://github.com/FAForever/fa/commit/252ede50c378c40fc0bba848ccb32b81b9b256b6 which removed reference to non-existant animation from the BPs.
=> Fix Aeon shields not rotating

lua/SimCallbacks.lua, lua/utilities.lua
This _should_ fix the issue we've been having with the engine for some reason letting the mex cap storages overlap other structures. Needs THOROUGH testing!!!!!
=> Manually filter for nearby overlapping structures for Mex Cap

lua/sim/Unit.lua
`ScenarioInfo.CampaignMode` is set at campaign game start https://github.com/FAForever/fa/blob/develop/lua/sim/ScenarioUtilities.lua#L553 so no way to cheat it in without using a sim mod
=> Dont delete restricted units when captured in coop

units/UAA0310/UAA0310_unit.bp, units/UAL0401/UAL0401_unit.bp, units/UAS0401/UAS0401_unit.bp, units/UEL0401/UEL0401_unit.bp, units/UES0401/UES0401_unit.bp, units/URA0401/URA0401_unit.bp, units/URL0401/URL0401_unit.bp, units/URL0402/URL0402_unit.bp, units/XRL0403/XRL0403_unit.bp, units/XSA0402/XSA0402_unit.bp, units/XSL0401/XSL0401_unit.bp
Buff Regen from vet to replace the instant healing from higher vet levels which was reduced greatly.
Regen/s = original regen/s from vet + regen/s required to replace the instant healing which was removed in 4 minutes.
=> buff XP Vet Regen

units/XEL0209/XEL0209_unit.bp
It was removed because of a bug which has since been fixed.
=> reintroduce e maintenance to sparky

units/UEA0103/UEA0103_unit.bp
Increase the DoTTime to prevent uef bomber one-shotting moving t1 land units.
=> nerf uef t1 bomber

lua/sim/Unit.lua
sometimes ships glitch on land and then get destroyed. When they have a death animation specified they start sinking through the ground.
This PR doesnt fix the glitch that they get on land, but it fixes the sinking.
=> fix/ ships with death animation sinking on land

lua/options/options.lua, lua/system/Localization.lua
fix for #1934
After changing the option for language and restarting the game, the new language will not appear.
That is caused by not saving options_overrides before gamerestart.
To solve this i modified the Localization.lua to get the actual language from useroptions instead of options_overrides.
=> BugFix loading right language after gamerestart

lua/ui/dialogs/options.lua
If you try to change the screen resulution of the game, you will get a requester with a 15 second count down:
But the time don't count down, instead you get an Error:
```
WARNING: Error running lua script: ...1.5.3603\gamedata\lua.scd\lua\ui\dialogs\options.lua(497): attempt to call method `SetText' (a nil value)
...1.5.3603\gamedata\lua.scd\lua\ui\dialogs\options.lua(497): in function <...1.5.3603\gamedata\lua.scd\lua\ui\dialogs\options.lua:494>
```
Line 497 is used to set the new text inside the button with the time count down:
`dlg._button1.label:SetText(LOC("<LOC _Ok>") .. " [" .. (secondsToWait - sec) .. "]")`
I added the "content" array level, now we can access the button again, and set the text:
`dlg.content._button1.label:SetText(LOC("<LOC _Ok>") .. " [" .. …
=> BugFix for ui-option-VerifyDialog

lua/ui/lobby/lobby.lua
As of the last update the game ignores the scenario requested by the client, always loading the last or default scenario instead. This breaks co-op.
=> Fix always loading last or default map

lua/spreadattack.lua
* Adds handling for moved or deleted orders to partially fix #1177. Due to limitations of the data returned by UserUnit.GetCommandQueue() this can't be used for factory units (Fatboy, Megalith, Tempest, Czar, Atlantis, carriers) or for handling changed entity targets. I tried a callback with the sim version of GetCommandQueue and it seemed to return no usable data at all.
* Adds support for more order types. This now allows splitting Patrol orders and spreading targets for ground Attack, Capture, Guard (useful for distributing scouts throughout a group), Nuke, OverCharge, Reclaim, Repair, and Tactical missile.
=> Improve Spread Attack

lua/ui/notify/notify.lua, lua/ui/notify/notifyoverlay.lua
This should improve accuracy and decrease lag when updating the overlay. It now updates the data more often and sends it less often instead of sending it 10 times a second and updating every 3 seconds. The overlay should also no longer disappear when the update loop skips a sim tick.
=> Notify Integration: Overlay Improvements

lua/ui/game/construction.lua
#2005
(http://forums.faforever.com/viewtopic.php?f=3&t=14602)
Removed the display of Buildcost inside Unitdetail window if you hover the mouse over `queuestack', 'unitstack' and 'attachedunit'
To do so, i used the fact, that we have already an if/then request inside function `unitviewDetail.lua.show()` to check if we have an buildingUnit.
If no buildingUnit is present, we don't display economy.
So i call 'Show' without an buildingUnit: (nil = buildingUnit)
```UnitViewDetail.Show(__blueprints[item.id], nil, item.id)```
=> Don't display BuildCost in 'queuestack', 'unitstack' and 'attachedunit'

units/UEA0203/UEA0203_script.lua
`GetCargo()` returns empty table if the gunship has no cargo which is
taken as true in the condition below
Fixes #2010
=> Check if gunship has a cargo properly

lua/ui/game/construction.lua
fix for bug where an error sound is played and build mode exits when building templates
see http://forums.faforever.com/viewtopic.php?f=45&t=14616
=> fix for bug with templates in build mode

lua/SimPing.lua
Addresses #1982 by changing the limit to be per player. It allows 3 pings with a 15 second cooldown. It also allows an additional marker after reaching the limit, to be a little more accommodating if someone takes the time to type out a message. The marker still adds to the cooldown to prevent low effort marker spam.
=> Change ping lockout to be per player instead of global

lua/keymap/hotbuild.lua, lua/ui/game/construction.lua
When rotating a template with middle click, the width and height numbers remain unchanged. That causes spacing problems when trying to drag out a line of the template after rotating 90° or 270°.
=> Fix tiling of rotated templates

lua/wreckage.lua
Issuing a repair command on the wreckage of a building gives an order to rebuild it. Currently that order is issued to all builders at once but for some reason it can only affect one, leaving the rest of the group sitting idle. Giving the order to each builder individually works as originally intended, except that the order can't be moved or deleted as easily as if it was correctly given to all builders as a group.
=> Fix only one engineer trying to rebuild wreckage

units/XRB2308/XRB2308_script.lua
adds a check if the y-coordinate of the unit (position[2]) has a value
below the water surface (GetSurfaceHeight) and terminates the sinking
thread in that case. 
This prevents it from sinking again when the unit is given.
=> fix harms sinking multiple times

lua/ui/lobby/lobby.lua
Last patch 3680 introduced some issues with lobby chat. 
ie : multi-line messages make is so chat isn't completely scrolled down.
People wanted it to be scrolled down immediatly when you write yourself.
Make it work with multiple font sizes. (didn't know this was a thing)
=> Lobby: fix some chat issues

lua/ui/lobby/lobby.lua
fixes #2041
Now unit restrictions will get removed when you click on default settings and have preset with no restrictions.
I added that default-settings-button also defaults team options. (Spawn,Team,AutoTeams)
The autoteams button now updates to match the currently selected autoteam option.
(previously it would only update when you clicked on it)
=> Make presets and default reset restrictions + bugfixes

lua/ui/game/orders.lua
Whenever the orders need to be redone, without there being a selection change (ie changed ui faction), it is possible that there are some destroyed units in the currentselection table. The function EntityCategoryFilterDown can't handle that. So we need to filter out the destroyed units before using it.
It causes an issue in coop when the acu dies while you have it selected and you can't go to the scorescreen anymore due to this issue.
https://github.com/FAForever/fa-coop/issues/68
=>  Check for destroyed units before EntityCategoryFilterDown in orders.lua

lua/ui/dialogs/mapselect.lua
if the game prefs file contains a section (usually empty) of the form
stored_filter_state = {  },
then the map_obsolete flag is not set to 1 and thus all maps are shown
even if the option for the filter sais "hide outdated maps".
part of #2024
=> fix "hide_obsolete" filter in map selection disabled by default

lua/ui/game/connectivity.lua
When pressing F11 in a replay or singleplayer game, the network stats overlay opens, but pressing the key again doesn't close it.
=> Fix network stats opening but not closing when alone

lua/ui/dialogs/mapselect.lua
extends the "hide obsolete" function in the map select window to hide maps where higher versions with the same name are available locally.
Currently it only hides maps on the blacklist.
=> hide maps if newer versions are available locally

lua/AI/OpAI/AirAttacks_save.lua, lua/AI/OpAI/BaseManager.lua, lua/AI/OpAI/BaseManagerPlatoonThreads.lua, lua/AI/OpAI/BaseOpAI.lua, lua/AI/OpAI/BasicLandAttack_save.lua, lua/AI/OpAI/NavalAttacks_EditorFunctions.lua, lua/AI/OpAI/NavalAttacks_save.lua, lua/ScenarioFramework.lua, lua/ScenarioPlatoonAI.lua, lua/cinematics.lua, lua/editor/BaseManagerBuildConditions.lua
Work in progress.
#JustCoopThings
* Base manager can now operate TML launchers, even if they are rebuilt/newly built.
* They don't need to be activated via script anymore.
* Enabled by default, can be disabled via `bm:SetActive('TML', false)`
* On `Hard` difficulty they use sorian function for predicting mobile target location
* Engineers wont initiate permanent assist on factories if there are no factories in the base
* Extra check in the perma assist function to not assist factory if there isnt one, the function should no longer end up with an error in that case.
* Upgrade thread is not properly set on the command units. If there are upgrades set in the base manager via `bm:SetUnitUpgrades` or `bm:SetACUUpgrades` or `bm:SetACUUpgrades` they will get upgraded.
* Fixed wrong order of the …
=> Base manager improvements

lua/formations.lua, units/XAL0305/XAL0305_unit.bp, units/XRL0403/XRL0403_unit.bp, units/XSL0305/XSL0305_unit.bp, units/drlk001/DRLK001_unit.bp
Here's my work on improving formations. This is a work in progress and addresses the points in #2040. Any comments or suggestions are welcome, but please look at the checklist first.
Progress:
=> Formation Improvements

projectiles/Sinker/Sinker_script.lua
Due to the collision detection in the bounce system, it's possible for an air unit to land near the shore with  bone 0 underground and the collision classified as a water crash. That causes it to create a Sinker under the seafloor, which is a problem. This adds a check when creating a Sinker to prevent that and similar situations.
Fixes #1985 and should fix #2012.
=> Fix air units sinking forever after bouncing off shield

lua/sim/Unit.lua, lua/ui/notify/notify.lua, lua/ui/notify/notifyoverlay.lua
* Overlays now show the enhancement name (respecting custom message toggle).
* Fixed completion messages being sent when an experimental or the like changes ownership.
* Fixed /enableNotify and /disableNotify permanently toggling the overlay.
=> Notify: Add enhancement names to overlay and fix bugs

lua/ui/dialogs/score.lua, lua/ui/game/tabs.lua, lua/ui/lobby/lobby.lua
Related issues: #248 #619 #790
This is a fix for exiting the game.
FAF needs the game to fall back to the desktop (FAF Lobby).
But without FAF the game should exit to the main menu, not the desktop.
This is how it works now:
Game launched from FAF will return to desktop on exit.(SafeQuit()->ExitApplication())
Game launched from Desktop will return to the ingame menu on exit.(ExitGame())
Also fixed:
Ingamelobby shows now "exit" instead of "back" button if launched from FAF.
(added tooltip to exit and back button)
Scorescreen shows now "exit to FAF" instead of "continue" if launched from FAF
(fixed tooltip for "exit to FAF" button, added tooltip to "continue" button)
Removed Rehost button from LAN Multiplayer menu.
Added EscapeHandler.SafeQuit() to singleplayer game exit.
All tests are done …
=> Fixed exit game for FAF and desktop launch

lua/ScenarioFramework.lua, lua/UserSync.lua, lua/ui/game/reclaim.lua
fixes #2032
I couldn't find anyway to get playable area from UI, so I made a new Sync for UserSync.
If anyone has a better way to do it, then let me know.
=> Only show reclaim in the playable area

lua/AI/aiarchetype-managerloader.lua, lua/AI/aiattackutilities.lua, lua/aibrain.lua, lua/editor/SorianBuildConditions.lua, lua/editor/SorianInstantBuildConditions.lua, lua/sim/EngineerManager.lua
Sorian Ai was identified by a string.find in some functions like this:
```
local per = ScenarioInfo.ArmySetup[self.Name].AIPersonality
if string.find(per, 'sorian') then
[...]
end
```
Now it's stored inside a variable while calling `OnCreateAI`:
```
self.Sorian = true
```
And can be accessed without a string find:
```
if aibrain.Sorian then
[...]
end
```
The Duncan Ai was identified by a file search:
```
if DiskGetFileInfo('/lua/AI/altaiutilities.lua') then
[...]
end
```
Now it can be accessed like the Sorian AI with:
```
if aibrain.Duncan then
[...]
end
```
Also AIx are now identified by aiBrain.CheatEnabled instead of string.find().
It was not working in german translation, because "AIx" is in german "KIx"
And fixed a small bug if more then 5 teams are assigned to Sorian AI's
=> Fix/Optimization: Identify Sorian AI with variable instead of string find

lua/SimObjectives.lua
#JustCoopThings
If called with manual result the objective continues after that even if
it should not
=> Check if Kill objective is still active

etc/faf/blacklist.lua, lua/sim/Unit.lua, lua/ui/notify/notify.lua, lua/ui/notify/notifyoverlay.lua
This stops showing non-enhancement messages after a certain number. That way if you start mass producing experimentals or factory HQs it won't spam allies for every single one completed.
Currently the limits are hard-coded at 1 message per factory HQ and 3 per nuke/arty/experimental. If the numbers should be changed let me know. I looked at allowing the numbers to be changed in the customizer, but I can't think of a way to do it that wouldn't just clutter up the window.
=> Notify: Add the ability to limit the number of times a message is shown and fix mod breaking

lua/ui/game/construction.lua, lua/ui/templates_factory.lua
Fixed: Factorytemplates was not supporting icons from mod units.
Fixed: Selecting a new icon to the template was not working because of a
different array structure from normal buildtemplates.
Structure of normal engineer buildtemplate:
```  templateData={ 3, 3, { "ueb2101", 936, 0, 0 }, },```
And this is how the factory buildtemplate looks:
```templateData={ { count=5, id="brnt1mt" } },```
To get the icon from the factory buildtemplate we need to use `templateData.id` instead of getting the first array entry with `templateData[1]`
=> Fix for factory build templates icons

lua/ui/uiutil.lua
In case the filspec has already a valid filepath we don't need a warning.
Will fix this error:
```
debug: [uiutil.lua, function UIFile()] - Unable to find file:/textures/ui/uef/textures/ui/common/hotstats/bt_sca.dds
```
In this case filspec is holding a valid filepath: `/textures/ui/common/hotstats/bt_sca.dds`.
=> Fix UIFile() warnmessage

lua/ui/lobby/lobby.lua
fixes #2100
Just need to set player to not ready before turning him into observer.
=> Lobby: fix bug with observers being Ready

units/XEA0002/XEA0002_script.lua, units/XEB2402/XEB2402_Script.lua
* Fix the satellite not being rebuildable after getting nuked (#2097)
* Fix the satellite disappearing while falling after the control center is destroyed
=> Fix Novax bugs

lua/system/Blueprints.lua, units/XSS0304/XSS0304_unit.bp
Currently the T3 Subhunter tends to stop at 32 range (it's torp def range) when using the attack move command which prevents it from using it's range properly.
This change should fix that problem.
=> fixes the distance for attackmove

lua/skins/skins.lua, lua/ui/game/gamemain.lua
When watching a replay you can have the incomplete 'random' skin selected if you were random in a lobby but didn't start the game, causing #2059. Even if that doesn't happen, the skin isn't properly loaded when starting as observer, causing chat window problems like #2082. This fixes the 'random' skin by basing it on the UEF skin instead of default, and the chat problems by properly refreshing the UI when starting.
=> Fix replay UI problems

etc/faf/blacklist.lua, lua/simInit.lua, lua/ui/lobby/lobby.lua
This is the start position part of #1810, #1284, and #1215. It's now updated to include empty slots in the random pool and switch spots between different teams when auto teams are disabled like in a free for all.
=> Randomize starting positions

units/URA0001/URA0001_script.lua, units/URA0001/URA0001_unit.bp
Fixes #2116 for the low, low cost of buffing all Cybran build power by 0.00067%. It seems that in rare cases the little laser drones are somehow being told to help capture a unit. That results in a division by 0 when calculating capture time, which causes the unit to be instantly captured.
=> Fix Hives instantly capturing units

units/URL0301/URL0301_unit.bp
This addresses #2020 and allows the SACU to hit targets at the edge of its range and/or running away at speeds of up to 8.
=> Fix Cybran SACU projectile lifetime not allowing it to use its full range

lua/ui/game/gamemain.lua
removes the quick tip prefix of the quick tips since its quite obvious
that they are tips.
fixes #2048
=> remove "quick tip" prefix

lua/ui/game/worldview.lua
If the bounds of a marker were evaluated before the first frame it was shown, bad things would happen due to invalid default bounds.
=> Fix spawn marker lazyvar error

lua/ui/lobby/ModsManager.lua
the mod manager sorts the mods by UI and SIM mods. That requires to have the UI_Only parameter set in the modinfo file.
Some mods dont have this parameter set at all and thus break the modmanager.
fixes #2128
=> fix modmanager handling of incomplete modinfo files

lua/ui/lobby/lobby.lua
Enabling auto teams doesn't currently disable use of the team selector on AIs, but changes have no effect. That can result in deceptive and confusing behavior when someone doesn't realize they have auto teams on while playing with AI.
=> Fix AI teams being changeable with auto teams enabled

units/UAS0305/UAS0305_unit.bp, units/UES0305/UES0305_unit.bp, units/URS0305/URS0305_unit.bp
allows you to use the guard/assist command with t3 sonar
very handy for cybran stealth/big maps where t3 sonar might not cover all the important parts of the map
=> assist command for sonar

lua/system/Blueprints.lua
http://forums.faforever.com/viewtopic.php?f=3&t=15002&p=153183#p153183
One of the last patch broke the BrewLan mod.
Just a small issue;
some brewLan units don't have a factionname, and causes an error in this line:
`bp.FactionCategory = string.upper(bp.General.FactionName)`
=> Fix for modded units with no factionname

lua/defaultunits.lua, lua/sim/ScenarioUtilities.lua
fixes #2147
due to the short delay before the acu is warped in, the acu was able to
start building stuff before the animation is played.
=> disable build ability of acu before warping in

lua/ui/game/unitview.lua
the engine function GetRolloverInfo() provides the UI with values for
massRequested and massConsumed. Before overcharging, these values
usually coincide. However, after firing an overcharge, the function
returns for massRequested only 0 independently of the actual
consumption. This issue can be fixed by using massConsumed instead. (the
same applies to energy as well)
fixes #717
=> fix acu consumption not correct after overcharge

units/UAS0203/UAS0203_unit.bp, units/UES0203/UES0203_unit.bp, units/URS0203/URS0203_unit.bp
fixes #1280
hover/direct fire units were unable to hit any of the vanilla subs when surfaced. Adding targetbones fixes the issue.
=> add targetbones to t1 subs

lua/sim/Unit.lua
naval units have a death animation which is only played when they are
more than 50% completed. In the DeathThread the degree of completion is
not checked again, just the existence of this animation. If the unit is
not sufficiently completed, it doesnt sink with its animation and thus
the SeaBedWatcher function doesnt terminate since the unit is not
sinking with the normal sinkerthread.
fixes #2076
fixes #1045
=> fix incomplete ships not being destroyed

lua/sim/Unit.lua, units/UEL0301/UEL0301_unit.bp, units/URL0001/URL0001_unit.bp, units/URL0301/URL0301_unit.bp, units/URL0402/URL0402_unit.bp
This commit fixes the following two issues:
The monkeylord loses its sonar capabilities in case of a powerstall when
the stealthfield is active. If it is deactivated, the sonar continues to
work. fixes #896
If the cybran acu, sacu or the uef sacu has a counter intel upgrade
(stealth, cloak, jamming) and the player powerstalls, the omni of the
unit will be deactivated.
=> counterintel disableing intel unintentionally

lua/sim/Unit.lua
fixes #2056
the vision is still enabled for acus and sacus (and other units with
omni sensors)
=> disable vision for submerged amphibious units

lua/AI/OpAI/BaseManager.lua
Cybran engie stations are never in 'Idle' state but in 'AssistingCommander' state.
Fixes #2175
=> Make Base Manager upgrade Hives as well

units/URA0001/URA0001_script.lua
add additional check to the cybran drones if the assisted unit is dead
or not
potentially fixes #2167
=> add failsafe to Buildstate of cybran drones

lua/sim/defaultweapons.lua, units/UEL0001/UEL0001_script.lua, units/UEL0301/UEL0301_script.lua
This reduces the duration of #717 and compliments #2157 and #2192. The inaccurate display is caused by the engine ignoring other resource consumption when a unit has an economy event, whether it's active or expired. This makes sure economy events are removed as soon as they finish to reduce the time displayed values are incorrect.
=> Remove expired economy events more quickly

units/UAB1201/UAB1201_script.lua
The Aeon T2 generator has a little ball hovering above it much like the T3 generator, but that ball is static. Given the Aeon love of spinning balls, it seemed like it should move. The T1 version also has a static ball that can be made to spin, but it's a solid color so the spinning is practically unnoticeable.
=>  	Make Aeon T2 generator ball spin like the T3 version

lua/sim/defaultweapons.lua
prevents early exits of the reload bar rendering which caused the bar to stop at 98%
fixes #2198
=> round clocktime for reload bar

lua/simInit.lua
logs the gametime every 30 seconds to make it easier to track the time when an error occurs
fixes #2169
=> add gametime logger

lua/sim/Unit.lua, lua/ui/notify/notify.lua, lua/ui/notify/notifyoverlay.lua, schook/lua/UserSync.lua
Currently Notify overlays don't show in replays when watching from a player's perspective. Switching to observer after starting the enhancement is even worse because it creates an overlay that never goes away.
This allows all observers to see all players' Notify stuff as well as fixing the overlay when watching a replay from a player's perspective.
=> Fix Notify overlay problems in replays

lua/maui/text.lua, lua/ui/controls/textarea.lua
Fixes #2204. This reverts a couple errors introduced with the UTF changes as well as removing a bug causing the first line of a TextArea to be empty when the UI is refreshed.
=> Fix word wrap problems when refreshing TextArea

units/UEL0111/UEL0111_unit.bp
brings the UEF MML in line with the MMLs of other factions in terms of dps by reducing the salvo size from 3 to 2
=> Balance:Nerf UEF MML

units/XSL0103/XSL0103_unit.bp
reduces the speed on water by 10% (same as other hover units such as the riptide or blaze
=> Balance:reduce fobo speed on water

lua/ui/game/reclaim.lua
Issue #2236
This fix checks for destroyed labels.
If an destroyed label is found, it will be removed from the LabelPool list.
Also a small fix in case the camera is not present while the ShowReclaimThread is asking for it.
If this happened we just wait another tick for the new camera.
=> Fix for "split screen breaks reclaim labels"

units/XSS0203/XSS0203_unit.bp
The sub fires it's torp defence every 5 seconds instead of every 20 secs.
=> buff sera t1 sub torp defence

units/UAL0001/UAL0001_unit.bp, units/UEL0001/UEL0001_unit.bp, units/URL0001/URL0001_unit.bp, units/XAL0305/XAL0305_unit.bp, units/XSL0001/XSL0001_unit.bp, units/XSL0305/XSL0305_unit.bp
This change makes it so that when walking your ACU, it will automatically prioritise enemy units rather than an enemy unit. This behaviour is already seen on the auto-OC gun.
For cases when you DO want to focus down an enemy ACU, simply giving a manual targeting command will tell the gun that's the highest priority target using the priority retainer system. So you can manually target, then give move commands and it will still focus in on the ACU.
Also have Sniperbots target ACUs above other targets, so they can kite and chase without wasting shots on unimportant targets.
=> Have ACU main weapon target mobile units before other ACUs. Have Snipers target ACUs.

lua/shield.lua
When changing the shield regen steps from every 10 ticks to every 2 ticks (actually 9 ticks to 1, see #2268) the amount per step wasn't reduced to compensate.
=> Fix shield regen rate

lua/defaultunits.lua
0.1 multiplier for ACU x ACU kills
equals to 5 points in the old system
=> reduce vet points from ACU kills

units/UEA0203/UEA0203_script.lua
TAirUnit is inside AirTransport class so it's not needed here.
I don't see any functionality removed by this.
Ive encountered ambiguous class definition error with RK explosion mod, it's hooking AirUnit class inside defaultunits.lua . The mod worked fine for all units except the UEF gunhips. Removing this ^^ seems to fix the problem and I dont think it's removing anyting from the gunship.
More tests are welcome.
=> Remove TAirUnit from the UEF Gunship class

lua/ui/game/layouts/unitview_left.lua, lua/ui/game/layouts/unitview_right.lua
Fixes #2290. It seems the new veterancy UI components were only added to the unitview_mini layout, ignoring the other two.
=> Copy veterancy UI code to all layouts

lua/simInit.lua
Issue #2241
Debuglog now shows the correct minutes.
Before:
DEBUG: Current gametime: 01:61:17
After:
DEBUG: Current gametime: 01:01:17
=> Fix gametime logger is printing wrong times

lua/ui/game/unitview.lua
Related to #2306
There are some problems with ACU enhancments icons, if you switch a player with [ALT]+[F2] and/or if you use Black Ops ACU's :
To fix this i added the "true" argument to UIUtil.UIFile. (see commit)
This way UIUtil.UIFile is also ckecking mods to find the icon :
=> Fix Global Icon Support for ACU enhancements

etc/faf/blacklist.lua
since we have integrated icon support and this mod just breaks the game for the user it should be blacklisted
=> Blacklist Icon Support

lua/shield.lua
Mobile shields have a line in their bp files ShieldSpillOverDamageMod which did nothing because of a typo. 
The affected units are T2 mobile shields, T3 mobile shield, Fatboy, UEF ACU bubble shield, Shieldboat, UEF SCU bubble shield and T3 transport.
=> fix ShieldSpillOverDamageMod

units/XAB2307/XAB2307_unit.bp
Since the Salvation is now an experimental unit, it should have `TechLevel = 'RULEUTL_Secret',`.
At the moment the unit has as Techlevel `RULEUTL_Advanced`.
(And that's reserved for Tech2 (two) units.)
=> MiniFix: Salvation has wrong Techlevel (not wrong category.Tech)

effects/mesh.fx
fixes the appearence of props underwater that use the VertexNormal and UndulatingNormalMappedAlpha shader (before they looked like they were above the water)
this is a modification by ozonex
=> change ordering of rendering for prop shader and water

lua/ui/dialogs/mapselect.lua, lua/ui/maputil.lua
this PR contains two changes to the map selection window:
1. the way the AI compatibility is tested for maps
instead of searching for a land path node with a specific name, search for a marker that has other markers listed as "adjacent" markers. These markers are usually path nodes (not necessarily land pathnodes). Markers with only one entry for this property correspond to chains, so searching for the separator (space) in this property yields markers with multiple adjacent markers.
2. fixes official maps being hidden by the outdated map filter
=> Improve map selection window

lua/simInit.lua
This was a hook inside my AI mod but should be part of the FAF code.
It's preloading templates for the AI from AI mods.
=> HotFix for AI mod loader

units/UAB2302/UAB2302_unit.bp, units/UEB2302/UEB2302_unit.bp, units/URB2302/URB2302_unit.bp, units/XSB2302/XSB2302_unit.bp
allows arty to shoot at higher ground
was possible before the last balance patch - so this is just a regression fix
=> fix t3 Arty targeting when shooting at higher ground

lua/defaultunits.lua
http://forums.faforever.com/viewtopic.php?f=3&t=16275
Unit can die during this "WaitTicks(1)", so check is needed.
There are some more bugs in this log (see Exotic's post). But as long as this bugs don't cause crashes - "don't touch it" :D
=> fix 'Game object has been destroyed'

units/DEA0202/DEA0202_Script.lua, units/DRA0202/DRA0202_Script.lua, units/XSA0202/XSA0202_Script.lua
Issue: https://github.com/FAForever/fa/issues/2321 and https://github.com/FAForever/fa/issues/2322
Description: The Notha, Corsair and Janus no longer slow down on the move order. Other commands will cause slow down. 
There is also similar script for t1 bombers, however I did not touch this in currect PR. 
Corsairs will no longer attack ground units on the movem whence not slow down. They will attack with patrol, attackmove, attack, or idle. 
Other bombers did not have corsair problem, but they were still slowing down in enemy range for no reason (on move command). 
I know, that you guys dont have time to review my PRs or test them, so i made i video to enhance the first one.
https://www.youtube.com/watch?v=yqKmcBocXDg&feature=youtu.be
=> Bomber speed fix.

lua/ui/lobby/chatarea.lua, lua/ui/lobby/lobby.lua
This commit adds colors and styling options (different fonts) into the lobby by making use of a new class for this chat, defined in chatarea.lua.
With this commit, people in the lobby have their name colored with their currently selected faction color. Grey if observer.
(huge thanks to hussar for the help and reviewing provided)
=> Added chat colors in the lobby depending on who's talking

units/UAS0201/UAS0201_unit.bp, units/UAS0302/UAS0302_unit.bp
TargetCheckInterval is more than RateOfFire.
Comparison with cybran:
So Omen's turrets just idling most of the time if you don't give them direct orders to attack smth. 
Replay ID: 8258690 (25 - 30 min, Robogear's navy)
*added Exodus. It has 4 sec interval and 5 sec reload time which is far from ideal too =)
=> Fix Omen's (*and Exodus) turrets

lua/sim/DefaultProjectiles.lua
Exotic found (and fixed=) a little bug in this pr #2487
Old code used all OC projectiles on map (including enemy ones) in energyLimit calculations.
=> OC little fix

lua/aibrain.lua
Possible fix provided by: `Strogo`. This should hopefully negate the AI takeover in ladder. This will need testing before merging. Not sure how we can test it but that should take care of the issue.
Addresses issue: https://github.com/FAForever/fa/issues/2571
=> Hotfix for AI Replacement in Ladder

lua/SimUtils.lua, lua/sim/Unit.lua, lua/ui/game/unitview.lua
vet 2,3,4,5 units become vet 1 after transfer because of this code
```
-- Limit the veterancy gain from one kill to one level worth
massKilled = math.min(massKilled, self.Sync.myValue)
```
now there is separate function for transferred units.
Also added massKilledTrue value (which is used by "Mass killed" feature) to the transfer process, so now it will be displayed for transferred unit too. And fixed little UI bug (If you select full veted unit and after that select smth else, then "Mass killed" text won't change to "Veterancy")
=> Fix units lose veterancy after transfer

engine/Core.lua, lua/AI/AIBuilders/AIEconomicBuilders.lua, lua/AI/AIBuilders/AILandAttackBuilders.lua, lua/AI/AIBuilders/AISeaAttackBuilders.lua, lua/AI/AIBuilders/SorianEconomicBuilders.lua, lua/AI/AttackManager.lua, lua/AI/aiutilities.lua, lua/AI/sorianutilities.lua, lua/EffectUtilities.lua, lua/defaultantiprojectile.lua, lua/editor/MarkerBuildConditions.lua, lua/editor/SorianBuildConditions.lua, lua/editor/ThreatBuildConditions.lua, lua/editor/UnitCountBuildConditions.lua, lua/platoon.lua, lua/sim/Builder.lua, lua/sim/EngineerManager.lua, lua/sim/FactoryBuilderManager.lua, lua/sim/Unit.lua, lua/ui/lobby/lobby.lua, lua/upgradetemplates.lua
Again an AI only fix :)
I fixed some engineer assist functions and the sorian custom unit replacement function.
Also added better error messages for ACU enhancments and some AI functions.
Changelog:
AIEconomicBuilders.lua
Added AssisteeType to Builder `T1 Engineer Find Unfinished`
------------------------------------------------------------------------------------
AILandAttackBuilders.lua
function LandAttackCondition()
-Fix: Added check for missing locationmanager 
------------------------------------------------------------------------------------
AISeaAttackBuilders.lua
function SeaAttackCondition()
-Fix: Added check for missing locationmanager 
------------------------------------------------------------------------------------
SorianEconomicBuilders.lua
-Fix: Added AssisteeType to …
=> AI Patch V2

lua/GameColors.lua
… other colour
You can see the new colour on the right here : 
(img)https://i.imgur.com/P1iCPY0.jpg
I put it with the nearest colours available (light blue, grey, blue) and it visually conflicts with none.
=> remove player color that is to close to civilian one

units/XSL0401/XSL0401_Script.lua
[Issue#1260](https://github.com/FAForever/fa/issues/1260) Ythotha fix destroy
Refactored code in fa/units/XSL0401/XSL0401_Script.lua
Changed:
1. Move lightning spawn from OnDestroy to OnReclaimed
2. Spawn lightning in DeathThread as original
3. Add defuse lightning from owner by reclaim
4. Call Unit:Destroy() not spawn lightning [as wanila]
This commits add lightning after reclaim Ythotha unit by any army (not owner). But it work more correctly then this [commit 1449dc5a3450b4cb497d20439969f0736ff6c784](https://github.com/FAForever/fa/commit/1449dc5a3450b4cb497d20439969f0736ff6c784) without using duct tape [IsBeingTransferred](https://github.com/FAForever/fa/commit/810ffcc30af98701374bd2588fbdc61d911a605b#diff-978e442e90e99e5cab1d4e27bd351351). Also not spawn lightning on Unit:Destroy() …
=>  [Issue#1260] Ythotha fix destroy

lua/sim/ScenarioUtilities.lua
Small fix for PR #2544 . Now naval on shallow water doesn't rotate
=> Naval on shallow water doesn't need to rotate

lua/terranunits.lua
"attempt to loop over field `PodData' (a nil value)"
=> Kennel hotfix

etc/faf/blacklist.lua
adds the Better Allies and the No Friendly Fire Collision V2 mods to the mod blacklist since projectile collision with friendly units is removed anyway (since 3699)
=> update mod blacklist

lua/terranweapons.lua, units/XEA0002/XEA0002_unit.bp
changing the script like that lead to mods that hook
defaultprojectileweapon to change something in there, have ambiguous
class definitions which is very difficult to fix if you dont know what
you are doing, and it locked out a bunch of modding opportunities. to
prevent this, there is a script free way of doing the same thing, with a
blueprint value.
what this really does is highlight the need to refactor the weapon
class. this only works because the Main function inside idle state waits
for the recoil manipulators, which lasts until the beam is destroyed via
the thread. its a complete mess really. but thats how all beam units
work.
there should be a proper blueprint value to end beam on retarget or not,
and the recoil should not stall the beam end sequence.
=> Fix Novax crashing other mods

lua/ui/lobby/changelog.lua
Every UI in the world ptus the "OK" button in a dialog box (or Close) in the bottom right corner.
https://www.google.fr/search?safe=off&tbm=isch&source=hp&biw=1910&bih=961&ei=J-MxXPbcLrKPlwTkmoL4DA&q=dialog+box&oq=dialog+box&gs_l=img.3..0j0i30l9.324.1065..1144...0.0..0.103.702.8j1......0....1..gws-wiz-img.....0..0i10.Icb9MVit33M#imgrc=1n5ta9JZZ2UPKM:
"More details" buttons and all should be on the other side of the window, or at the left of such button.
I keep pressing the wrong button by reflex when I want to close the window and I think that means the window isn't very intuitive to use.
sure your changes are rebased onto [development/balance] …
=> github and close button are now reversed

units/UAB2303/UAB2303_unit.bp, units/UEB2303/UEB2303_unit.bp, units/URB2303/URB2303_unit.bp, units/XSB2303/XSB2303_unit.bp
Making t2 arties a little less good and making sure they are used for their original purpose: Long range shelling. Min range = t2 pd max range
All t2 arties: Min range: 5 > 50
=> Increasing t2 arty minimum range

units/URL0203/URL0203_unit.bp, units/XRL0305/XRL0305_unit.bp, units/XSL0303/XSL0303_unit.bp
Making the torpedo worth not being a complete joke anymore.
ratio dps/mass : 0.15 for wagner; 0.1 for brick/othuums
comparison : 0.4 T1 subs, ~0.18 for destro (apart uef) but they also have good anti-torp, range and vision advantage; 0.4 T2 subs + they have antitorp, range/vision (possibly stealth) advantage
=> useful torpedo on amphibious unit

lua/ui/dialogs/hotstats.lua
In case there is no data available at the endscreen, we have no exit button.
This PR will add one.
If the game was launched from FAF it will show "Exit to FAF".
If launched from desktop it will show "Continue".
=> Adds exit button to endscreen

lua/simInit.lua
Only load AI templates from mods if the mod is enabled.
=> Fix AI mod templates are loaded even if mod is disabled

lua/SimUtils.lua
I just forgot to import createWreckage() function, so in some situations transfer stops and all units stay in dead army. Also added check for units which interfere construction.
=> Fix unfinished units transfer in fullshare games

lua/sim/Unit.lua
Fixes a bug where you could create a free resource by pausing a builder
after it built at least one 1 unit.
=> Update consuption values on paused only when building

units/URL0402/URL0402_script.lua, units/XES0307/XES0307_script.lua
so, if you called OnKilled on the ML and battlecruiser after they were
killed, then bad things happened since GetWeapon doesnt work on dead
units.
this removes the possibility of that happening.
done for clean code and mod support reasons.
=> Check for dead status before killing beams

lua/sim/Unit.lua
pretty much what it says on the tin. This allows blueprints to have
TransportAnimationSpeed and TransportDropAnimationSpeed which can
configure the rates at which the animations play. If they are missing,
the code assumes default behavior, so its backwards compatible.
this is for mod support reasons.
=> Enable transport rates to be set vs blueprint

lua/victory.lua
Uncompleted units will no longer count for end game conditions.
Also we don't really need to know how many units are alive, we only need to know if at least 1 unit is not dead.
So i renamed the function CountCurrentUnits to AllUnitsInCategoryDead.
The function is now returning true or false instead of a unitcount.
This way we only need to find the first unit and break the search loop, instead of looping over all units.
=> Optimized unitcount for VictoryConditions.

projectiles/AIMAntiTorpedo01/AIMAntiTorpedo01_proj.bp, projectiles/AIMAntiTorpedo01/AIMAntiTorpedo01_script.lua
Copy values from sera torp defence to aeon torp defence used by frigate and destroyer.
Currently Beacon and Exodus torp defence is unable to intercept incomming projectiles and calculates impact point after the targetted unit. This change makes torp defence a little more reliable at defending nearest units. Just like sera torp defence or Vesper. Although doesn't solve the problem entirely.
Adds cosmetic behaviour from sera torp defence. When target is lost the projectile loses its speed and dies.
https://youtu.be/kvvDlgi49mY
=> Aeon torp def

lua/defaultunits.lua
Uveso reported that immobilization breaks AI. Now we do it only for player's ACUs.
https://github.com/FAForever/fa/pull/2733
=> Use SetImmobile only for player's ACU

units/XEB2402/XEB2402_unit.bp
The Novax has "land" as background icon but sould have "air" like air-factories.
=> Fix Novax Background Icon

etc/faf/blacklist.lua
Changed label for Experiemtnal Wars from BROKEN to UPGRADE, because we have a newer version in our vault.
=> Modblacklist exp war

lua/ui/dialogs/teamkill.lua
increases the time someone has to wait to create a teamkill report from 3 to 10 seconds
currently 9/10 reports are just people getting blown up by chain reactions eg by standing too close to t3 pgens of a teammate -> teammate dies -> pgens blow up -> user dies as well -> not a teamkill and just a massive waste of my time
=> increase teamkill report wait time

units/XRB0104/XRB0104_unit.bp, units/XRB0204/XRB0204_unit.bp, units/XRB0304/XRB0304_unit.bp
Since build bots are calculated from the build power, hives don't have
1/2/3 bots anymore but 3/4/6
One per 15 build power
Fixes #2715
=> Fix Hives build effects

lua/defaultunits.lua
- Load unit into Stinger
- Load Stinger into any Naval Aircraft Carrier (Czar doesn't work)
- When Carrier dies, we get invulnerable, invisible units capable of attacking
This was caused by the engine Kill() command calling SetDead() before the detach/kill code was called, so the `if not self.Dead` safety check backfired and prevented the proper handling. 
This PR refactors some duplicated loop code, moves it into BaseTransport for inheritance, and adds a Kill() override to AircraftCarrier, fixing the bug.
Please test as many combinations of units inside units inside units as you can think of. Of concern I don't have time to check right now:
- Fatboy
- Air Staging
=> Fix invulnerable sub-carried units

units/URL0402/URL0402_script.lua
=> Fix ML exhaust effects playing during construction

units/URB0201/URB0201_unit.bp
Could fix Fixes #2784
The BP has a target bone from a T1 factory.
Comparing visually the position of the bones, this could fix the issue.
Untested, go crazy.
=> Fix target bones of Cybran T2 Land HQ

lua/sim/Unit.lua
Fixes #2836
It was added
https://github.com/FAForever/fa/commit/0e1540799e7a69843cb61bc694fb3c230cd8af1e#diff-7d1c65a3fbe3fe1c1cf7016d8b83b162
but I see no explanation why.
=> TryCopyPose for unit without death animation as well

units/UAL0401/UAL0401_unit.bp, units/UAS0302/UAS0302_unit.bp, units/UEL0001/UEL0001_unit.bp, units/UES0302/UES0302_unit.bp, units/URA0401/URA0401_unit.bp, units/URL0104/URL0104_unit.bp, units/URL0203/URL0203_unit.bp, units/XSS0302/XSS0302_unit.bp
Adds LOD1 model to be used for some units which have the model and textures and look decent enough (like other units LOD1 models that exist)
=> Use LOD1 models

lua/terranunits.lua
Some clean up + fix for UEF factory build arms
=> Cleanup terran units file

etc/faf/blacklist.lua
this is rather annoying since people keep trying to use it, and its
completely messed up. This doesnt even show up in the mods list ingame!
its been hidden in the mod vault but whoever still has it might still
think its a great idea to try and use it.
=> Blacklist old nomads version

units/UEA0305/UEA0305_unit.bp, units/XRA0305/XRA0305_unit.bp
- add 'OVERLAYCOUNTERINTEL' to uef t3 gs
- remove 'OVERLAYCOUNTERINTEL' from cybran t3 gs
fix #2861
=> fix T3 uef gs jammer ring

lua/sim/Unit.lua
if a wreck was created (unit killed after 50% completion) air facto would start construction of the same unit with 50% done already.
fix #2386
=> fix air facto rebuild on wreck

env/Swamp/Props/Rocks/boulder01_prop.bp
I missed one fix in the Supreme Props integration. The 10 energy of the boulder/rock should be removed. The value should be 0 like all the other rocks.
See here: https://user-images.githubusercontent.com/28671151/57193683-2e7b5180-6f3e-11e9-9e24-cf2af24384e7.png
=> Supreme Props: Added missing fix

lua/sim/Buff.lua, units/XSL0001/XSL0001_script.lua, units/XSL0001/XSL0001_unit.bp
As per call changed the slots of regen field and ras around (I know there is an open PR for it but it seems to be missing a few lines of upgrade VFX code.)
Rebalanced to have a regen ceiling based on a tech level as opposed to a shared one.
Regen field ceilings:
* T1 - 10
* T2 - 15
* T3 - 25
* T4 - 40
Advanced regen field ceilings:
* T1 - 20
* T2 - 50
* T3 - 120
* T4 - 240
=> Sera ACU regen field rework

units/UAA0101/UAA0101_unit.bp, units/UAA0302/UAA0302_unit.bp, units/UEA0101/UEA0101_unit.bp, units/UEA0302/UEA0302_unit.bp, units/URA0101/URA0101_unit.bp, units/URA0302/URA0302_unit.bp, units/XSA0101/XSA0101_unit.bp, units/XSA0302/XSA0302_unit.bp
T3 air scout : 
- speed nerf from 28 to 25
- turnspeed nerf from 0.8 to 0.6
T1 air scout : 
- turnspeed nerf from 0.8 to 0.6
=> Air scout nerf

units/UEA0305/UEA0305_unit.bp, units/XRA0305/XRA0305_unit.bp
makes T3 gunship harder to rush. They nearly had same stat ratio as their T2 counter part. Need to lose efficiency for their beefiness.
mass cost : from 1260 to 1500
e cost : from 42000 to 65000
=> T3 gs nerf

lua/sim/score.lua, lua/ui/dialogs/hotstats.lua, lua/ui/game/layouts/score_mini.lua, lua/ui/game/score.lua
Present three mode display resources.
Switch button located below energy icons.
I - Income (default), B - Balance, S - Storage
Transferring mass, energy, units on click with Shift and
request him with Ctrl.
Add display map size and replay ID.
Fixed formatted negative values displayed resources.
=> Add allies resources balance to scoreboard

units/DEL0204/DEL0204_unit.bp
tested so sera T2 pd and rhino can hit them.
SizeZ = 0.7 is enough for sera pd; but SizeZ = 1 is needed for rhino.
=> fix mongoose hitbox

loc/US/strings_db.lua, lua/ui/lobby/lobby.lua, lua/ui/lobby/lobbyOptions.lua
New optimal, mirrored option
For example, if you're ranked `#1` in your team you will be against the guy ranked `#1`  in the opposite spot.
Won't work on maps where spots aren't in logical order, I'm too lazy to start calculate mirrors by looking at left / right / top bottom option  + the x,y positions on the map
Needs testing
=> Add new optimal / mirrored spawn

lua/AI/AIAddBuilderTable.lua, lua/AI/AIBaseTemplates/NavalExpansionLarge.lua, lua/AI/AIBaseTemplates/NavalExpansionSmall.lua, lua/AI/AIBaseTemplates/RushExpansionAirFull.lua, lua/AI/AIBaseTemplates/RushExpansionAirSmall.lua, lua/AI/AIBaseTemplates/RushExpansionBalancedFull.lua, lua/AI/AIBaseTemplates/RushExpansionBalancedSmall.lua, lua/AI/AIBaseTemplates/RushExpansionLandFull.lua, lua/AI/AIBaseTemplates/RushExpansionLandSmall.lua, lua/AI/AIBaseTemplates/SorianExpansionAirFull.lua, lua/AI/AIBaseTemplates/SorianExpansionBalancedFull.lua, lua/AI/AIBaseTemplates/SorianExpansionBalancedSmall.lua, lua/AI/AIBaseTemplates/SorianExpansionTurtleFull.lua, lua/AI/AIBaseTemplates/SorianExpansionWaterFull.lua, lua/AI/AIBaseTemplates/SorianMainAir.lua, lua/AI/AIBaseTemplates/SorianMainBalanced.lua, lua/AI/AIBaseTemplates/SorianMainRush.lua, lua/AI/AIBaseTemplates/SorianMainTurtle.lua, lua/AI/AIBaseTemplates/SorianMainWater.lua, lua/AI/AIBaseTemplates/SorianNavalExpansionLarge.lua, lua/AI/AIBaseTemplates/SorianNavalExpansionSmall.lua, lua/AI/AIBaseTemplates/TechExpansion.lua, lua/AI/AIBaseTemplates/TechExpansionSmall.lua, lua/AI/AIBaseTemplates/TurtleExpansion.lua, lua/AI/AIBuilders/AINavalBuilders.lua, lua/AI/AIBuilders/SorianNavalBuilders.lua, lua/AI/aibuildstructures.lua
`Fix for AI Base templates:`
GPG AI Tech had no expansion template for `Expansion Areas` or `Large Expansion Areas`.
(It's now using the existing expansion template for all expansions)
Also fixed an issue where the GPG AI was using a sorian expansion template.
(changed expansion function return value to -1 for sorian templates)
Left some (inactive) debug lines for other AI developers ^^
(only way to see the actual used expansion template)
---
`Added check for naval expansions:`
Added new buildcondition to all naval expansion builders to respect naval expansion count from game options
=> Fix for AI Base templates

units/UAA0302/UAA0302_unit.bp, units/UAA0303/UAA0303_unit.bp, units/UEA0302/UEA0302_unit.bp, units/UEA0303/UEA0303_unit.bp, units/URA0302/URA0302_unit.bp, units/URA0303/URA0303_unit.bp, units/XSA0302/XSA0302_unit.bp, units/XSA0303/XSA0303_unit.bp
- to reduce the need of ASF spam
- to make droping a bit more prevalente even if T3 air is in the game
- to make air exp less easy to snipe
- some speed tweaking might be needed for T3 scout/strat, although ASF still have 5 more speed than strat.
=> ASF rebalance

init.lua
Right now, mods cannot change some ui textures, as game is hardcoded to read them from "/textures/ui" directory. This particularily impacts ability to change or add strategic icons. The only way to do it is to pack them into an .scd and drop it into gamedata folder - which means installing mods from the mod vault requires additional manual step. This code change fixes that.
Reference to the forum post:
https://forums.faforever.com/viewtopic.php?f=45&t=18453#
=> Mounting ui textures from mod directories

units/UAA0310/UAA0310_unit.bp, units/UAL0401/UAL0401_unit.bp, units/UAS0305/UAS0305_unit.bp, units/UAS0401/UAS0401_unit.bp, units/UEL0401/UEL0401_unit.bp, units/UES0305/UES0305_unit.bp, units/UES0401/UES0401_unit.bp, units/URA0401/URA0401_unit.bp, units/URL0401/URL0401_unit.bp, units/URL0402/URL0402_unit.bp, units/URS0305/URS0305_unit.bp, units/XRL0403/XRL0403_unit.bp, units/XSA0402/XSA0402_unit.bp, units/XSB3202/XSB3202_unit.bp, units/XSL0401/XSL0401_unit.bp
adding a cat that have been introduce with an exe update to reduce the priority of selection of mobile exp/sonars when being built.
i added the category only to mobile exp/sonar since T4 arties, para and novax doesn't have the selection issue.
This issue was brought when introducing CQUEMOV with exe patch to allow the selection of mobile exp/sonars under construction (in order to give rally point order for example) and to give attack order to pds (when their construction isn't yet finished)
worth noting : unfinished T4 building are selected over unfinished mobile exp/sonars, apart paragon that is selected last.
=> make selection of mobile exp/sonar under construction act as building

lua/AI/OpAI/BaseManager.lua, lua/SimCallbacks.lua, lua/SimUtils.lua, lua/aibrain.lua, lua/defaultunits.lua, lua/overspill.lua, lua/selfdestruct.lua, lua/sim/CalcBallisticAcceleration.lua, lua/sim/weapon.lua, lua/terranweapons.lua, schook/lua/SimSync.lua
EntityId is saved in the unit on creation, so this is faster than
calling an engine function. Works only in sim on unit entities.
=> Use saved EntityId from the unit

units/UAL0307/UAL0307_unit.bp, units/UEL0307/UEL0307_unit.bp, units/XSL0307/XSL0307_unit.bp
Tweak shield GuardScanRadius and maxrange so they stop just behind the unit they are most likely to be partnered with instead of stopping short and not covering anything
=> Tweak mob shield attack move stop range

units/UAL0101/UAL0101_unit.bp, units/UEL0101/UEL0101_unit.bp, units/XSL0101/XSL0101_unit.bp
Set a GuardScanRadius for t1 scouts with weapons so they don't run into enemy units but shoot from proper range.
Might be worth it to look into the code that auto-sets this to see why they aren't affected and if there are other units that might suffer from the same problem. I _might_ do it later.
=> t1 scout attackmove range hotfix

units/UAS0305/UAS0305_unit.bp, units/UES0305/UES0305_unit.bp, units/URS0305/URS0305_unit.bp
T3 sonar is very cheap, and can even get supported on T1 pgen. Forcing player to get at least a T2 pgen should be the very least we can do.
also might promote the use of T2 sonar a little bit more (for the transition period).
=> increase energy drain of T3 sonar

units/UAL0105/UAL0105_unit.bp, units/UAL0208/UAL0208_unit.bp, units/UAL0309/UAL0309_unit.bp, units/UEL0208/UEL0208_unit.bp, units/UEL0309/UEL0309_unit.bp, units/URL0105/URL0105_unit.bp, units/URL0208/URL0208_unit.bp, units/URL0309/URL0309_unit.bp, units/XSL0105/XSL0105_unit.bp, units/XSL0208/XSL0208_unit.bp, units/XSL0309/XSL0309_unit.bp
Should help some with annoying pathfinding shit when building bases with lots of 5x5 buildings.
Would have to be approved by balance team so feel free to close this PR if declined
T1 build range is still 5 (was the default if not set)
=> Increase engineer build distance by 1 per level

lua/defaultunits.lua
StartBuildingEffects is called from Unit.OnStartBuild so this was
actually calling it second time.
In game it was almost not noticable, since the the effect was just
brighter since there were 2 same emitters on top of each other doing the
same thing.
=> Fix building effect playing twice for command units

units/UES0202/UES0202_unit.bp, units/XES0205/XES0205_script.lua, units/XES0205/XES0205_unit.bp
Before:
After:
Before:
After:
Before:
After:
=> Fix UEF Navy UI things

units/UAL0201/UAL0201_unit.bp
Auroras were firing their first shot before barrel could be fully aligned with their target, missing their first shot quite frequently. And with low fire rate and paper armor, that is a significant detriment to their effectiveness. This change forces Auroras to complete their aim before firing a shot.
Fixes issue:
https://github.com/FAForever/fa/issues/2924
=> Fix Aurora missing first shot 

lua/ui/controls/ninepatch.lua
Fixes #2996
With the trial and error I found out this line causing the most problems. If you test it (described in the linked issue) you get much better performance. Changelog not causing any load anymore. Going into map selection is still more expensive, but if you go to unit restrictions, you get no lag anymore.
The thing is I don't know what SetTiled(true) does, can someone tell me?
=> Don't set the center background Tiled in the popout window

lua/terranunits.lua, units/XEA3204/XEA3204_script.lua
Old Issue; if you build more than 30 kennels and upgrade them at the same time, it was freezing the game for 2-3 seconds when new drones spawns.
The lag came from a table.deepcopy function that was making a deepcopy of the drone data.
The deepcopy was not only making a copy of the unit, it also did a copy of platoondata, Brain and all other tables that where only present by a pointer.
This was also triggering a error after several hours of playtime:
```
WARNING: Error running OnStopBuild script in Entity xeb0104 at 7c42e708: ...:\programdata\faforever\repo\fa\lua\system\utils.lua(91): stack overflow
...:\programdata\faforever\repo\fa\lua\system\utils.lua(91): in function `deepcopy'
...:\programdata\faforever\repo\fa\lua\system\utils.lua(102): in function `deepcopy'
``` …
=> Fix Kennel lag and animation

lua/aeonunits.lua, lua/seraphimunits.lua
happened when unit inside sera/aeon factories died and then we pause/unpause
logs : 
`WARNING: Error running OnPaused script in Entity uab0201 at 22247308: c:\programdata\faforever\repo\fa\lua\aeonunits.lua(50): attempt to call method 'Add' (a nil value)
c:\programdata\faforever\repo\fa\lua\aeonunits.lua(50): in function 'StartBuildFx'
c:\programdata\faforever\repo\fa\lua\aeonunits.lua(153): in function 'StartBuildFx'
c:\programdata\faforever\repo\fa\lua\aeonunits.lua(58): in function 'OnPaused'
c:\programdata\faforever\repo\fa\lua\aeonunits.lua(157): in function <c:\programdata\faforever\repo\fa\lua\aeonunits.lua:156>
[C]: in function 'SetPaused'`
`WARNING: Error running OnUnpaused script in Entity uab0201 at 22247308: …
=> Fix error when pausing/unpausing factory

lua/sim/weapon.lua, lua/system/class.lua
This PR contains 2 key changes
- Removing the asserts that happen on state changes (this happens ~8 times or something like that per weapon firing cycle)
- Caching the projectile data in the weapon (and correctly invalidating it) instead of recreating it on every shot
Both changes have been tested in my Simspeed++ mod for a few months now and have not caused any issue.
Getting good data on how much it helps is hard, for comparison for the sake of this PR I ran replay 11042968 at the max speed with and without those changes in it.
Without them it took 29min 30sec
With them it took 27min 30sec
Giving a roughly 7% speedup in a real game (a fairly short and casual ~1.2k setons)
=> Misc Performance Enhancements

lua/cybranunits.lua, lua/sim/Unit.lua
Untested, might have side effects of breaking up something else. Up to the testers to find out all possible combinations of building and assisting.
=> Update units consumption values only if building something

lua/ui/game/gameresult.lua
When any player dies, the focus army switches to the observer. Prevented.
=> Prevented unnecessary focus changes when cheats are enabled

lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/keymap/selectedinfo.lua, lua/options/options.lua, lua/ui/game/gamemain.lua
This code was added to fix issue #94 or at least to make it less harmful. But code logic is broken and doesn't work as intended.
Also idea is bad overall, cause if you have 'global' rings disabled and this code works as intended, then you can't see any rings for multiple selected units at all.
And it's 2020 after all, gpus are good enough to handle range rings in most cases + we did some optimisations in engine.
-----------------Testing-------------------
As I said, the code logic is broken and removing this code won't affect anything. Some basic tests: select units with `Selection rings on` then with `Selection rings off` and things like that.
=> SingleRangeOverlay cleanup

init.lua, lua/system/Blueprints.lua, lua/ui/lobby/lobby.lua
This requires a change to the init file. running this without the init
file should result in no changes - nothing breaks but no new features.
This adds support for custom props, and more to maps, and allows passing
arbitrary data to blueprints.lua, which is insanely useful and has been
a limitation for a long time.
Currently this is only used to load the custom content in the current
map, but mods and maps could do loads of stuff with it. Such as:
1. adding mod settings to turn off/on changes
2. adding map settings for optional features, and props.
3.mods can edit the logic by hooking modblueprints, and so can have
total control over which parts of themselves get loaded.
a note on security - this might sound like it creates a hole but it
doesnt let you break anything that couldnt be …
=> Add support for custom map Props

init_faf.lua, init_fafdevelop.lua
Extends init.lua
Mounting foreground folder 'bin\\..\\DevData'
It mounts an optional folder for development/testing.
Files from it have priority over all others.
init.lua and init_fafdevelop.lua for develop builds are identical(the server is in a mess).
This uses init.lua to get rid of copy-paste and does not make any other changes.
Why these files( init.lua, init_faf.lua, init_fafdevelop.lua ) are not being deployed from deploy/fafdevelop repo?
=> init_fafdevelop.lua

lua/ui/dialogs/eschandler.lua, schook/lua/UserSync.lua
Fixes #3031.
Works like a charm. If our instance of FA closes via `Exit to FAF` then that will be picked up by the other players in the game and our `defeat` result will be reported appropriately, but we won't be spamming bogus `defeat` results for the other remaining players.
=> Issue/#3031 Don't send results after initiating a `SafeQuit`.

lua/ui/game/missiontext.lua
To reproduce the problem, delete the movies folder and launch the scenario.
As a consequence of this fix if video dialogue is broken, text dialogue is show.
It not adds desyncs and not eliminate them.
History:
The game only plays unpacked videos.
Videos from gamedata are found but not played. The sound also does not play.
Problem in any SC1 scenario. For example Joust.
After switching to Win 10 and reinstalling FAF, the problem disappeared.
=> Corrects text display if video doesn't play

lua/ScenarioFramework.lua
Removed re-calling OnKilled event.
To see the error, you need to put the WARN in the PlayerDeath function and destroy the ACU in Coop.
=> Added PauseUnitDeath control

lua/maui/window.lua
Some windows have the default position by numbers and some by functions. Gotta cover both cases, once is saved in the game.prefs, it's always numbers.
Fixes #3051
=> Fix broken scaling of default position of the chat

units/UAL0303/UAL0303_unit.bp
1.85 -> 2
These numbers are functionally the same because the game works in ticks which are 1/10 of a second but a rof of 2 requires no rounding.
=> update harb rateoffire to accurately represent behaviour

lua/ui/game/construction.lua
The whole code for the bigger strategic icons is a ugly hook from some mod instead of a proper implementation, so I'm not ashed with this solution for now.
=> Fix bigger strat icons

loc/DE/strings_db.lua
The name of the unit xss0304 was missing in the german translation.
(Yathsou)
=> Fixing NukeSubname (Yathsou) in german translation

lua/defaultunits.lua
This one fixes a minor visual bug.
Destroying a structure spawns a new tarmac with a limited lifetime. When this new tarmac is created when the unit is destroyed it will spawn over the explosion decal. Calling it together with OnKilled places it under the explosion decal, so it looks like the explosion decal appeared over the tarmac (like it should be).
=> Fix tarmac spawning

units/URS0305/URS0305_unit.bp
- nerf sonar stealth from 90 to 70
- buff radar stealth from 45 to 70
get the same range for both stealth, so it makes sense ui wise when displaying the stealth range.
=> rebalance T3 sonar stealth

lua/maui/window.lua
To reproduce the error, place the minimap on the edge of the window and reduce,
and then increase window size.
The right side of the map sticks to the window and stretches with it.
The chat window behaves the same way.
=> Window Resize Fix

lua/ui/dialogs/eschandler.lua, schook/lua/UserSync.lua
New idea, use existing `RequestingExit` property of the Sync table to selectively ignore results. I found this property after tracing what happens when a user clicks the "Score" button, as this turns out to be another way of causing the false results. I suspect it can happen whenever the simulation is stopped early, which probably causes the engine to set all players to "defeated" for a brief moment before exiting. However, I am also hoping that this same code will also be setting the `RequestingExit` property at the same time, and that we can use this to ignore results. 
Still needs to be tested.
Hopefully fixes #3087.
=> Issue/#3087 Result reporting on 'Exit to Windows` fix

lua/MODS.LUA
The existing implementation of mod sorting seems to have several issues:
* `ModComp` comparison does not check the before and after lists of the
second argument
* sorting relies on `table.keys` from `lua/system/utils.lua` and through
it on builtin `table.sort`, which assumes that an order between any pair
of elements can be established directly, which is not the case of mods
(for example if `mod2` depends on `mod1` and `mod3` depends on `mod2`,
`ModComp` looking at before/after lists of `mod1` and `mod3` will not be
able to establish a relationship between them correctly)
* there appears to be no functionality to log a warning if mods declare
an inconsistent ordering, contrary to the specification on top of the
`lua/MODS.LUA` file
This change introduces a new function `ModTopSort`, which …
=> add topological sorting for mods

lua/ui/dialogs/score.lua, lua/ui/game/missiontext.lua
This allows super easy hooking for mods to add custom entries (including nomads) for both the in game videos and the score screen.
=> Move faction data out of the functions

units/UEB5101/UEB5101_unit.bp
Fixes the UEF wall segment wreck only having 20% hp rather than 90% like all other units and walls.
=> Fix UEF Wall Reclaim Multipliers

lua/ui/lobby/lobby.lua
This addresses issue #3136.
The default map options are being marked, but not loaded if not manually set. Added a small piece of code that on launch checks whether the map options are set, and if not, sends along the marked defaults.
Code such as:
``` lua
if (ScenarioInfo.Options.RainmakersMobileStealthFieldGens == nil) then
ScenarioInfo.Options.RainmakersMobileStealthFieldGens = 2
WARN("Options: RainmakersMobileStealthFieldGens is not set.");
end
```
Which checks whether a map option is set which resides in the <map-name>_options.lua file is therefore no longer required for FAF, it would still be required for Steam FA.
=> Load in the defaults of map options if an option is not set

engine/Sim/CAiBrain.lua, lua/AI/AIBehaviors.lua, lua/AI/AIBuilders/SorianStrategyBuilders.lua, lua/AI/AttackManager.lua, lua/AI/aiarchetype-managerloader.lua, lua/AI/aiattackutilities.lua, lua/AI/aibuildstructures.lua, lua/AI/aiutilities.lua, lua/AI/sorianutilities.lua, lua/aibrain.lua, lua/cybranunits.lua, lua/defaultunits.lua, lua/formations.lua, lua/platoon.lua, lua/sim/BuilderManager.lua, lua/sim/EngineerManager.lua, lua/sim/ScenarioUtilities.lua, lua/sim/Unit.lua, lua/system/Blueprints.lua, units/UEL0001/UEL0001_script.lua, units/UEL0301/UEL0301_script.lua, units/XRB2308/XRB2308_script.lua, units/XRB2309/XRB2309_script.lua
(Rebased 25.May)
(Rebased 10.Aug)
Finally this patch will fix the game slowdown on long AI games.
Reason for the slowdown was the engineermanger while ping pong forking functions.
This was causing in the end a engine slowdown a finally a stack buffer overrun.
This patch also stores almost every forked thread to the corresponding unit/weapon,
so it can be destroyed on unit dead to prevent parentless threads.
The transport function is now using surfaceghight for the transportation target
for faster unit drops.
Also fixed an issue where the ACU is not moving on gamestart.
This was caused by the `BlockCommandQueue` from the ACU WarpInAnimation
Changelog: (updated 06.Jun)
------------------------------------------------------------------------------------
CAiBrain.lua
-Upd: fixed/updated some …
=> AI Update V8

units/UAA0302/UAA0302_unit.bp, units/UAA0303/UAA0303_unit.bp, units/UAA0304/UAA0304_unit.bp, units/UEA0302/UEA0302_unit.bp, units/UEA0303/UEA0303_unit.bp, units/UEA0304/UEA0304_unit.bp, units/UEA0305/UEA0305_unit.bp, units/URA0302/URA0302_unit.bp, units/URA0303/URA0303_unit.bp, units/URA0304/URA0304_unit.bp, units/XAA0305/XAA0305_unit.bp, units/XAA0306/XAA0306_unit.bp, units/XEA0306/XEA0306_unit.bp, units/XRA0305/XRA0305_unit.bp, units/XSA0302/XSA0302_unit.bp, units/XSA0303/XSA0303_unit.bp, units/XSA0304/XSA0304_unit.bp
T3 scout from 100 to 150 damage and 1 aoe to 2 aoe
ASF stay at 200 damage and get from 1 to 2 aoe
strat stay at 500 damage and get from 1 aoe to 2 aoe
uef T3 gunship stay at 300 damage and get from 1 aoe to 2 aoe
cybran T3 gunship / resto get from 100 to 300 aoe and get from 1 aoe to 2 aoe
solace get from 150 damage to 400 damage, and get from 1 aoe to 2 aoe
T3 transport get from 25 damage to 500 damage, and from 3 aoe to 4 aoe
=> improved T3 air crash

engine/Sim.lua, lua/ScenarioPlatoonAI.lua, lua/platoon.lua, lua/utilities.lua
Introducing an alternative approach to move platoons around. The current approach forces the platoon to orient to the south at the end of every move order.  The new approach either aligns them to the line between the current and next node (...ByFuture) or between the current and past node (...ByPast).
To showcase, see the following video:
https://www.youtube.com/watch?v=e4LH9oaKwTQ
The video becomes especially interesting about 30 seconds in, when the platoons are moving to the north.
From the outer to the inner line:
- (new) platoon:MovePathOrientedByFuture(...)
- (new) platoon:MovePathOrientedByPast(...)
- (old) platoon:MoveToLocation(...)
- (old) platoon:Patrol(...)
Especially platoon:MovePathOrientedByPast(...) (2nd from the outer one) is promising: it appears to be very smooth and is …
=> Platoon movement

lua/system/utils.lua
I discovered that many functions in this file are are implemented in a very inefficient way. These two were just the easiest to fix, which is why I took a few seconds of my time to do so.
The new `table.empty` no longer needs to iterate over the whole table to know whether it's empty. It's therefore O(1) as opposed to O(n).
The new `math.round` no longer converts the value to a string and back again. It also supports using negative values to round to the nearest digit on the left side of the decimal point, as opposed to only allowing positive values to round to sub-decimal values.
Quick performance comparison of math.round
```
old round 5,000,000 iterations:	4.74 sec
new round 5,000,000 iterations:	0.628 sec
```
=> increase performance of table.empty and math.round

lua/ui/controls/resmappreview.lua, lua/ui/lobby/lobby.lua
Fixes #3186 
This change adds an option to not spawn the resource and spawn markers in the spawn preview. It introduces a boolean variable hidePreviewMarkers in the scenarioInfo of a map that is used to determine whether or not the preview should include markers.
This allows the determination to be made on a map by map basis.
=> Add option to hide resource markers on preview

lua/cybranweapons.lua, lua/sim/defaultweapons.lua, lua/sim/weapon.lua
Some were pretty obvious, just save the first call in a local variable and reuse.
Then saving some values directly in the weapon table and reusing them.
=> Reduce GetBlueprint() calls in weapons

lua/EffectUtilities.lua, lua/terranunits.lua, units/UEL0001/UEL0001_script.lua, units/UEL0301/UEL0301_script.lua
Changes logic of the UEF build beams.
This way it will never happen that we would have slice beams without the building cube.
It currently changes the effect for assisting factory producing units. From slices to default beam.
I believe it looks better, since those units don't have cube. And it's also more sim friendly beam, so I'll take it!
=> Improve build effects logic

lua/EffectUtilities.lua
Why so much extra logic when using the correct function works just fine?
=> Simplify Sera effect flash at finished structure

units/XSB2401/XSB2401_unit.bp
https://forum.faforever.com/topic/523/aeon-shield-animation related
WeaponRepackTimeout 32.5 -> 20
it still shits the bed hard when you drag the order around as its shooting, seemingly locking it forever, something to look into in the future
=> Make yolo a little smoother

lua/ui/uiutil.lua
This is the port of fixes https://github.com/FA-mods/SupremeScoreBoard/pull/20.
Previously `/savereplay` cmd arg had a format of `gpgnet://localhost/uid/username.SCFAreplay`, but in https://github.com/FAForever/downlords-faf-client/commit/1ae6c7e936305f0336ecb9c324e9fc0560b843c3#diff-3d47503b30b47f5a259049a2e45e1eb555b502bd1f9cc68c936394a0d8fc6f1fR192 it has been changed to `gpgnet://localIp:localReplayPort/uid/username.SCFAreplay`, what leads a bug when in the `ID` text in score board instead of replayid there is local replay port ("magic number" `20` in `string.find(url, "/", 20)` and `string.sub(url, 20, lastpos-1)` is for length of `gpgnet://localhost/`) ¯\_(ツ)_/¯
This PR fixes this bug.
=> Fixed getting game/replay id from /savereplay cmd argument

lua/ui/lobby/lobby.lua
This removes the ability to see the large preview when map markers are hidden as otherwise the map markers are visible on the large preview when it is opened a second time
=> Remove large preview when map markers hidden

lua/defaultunits.lua
`CreateAdjacentEffect` is called twice, since there are always 2 building adjacent to each other. But the check if the adjacency beams are already created doesnt work, since the function CreateAdjacencyBeams is threaded and runs twice at the same time. Since there is no waiting inside it, it's safe to not thread it, which fixes the check for duplicates.
In the end you get only one set of effects per 2 adjacent units instead of two (they overlapped most of the time, so they were just brighter)
=> Create adjacency effects only once

lua/platoon.lua
Currently the Aeon Nuke launcher will never fire for an AI that is using this platoon function. Have corrected for the default AI and the Sorian AI NukeAI platoon function.
The default WaitSeconds time of 10 does not allow the Aeon SML enough time to complete its animation to fire a missile. This results in the default AI issuing a clear commands request and canceling the launch sequence. Increased to 12 seconds to allow time to launch missile. 
To test, spawn an Aeon T3 SML for the AI to pick up in its main base and validate missile is fired when completed.
sure your changes are rebased onto [development/balance] …
=> Fix wait on NukeAI to enable Aeon SML time to complete firing animation.

units/UAL0001/UAL0001_unit.bp, units/UAS0203/UAS0203_unit.bp, units/UEL0001/UEL0001_unit.bp, units/UES0202/UES0202_unit.bp, units/UES0203/UES0203_unit.bp, units/UES0401/UES0401_unit.bp, units/URL0001/URL0001_unit.bp, units/URS0203/URS0203_unit.bp, units/XAS0204/XAS0204_unit.bp, units/XRB2308/XRB2308_unit.bp, units/XRS0204/XRS0204_unit.bp, units/XSL0001/XSL0001_unit.bp, units/XSS0202/XSS0202_unit.bp, units/XSS0203/XSS0203_unit.bp, units/XSS0304/XSS0304_unit.bp
- Revert ACUs to their previous "loose" targeting of mobile units with no preference
- Cruisers now target navy before structures again
- Subs target other subs before coopers
=> priority rework adjustments

lua/sim/score.lua
This removes the reclaim rate from the score income rate as mentioned in #3202 1-2
This has the trade off of measuring all rates as the estimated change over time based off the change in totals rather than using the instantaneous values returned from the GetArmyStats() function. This was done to try to preserve some of the sim performance increases.
The alternative would be to calculate the rates every tick which is ultimately a trade off of resource usage for instantaneous accuracy.
=> Remove reclaim rate from score income

lua/sim/Unit.lua
Fixes #3095 
This sets the rebuild progress from a wreck proportionally to the amount of mass left in the wreck compared to the buildCost*wreckageMult.
This has to retrieve the unit blueprint first to calculate the max wreckage mass for the unit. This could be avoided if overkill damaged the wreck rather than just changing the initial mass value.
Additionally this sets the maximum rebuild progress after ctrl king a building to 45% from 50% due to the difference in intial reclaim left vs the buildCost*wreckageMult.
=> Set rebuild progress based on ratio of mass to max possible wreckage mass

lua/ui/game/unitviewDetail.lua, units/UAA0104/UAA0104_unit.bp, units/UAA0107/UAA0107_unit.bp, units/UEA0104/UEA0104_unit.bp, units/UEA0107/UEA0107_unit.bp, units/UEA0203/UEA0203_unit.bp, units/URA0104/URA0104_unit.bp, units/URA0107/URA0107_unit.bp, units/XEA0306/XEA0306_unit.bp, units/XSA0104/XSA0104_unit.bp, units/XSA0107/XSA0107_unit.bp
Some mods provide Experimental Trasnporter and the ability function only checks for Tech1-3 units.
Experimental Transporters will trigger an error.
Also the description for transportcapacity only has estimated values so we need to add a helper variable.
---
Added Class1Capacity to all transporter blueprints to set the real transportcapacity
Unit ura0104 (Air Transport) Added missing transport capacity variable (Class1Capacity = 10,)
Unit xsa0104 (Air Transport) Added missing transport capacity variable (Class1Capacity = 16,)
Unit xsa0107 (Light Air Transport) Added missing transport capacity variable (Class1Capacity = 8,)
Unit ura0107 (Light Air Transport) Added missing transport capacity variable (Class1Capacity = 6,)
Unit xea0306 (Heavy Air Transport) Added missing transport capacity …
=> Fix Tooltip for Experimental Transporter

lua/ui/lobby/lobby.lua
Benchmark is now testing RAM speed, not CPU calculating speed.
Benchmarks: (lower = better)
old= old CPU benchmark
new= new RAM benchmark
old: 144 new: 98 - netjaxx ( i7-6700K DDR4 )
old: 156 new: 144 - Uveso ( i7-4790K DDR3 )
old: 184 new: 115 - Moby ( Ryzen 5 DDR4 )
old: 327 new: 325 - Lionheart ( Q8400 DDR2 )
Ingame gamespeed multiplayer: (higher = better)
+7 netjaxx ( i7-6700K DDR4 ) CPU is slower than i7-4790 but RAM is DDR4
+6 Moby ( Ryzen 5 DDR4 ) slightly faster than i7-4790K Also because of DDR4
+6 Uveso ( i7-4790K DDR3 )
+3 Lionheart ( Q8400 DDR2 ) Old Intel Core 2 Quad
=> Fix Ingame CPU Benchmark

lua/editor/SorianBuildConditions.lua
Arty range was patched in FAF but only blueprints got patched, not the AI functions related to it.
=> Fix for Sorian Arty Range function

lua/aibrain.lua, lua/sim/EngineerManager.lua, lua/sim/FactoryBuilderManager.lua
The Table and all child functions are not in use,
and we don't need to track energy/mass consumption in LUA for the AI.
We can get the data from every unit direcly with
Unit:GetConsumptionPerSecondMass()
Unit:GetConsumptionPerSecondEnergy()
=> AI-Patch -  Removing unused MassConsumption table and all child functions

lua/ui/controls/acubutton.lua
When you open the large map preview in the lobby you can right click on the acu buttons to close spots.
When you open it the first time, you can right click and X appears to show that it slot is closed.
When you open it the second time or more, you can still remove X by right clicking it, but no more X will appear if you want to close something.
Weirdly when you hide and reopen the large map preview, the overlays all appear correctly.
But once you edit the correct X aren't shown.
This PR fixes this, so the X will always appear when you right click even on second or third try.
=> Fix bugged acu button textoverlay labels when opening large map preview for second time

units/UEL0303/UEL0303_unit.bp, units/URL0303/URL0303_unit.bp
Bring the E cost in line with Percy/Brick.
Buff the BT/mass from 5 -> 4.5 (Brick & Percy have 3.75)
=> Buff BT and E cost of Loya & Titan

units/XSL0103/XSL0103_unit.bp
Increase the BT of Fobo to 270 to bring it in line with other t1 units and the BT/mass cost ratio for t1 units.
=> Increase the BT of Fobo

lua/shield.lua
Function was checking for EntityId not UnitId.
This caused an error in executing instigator:GetWeaponByLabel()
while checking shields for a overcharge weapon.
This happens when UnitId is false and EntityId is true.
In this case we got overspill damage from a shield unit near the ACU that was impacted
by the splat damage of an ACU overcharge weapon.
=> Fix shield ApplyDamage() function for ACU overcharge

lua/AI/AIBuilders/SorianStrategyBuilders.lua, lua/editor/SorianBuildConditions.lua, lua/platoon.lua
resubmission of previous PR that had some unwanted extra code.
When SorianAI was migrated to faf an error was made in the if statements related to the game status Result. The original code used if not v:IsDefeated then, when it was migrated to faf the following was used.
if not v.Result == "Defeat" then
This never returns true.
I have corrected it to
if v.Result ~= "Defeat" then
across the instances within the sorian builder/strategy conditions and one of its platoon function.
Impacted AI Logic.
Platoon Functions. 
AvoidBasesSorian. Impacts AI's ability to detect if they are avoiding bases correctly.
BuildConditions.
AIOutnumbered. Calculating players vs AI strength.
EnemyToAllyRatioLessOrEqual. Calculating enemies vs allies.
ClosestEnemyLessThan. Allows the sorian rush AI to use the ACU …
=> fix ArmyBrain result not equal to defeat bug in Sorian AI logic

lua/overspill.lua, lua/sim/DefaultProjectiles.lua, units/UAL0307/UAL0307_script.lua, units/UEL0307/UEL0307_script.lua, units/XSL0307/XSL0307_script.lua
Fixes #3315 
Also fixes the following error:
```
WARNING: Error running lua script: ...rs\jip\documents\supreme commander\fa\lua\shield.lua(188): attempt to call method `GetWeaponByLabel' (a nil value)
...rs\jip\documents\supreme commander\fa\lua\shield.lua(188): in function `ApplyDamage'
...jip\documents\supreme commander\fa\lua\overspill.lua(90): in function <...jip\documents\supreme commander\fa\lua\overspill.lua:83>
```
Which is caused by the overspill function passing in the wrong table to the instigator parameter (source instead of instigator). Not sure if this has impact on other areas of the code - in my own testing I couldn't find any issues. I tried shooting with a commander that has enough storage for full overcharge at a few shields, behavior appears to be …
=> Fix shield warning

lua/system/trashbag.lua
It is now optimized according to the loops benchmark - instead of using table.getn we keep a separate counter. The trashbag is not
used often (primarily during initialization) but it does have a significant difference overall. There is commented blocks of code that you can uncomment to trace where invalid calls to the class are made - makes them easier to track down and clean up.
=> Optimize Trashbag

lua/defaultunits.lua
The original function first gathers all the units in radius, sorts them and then chooses the unit with the most threat. That is O(n) space and O(n * lg(n)) computation time, where _n_ is the number of units found. Since we're only interested in the unit with the most threat we can store it in O(1) space and run it in O(n) complexity.
It doesn't happen often that this function runs on a large amount of units - but when building artillery pieces it can happily sort all hostile units on the map and that may cause a stutter.
=> Rotate towards enemy logic redo

lua/ui/controls/worldview.lua
Fixes the auto build of KionX not referencing the class variable, but a non-existing global. It didn't affect me personally, but someone else reported this stack trace to me:
```
WARNING: Error running HandleEvent script in CScriptObject at 15e02600: ...rever\gamedata\lua.nx5\lua\ui\controls\worldview.lua(181): access to nonexistent global variable "AutoBuild"
[C]: in function `error'
...alliance\gamedata\mohodata.scd\lua\system\config.lua(53): in function <...alliance\gamedata\mohodata.scd\lua\system\config.lua:52>
...rever\gamedata\lua.nx5\lua\ui\controls\worldview.lua(181): in function <...rever\gamedata\lua.nx5\lua\ui\controls\worldview.lua:159>
```
And I'm not sure why it didn't crash for me, but it did crash for the other person.
=> Fixed autobuild not referencing class variable

lua/platoon.lua
Within the Engine Code, this callback is completely busted there is no way to fix this.
Instead Duncan decided in his wisdom to change this... to where the build would not be repeated, which 99% of the time fixed the issue.
When True we would not attempt to repeat the job, When False would attempt to repeat the job again in case it had accidentally failed.
This as stated fixes the Engine Issue.
I logged all processes and tested it.
ProcessbuildCommand Function
EngineerBuildAI Function
EngineerSetupCallbacks
WatchforNotBuilding
Attempted to fix with several fixes (help from Sprouto) none fixed said issue. Concluding that this relates back too callbacks and when logging callback Failed to Build, you will see it fail to build.
When changing said callback to false for it to try/attempt build …
=> Fixed Failed To Build in EngineerFailedToBuild Callbacks

lua/ui/lobby/lobby.lua
Allows prefetching of all assets (including mod blueprints) up to the point where 'BeginSession' is called. No mod or map code is actually being run during prefetching. Lowers the loading time significantly, especially for slower computers.
Inspired by LOUD.
Tested with and passed with flying colors:
- AI-Uveso
- All Blackops mods
- Dilli Dalli AI
- SSB
To test it, make sure to have the Moholog open while in the lobby. You can do so by having /showlog as a program argument. You can see that when you change mods / maps, the loading already happens. Where as previously, that only happened during loading.
=> Prefetch loading in lobby to lower time spent in loading screen

lua/defaultunits.lua, lua/sim/Unit.lua, lua/terranunits.lua
All calls to starting / stopping the rocking behavior are removed. If you're wondering what it is - it wasn't used in practice. It requires blueprint values set that aren't set by any blueprint, both of the base game files (including those that are not part of the repository) and common mods. 
Removing the call on its own is good - but preventing _a lot_ of threads from being made is better. To give an idea, each time StartRocking is called a thread is made. Each time StopRocking is called, if a thread was made, a new thread is made to stop the previous one. In a game of 4 AIx fighting these functions were called 2030 times to start rocking and introduce a thread and 2580 times to kill the start thread and start a new thread to stop rocking. This was over a timespan of 13 minutes, which …
=> Remove rocking behavior calls

units/UAB3102/UAB3102_unit.bp, units/UAB3202/UAB3202_unit.bp, units/URB3102/URB3102_unit.bp, units/URB3202/URB3202_unit.bp
Especially relevant when firing with low-arc units such as the riptide and the aurora. Fixes issue #3326. Tested on all sonars, also tested submarines being able to hit them or not. All should be good.
=> Changed collision size of sonars to make them easier to hit

units/XEA3204/XEA3204_unit.bp
Selection Priority 6 -> 3 (same as engies)
It still gets selected after engies (no idea why)
=> Change SelectionPriority of UEF Drones (kennel ones)

env/Lava/Props/Trees/LV_Dead01_s1_prop.bp, env/Lava/Props/Trees/XDead01_s1_prop.bp, env/Lava/Props/Trees/xDead01_s2_prop.bp, env/Lava/Props/Trees/xDead01_s3_prop.bp
With the missing normals:
Without the missing normals:
This PR closes https://github.com/FAForever/fa/issues/2258 - as badbowi suggested there is no visual difference except for missing out on a few warnings in the log.
=> Fix missing normals on lava/trees

units/UAL0101/UAL0101_unit.bp, units/UEL0101/UEL0101_unit.bp, units/URL0101/URL0101_unit.bp, units/XSL0101/XSL0101_unit.bp
Remove the GuardScanRadius to prevent the scouts from agro'ing onto units and buildings from very far away, now they will trigger based on their weapon's maxRadius which is still much larger then their tank counterparts which should prevent them from suiciding too often when attack moved while removing the great annoyance of your scouts getting stuck if they are attack moved or assisted.
=> T1 Land Scout Rework

lua/ui/game/buildmodedata.lua
When using the Seraphim SACU in buildmode, the hotkeys are not working.
The unit was already present in buildmodedata.lua, but a (most likely) copy/paste error in the unit-name prevented it from working.
=> Fixed Seraphim Rambo SACU buildmode keys

lua/ui/game/taunt.lua
fixes #3294 
A check for the sender variable being performed before calling the "sendTaunt" function which itself then checks for the variable.
=> Removed duplicate test for sender

lua/EffectUtilities.lua, lua/cybranunits.lua, units/URB1104/URB1104_script.lua
Contains a few fixes:
- Removed a LOG that should not have been merged
- Prevent a mass fabricator from crashing its script (no idea why, has to do with eco manager)
- Prevent drones from trying to update the engineer / hive when it got gifted
- Prevent hives from thinking the unit they're building still exists when unpausing, when in reality it died to a mantis (or a bomber, of course)
=> Fafdevelop hotfix 1

init_faf.lua, init_fafdevelop.lua
Also modules.nx was removed because
https://github.com/FAForever/fa/search?q=modules&type=commits
We should do something about the copy-paste.
I suggest putting the general part in init_common.lua
The problem is only with patches...
=> Synchronization init files

lua/defaultexplosions.lua
A small hotfix:
- A typo in variable name that prevents the Galactic Colossus and Ythotha to spawn their wrecks.
- A quick tweak magic values that determine what unit should receive what type of explosion
=> Hotfix explosions

changelog-3724.md, units/URA0001O/URA0001O_unit.bp, units/URA0002O/URA0002O_unit.bp, units/URA0003O/URA0003O_unit.bp
Yes - silly mistake. Apparently that category is quite vital. Closes #3384
=> Fix drones not being visible by recon

changelog-3724.md, lua/defaultcollisionbeams.lua
This PR undo's some work done by #3200. According to KionX [in this topic](https://github.com/FAForever/fa/issues/2045#issuecomment-924858053) the cause of exceptions with the address `0x0050dfd8` originate from this file, in specific the functions that this PR comments out.
The issue with these hard-crashes is that they do happen, but they're hard to reproduce. I have not been able to reliably reproduce them myself as of yet, and therefore I can not test if this will solve the actual problem.
=> Fix hard-crashes in /lua/DefaultCollisionBeams.lua

changelog-3724.md, lua/sim/Unit.lua
As a safeguard only get blueprints after we're sure it's a unit and actually need to use blueprint values.
See comment here about GetBlueprint() on a shield bubble entity crashes the game.
https://github.com/FAForever/fa/issues/2045#issuecomment-922841853
=> GetReclaimCosts() - Grab blueprints after we know it's a unit

changelog-3724.md, lua/terranprojectiles.lua, projectiles/TDFGauss02/TDFGauss02_script.lua, projectiles/TDFGauss04/TDFGauss04_proj.bp, projectiles/TDFGauss04/TDFGauss04_script.lua, projectiles/TDFGauss05/TDFGauss05_proj.bp, projectiles/TDFGauss05/TDFGauss05_script.lua, units/UES0201/UES0201_unit.bp
Fixes the (accidental) change in [this commit](https://github.com/FAForever/fa/commit/b80bf286ee0ddd79f3376b77e275568ae637dea9). 
Destroyer finally got its 'wow' factor, just to see it taken away again.
=> Fix explosion of UEF Triad and UEF Destroyer

changelog-3724.md, lua/cybranunits.lua, lua/sim/Unit.lua, units/URA0001O/URA0001O_unit.bp, units/URA0002O/URA0002O_unit.bp, units/URA0003O/URA0003O_unit.bp
Fixes a few drone issues:
- Add INSIGNIFICANTUNIT category as that prevents all kinds of interaction.
- Add UnitId to the drone as that is a value scripts expect to be cached.
- Removes drones from UpdateAssistersConsumption function.
An example of interaction that is not desirable: being able to change the target the drone is 'building' as seen in [this cast](https://youtu.be/n_ka_woZ3Q4?t=249). 
Has no impact on the performance of the drones.
With thanks to Softles and Archsimkat.
=> Drone issues

changelog-3724.md, lua/SimUtils.lua, units/UEL0401/UEL0401_script.lua, units/UES0103/UES0103_script.lua
Both `GetReclaimablesInRect` and `GetUnitsInRect` return nil if nothing is found, instead of an empty table. This can happen, as it did during [this replay](https://replay.faforever.com/15419462) at around 35:00 to LilMiss.
=> Fix potential nil on transfer

changelog-3724.md, lua/UserSync.lua, schook/lua/UserSync.lua
And here we are - this PR is a direct result of https://github.com/FAForever/fa/pull/3275 where changes were made to how games are reported to the server. And it intents to close https://github.com/FAForever/fa/issues/3459 .
Before that there were several PRs that changed the reporting (#3032, #3115, #3152, #3166) as a result of a [discussion on Zulip](https://faforever.zulipchat.com/#narrow/stream/203478-general/topic/DrawBug) and those got into the previous patch (https://github.com/FAForever/fa/releases/tag/3715) and that was considered stable with the exception of one particular draw bug.
I've been trying to re-produce the errors that people [have been reporting](https://forum.faforever.com/topic/2656/game-was-not-reted-reason-unknow-result) [on the …
=> Revert the changes made to how game results are send

changelog-3724.md, lua/shared/overcharge.lua, lua/sim/DefaultProjectiles.lua, lua/ui/game/unitview.lua
The latter is to fix issues like the former in the future. The original authors copied the code over, and then when the change was made the coupling was not clear and therefore it got left with the old damage calculations.
=> Fix overcharge indicator and add shared code

units/UAL0101/UAL0101_unit.bp, units/UEL0101/UEL0101_unit.bp, units/URL0101/URL0101_unit.bp
80 -> 60 BT for UEF, Aeon, and Cybran.
Adjust the E cost slightly
=> Adjust BT and costs of T1 Land scouts

units/XAB1401/XAB1401_unit.bp
Gives Paragon 100k E storage to avoid stalls when sudden changes in player's E consumption occur.
=> Paragon adjustments

lua/platoon.lua
UnitBeingBuilt is only SET by defaultunits.lua - OnStartBuild() and OnStopBuild()
All other files only READ from this value.
So setting it in AI function is the wrong place.
I can remember to put this line in there for debug reasons.
We don't need it any more :)
=> UnitBeingBuilt is only SET by defaultunits.lua

lua/system/trashbag.lua
This allows a trashbag to be re-used after it is 'destroyed'. Useful for effects that come and go. Allows us to replace [these tables](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/Unit.lua#L192) for example. They are currently 'destroyed' through [this function](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/EffectUtilities.lua#L1338) which is silly at best 😄 : 
- A new table is allocated, that starts fresh. This means the first few entries will trigger reconstructions.
- The old table is de-allocated, which is a shame because we're going to use another table for the same task.
=> Allow trashbag to be re-used

lua/SimCallbacks.lua, lua/ui/game/commandmode.lua
Adjusts the capping behavior based on feedback from the community:
- Reduce the number of clicks required to 1 for all capping structures except for fabricators (those remain 3).
- Make shift mandatory in order to queue cap orders.
=> Adjust capping behavior

lua/sim/CalcBallisticAcceleration.lua, lua/system/import.lua
Optimizes the import function. It ensures as little globals are touched as possible as those are slower than up values. This won't have a noticeable impact (I suspect) but it is a commonly used function, even in critical code. Therefore it can't harm either.
=> Optimize import.lua

.github/workflows/build.yaml, lua/system/utils.lua, run_lua_tests.sh, tests/lust.lua, tests/test_utils.lua
I found a single file test framework that was pretty easy to convert to lua 5.0 syntax. With the help of the `repr` function it gives fairly useful test output on failures too. I had to change all of the `str:foo` calls to `string.foo(str)` because by default in lua 5.0 you must invoke them like that. But, I see the `str:foo` all over the codebase so I feel like GPG must have added it to SupCom (which means I'll need to add it to faflua and then probably revert all those changes in this PR).
Here's an example of what the console output looks like:
=> Add unit tests for string utils

lua/defaultunits.lua, lua/simInit.lua
This closes https://github.com/FAForever/fa/issues/3508 and removes threat additions when a mobile unit dies. This has been discussed with the AI devs and they are in favor.
=> Fixes ai detection and threat addition

effects/emitters/aeon_groundFX_emit.bp, effects/emitters/aeon_t1eng_groundfx01_emit.bp, effects/emitters/aeon_t2eng_groundfx01_emit.bp, effects/emitters/aeon_t2eng_groundfx02_emit.bp, effects/emitters/seraphim_adjacency_node_01_emit.bp, effects/emitters/seraphim_groundFX_02_emit.bp, effects/emitters/seraphim_groundFX_03_emit.bp, effects/emitters/seraphim_groundFX_04_emit.bp, effects/emitters/seraphim_groundFX_emit.bp
Optimizes the hover effects used by units. In particular Aeon engineers can easily take 2% - 4$ of the sim time just by having their effects being rendered on screen.
The following results are with 150 units of each, comparing the difference between zoomed in (all rendering their effects) and zoomed out (no effects rendered).
```
`aeon_groundfx_emit -> AeonGroundFX01` done marginal gains -0.3/0.5 ms
Used by: DAL0310, ual0101, ual0201, ual0205, ual0307, xal0203 
`aeon_t1eng_groundfx01_emit -> AeonGroundFXT1Engineer` done -2/2.5 ms
Used by: UAL0105, UAL0309
`aeon_t2eng_groundfx01_emit -> AeonGroundFXT2Engineer` done -2/2.5 ms
`aeon_t2eng_groundfx02_emit -> AeonGroundFXT2Engineer` done -2/2.5 ms
Used by: UAL0208
`seraphim_groundFX_emit -> SeraphimGroundFX01` done marginal gains -0.3/0.5 ms …
```
=> Optimize hover effects

units/XSB0304/XSB0304_unit.bp
Closes #3514 .
Idea was to consider the 'hover pads' (Halo - thanks) as unpathable.
=> Fix the seraphim quantum gate skirts

lua/ui/lobby/lobby.lua
Closes https://github.com/FAForever/fa/issues/3474.
The curator map button is removed until an alternative is available on the new wiki.
=> Remove curated maps button

init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua, lua/ui/game/gamemain.lua
The nvidia fix mod as found in the vault will be applied by default. It prevents stuttering with the recent drivers of Nvidia.
=> Integrate nvidia fix

lua/options/options.lua
Adds an additional option to UI scaling for monitors with very low resolutions. Otherwise just the scoreboard may take up half of the screen.
=> Add an 80% option for low resolution screens

lua/sim/Buff.lua
Closes https://github.com/FAForever/fa/issues/3429 where buffs were applied to the drones whom do not have a buff table anymore. As they are insignificant they shouldn't be able to take on buffs anyhow.
=> Do not apply buffs to insignificant units

units/XRL0302/XRL0302_unit.bp
low trigger radius resurfaces the issue of https://github.com/FAForever/fa/issues/109
Adjust it to be slightly bigger, the only problematic unit I found with this radius is fatboy, which is a lesser evil than having bad behavior vs every other unit
=> adjust beetle trigger radius

units/URL0202/URL0202_unit.bp
An attempt to fix the rhino from missing shots when the beam weapon got introduced. The test case I had going was no longer reproducible after changing this file. The test case was having a gatling bot (UEF, T2) walk around the Rhino at about half range while the gatling bot was aiming for the Rhino. This would cause the Rhino to miss, I assume because it tried to aim ahead of the entity. 
I'm not entirely confident that this solves the issue.
Closes #3548 .
=> Fix Rhino missing shots

lua/ui/lobby/ModsManager.lua
As an example, prevents losing a V at the start of a word
=> Update regular expression of mod version removal

units/XRL0302/XRL0302_Script.lua
The EMP didn't fire properly in various situations. The EMP and the suicide damage should now both fire accordingly when:
- You manually detonate
- It dies due to (enemy) fire
- It gets CTRL + K'ed
And it doesn't apply the EMP / suicide damage when:
- Unit is cancelled during construction in the factory
Rebased version of #3577
=> Fix EMP buff of Fire Beetle

init_fafbeta.lua, init_fafdevelop.lua
Shader compilation is forced upon release, but not between development iterations. When hosting on a development branch (FAFBeta or FAFDevelop) then the shader cache is removed to force shader compilation. This prevents missing techniques when a shader has been updated.
=> Force shader compilation on development branches

lua/system/Blueprints.lua
Introduces a guard in case a blueprint doesn't have categories.
=> Fix backwards compatibility of blueprints.lua

lua/sim/weapon.lua
Apparently caching the functions calls like that is not what we want. It prevents the game of finding the correct function.
=> Hotfix for incorrect weapon optimization

lua/EffectUtilitiesOpti.lua
Fixes a typo introduced by #3582.
=> Fix typo that breaks Cybran build beams

effects/emitters/build_sparks_blue_01_emit.bp, lua/SimCallbacks.lua, lua/SimUtils.lua, lua/sim/Unit.lua, units/URL0202/URL0202_unit.bp
Fixes the following issues:
- Due to Rhino projectile speed being too high it could miss units
- Weapon trashbags are destroyed when a unit is killed
- Some guards when gifting units to prevent gifting dummy units (cybran build drones)
=> Fix various minor issues

lua/defaultunits.lua, lua/sim/Unit.lua
Closes #3592 . All engineers in the area have to update their consumption computations when an (S)ACU starts an enhancement.
=> Fix consumption bug

lua/SimCallbacks.lua, lua/ui/game/commandmode.lua
This changes the capping behavior to:
- 2 clicks + shift to mass storage an upgrading t1 (or t2) extractor
- 1 click (+ shift) to mass storage a (finished) t2 / t3 extractor
- 3 clicks + shift to mass fab cap an upgrading t2 extractor
- 2 clicks + shift to mass fab cap a t3 extractor
- 1 clicks + shift to mass storage a t3 fabricator
- 1 clicks + shift to pgen an artillery
- 2 clicks + shift to pgen an upgrading t1 radar
- 1 clicks + shift to pgen an radar, t2 radar or t3 radar
- 1 click + shift to wall a t1 pd
General rule of thumb:
- Typical: shift + 1 click
- Upgrading: shift + 2 click
- Dangerous: shift + (regular click count + 1)
Also closes #3513
=> Capping feature adjustment nr 2000

units/DSLK004/DSLK004_script.lua
This doesn't fix #3153 but at least it addresses it to land-based targets. The unit was doing damage to its target regardless of context. Beam weapons are inherently broken in this game - hitting an air unit is essentially impossible. Hence they 'fixed' it with this. 
Needs to be replaced with a projectile-based weapon, similar fix to the Rhino.
=> Hotfix for Seraphim T3 MAA

lua/system/Blueprints.lua
The blueprints of support ACUs were inserted into the blueprints table. The keys of the blueprints table is based on the blueprint id, not on some arbitrary key that is assigned when inserting.
=> Fix custom icon support of Support Commander Presets

lua/ui/game/commandmode.lua
Fixes consistency of upgrading (requires shift) and prevents state build up when upgrading and not pressing shift.
=> Fix ringing attempt 62

engine/Sim.lua, lua/ScenarioFramework.lua, lua/SimCallbacks.lua, lua/SimHooks.lua, lua/utilities.lua, units/XRB0204/XRB0204_script.lua, units/XRB0304/XRB0304_script.lua
Apparently the function GetUnitsInRect can have a rectangle (table) as an argument but also the four elements that make up the table as separate arguments.
=> Fix GetUnitsInRect hook for insignificant units

lua/UserSync.lua, lua/simInit.lua, lua/ui/dialogs/disconnect.lua, lua/ui/game/gamemain.lua, lua/ui/lobby/lobbyOptions.lua
Ensures that the exit dialog is always on top of the disconnection dialog and the disconnection dialog waiting time can be set by the host in the lobby.
=> Expand disconnection dialog

lua/EffectUtilitiesSeraphim.lua, units/URL0001/URL0001_script.lua, units/XSL0101/XSL0101_script.lua
```
warning: Error running lua script: ...amdata\faforever\gamedata\lua.nx5\lua\sim\weapon.lua(594): Game object has been destroyed
[C]: in function `SetEnabled'
...amdata\faforever\gamedata\lua.nx5\lua\sim\weapon.lua(594): in function `SetWeaponEnabled'
...gramdata\faforever\gamedata\lua.nx5\lua\sim\unit.lua(2092): in function `SetWeaponEnabledByLabel'
...\gamedata\units.nx5\units\xsl0101\xsl0101_script.lua(77): in function <...\gamedata\units.nx5\units\xsl0101\xsl0101_script.lua:67>
```
```
warning: Error running lua script: ...ver\gamedata\lua.nx5\lua\effectutilitiesseraphim.lua(52): Game object has been destroyed
[C]: ?
...ver\gamedata\lua.nx5\lua\effectutilitiesseraphim.lua(52): in function `CreateSeraphimUnitEngineerBuildingEffects' …
```
=> Fix various issues

init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua
Adds a separate exception for Kyro's lobby to the initialization files. In particular, a file named `kyros.nxt` is accepted.
I was not aware that many people were using this. Note that this doesn't mean that we officially support it - if the game breaks then there is nothing we can / will do about that.
=> Whitelist Kyro's lobby

lua/ui/game/construction.lua
- the template removal window pops up again
- the unit highlights in transports work again
- the factory queue on hover works too
=> possible fix of a bug with secondary display

init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua
When the shaders are changed they're not necessarily recompiled for all users. This is especially relevant when new techniques are introduced like in patch 3728. This introduces a 'minimum' version of the shader and any other version is removed.
=> Improve shader recompilation logic

engine/Sim/CAiBrain.lua, lua/aibrain.lua
```
warning: Error running lua script: ...faforever\gamedata\lua.nx2\lua\scenarioframework.lua(1984): attempt to call method `SetCanBeKilled' (a nil value)
...faforever\gamedata\lua.nx2\lua\scenarioframework.lua(1984): in function `UnflagUnkillable'
...amdata\faforever\gamedata\lua.nx2\lua\cinematics.lua(76): in function `SetInvincible'
...ce\maps\x1ca_coop_001.v0026\x1ca_coop_001_script.lua(1312): in function <...ce\maps\x1ca_coop_001.v0026\x1ca_coop_001_script.lua:1256>
```
Related to #3441 .
=> Hook Brain.GetListOfUnits to exclude insignificant units

lua/options/options.lua, lua/ui/game/unitview.lua, lua/ui/help/tooltips.lua
This ensures the selected unit is always set if there is just one. Originally it was only used by one feature, but these days more features depend on it. It also fixes the default value being set properly (to 'only-obs').
=> Always define the selected unit in UI

init.lua, init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua
Includes the `kyros.scd` to `init_faf.lua` and proper checks the extension of maps / mods instead of triggering on the the existence of the `.rar` pattern somewhere in its name.
=> Update initialisation files

lua/SimHooks.lua, lua/aibrain.lua, lua/cybranunits.lua, lua/sim/Unit.lua, units/URA0001O/URA0001O_unit.bp, units/URA0002O/URA0002O_unit.bp, units/URA0003O/URA0003O_unit.bp
We used the `categories.INSIGNIFICANTUNIT` categories to identify the new dummy units (that are no real unit - but just exist like the Cybran Build Drones). By doing so we also destroyed some mods that used this category before, like the anti teleporting towers.
To fix this we introduce a new category: `DUMMYUNIT`, that we use to filter out these units.
=> Fix filtering insignificant units

lua/GameColors.lua
We didn't really think about army colors in the team matchmakers, so they were pretty random. This new order creates team red vs.team blue for 2v2. For 4v4 we get a "warm" team against a "cold" team.
I ordered the rest of the colors in a way that somwhat similar colors are in order when picking them in the lobby. As I don't expect that we will make any 5v5+ matchmaker in the foreseeable future.
=> Change army color order

lua/shared/observable.lua, lua/ui/dialogs/disconnect.lua, lua/ui/game/connectivity.lua, lua/ui/game/gamemain.lua, lua/ui/override/ArmiesTable.lua, lua/ui/override/SessionClients.lua, lua/ui/override/readme.md, lua/ui/uimain.lua
Caches result of GetSessionClients and GetArmiesTable. These are often called (as much as at least once per frame). Each call returns a unique result. Each unique result needs to be populated. And tables are expensive memory-wise. 
By default the cache is refreshed every two seconds. A faster interval is available: then the cache is refreshed every 0.025 seconds. As an example, GetSessionClients needs a faster interval when the connectivity / disconnection dialogue is open.
=> Optimize session armies and clients

lua/SimCallbacks.lua, lua/sim/Unit.lua, lua/ui/dialogs/createunit.lua, lua/ui/game/commandmode.lua
The previous implementation checked every 0.1 seconds if the mouse was pressed - if it was, then a callback would trigger. In practice however there can be the case that a mouse click is shorter than 0.1 seconds, effectively missing a click. As an example in the logs:
The command issues are triggered at the same moment we click. But the spawn function is not called sometimes. 
The new implementation uses the build mode introduced by Balthazar as a callback mechanism - the build preview is issuing a command and we make use of that. In turn, no clicks are missed while retaining the current functionality.
Closes #3655 .
=> Remove inconsistency with spawning units through the cheat menu

lua/system/Blueprints.lua, lua/system/blueprints-lod.lua
Some of the LOD values are out of balance. This can cause sudden framerate drops. This pull request scales the LOD of entities according to their size. A small entity occupies less screen space, therefore it is less detailed and can do with a lower LOD. The same (but reversed) logic can be used for a large entity.
This pull request is a result of a discussion with Strogo about [this video](https://youtu.be/dAqlgrOjy2Q).
=> Dynamic LOD settings

lua/EffectUtilities.lua, lua/EffectUtilitiesGeneric.lua
Removes the creation of an entity, prevents a surface lookup and a table allocation. Does not impact the functionality or visuals of the effects.
=> Optimize reclaim effects

lua/sim/Unit.lua, lua/sim/defaultweapons.lua, lua/sim/weapon.lua
Solves two open issues with weaponry:
- The weapon manipulators were removed of a unit before the wreck was made. All weapons switched back to their default orientation when the unit dies. This looks bad. The wreck then copies the default location.
- Trash of weapons were not removed properly. This could leave potential lingering beams when units die. This is no longer the case.
=> Improve weapon state when owner dies

lua/sim/Unit.lua
A typo slipped into #3587 and in turn no trampling damage was applied - this pull requests fixes that typo. 
Edit: With thanks to @Dragun123 for spotting the mistake.
=> Fix trampling damage of units

engine/User.lua, lua/SimCallbacks.lua, lua/ui/game/commandmode.lua
Allows the hive to upgrade immediately when you are not holding shift.
Worked with @Tagada14  on this pull request as a study session.
=> Allow Hive to upgrade immediately

lua/ui/game/minimap.lua, lua/ui/game/multifunction.lua, lua/ui/help/tooltips.lua
I'm currently working on ability to change LOD modifiers for different type of objects via console and one thing that bothered me is why mesh renderer code that makes LOD calculations for visible objects is called so often, as if there are thousands objects in view, even though I'm zoomed in and there is 1 unit and a few props on the screen.
The answer is simple - minimap. Why bother adding simplified renderer for minimap, if you can just copy-paste main camera implementation and apply fancy cartographic view on it :+1: And things become even more dramatic if you accidentally zoom in and minimap starts to  render all these props and units.
Anyway, with this engine patch https://github.com/FAForever/FA-Binary-Patches/pull/7 `cam_DefaultMiniLOD 0` command will disable minimap mesh renderer …
=> Disable mesh rendering for minimap

lua/ui/lobby/lobby.lua
In 5.1, getn works differently than in FA.
=> For lobby.lua compatibility with Lua 5.1

lua/sim/DefaultDamage.lua
Applications of the benchmarks. Prevents unnecessary table allocations when unit-based damage over time is applied.
=> Optimize damage over time threads

lua/defaultunits.lua, lua/shield.lua, lua/sim/Projectile.lua, lua/sim/Unit.lua
According to commit https://github.com/FAForever/fa/commit/dfb363dcdc6685bdf4daf8f94178a7da2b06ae8f the sound of submarine units do not work. The solution introduced is applied to all units and allocates a handful of entities per unit. These allocations are expensive!
By default, units try to play the sound themselves. For submarine units we introduce one entity that plays all the sounds of the submarine. This appears to work fine - note that sound is important, but during the late accurate sound is by far less critical than having a high performing simulation.
=> Improve performance of unit sound interactions

lua/ui/game/buildmodedata.lua
adds hotkeys for sparkies, engymod support factories, and t3maa included with FAF by default
=> add build mode hotkeys for FAF default mods

lua/system/blueprints-ai.lua, units/DAL0310/DAL0310_unit.bp, units/UAL0001/UAL0001_unit.bp, units/UEL0001/UEL0001_unit.bp, units/URL0001/URL0001_unit.bp, units/XSL0001/XSL0001_unit.bp
Introduces a flag to allow a unit to skip the dynamic threat computations, used by the armored command units. Only weapons that can be blocked by an artillery shield produce economic threat.
=> Adjust dynamic threat computations

lua/AI/AIBehaviors.lua, lua/AI/AIBuilders/AIAirAttackBuilders.lua, lua/AI/AIBuilders/AILandAttackBuilders.lua, lua/AI/AIBuilders/AISeaAttackBuilders.lua, lua/AI/AIBuilders/SorianAirAttackBuilders.lua, lua/AI/AIBuilders/SorianExperimentalBuilders.lua, lua/AI/AIBuilders/SorianLandAttackBuilders.lua, lua/AI/AIBuilders/SorianSeaAttackBuilders.lua, lua/AI/AIBuilders/SorianStrategyPlatoonBuilders.lua
Final ACU value needed. 
Correct error in CalculatePlatoonThreat and CalculatePlatoonThreatAroundPosition usage where it was checking for 'AntiSurface' rather than 'Surface' so it was getting 'Overall' instead. These two functions look at the bp's so antisurface is not present. Same for AntiAir (should be Air) and AntiSub (should be Sub)
For the function fix, based on testing done I believe the internal engine is performing a string search on the defense table of the blueprint for each unit looking for the values.
Below is an example from in game.
info: Platoon Threat values
info: Surface 8
info: AntiAir 11
info: Air 3
info: AntiSurface 11
info: Overall 11
This platoon had 4 x T1 Tanks (2 surface threat each) and 1x T1 Mobile AA (3 air threat each)
The following code was used. …
=> Update AI threat values to suit new unit threat value generation.

projectiles/CDFLASERHEAVY02/CDFLaserHeavy02_proj.bp, units/URB2301/URB2301_unit.bp, units/URL0202/URL0202_unit.bp
An interesting bug discovered by Archsimkat that allowed Cerberus turrets (and Rhino's up to an extent) to seriously increase their attack range in niche situations. 
To be specific, firing at a prop (something that is slightly above the ground) could cause the projectiles to try and loop around
It would allow behavior such as this 😄
=> Fix Cerberus turrets over extending their range

lua/SimUtils.lua
The weapon cooldowns of units are reset when it is gifted. This pull requests disables the weapons in question. They're enabled after their 'reload time' has passed.
=> Temporarily disables weapons of a unit when gifted

lua/ui/lobby/lobby.lua
Made it so the in-lobby color selection drop-down lists will be accurate.  They previously would be inaccurate in many instances (ie: showing unintended numbers of colors, which did not properly match the colors available).
Also removed some extra spacing.
While additional performance improvements could be made to the lobby's color-related functionality, that is largely beyond the scope of this PR, as the purpose of this PR is to fix some buggy behavior, and it runs fine.
=> Bugfix in-lobby color selection drop-down lists

lua/GameColors.lua, lua/ui/lobby/autolobby.lua, lua/ui/lobby/lobby.lua
Adjusts which colors are available
Reorders available colors
Adds a ColorOrder local to lobby.lua that specifies the default color order for TMM/etc that gets used if color is not specified otherwise
Theoretically fixes TryAddPlayer's IsColorFree functionality, which theoretically used to give a false negative every time it was positive
Available Colors:
Default Color Order:
=> Add colors, reorder colors, add color order functionality, & fix lobby AI color bug

.github/workflows/build.yaml, lua/ui/lobby/lobby.lua
If an AI exists in a lobby slot, and that AI is replaced with another AI (ie: an Easy AI is changed to an Adaptive AI), this PR makes it so the new AI gets the same color as the old AI that was in that slot. (as opposed to getting the next available color instead)
=> AI Color Fixing

engine/Sim/Projectile.lua, lua/proptree.lua, lua/sim/DefaultProjectiles.lua, lua/sim/Profiler.lua, lua/sim/Projectile.lua, lua/sim/Unit.lua, lua/system/import.lua, projectiles/SIFThunthoArtilleryShell01/SIFThunthoArtilleryShell01_script.lua, projectiles/SIFThunthoArtilleryShell02/SIFThunthoArtilleryShell02_script.lua
Our benchmark is 400 Zthuee firing at once on the map White Fire. The map has no civilians. All functionality of the original projectile is still there, just faster. A base line is the same scenario, but without the Zthuee firing.
On the FAF branch: `12 - 14 ms` with a base line of `3 ms`
This pull request: `9 - 12 ms` with a base line of `3 ms`
This pull request, without decals: `9 - 10.5 ms` with a base line of `3 ms`
If we'd reduce the base lines:
- FAF branch: `9 - 11 ms` for firing
- This pull request: `6 - 9 ms` for firing
- This pull request, without decals: `6 - 7.5 ms` when firing
Therefore we can safely assume that there's at least a 20% performance improvement. Some of these changes apply to all projectiles.
=> Optimize Zthuee projectiles (amongst other projectile things)

lua/ui/lobby/lobby.lua
Rounds displayed team ratings
Refresh observer list more often
Fix weird bug involving the observer list's numTeams sometimes being calculated incorrectly
=> Lobby team ratings improvements

lua/sim/DefaultDamage.lua, lua/sim/Prop.lua
Fixes an issue when DOT damage is applied and an issue with wreckages when full share is enabled.
```
WARNING: Error running lua script: ...faforever\gamedata\lua.nx5\lua\sim\defaultdamage.lua(33): Game object has been destroyed
[C]: in function `GetPositionXYZ'
...faforever\gamedata\lua.nx5\lua\sim\defaultdamage.lua(33): in function <...faforever\gamedata\lua.nx5\lua\sim\defaultdamage.lua:21
```
=> Fix wreckages causing an error when full share triggers

lua/lazyvar.lua, run_lua_tests.sh
Dealing with LazyVars I recently found out that setting value of lazyvar `false` causes troubles:
First of all:
`a  = Lazyvar.Create(false)`
`LOG(a())` - returns `0` that is not `false` at all (FYI 0 is a true value in Lua, so, 
`LOG(not 0)` is false)
Secondly:
`a:Set(false)` - ok fine, now it is false
`LOG(a())` - oh no, tried to call `nil` value?
Thirdly:
`a.OnDirty = function(self) LOG('i have a new value'..self()) end` - if we set a new value this would be called
`a:Set(false)` - no, we didn't...
=> Fix LazyVars behaviour with `false` value

lua/UTF.lua, lua/ui/lobby/lobby.lua, lua/ui/notify/customiser.lua, lua/ui/notify/notify.lua
Reverts FAForever/fa#3711
```
Can't copy lua objects of type function from one state to another.
Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init_dev.lua /EnableDiskWatch /showlog /log dev.log /RunWithTheWind
Callstack:
Unknown symbol (address 0x00914412)
Unknown symbol (address 0x16871fbb)
```
This doesn't apply on the machine of 4z0t, but it hard-crashes on my machine. Reverting the changes. The pull request is welcome once it is stable.
=> Revert "String utils for storing in game.prefs"

lua/EffectUtilitiesUEF.lua
```
Error running lua script: ...aforever\gamedata\lua.nx5\lua\effectutilitiesuef.lua(309): attempt to call method `HideLandBones' (a nil value)
...aforever\gamedata\lua.nx5\lua\effectutilitiesuef.lua(309): in function <...aforever\gamedata\lua.nx5\lua\effectutilitiesuef.lua:254>
```
=> Fix the build animation of the fatboy and atlantis

effects/water2.fx
Fixes an issue of #3748 where the changes in the low fidelity shader of the water were also applied to the medium fidelity preset.
High fidelity
Medium fidelity
Low fidelity
The issue that #3748 fixed was that low fidelity water would look like a grey mass, being almost invisible.
=> Introduce a medium fidelity preset for water

units/XSL0301/XSL0301_script.lua
Adds the default build effect to the construction of the Seraphim support commanders. This effect is used on all the other Seraphim units and buildings.
=> Fix seraphim support commander build effect

lua/ui/lobby/chatarea.lua, lua/ui/lobby/lobby.lua
Most of lobby issues come from chat: in some cases a lots of messages can cause lobby bug or even crash and here is why. 
Every message you receive creates a control. More messages = more controls = more usage of memory and, most importantly, when you Alt-Tab each LazyVar calculates its position on frame, which are 6 times more than controls...
=> ChatArea refactor

lua/ui/lobby/lobby.lua
Fix an edgecase (trying to autobalance with 0 players) and change rating-based sorting order to factor in deviation as well (this doesn't impact who gets whom as a teammate, but does impact intrateam slot order.
=> Changes to new Autobalance

lua/lazyvar.lua
Recent fix of lazyvars caused another hidden problem. Fixed now.
=> Fix the issue with behaviour of lazyvars

lua/ui/controls/combo.lua, lua/ui/lobby/lobby.lua
This makes the in-lobby color list able to update without "closing."
Fixes the problem of the available color list "closing" (being destroyed and recreated, with the new one set to hidden) when the available color list is updated.  Now, when a BitmapCombo is changed via ChangeBitmapArray, the new one is not hidden if the old one was not hidden.
Also simplifies where Check_Availaible_Color is called and makes it get called when a player switches to observer (the available color list was previously not triggered to update by this action).
=> Better available color list update functionality

lua/GameColors.lua
Remove half of the new colors and adjust the color order values accordingly (the default color results of the color order for the top 8 slots is not changed by this).
=> Color Compromise

loc/US/strings_db.lua, lua/ui/lobby/lobby.lua
Adds AutoBalance button functionality of automatically setting spawns to fixed if that's not already the case
Adds AutoBalance button functionality for odd vs even, top vs bottom, and left vs right AutoTeams configurations (rather than forcing manual and using the previously occupied slots) - slots are used in numerical order, only skipping closed slots and slots necessary to skip to keep team size equal (if any)
=> In-Lobby AutoBalance Improvements

lua/wreckage.lua
The health of a wreck is used to determine the reclaim value of a wreck. The health was set after the reclaim values were computed. The order was changed by #3714 .
=> Fix issue of wrecks having roughly 10% more value

lua/EffectUtilities.lua, lua/selfdestruct.lua, lua/sim/Unit.lua, lua/system/trashbag.lua, lua/ui/game/confirmunitdestroy.lua, units/XRL0302/XRL0302_Script.lua, units/XRL0302/XRL0302_unit.bp
Allows the `CleanupEffectBag` function of `effectutilities.lua` to work with both regular tables and trashbags. Revamps the self destruct that was doing a lot of additional logic - I have no idea why as the default flow of code when a unit is destroyed triggers all of that too.
=> Fix issues with the Fire Beetle and trashbag management

lua/ui/lobby/lobby.lua
Fixes an issue when swapping players that can cause a desync between the GUI and the internal state of the lobby. In particular, players appearing as not ready for the host while locally to the user in question they appear ready.
=> Fix ready checkbox being self-aware

lua/sim/Projectile.lua
An invariant was broken in an eager attempt to improve the performance of the game . 
With #3718 we introduced the use of cached vectors (a table that represents a position, that we re-use the memory location of). The idea of a cached vector is that it prevents the typical 'allocate table, use table, de-allocate table' pattern. One invariant of it is that you can not assume that the same value holds after a wait or fork statement. In other words:
```lua
-- somewhere in outer scope
local VectorCached = Vector()
-- somewhere in a function in the same file
local vc = VectorCached
vc[1], vc[2], vc[3] = unit:GetPositionXYZ()
-- (...)
WaitSeconds(...)
-- Invariant broken, we can't be sure that the same content is still in vc at this point, as it is used across instances
DamageArea(..., vc, ...) …
```
=> Fix damage over time instances

lua/EffectUtilitiesUEF.lua, lua/SimUtils.lua, lua/maui/cursor.lua, lua/shield.lua, lua/sim/defaultweapons.lua, lua/sim/weapon.lua, units/XRL0302/XRL0302_Script.lua
Removes lonely LOG statements and fixes the following issues:
```
WARNING: Error running lua script: ...gramdata\faforever\gamedata\lua.nx5\lua\simutils.lua(73): Game object has been destroyed
[C]: in function `SetEnabled'
...gramdata\faforever\gamedata\lua.nx5\lua\simutils.lua(73): in function <...gramdata\faforever\gamedata\lua.nx5\lua\simutils.lua:65>
```
As part of #3696, always check if it has not been destroyed after a wait.
```
WARNING: Failed to create emitter as you passed in an invalid blueprint name /effects/emitters/antiair_muzzle_fire_01_emit.bp.
WARNING: ...aforever\gamedata\lua.nx5\lua\sim\defaultweapons.lua(215): attempt to call method `ScaleEmitter' (a nil value)
WARNING: stack traceback:
WARNING: …
```
=> Fix release 3732 09

lua/ui/lobby/lobby.lua
Added UpdateGame to DoSlotSwap for the swapping bug (and removed the consequently superfluous ready set checks)
Made SlotMove set ready to false in the relevant playeroption for the ready bug
Tested doing 20ish swaps/moves in-lobby and launching a few times
=> Potential swap and ready bugfixing

lua/shield.lua, lua/sim/Projectile.lua, lua/sim/Unit.lua
Fixes the issue where collision beams can destroy projectiles other than tactical missiles and strategic missiles. Re-applies some table reductions removed by #3794 , but this time correct and with more documentation.
=> Fix projectile-related issues

projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
Closes #3802. 
We didn't remove all of the code related to the old decal / tree knocking behavior. Likely a mistake from #3719 .
=> Remove remainder of old decal / tree knocking code

lua/defaultunits.lua, lua/sim/Unit.lua
Fixes an issue reported by AlfaViTe#4489 on Discord where extractors would still produce mass even when they are paused. Removes some old TA-like code that caused an extractor to loop over all the markers of the map when it is created. This can easily be more than thousands of markers on AI-related maps.
=> Fix issues with extractors

lua/system/class.lua
Allows for ambiguous states. In contradiction to classes, a state doesn't typically inherit from another state. Instead, it just directly overwrites the previous state. As an example:
```lua
-- of StructureUnit class
IdleState = State {
Main = function(self)
end,
},
-- of FactoryUnit class
IdleState = State {
Main = function(self)
self:SetBusy(false)
self:SetBlockCommandQueue(false)
self:DestroyBuildRotator()
end,
},
```
There is no base defined. Therefore anything we do is based on assumptions. And as we can't assume anything when mods are in play we can only make an educated guess.
Luckily, this appears to only happen with the `RKs Explosions` mod - at least what I've heard of. It is because of this pattern, that uses the example of earlier:
```
local oldFactoryUnit = FactoryUnit …
```
=> Allow for ambiguous states

lua/wreckage.lua
Props were changed in #3714 to improve performance, a mistake slipped in that accidentally makes wrecks immune to damage. In particular, a wreck no longer calls the base class. The value `CanTakeDamage` was set in the base class. Wrecks now just always take damage.
=> Fix wreckage not taking damage

lua/system/blueprints-lod.lua, lua/ui/game/gamemain.lua
Tree groups could disappear when broken due to #3662. Now all trees share the same LOD, regardless whether they are an individual tree or a tree group.
=> Fix inconsistent lods

lua/SimHooks.lua
Causes the functions `DrawCircle`, `DrawLine` and `DrawLinePop` to desync if used asynchronously.
=> Anti cheat measures

lua/defaultunits.lua
Removes the delay that causes Aeon structure to look a bit off for the first two seconds after construction.
=> Fix Aeon structures looking off after construction

lua/ui/dialogs/createunit.lua, lua/ui/game/commandmode.lua
Closes https://github.com/FAForever/fa/issues/3819 .
Allows you to select and spawn multiple units, like you were able to in the past.
=> Allow for multiple selected units in cheat window

.git-blame-ignore-revs, config
Allows us to ignore various large commits when using the blame view.
=> Introduce .git-blame-ignore-revs

lua/ui/game/gamemain.lua
Reverts https://github.com/FAForever/fa/commit/cfe4dab93011cdb428d2dba864e67287e80e50eb that removes the input delay of 500ms when someone is playing alone. It also reverts #3653, that tried to tackle this issue.
It introduces a significant penalty on the simulation, causes a wide range of stuttering and introducing the 11'th tick, slowing down the game even though the simulation is at +0. It also breaks the `wld_RunWithTheWind` command.
This behavior was captured with the Benchmark map where there is only one player. The benchmark map could easily be 40 to 50 seconds (on a scale of 180 seconds) faster. A few data points:
- 120.6 revised 74.6
- 155.9 seconds (revised time: 91.9422 seconds ) 
The impact is most notable when you speed up the game. But it is also notable when the game is …
=> Re-introduce input delay when there is one or fewer players

lua/sim/Projectile.lua
When refactoring with #3847  the body of an if statement got reversed, but the condition did not. Closes #3854 .
=> Fix SMDs being unable to shoot down strategic missiles

lua/sim/Entity.lua
(https://github.com/FAForever/fa/pull/3824) introduced an upvalue that caused issues with some UI mods importing sim related files. One of those files was the Entity script. Removing the upvalue improves compatibility with unmaintained UI mods.
=> Fix a bug with Alliance of Heroes mod

lua/defaultantiprojectile.lua, lua/shield.lua
Fixes an issue introduced by #3699 . The shield bar (the blue bar below the shield) was not being updated often enough. In turn, the shield bar was not always in sync with the actual health of the shield. This was most notable when the shield is being assisted, right after it took damage and when it was done healing (when being assisted). 
This was purely a visual glitch, the shield was being healed and it was in fact full health 😄 .
=> Update the shield bar more often

lua/ui/lobby/lobby.lua
Makes it so that when a slot is closed, the game checks if there are any open slots left, and if not, announces that the game is full.
=> Possibly announce game full on slot closure

lua/system/repr.lua
Re-introduces the old repr function and remove some of the verbosity of the new repr function.
`repru` refers to `recursive printing unsafe`, which uses the old repr function
`reprs` refers to `recursive printing safe`, which is the new repr function
`reprsl` refers to `recursive printing safe to log`, which is the new repr function but it immediately logs it uses LOG
=> Adjust recursive printing

lua/sim/weapon.lua
For issue #3758 
Followed Approach 1 and added RecycledPriTable in the outer scope. This table is re-used and cleared each time SetWeaponPriorities() is run.
Followed the [table insertion benchmarks](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/benchmarking/benchmarks/table-insert.lua) for inserting into the priority table as well.
I ran through a few bot matches just to make sure I didn't break the game, but I'm new to Lua and FAF so I may have missed something, please let me know if you spot any issues and I'll attempt to fix them 😁
Edit by Jip: closes #3758
=> Optimized weapon prioritization by re-using single table

lua/ScenarioPlatoonAI.lua
AggressiveMoveToLocation takes second optional arg for the squad to move, but GetHighestThreatPosition was feeding it threat value
=> Hunter AI - fix args for AggressiveMoveToLocation

lua/shield.lua, lua/sim/Buff.lua, lua/sim/Unit.lua
Introduces two flags that can be used by mods:
- `unit.ImmuneToStun`: Prevents the unit from being stunned
- `shield.SkipAttachmentCheck`: Prevents the shield from turning off when attached or not turning on when attached
=> Add flags for mods

lua/ui/game/economy.lua
Fixed red underlying warning texture which stayed visible after UI_ToggleGamePanels.
Before:
https://user-images.githubusercontent.com/36369441/170463095-46859726-4352-495b-8a55-057431ec18cb.mp4
After:
https://user-images.githubusercontent.com/36369441/170462573-32a86846-97b6-4e56-86c6-d23246def421.mp4
=> Economy bar red warning texture fix

lua/ui/game/chat.lua
1) Chat settings window is not displayed correctly, when more than 6 players is in game (or so).
With higher number of the players, bottom part of the window is hidden and you can't save changes.
Before:
After:
- you can also drag this window with mouse, which was not possible
- font size slider steps changed from 2 to 1, so you gain more precise font size
2) When you choose to "Show feed background" under the bare chat lines, there are an ugly paddings, which looks too "stripy": 
Before:
After:
3) Added a QOL button "Apply", so when you trying to find a proper Font size and Alpha, you can use "Apply" button so see your settings without need to always re-open Settings window:
Fig1:
=> Chat settings window fixes & small improvements

lua/system/blueprints-units.lua
Fix for #3892 , where air factories have a significant offset.
=> Do not include (air) structures into footprint adjustments

lua/UserMusic.lua, lua/options/options.lua, lua/ui/menus/main.lua
Although `/nomusic` can be found in binary.exe, seems it is ignored.
Both main menu and in-game music is now actually disabled with this PR, not just muted.
As this switch serves as an override, it does not reset the old `music_volume` value.
Also follows the pattern (Fig1) seen in the video settings (Fig2) if `/windowed` is used while the profile may be set to fullscreen. `Command Line Override` text is not new, therefore does not need new translation.
Tested on:
- campaign
- skirmish
- populated profile
- empty profile
Fig1:
Fig2:
=> Mute all in-game music with /nomusic switch

lua/ui/game/score.lua
Visibilty on UI_ToggleGamePanels fixes:
- properly hides the panel - namely the child icons and the open arrow(when panel is toggled off and ui is hidden)
- improved behavior of the initial state based on the last saved state
- when the last state was hidden: no longer draws thin side of the panel on new game
- when the last state was hidden: no longer needed to double press hotkey to show it again
Tested on empty profile, with no mods
=> Visibilty on UI_ToggleGamePanels fixes

lua/ui/game/score.lua
Change the map size in the score panel to reflect the current playable area instead of the raw map bounds. Some maps will use a base size but edit the playable area to something smaller (e.g. use a 20x20 base size and then limit it to a 15x15). This will update the map size indicator in the score panel to show that.
=> Use playable area for map size

lua/ui/controls/combo.lua, lua/ui/lobby/lobby.lua
This PR does some make-ups to the UI - namely to the:
- scrollbars offsets (general change, Combo+Scrolling )
- scrollable combo last-item empty space
- some lobby UI elements repositioning
- improved [ESC] key behavior in the Lobby
example of the impact - all auto-attached Scrollbars to the Combo elements are repositioned a bit.
Removed an "extra air" under the last Item
This change doesn't affects other (thin) scrollbars nor the some other Vanilla scrollbars (options, in-game chat etc.)
Tested:
- tried to dig through all sections where this particular element is used, does look ok everywhere
- also the "original" remnants in UI, like Replays, load Save etc.
the change is that Esc key can dismiss "Lobby exit prompt" and by pressing Enter key exits lobby.
=> Scrollbars & Lobby small make-ups, widths, paddings

lua/ui/game/score.lua
Closes #3935 
An error sneaked in for co-op where the usual scoreboard doesn't exist. As a consequence all of the UI bogs down for co-op.
=> Add guard surrounding expand / contract functions of scoreboard

lua/defaultunits.lua, lua/sim/Unit.lua, units/UAB0101/UAB0101_script.lua
In particular relevant for tech 1 land factories that can either upgrade to an HQ or a support factory. These should have different upgrade animations.
=> Add support for multiple upgrade animations

lua/EffectUtilitiesAeon.lua, lua/EffectUtilitiesUEF.lua
Closes #3929
Fixes an incorrect replacement done by #3875 to reduce the memory impact of the game.
=> Fix Aeon and UEF build animations

projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua, projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua, projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
Closes #3902
In particular the child projectiles of Cybran missiles did no damage.
=> Fix damage of various projectiles after a split

lua/defaultunits.lua
Closes #3871.
This is a strange one where the engine calls `OnLayerChange` before it calls `OnCreate`. Because of that, the `self.Blueprint` field does not exist yet and therefore we need to add a guard.
=> Add guard around blueprint access

units/DAA0206/DAA0206_unit.bp
Removes a test statement that was part of #3857 , allowing the Mercy to do Mercy things again.
=> Fix Mercy being set to manual fire

.vscode/settings.json, engine/BlueprintCategories.lua, engine/Sim/Entity.lua, engine/Sim/Unit.lua
Currently annotations for EntityId and UnitId treate them as numbers when in reality they are strings, this fixes that.
This also changes settings so that `.bp` files should be treated as `lua` files (the file association setting). however it tells the extension not to parse them for references and diagnostics unless that file is opened in the editor (the ignoreDir setting)
=> Fix bp parsing and annotation types

lua/cybranweapons.lua, lua/defaultunits.lua
Removed all of the truly empty functions I could find.
There are so many more methods that restore a parent's parent behavior, or that does its own version of multiple inheritance; those are beyond the scope of this PR.
Files I checked: everything in `/lua/` and `/lua/sim/`
=> Remove empty functions

projectiles/TDFGauss01/TDFGauss01_proj.bp, projectiles/TIFAntiMatterShells01/TIFAntiMatterShells01_proj.bp, projectiles/TIFHETacticalNuclearShell01/TIFHETacticalNuclearShell01_proj.bp, projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp, projectiles/TIFMissileCruise02/TIFMissileCruise02_proj.bp, projectiles/TIFMissileCruise03/TIFMissileCruise03_proj.bp, projectiles/TIFMissileCruise05/TIFMissileCruise05_proj.bp, projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp
ADD LODCutoff in Projectiles bp for bombs, missiles and torpedos : UEL0001, UEB2108, UES0304, UEL0111, XEL0306, UEL0201, UEB2302, UEB2401
The mainpart here is the lodcutoff add to shells that are used by all UEF tanks and ships.
=> ADD LODCutoff in Projectiles-3

projectiles/AAAZealotMissile01/AAAZealotMissile01_proj.bp, projectiles/AAAZealotMissile02/AAAZealotMissile02_proj.bp, projectiles/AANTorpedo01/AANTorpedo01_proj.bp, projectiles/AANTorpedo02/AANTorpedo02_proj.bp, projectiles/AANTorpedoClusterSplit01/AANTorpedoClusterSplit01_proj.bp, projectiles/AIFBombGraviton01/AIFBombGraviton01_proj.bp, projectiles/CIFMolecularResonanceShell01/CIFMolecularResonanceShell01_proj.bp, projectiles/CIFProtonBomb01/CIFProtonBomb01_proj.bp, projectiles/TAAMissileFlayer01/TAAMissileFlayer01_proj.bp, projectiles/TANAnglerTorpedo01/TANAnglerTorpedo01_proj.bp, projectiles/aaserpentine/AASerpentine_proj.bp
ADD LODCutoff in Projectiles bp for bombs, missiles and torpedos : UEB2304, UES0201, UAA0103, URB2303, URA0304
add "--unused by faf" in AANTorpedo02_proj.bp
=> ADD LODCutoff in Projectiles-2

lua/SimCallbacks.lua, lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/keymap/misckeyactions.lua
As per #3857 weapons no longer retarget as usual. The average scenario does not require this, but especially at the start of the game there are moments where a weapon retargeting is critical. With this pull request we introduce the capability to force a weapon retarget.
As weapon retargeting is not cheap there is a cooldown of one second per unit at which it can retarget its weapons. To confirm to the player that it occurred a small print message is displayed on screen indication how many weapons are rechecking their targets.
=> Add the ability to force a weapon retarget on selected units through a hotkey

lua/system/blueprints-weapons.lua
As reported [on the forums](https://forum.faforever.com/topic/4139/game-version-3738/6) there was an issue with the tactical missile enhancement. The fix was not turning the death weapon into a manual fire weapon. I don't understand why this fixes the issue - the death weapon and the tactical missile appear to be unrelated.
But here we are.
=> Fix the tactical missile enhancements

units/URL0103/URL0103_unit.bp
Medusa often times damage units without stunning them. This changes the stun radius to more closely fit the damage radius.
=> Medusa stun radius fix

lua/system/class.lua
The state initialization of simple classes was skipped, as a consequence these were very buggy. Ironically enough this issue has been in the game for a few months now and nothing crashed - which suggests that it was never used until I was experimenting with it a few days ago.
=> Fix initialization of states of a simple class

init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua
It conflicts with the optimalisations already applied to the game and it introduces a free resource producing unit to only the Cybran faction. It is marked as a cheat mod because of that.
=> Add Quality of Performance 2022 to mod blacklist

lua/ScenarioPlatoonAI.lua, units/UAA0104/UAA0104_unit.bp, units/UAA0107/UAA0107_unit.bp, units/UEA0104/UEA0104_unit.bp, units/UEA0107/UEA0107_unit.bp, units/URA0104/URA0104_unit.bp, units/URA0107/URA0107_unit.bp, units/XEA0306/XEA0306_unit.bp, units/XSA0104/XSA0104_unit.bp, units/XSA0107/XSA0107_unit.bp
Fixes the continental for AIs as it thought the continental could carry 12 tech 3 units instead of 6.
=> Allow transports to define the number of slots in the blueprint

lua/system/blueprints-units.lua
Tech 1 bombers / gunships (footprint of at most 2)
Tech 2 bombers / gunships (footprint of at most 3)
Tech 3 bombers / gunships (footprint of at most 4)
All tech 1 / tech 2 / tech 3 interceptors have a footprint of 2.
=> Adjust spacing of tech 1 bombers and gunships

lua/system/Blueprints.lua, lua/system/blueprints-weapons.lua
=> Fix a typo in `blueprint-weapons.lua`

lua/maui/layouthelpers.lua
Refactor layouthelpers, as proposed in [issue#3762](https://github.com/FAForever/fa/issues/3762#issue-1193077875). Mostly just the things requested there, but comprehensively:
- Standardized comments
- Upvalued math.floor
- Replaced Set with SetFunction where appropriate
- Removed double divide by 2 in centering functions
- Moved optional argument checking into parent functions
- Reused tablelayouts in RightRelativeTo and BottomRelativeTo functions (though if the cost of setting extra local variables is more expensive than the table lookup, let me know)
- Removed redundant multiplication in InvScaleNumber
There's a lot a extra parentheses in here--I just left them because it doesn't matter, but I'd be interested to know if we have a style guideline for that.
=> Refactor layouthelpers

units/URA0401/URA0401_unit.bp, units/URL0402/URL0402_unit.bp, units/XRL0403/XRL0403_unit.bp
Update so units use the overlayantiair and overlayantinavy variants for antiair and antinavy where it is very weak at that role
-Soul ripper, Monkeylord and Megalith
=> Update antiair and antinavy categories-Cybran Experimentals

lua/platoon.lua
Fix for #3282
The ACU can still stop building when enemies are nearby, but this is intended.
Note:
To resume the construction it's needed to fix the AIBehaviors.lua.CommanderThreadImproved() function.
At the moment this will be compensated by the "ManagerEngineerFindUnfinished" platoon.
Before:
after:
=> Reduce unfinished buildings

lua/proptree.lua, units/URA0001O/URA0001O_script.lua, units/URA0002O/URA0002O_script.lua, units/URA0003O/URA0003O_script.lua
Removes the collision shape of various entities that do not or no longer need it.
_Props and drones without a collision shape_
_Props and drones with a collision shape, note that the one of the drones is (really) small_
This was made possible due to an engine patch, see also the [changelog](https://github.com/FAForever/FA-Binary-Patches/blob/master/README.md) of the assembly repository.
=> Remove collision shape from build bots and fallen trees

lua/EffectUtilities.lua, lua/cybranunits.lua, lua/defaultexplosions.lua, lua/defaultunits.lua, units/DEL0204/DEL0204_Script.lua, units/DELK002/DELK002_script.lua, units/URA0001/URA0001_script.lua, units/XEB2306/XEB2306_Script.lua
Replaces all references to the old unoptimized effect utility functions to the optimized ones.
This PR changes `DEL0204`, `DELK002`, and `XEB2306` to no longer store their weapon effects into `ExhaustEffects`, since those units weren't actually taking care of them.
This needs [part 1](https://github.com/FAForever/fa/pull/3995) to work!
=> Refactor effect utilities part 3

lua/ScenarioFramework.lua, lua/UserSync.lua, lua/aibrain.lua, lua/defaultunits.lua, lua/sim/MatchState.lua, lua/sim/score.lua, lua/simInit.lua, lua/ui/game/gameresult.lua, lua/ui/uimain.lua
Re-implements the code that manages the game results that are send to the server. A few big changes:
- The brain is no longer responsible for sending game results
- The file `/lua/victory.lua` is now `/lua/sim/matchstate.lua` and is responsible for sending game results
- The limit of the number of game results to send has been removed
- The 'score' game result is removed entirely
Throughout the game we scan for the conditions of the game mode. We'll take assassination as an example. For that game mode the command unit needs to be alive, if it no longer is then the game mode should end. We scan the brains over time to see if they meet this requirement. 
For each brain scanned there is a small delay. If a brain is considered to be defeated (no units alive that are required for the game …
=> Re-implement game results

engine/Sim/Blueprints/WeaponBlueprintDefinition.lua, engine/Sim/Prop.lua, engine/Sim/Unit.lua, engine/Sim/UnitWeapon.lua
Allows them to return the correct type of blueprint.
=> Add annotation overrides to `GetBlueprint`

units/UAL0202/UAL0202_unit.bp
Makes category more consistent - it has a personal shield, and other units with personal shield have the category PERSONALSHIELD instead of SHIELD (e.g. titan)
=> Category update - obsidian

units/UAA0310/UAA0310_unit.bp
Consistent use of antiair and antinavy categories for experimentals - updates Czar (no changes required to other Aeon experimentals)
Refer to pull request #3952 for discussion on this.
=> Update antiair and antinavy categories-Aeon Experimentals

units/XSL0401/XSL0401_unit.bp
Consistent use of antiair and antinavy categories for experimentals - updates Ythotha (no changes required to other Seraphim experimentals)
Refer to pull request #3952 for discussion on this.
=> Update antiair and antinavy categories-Seraphim Experimentals

units/UEL0401/UEL0401_unit.bp
Consistent use of antiair and antinavy categories for experimentals - updates Fatboy (no changes required to other UEF experimentals)
Refer to pull request #3952 for discussion on this.
=> Update antiair and antinavy categories-UEF Experimentals

units/UEL0105/UEL0105_unit.bp, units/UEL0208/UEL0208_unit.bp, units/UEL0309/UEL0309_unit.bp, units/URL0105/URL0105_unit.bp, units/URL0208/URL0208_unit.bp, units/URL0309/URL0309_unit.bp, units/XEL0209/XEL0209_unit.bp
Consistent use of AMPHIBIOUS for units with amphibious pathing - updates engineer units that are missing this category.
Part of wider change also impacting engineers where all units with amphibious pathing are updated to have the AMPHIBIOUS category - code used to check for such units is:
https://github.com/maudlin27/M27AI/commit/01e45116eb77f8b9adca5af1eb1c4816e8646800
=> Category update - Amphibious - Engineers

units/UAL0001/UAL0001_unit.bp, units/UEL0001/UEL0001_unit.bp, units/URL0001/URL0001_unit.bp, units/XSL0001/XSL0001_unit.bp
Consistent use of AMPHIBIOUS for units with amphibious pathing - updates ACU units that are missing this category.
Part of wider change also impacting engineers where all units with amphibious pathing are updated to have the AMPHIBIOUS category - code used to check for such units is:
https://github.com/maudlin27/M27AI/commit/01e45116eb77f8b9adca5af1eb1c4816e8646800
=> Category update - Amphibious - ACUs

effects/emitters/tractor_01_emit.bp, effects/emitters/tractor_02_emit.bp, effects/emitters/tractor_03_emit.bp, lua/EffectTemplates.lua, lua/aeonweapons.lua, lua/sim/Blip.lua, lua/sim/weapon.lua, units/UAL0401/UAL0401_Script.lua, units/UAL0401/UAL0401_unit.bp
Completely re-implements the tractor beams, fixing all the critical issues with them. Similar to #4020, closes https://github.com/FAForever/fa/issues/2342 .
This pull request tackles:
- The units being sucked up now leave wreckages
- The tractor beam weapons actually properly function, as the previous implementation could cause them to not work at all
And it pimps the behavior slightly:
- More effects to give it a bigger 'oof' factor
- Unit that is being sucked up rotates randomly, like the Aeon Power Generators do. Gives a feeling of 'helplessness' when the unit occasionally manages to aim and fire a shot or two at the colossus
https://user-images.githubusercontent.com/15778155/178206449-965c7bb8-2e88-4aed-8625-b62d33e6bc13.mp4
=> Re-implement the tractor beams of the colossus

lua/shield.lua
Removes the shield bar when the shield is turned off, as it was before #3681. See also [this](https://forum.faforever.com/topic/4449/all-factions-shield-generator-mobile-shields-bug) forum post about it.
=> Disable UI of shields when turned off

effects/range.fx, effects/vision.fx
Another optimization range rings and vision.
TwoSidedStencil hardware support is required.
Since DX9 is very old, I think there will be no problems.
=> Optimize range shaders

lua/sim/MatchState.lua
in case there is no team set in lobby, then brain.RequestingAlliedVictory is nil.
=> fix for game victory in case no team is set.

units/UAL0307/UAL0307_script.lua, units/UEL0307/UEL0307_script.lua, units/XRL0403/XRL0403_script.lua, units/XSL0307/XSL0307_script.lua
Closes #4019 
Adds a guard to check if the weapon still exists (on the c-side), especially relevant when units are sinking. They hit a single `OnLayerChange` call right at the bottom.
=> Add guard if the weapon has been destroyed

lua/shield.lua
```
WARNING: Error running lua script: c:\users\jip\documents\delete-me\fa\lua\shield.lua(593): Game object has been destroyed
[C]: ?
c:\users\jip\documents\delete-me\fa\lua\shield.lua(593): in function <c:\users\jip\documents\delete-me\fa\lua\shield.lua:574>
```
Adds a guard to check if the shield still exists when we create the impact effects.
=> Add guard when creating impact effects

lua/sim/DefaultProjectiles.lua
```
WARNING: Error running OnImpact script in Entity /projectiles/tdfovercharge01/tdfovercharge01_proj.bp at 2bb2c000: ...ocuments\delete-me\fa\lua\sim\defaultprojectiles.lua(513): Game object has been destroyed
[C]: in function `GetBlueprint'
...ocuments\delete-me\fa\lua\sim\defaultprojectiles.lua(513): in function `OnImpact'
...ojectiles\tdfovercharge01\tdfovercharge01_script.lua(19): in function <...ojectiles\tdfovercharge01\tdfovercharge01_script.lua:18>
```
Technically this means that OC has never done damage when it launched but the ACU got destroyed before the projectile impacted.
=> Add check if on overcharge if weapon is destroyed

lua/EffectTemplates.lua, lua/UserSync.lua, lua/lazyvar.lua, lua/ui/game/vo_computer.lua, lua/ui/game/vo_xgg.lua
These files had errors from the extension because there's so many locals declared and it gives up at some point, this just disables those errors. And a few other minor errors.
=> Add annotation to ignore some file specific non errors

lua/system/class.lua, lua/system/import.lua
The pattern reverted in this pull request cause issues when you save / load the game. The up value (read: local in file-scope) pattern on a file-scope applied to tables causes issues. The reference doesn't appear to be updated properly. As a result, the file ends up with an empty table (decoupled from the actual table) that is then used.
Subtle little bug 😄 
I've scanned the code for other places where I used this pattern. I found them in `class.lua` and in the init files. The latter is irrelevant.
closes #3877
=> Fix the save / load functionality of the game

units/XAA0306/XAA0306_unit.bp
Just like all the other torpedo bombers.
=> Fix Solace not having the bomber category

lua/system/class.lua
Basically a while ago I merged in new changes to the extension, and that broke how our class function worked. Looks like some people have tried to fix it with some annotations, but that didn't really seem to work.
This should be a working fine, please confirm we're not seeing any warnings like this:
=> adjust typing of Class so it works again

units/UAA0310/UAA0310_unit.bp, units/URA0401/URA0401_unit.bp, units/XSA0402/XSA0402_unit.bp
Ahwassa: 16.25 -> 40
CZAR: 16.25 -> 34
Soul Ripper: 14.1 -> 28
Justification:
Air T4s had extremely low E-to-mass ratios compared to other T3 air units (For comparison Strat is 68.5 and ASF is 114.2) allowing players to rush them on 2-3 t3 pgens or make them while producing ASF as well. This should also reduce the viability of an Ahwassa Rush Cheese.
=> Adjust Air T4 E to mass ratios

units/XSA0402/XSA0402_unit.bp
Decrease Ahwassa's AoE from 20 to 19. A small nerf to Ahwassa decreasing its effectiveness vs Armies and Air grids
=> Nerf Ahwassa's AoE

units/UAL0307/UAL0307_unit.bp
45 e/s -> 55 e/s
Nerf Aeon Mobile Shield E-drain cost.
Aeon T2 land has become arguably the best with a combination of powerful tanks, cheap shields, and the best ACU. This minor nerf aims at reducing the oppressiveness of Aeon T2 Obsidian + mobile shield spam.
=> Nerf E drain of Aeon Mobile Shield

units/XEB0204/XEB0204_unit.bp
- Set BuildCostMass to `1050` from `500` to allow for the Differential Upgrade Cost Calculation Parameter to work correctly
- Set BuildCostEnergy to `2500` from `5250`
- Add `DifferentialUpgradeCostCalculation = true`
=> Fix The Mass Left Behind when the upgrade kennel is destroyed

lua/cybranunits.lua, lua/defaultunits.lua, lua/sim/Unit.lua
A lot of trashbags are allocated for a unit even if the unit is incapable of using the bag. One example being the `CaptureEffectsBag`. Instead of pre-allocating, we allocate them as we start using the bags.
=> Reduce pre-allocated trashbag count

lua/EffectUtilitiesAeon.lua, lua/EffectUtilitiesSeraphim.lua, lua/defaultunits.lua, lua/shield.lua, lua/sim/Unit.lua
Removes the caching concept that was introduced a while back with https://github.com/FAForever/fa/issues/3691. The concept didn't work out, it was better to just put the data in the blueprint during blueprint loading and store a reference to the blueprint in the unit.
Builds on top of #4138 to prevent collisions
=> Remove cache concept of units

lua/sim/defaultweapons.lua
Fix an issue introduced by #4111 , where beam weapons would no longer disable themselves.
=> Fix beam weapons everlasting

lua/ui/game/multifunction.lua
Fix the hotkey (CTRL + E) and disable the feature in replays.
=> Fix hotkeys and disable in replay

changelog-dev.md, lua/SimUtils.lua
Also includes a partial changelog 😄 
Fixes the issue where units that are being upgraded are gifted twice, in-place. See also:  https://replay.faforever.com/17811485
=> Do not gift units that are not finished

lua/sim/defaultweapons.lua
The table was used by multiple barrels separately, they were overwriting each others manipulators. See also https://github.com/FAForever/fa/pull/4064/files , and in particular this change: https://github.com/FAForever/fa/pull/4064/files#diff-29a4964e78571ea3d37fe1cd130083a802cf3a9341d1909864d9f9445af592f6R498
=> Re-introduce `table.insert` over using a separate counter

lua/defaultunits.lua
As mentioned on Discord and on [the forums](https://forum.faforever.com/topic/4696/cant-build-support-factories) there's an issue with the internal state of HQs. When refactoring it to fix an issue we didn't properly check the edge cases. In particular:
- if an hq would be cancelled during construction then the internal state becomes corrupt
- if an hq tech 3 is finished, the previous tech is removed twice: corrupting the internal state again
=> Fix internal state of HQs

lua/editor/EconomyBuildConditions.lua
This PR replaces some of the default economy condition functions. By default all conditions perform a call to the function aiutilities.lua AIGetEconomyNumbers. This function runs 13 economy functions and does a few other calculations then returns a table. The economy condition then takes the economy property its interested in from this.
For instant build conditions this gets called each time the build condition monitor performs its condition check. This PR removes the excess calls by making the build conditions only call the functions they need for the data required.
Perform an AI game and record the number of times the economy based functions are called using the built in profiler. Then rerun the same game via replay with the refactored code. Ensure no desync due to errors and compare …
=> refactor AI economy conditions

engine/User.lua, engine/User/CUIWorldMesh.lua, lua/UserSync.lua, lua/maui/control.lua, lua/ui/game/casting/mouse.lua, lua/ui/game/gamemain.lua
A useful feature for casters: being able to see where the mouse of the players is pointing at! The feature isn't smooth yet, still needs some polishing. But the idea works and it is cheat free. We 'abuse' the chat system that allows you to send any data to any client. The data is properly culled by the engine, as a result players that should not receive the data has no idea that information has been send. There's no way to retrieve this via the UI.
https://user-images.githubusercontent.com/15778155/187092955-a22027f5-af25-44fe-868a-f1e801b6db97.mp4
Things to take care of:
And nice to have features:
This pull requests adds in the tracking of the mouse of players. But similarly, we could track their camera settings (to see what they are seeing) and other interesting information that can be …
=> Share mouse position of players with observers

lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/keymap/misckeyactions.lua, lua/keymap/targeting.lua
This PR integrates @4z0t's ui mod called Specific Target Priorities to the game. This mod allows a player to select with a hotkey the kind of unit they with their units to target. In addition to integrating the current mod i am also making modifications that will allow the targeting of all variations of units (different factions) without selecting each on individually.
=> Integrated STP with Category Support

units/XSL0401/XSL0401_unit.bp
Fixes a few issues that were introduced by https://github.com/FAForever/fa/pull/4084.
Fixes the issue where the collision box no longer extends towards the ground. Apparently bombers always aim at the ground near units, not anywhere else. As a consequence some bombers (Tech 1 Cybran, tech 2 Seraphim) were essentially unable to hit the Ythotha. 
Also fixes the issue where the footprint of the Ythotha was accidentally changed to a 1x1 Amphibious footprint, instead of a 3x3. The footprint is derived from the collision size box, and the latter got changed. As a result the experimental was no longer 'Massive', and could not pass over structures.
And fixes the issue where only one engineer would try and build the Ythotha. Not sure what caused or fixed this exactly - maybe it is because the unit …
=> Fix issues with Ythotha

lua/defaultexplosions.lua, lua/defaultunits.lua, lua/utilities.lua
Related to this change: https://github.com/FAForever/fa/pull/4129/files#diff-2a6f1a4e584cb2b6df034b8760a5bcfb2feaaf3eadd4dfc6caa4e86b96d57433R141
The duration of the death animations (read: number of explosions) was technically not related to the size of the unit, but to the size of the x-axis of the unit. This was (in accident) 'fixed', where as it was purposefully left like that to prevent having to remap a lot of effects. Anyway, ended up doing that now.
The animation duration is now roughly where they were before, but with less randomness in them.
=> Fix duration of death animations

lua/ui/lobby/lobbyOptions.lua
Just a QoL change that makes share condition the top option in its options list and allow observers third (as opposed to both being lower down on the list)
=> Reorder Lobby Options

lua/sim/defaultweapons.lua
* Props no longer break the targeting of bombers
* Salvo data is now reset once the salvo cycle is complete
* Improved free-falling of bomb clusters in the failure mode
* More hyper-optimization of `CalculateBallisticAcceleration`
=> Fix props breaking bomber targeting

lua/sim/Projectile.lua, lua/sim/Unit.lua
This PR corrects a small typo and makes some changes to enable callback functionality for the previously created callback `OnMissileImpactTerrain`. I'm not 100% on initializing the self.Callbacks table in the OnCreate function for the unit class but it seemed like the way to go.
I'll work my way through testing the other OnMissile callbacks against the AI when I can get time.
This PR was tested against the RNGAI sim mod by the following method.
Within the tactical missile platoon function it will loop through all available launchers.
It will then perform the following.
```
if not tml.terraincallbackset then
tml:AddMissileImpactTerrainCallback(missileTerrainCallbackRNG)
tml.terraincallbackset = true
end
```
The callback function
```
function MissileCallbackRNG(unit, targetPos, impactPos) …
```
=> OnMissileImpactTerrain changes required for functional callback

lua/tests/DumpQAVChecklist.lua
Flipped the `\` to `/` that errored out the Intellisense due to it thinking that it trying to escape.
=> Fix Escaping Characters

lua/system/blueprints-units.lua, units/UAL0303/UAL0303_unit.bp
As https://github.com/FAForever/fa/pull/4218 points out, there's no good way to solve Harbingers stopping to reclaim with Attack-Move without an engine patch. This PR makes it happen by applying a new category, `SACU_BEHAVIOR`, to the Harbinger. This works due to https://github.com/FAForever/FA-Binary-Patches/pull/13 renaming the `SUBCOMMANDER` category to `SACU_BEHAVIOR` in the engine (and we prevent compatibility issues by automatically adding `SACU_BEHAVIOR` to any unit with `SUBCOMMANDER`). There are no other side-effects because Harbingers cannot rebuild structures.
=> Make Harbinger behave like SACU's

lua/sim/ScenarioUtilities.lua
Got broken in the recall patch; this fixes it
=> Fix "reveal civilians" not resetting civilians to neutral

engine/User/UserUnit.lua, lua/lazyvar.lua, lua/maui/border.lua, lua/maui/layouthelpers.lua, lua/maui/window.lua, lua/system/class.lua, lua/ui/game/cursor/depth.lua, lua/ui/game/cursor/hover.lua, lua/ui/game/diplomacy.lua, lua/ui/game/gamemain.lua, lua/ui/game/recall.lua, lua/ui/lobby/data/watchedvalue/watchedvalue.lua, lua/ui/uiutil.lua
This PR introduces Layouter support for the `Layout()` pattern by having the Layouter call it on `End()`. This moves laying-out out of the initializer so that controls can be completely created before they're laid out--something very handy when `End()` requires the entire component hierarchy to be complete to function properly. This also eliminates the need for a component to layout itself to layout its children, and thus increases modularity. In addition, controls can now set their layout to depend on children attributes without needing to interlace their layouts in a confusing manner.
See the [documentation](https://github.com/Hdt80bro/fa/blob/layout-pattern/lua/maui/layouthelpers.lua#L1090-L1175) for more details.
=> Decouple UI intialization and laying out

lua/system/Localization.lua, lua/ui/lobby/lobby.lua
In an attempt to increase type safety, `LOC()` was prevented from having numbers passed in as an argument. While this uncovered several bugs, it appears to have broken several mods that try to localize numbers this way and needs fixing.
=> Let numbers be passed into LOC

lua/seraphimunits.lua
In response to [this forum post](https://forum.faforever.com/topic/4965/sera-airfab-engineers-are-not-selectable-in-the-unloading-process). I always found it annoying too 😄 
Appears there is no easy solution with the existing approach (where the engineer is 'tethered' off), but why not just 'blink' it off? Like a rabbit from a magicians hat:
https://user-images.githubusercontent.com/15778155/194754212-5e56257a-3f06-4dbf-bdb5-1baf4731bbb0.mp4
I'm not entirely sure about the effects being used, open to suggestions for alternative effects. But this would be the only viable solution that I can see so far.
=> Attempt at fixing engineer behavior for Seraphim air factories

lua/keymap/hotbuild.lua, lua/ui/game/commandmode.lua
Fixes the issue where if you issue (heh) the command to produce a unit the command mode would end in an indefinite loop, and by doing so it would cancel the first order you try to give. This fixes that by properly resetting the command mode state, which didn't happen previously.
And a video of the issue: https://youtu.be/_v2U8sVnGlw
With thanks to @FemtoZetta for reporting it
=> Fix an odd CommandMode related bug with queueing factory orders

lua/sim/Unit.lua
One could end up with an invisible and invulnerable unit if you'd attach them to the UEF t2 gunship, let that dock with the Atlantis and then the Atlantis gets destroyed. The cargo would live on, as if it is a ghost that will haunt its opponents indefinitely.
Either how, that is fixed now - when a unit is de-attached it will check if the unit it was attached to is destroyed. If it is, then so is the de-attached cargo.
=> Fix a glitch with the atlantis and gunships with cargo

lua/AI/AIBaseTemplates/ChallengeMain.lua, lua/AI/AIBehaviors.lua, lua/AI/aiattackutilities.lua, lua/AI/aiutilities.lua, lua/aibrain.lua, lua/editor/EconomyBuildConditions.lua, lua/platoon.lua, lua/sim/EngineerManager.lua
This PR implements the first of a series of AI fixes and improvements.
The PR focuses on the following.
Small adjustment to the base template for the 'Normal AI' so that it will build a couple more engineers and one more land factory.
**Improve the AttackForceAI by the following**
Add a maximum platoon size count to stop attack force platoons growing beyond a comfortable size. A PlatoonFull property will be set when the platoon goes beyond its size limit. It will default to 40 if unset.
Add size restrictions to the MergeWithNearbyPlatoons platoon function by way of a maxPlatoonCount param that will check if the platoon is already at maximum size.
**Improve the EconomyMonitor**
Implements a new Economy Over Time thread that will provide a 30 second history (compared to the previous 8) of …
=> Implement first round of ai fixes and improvements

.github/workflows/build.yaml, run_lua_syntax_checker.sh, run_lua_tests.sh, tests/test_class.lua
Currently, all testing in the workflow is hardcoded to the end of the syntax checker. This PR will separate them out, and support all test files in `/tests`.
=> Improve workflow for testing

lua/sim/NavDebug.lua, lua/sim/NavGenerator.lua, lua/system/import.lua, lua/ui/game/NavGenerator.lua
Moves `__OnDirtyModule()` to `__moduleinfo.OnDirty()` and introduces a mechanism for old modules to share their data new modules either via `__moduleinfo.old` (set in the new module while it loads) or `__moduleinfo.OnReload(newmod)` (called from the *old* module with the new one as the argument).
=> Refactor module reloading

lua/sim/MatchState.lua
The defeat time was inadvertently increased. It should now better match what it was before. Also adds in log statements as to when a player is defeated, won or drew.
=> Match defeat time with pre-3744 patch

lua/AI/aiattackutilities.lua
This PR updates the default platoon function NavalForceAI to use the IssueAggressiveMoveAlongRoute method for pathing movement instead of AggressiveMoveToLocation. This improves the platoon movement mechanics and movement speed along complex routes when the platoon size is greater than 3.
Setup an AI game with a default normal AI on a naval map. Once they have established a naval expansion spawn a bunch of frigates/destroyers/navalunits and the AI should form a platoon using the NavalForceAI. Similar to the screenshot. The platoon should have a much smoother form of movement compared to previously, especially once the number of units in the platoon gets up. Because it is using an aggressive move then platoon members may stop to try and shoot something that will hold up the platoon …
=> Update NavalForceAI to use IssueAggressiveMoveAlongRoute

lua/ui/game/straticons.lua
Fix: #2888
https://github.com/FAForever/fa/issues/2888
The instruction was a bit unclear but in consultation with Jip, we agreed to add the missing big icon for the seraphim.
=> Fix: E storage icon is now displayed correctly

lua/sim/BuilderManager.lua, lua/sim/FactoryBuilderManager.lua
This PR fixes a long standing issue with the default factory manager. When a factory is upgraded the original factory is never destroyed or removed from the AI's factory manager list. This in turn causes the FactoryLessAtLocation and FactoryGreaterAtLocation conditions to return incorrect results. Any AI logic that queries factory counts from this list will be invalid after the first factory has upgraded.
Note : I wasn't sure about adding the table rebuild function. But it seemed like a valid requirement for maintaining the factory list table.
Test setup for the changes
With the default code add logging to the factory manager that will provide the list of factories that the AI has (or a count). When the AI upgrades a factory you will see that the factory list …
=> Fix/ai factory manager not removing factories after upgrade.

lua/seraphimunits.lua, units/XSL0402/XSL0402_unit.bp
Originates from [this forum post](https://forum.faforever.com/topic/4441/make-the-ion-storm-selectable-as-a-neutral-unit-and-give-it-a-veterancy-bar/3). Allows a player to hover over the storm that originates from the Ythotha upon dying. This allows players to see how much experience the storm gained over its life span.
https://user-images.githubusercontent.com/15778155/197402658-a64df719-acc9-49e2-80c9-20072b555d91.mp4
I've look at the example mod (Othuy mass killed) - the implementation in this pull request preserves the original behavior.
=> Allow hovering over the Ythotha storm

lua/defaultunits.lua
Solves the issue of the HQ system being not fully supported by the upgrading mechanics of the game. This allows you to easily determine if you can do an upgrade, and if you can to what blueprint id you can upgrade to.
=> Add support functions for the HQ mechanic for AIs

lua/sim/NavGenerator.lua
Issue showed up on the map Autumn, that actively uses the terrain type to prevent units from walking onto cliffs.
=> Fix terrain type using local coordinates

lua/shared/color.lua, tests/luft.lua, tests/test_colors.lua, tests/test_utils.lua
Please have in mind that this is my first contact with **Lua**.
I've started working on first task from #4295 and found out that `equal` function in Luft is not working (always returns `true`).
I created this PR to address found problems and provide potential improvements
- `to.equal` node had assigned `test` function instead of `Test`, so testing function was not invoked, and tests using it returned `true` - fixed
- ~~Each `PathNode` in `Luft` has `To` field, I assume it was added to describe how nodes should be combined, e.g.:
`Test.expect().to.equal()` is correct
`Test.expect().to.equal.equal()` is not
The `PathNode:GetNext(word) -> PathNode` at the end of the function was always checking if there is matching `PathNode` for current word in list of all possible nodes instead of `To` …
=> [4295] Part zero - fix bugs found in luft.lua

tests/test_NavDatastructures.lua
PR covers first task from #4295
It contains black box unit tests for `sim/NavDatastructures.lua`, covered functions:
- `IsEmpty`
- `Clear`
- `Insert`
- `ExtractMin`
=> Create tests for NavDatastructures.lua

engine/Core.lua, engine/Core/Blueprints/UnitBlueprint.lua, lua/aibrain.lua, lua/defaultunits.lua, lua/sim/Unit.lua
This pull request fixes various issues with factories:
- (1) A factory that assists another factory uses the rally point of the other factory to compute the correct roll off point
- (2) A factory can now spin the unit to the correct roll off point when the unit is finished building, see also:
https://user-images.githubusercontent.com/15778155/197396006-eac6737a-aa3b-4012-be22-0579abb667a4.mp4
- (3) A factory no longer waits for the unit that is being built to finish its first order. That order can get cancelled by a player (or an AI) and by doing so, artificially decreasing the 'roll off costs'. Instead, the function takes into account the distance of the unit to the build pad. If unit is sufficiently far away it will start building the next unit …
=> Adjust factory behavior when building and finished building a unit

init.lua, init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua
With thanks to #4321 we can now deprecate a specific version of a mod. This updates the remainder of the deprecated mods to have a version number, with the one exception that I couldn't find any more 😄
=> Update deprecated mods with the correct version number

lua/defaultunits.lua
Fixes the warning `warning: Precondition Failed: No AdjacentUnits registered for entity: cfunction: 1B43C500` and properly populates the table for both units (both the provider and the recipient). You can now use the table to retrieve units that are providing adjacency bonusses to another unit.
=> Fix adjacency warning and properly populate the table

lua/ui/game/reclaim.lua
Increase 'batch radius' and adjust depth of label to its mass value.
=> Tweak reclaim overlay parameters

lua/defaultunits.lua
The functions `OnAdjacentTo` and `OnNotAdjacentTo` are called to all adjacent structures when a structure is finished or destroyed. It does not take into account whether the adjacent structure is finished too.
This additional check guarantees that 😄
=> Guarantee that units are finished building when updating adjacency

engine/Sim/UnitWeapon.lua, lua/aeonweapons.lua, lua/defaultunits.lua, units/UAL0401/UAL0401_Script.lua
Units that are tractored into the water get killed now. The colossus will also try and actively prefer beaming units that are not tractored, the only exception when this doesn't happen is when the player specifically orders the colossus to attack a given unit. 
In the 'usual' cases (where you just walk) it works better now.
=> Fix glitches with colossus tracking

lua/SimHooks.lua, lua/WeaponPriorities.lua, lua/sim/CategoryUtils.lua
By carefully tweaking the string that should represent a table of categories, one could execute any code in the simulation and have it synced too. This was found by @iczero , and provided a sample:
```lua
local derp_orig = "for k, v in ArmyBrains do " ..
"if not IsAlly(v:GetArmyIndex(), __OWN_ARMY__) then " ..    
"print('army: ' .. v.Nickname .. ' ' .. v.Name) " ..                             
"for _, u in v:GetListOfUnits(categories.COMMAND, false) do " ..                 
"u:Kill() " ..                                                               
"end " ..                                                                       
"end " ..                                                                           
"end return categories.COMMAND" …
```
=> Fix remote code exploit

lua/ui/controls/worldview.lua
Allows the attack ping to function as expected again, as that uses the same cursor.
=> Add guard around attack reticules tracking
