FAForever/fa

lua/ui/lobby/lobby.lua

Looks like someone screwed up a merge conflict somewhere and brought this now very-much-dead code back.

Remove "Extra" background option... again

---

lua/ui/lobby/lobby.lua

Autobalance now choose a balance within 95% of optimal balance instead of
90%.

Reduce tolerance of autobalance

---

lua/ui/lobby/lobby.lua

Working towards resolving our two outstanding issues with the preset system:
\#399 and \#402

Overhaul preset system

---

lua/maui/button.lua
lua/ui/lobby/lobby.lua

This prevents disabled buttons from losing their "disabled" appearance under certain conditions.

Don't handle mouse events for disabled buttons

---

lua/ui/lobby/lobby.lua

A variety of very trivial steps toward using UpdateGame less.
Future work should exploit the WatchedValue mechanism to further reduce the amount of work being done here (but this is a reasonably good first step that'll make the next stage simpler)

Call UpdateGame less

---

lua/ui/maputil.lua

Make the map list sort in a case-agnostic alphabetic way. AaBbCc instead of ABC...XYZabc...xyz

Improve map sorting

---

lua/system/Blueprints.lua

Check enhancements for MaxRadius when setting GSR

---

lua/sim/Unit.lua

Couldn't get the methods in #603 working for the sinking naval units, seems like the animation doesn't trigger any impact at all (I guess the actual phsyical unit isn't moving)
Restored the seabed check for naval units until we can come up with a better way (doubled the poll time to reduce cpu-load). Can keep this PR open until closer to release if we find a better way. At least we got rid of the seabed watcher for non-naval wrecks which should be an improvement anyhow
Fixes #603

Detect seabottom impact of sinking navy

---

lua/sim/Unit.lua

Make sure originalBuilder is reset

---

lua/ui/game/layouts/unitview_left.lua
lua/ui/game/layouts/unitview_mini.lua
lua/ui/game/layouts/unitview_right.lua
lua/ui/game/unitview.lua
units/XSL0001/XSL0001_unit.bp
units/XSL0301/XSL0301_unit.bp

Fixing a couple issues with the unit view icons.

Unitinfo icons

---

lua/defaultunits.lua

Paused commanders still had the build effects going.
~~Did some refactoring so the build effect stuff is handled in the base Unit class instead.~~

Fixed bug with build effects

---

lua/maui/text.lua
lua/ui/game/chat.lua

Multi-line messages no longer time out faster the more lines it's on.
New messages no longer necromance the previous line.
Line wrapping is much less stupid.

Chat fixes

---

lua/ScenarioFramework.lua

Washy's fix for https://github.com/FAForever/fa-coop/issues/12 cause he's too lazy.

Fixing FakeTeleportUnit function

---

effects/Entities/InainoEffectController01/InainoEffectController01_script.lua

https://github.com/FAForever/fa/issues/878

Make Seraphim T3 Nuke damage itself

---

lua/ui/dialogs/teamkill.lua

Hotfix teamkill to not show up in replays

---

lua/aeonweapons.lua
lua/cybranweapons.lua
lua/seraphimweapons.lua
lua/sim/defaultweapons.lua
lua/terranweapons.lua
units/UAL0001/UAL0001_script.lua
units/UEL0001/UEL0001_script.lua
units/URL0001/URL0001_script.lua
units/XAB1401/XAB1401_script.lua
units/XSL0001/XSL0001_script.lua

Refactor death explosion nukes

---

lua/sim/CollisionBeam.lua
lua/sim/Projectile.lua
units/UAL0401/UAL0401_unit.bp

Asked Zock what to be done, wants consistent behaviour. Quick aeolus polls had most saying impact should happen and missile should die to the beam.
Fixes #628

Have beams kill missiles

---

lua/AI/OpAI/BasicLandAttack_save.lua

PR to see if travis stops borking

Fix travis error

---

changelog.md
lua/ui/lobby/ModsManager.lua
lua/ui/lobby/UnitsAnalyzer.lua
lua/ui/lobby/UnitsRestrictions.lua
lua/ui/lobby/lobby.lua

Fixed #1221 and #1219 by correcting bad merge of a fix for #1216.

Hotfix for pre-loading BPs after mods are changed

---

units/UEA0203/UEA0203_unit.bp

Uveso's change. He deleted the branch for some reason and git wouldn't let me merge.

Add TRANSPORTFOCUS to UEF T2 Gunship

---

lua/aibrain.lua
lua/sim/score.lua

I would love to have this deployed ASAP so we can reset the stats
Fixes #1362

Fix same unit stats being reported for all players

---

units/XSL0101/XSL0101_script.lua

Seems Selen got left out of https://github.com/FAForever/fa/pull/872/commits/ff09831003a616c62a51e7ef9ebfdd41ce488fb3
This just brings it up to date. Fixes #1384

Fix Selen radar not enabling properly on build

---

units/UEL0203/UEL0203_unit.bp

Riptide speed on water increased to 3.3 from 3.

riptide speed increase on water

---

units/UAL0001/UAL0001_unit.bp
units/UEL0001/UEL0001_unit.bp
units/URL0001/URL0001_unit.bp
units/XSL0001/XSL0001_unit.bp

RAS and ARAS buildtime doubled from 1400 to 2800

Double RAS and ARAS buildtime

---

units/XAL0203/XAL0203_unit.bp
units/XSL0203/XSL0203_unit.bp

Increase the aeon and sera hover tanks speed on water to 3.5 from 3

hovertanks waterspeed increase

---

units/UAL0205/UAL0205_unit.bp
units/XSL0205/XSL0205_unit.bp

increase hoverflak speed to 3.5 from 3

hoverflak speed = 3.5

---

units/UAA0310/UAA0310_unit.bp
units/UAB2205/UAB2205_unit.bp
units/UAB4202/UAB4202_unit.bp
units/UAB4301/UAB4301_unit.bp
units/UEB1102/UEB1102_script.lua
units/UEB1102/UEB1102_unit.bp
units/UEB1302/UEB1302_unit.bp
units/URB1302/URB1302_unit.bp
units/URB2104/URB2104_unit.bp
units/XSA0402/XSA0402_unit.bp
units/XSB2205/XSB2205_unit.bp

Some animations are declared inside Blueprint but are not existent as file.
Also removed animation scripting inside UEB1102 (UEF Hydro)

Fix missing animations

---

lua/sim/Unit.lua
units/UEA0203/UEA0203_script.lua
units/XAB2307/XAB2307_unit.bp

https://github.com/FAForever/fa/issues/1444#issuecomment-243266821
Faster drain means that the weapon no longer jams at buffed fire rates.

Fix Salvation Adjacency

---

lua/sim/Unit.lua
units/UEA0203/UEA0203_script.lua

Fixes https://github.com/FAForever/fa/issues/1456

Stop carrier content being targeted

---

units/XEA0306/XEA0306_Script.lua

Also check damageType instead of instigator category

Fix Continental not dying to nukes

---

units/XAB1401/XAB1401_unit.bp

To get through Continental Shielding

Use 'Nuke' damage category for Paragon explosion

---

units/UEL0111/UEL0111_unit.bp

UEF mml friendly fire fix

---

units/DEA0202/DEA0202_unit.bp
units/DRA0202/DRA0202_unit.bp
units/UAA0203/UAA0203_unit.bp
units/UAA0204/UAA0204_unit.bp
units/UAA0302/UAA0302_unit.bp
units/UAA0303/UAA0303_unit.bp
units/UEA0203/UEA0203_unit.bp
units/UEA0204/UEA0204_unit.bp
units/UEA0302/UEA0302_unit.bp
units/UEA0303/UEA0303_unit.bp
units/UEA0305/UEA0305_unit.bp
units/URA0203/URA0203_unit.bp
units/URA0204/URA0204_unit.bp
units/URA0302/URA0302_unit.bp
units/URA0303/URA0303_unit.bp
units/XAA0202/XAA0202_unit.bp
units/XAA0305/XAA0305_unit.bp
units/XAA0306/XAA0306_unit.bp
units/XRA0305/XRA0305_unit.bp
units/XSA0203/XSA0203_unit.bp
units/XSA0204/XSA0204_unit.bp
units/XSA0302/XSA0302_unit.bp
units/XSA0303/XSA0303_unit.bp

Will allow planes to refuel more easily by packing more onto one structure.

Reduce Air Staging size for most planes

---

lua/AI/OpAI/BaseManager.lua
lua/AI/OpAI/BaseManagerPlatoonThreads.lua
lua/editor/BaseManagerBuildConditions.lua

Remove more instances of GetUnitBeingBuilt()

---

loc/ES/strings_db.lua

Small typo that prevents the file from loading.

Fix Typo languagefile ES

---

lua/SimPing.lua
lua/sim/defaultweapons.lua

The old pings used army-1 for some stupid reason, billy nuke launch data never got to know that this now changed.

Fix offset hack of billy nuke

---

lua/sim/Unit.lua
lua/system/Blueprints.lua

But with significantly less overhead :D
(Works great with Selen)

Integrate visual cloaking FX from BlackOps

---

lua/sim/ScenarioUtilities.lua

Coop: AIs get faction chosen in lobby

---

lua/ui/lobby/lobby.lua

Depends on https://github.com/FAForever/server/pull/232

Click on game title to update it

---

lua/SimObjectives.lua

fixes FAForever/faf-coop-maps#131 (speed2 told me to PR it here)
I created an extra parameter in the Requirements list : Armies
Armies allows to add multiple armies to the requirements and all of the armies in this list will contribute for the objective.
Old ArmyIndex still works and can be used together with Armies.
I tested with this custom coop scenario.[cat.zip](https://github.com/FAForever/fa/files/546609/cat.zip)

Make CategoriesInArea objective work for all players

---

lua/ui/dialogs/mapselect.lua
lua/ui/lobby/lobby.lua

fixes #1666
I made some changes to lobby setting persistence like we talked about in the issue.
Needs some testing to see if its what people had in mind.

Improve lobby option persistence

---

lua/ui/game/chat.lua

fixes https://github.com/FAForever/fa/issues/1690

Rename lobui_0592 to lobui_0692

---

lua/ui/lobby/lobby.lua

the host now sends the information if a spot is closed or closed - spawn mex in a cleaner way
also bug fix for handling this message on the client side

bug fixes for close - spawn mex

---

lua/EffectUtilities.lua

fixes https://github.com/FAForever/fa/issues/1709

fix reclaim beam endpoint

---

lua/SimObjectives.lua

Currently only 1 person can complete these objectives, so you can't really call that coop.
fixes FAForever/fa-coop#55

Allow StatCompareObjectives for more armies

---

lua/ui/lobby/lobby.lua

Lobby: From-To private message, bugfix

---

units/XAC2101/XAC2101_unit.bp

added the economy values for the aeon palace shield based on zocks suggestion.

add balance changes for aeon palace shield

---

effects/terrain.fx

Fix by ozonex, but since he doesn't git ...

Fix terrain rendering bug on maps with water and TTerrainXP shader

---

etc/faf/blacklist.lua

Blacklist some mods

---

units/DEA0202/DEA0202_unit.bp

Increase the burn time and reduce the initial damage of the bombs.

Rebalance Janus bomber

---

lua/defaultunits.lua
projectiles/ShieldCollider/ShieldCollider_script.lua
units/UAA0104/UAA0104_unit.bp
units/URA0104/URA0104_unit.bp

Enhanced version of Exotic's transport death that we think has ironed out the bugs with version 1. #1432

Feature/transport wreckage - Fixes #1432

---

lua/SimUtils.lua

This will make it possible to use in Coop where unit can changes during
the mission.

Use current value for updating UnitCap

---

units/UAB2305/UAB2305_unit.bp
units/UEB2305/UEB2305_unit.bp
units/URB2305/URB2305_unit.bp
units/XSB2305/XSB2305_unit.bp

Re-scale some launchers in physical size to fit the new box

Normalise Nuke Launcher hitbox extents

---

lua/sim/Unit.lua
lua/ui/game/construction.lua
lua/ui/game/layouts/construction_left.lua
lua/ui/game/layouts/construction_mini.lua
lua/ui/game/layouts/construction_right.lua

You should now be able to use pause button in all 3 tabs.
Currently whenever you pause in selection tab, an error is thrown in the log. 
This should also be fixed with the last commit.
fixes #1739

Allow Pause button in all tabs + small bug fix

---

lua/ui/lobby/lobby.lua

Should fix some of the issues with faction selector for non-host players.
Probably also fixes #1825

Lobby: Properly update FactionSelector

---

lua/ui/game/orders.lua

Just a simple refactor for a hook. No need to add other stuff like my previous commit.

Refactor for easier hooking for AbilityButtons

---

lua/ui/lobby/lobby.lua
lua/ui/uiutil.lua

Fixes some bugs for this https://github.com/FAForever/fa/commit/127608ceb5de4420c67e07323de94bc70219228b
In normal play all maps are of type skirmish, right?

Check if the lastscenario is of the correct type for this host

---

lua/SimUtils.lua

Update unit buildrestrictions incase of RESEARCH unit sharing

---

lua/ui/game/construction.lua

Make sure to clean up variable that saves current selection.
fixes #1624

Fix for pause bug

---

units/DEA0202/DEA0202_unit.bp

correct overall damage by reducing damage over time pulses

---

lua/ScenarioFramework.lua

This got accidentally added  by https://github.com/FAForever/fa/commit/654dd419e1855992e205235b086d2a20563fd50b

Fix FakeGateInUnit function

---

lua/ui/game/construction.lua

Ok this should do it, i think.

Fix always visible construction

---

lua/keymap/hotkeylabels.lua

Fix error message of hotkeylabel for upgradekey

---

effects/mesh.fx

Copied and renamed the old NormalMappedPS function to
NomadNormalMappedPS and updated all nomad techniques that were using the
old version to use the new version. The new version adjusts the color
and alpha values to give things a bit more glow while not desaturating
the color.

Added Pixel Shader for Nomads and tweaked bloom values

---

units/XEA0002/XEA0002_unit.bp

Crash damage reduced from 3k to 1k to discourage abuse.

reduce satellite crash damage

---

units/UAB2204/UAB2204_unit.bp
units/UEB2204/UEB2204_unit.bp
units/URB2204/URB2204_unit.bp
units/XSB2204/XSB2204_unit.bp

Buff static flak to allow it to hit t3 bombers more often.

rebalance static flak

---

units/UAL0201/UAL0201_unit.bp

FiringRandomnessWhileMoving from 0.1 to 0.6

increase aurora inaccuracy while moving

---

lua/ui/game/objectives2.lua

Fix objective tooltip not changing with the faction skin

---

lua/sim/Unit.lua

only test if the unit should sink when it's a naval unit

fix/ large experimentals not using death animation

---

lua/ui/dialogs/mapselect.lua
lua/ui/lobby/ModsManager.lua
lua/ui/lobby/lobby.lua

Lobby: update number of activated mods display

---

lua/ui/game/missiontext.lua

Result: https://puu.sh/vKt08/46660b57a6.png

Save VOs for a Transmission log

---

lua/ui/lobby/lobby.lua

Lobby: Fix bugs with double clicking allowing changes afters x-ing

---

lua/ScenarioPlatoonAI.lua

Caused by wrongly uncommenting in the clean up
https://github.com/FAForever/fa/commit/20441e537f632fd22cc2c2131f609ea25af16e7a

Fix cleanup error

---

schook/lua/SimSync.lua

Fix observers not seeing correct unit regen

---

lua/ui/game/gamemain.lua

Add dropshadow so the loading tips text gets more constrast compared to the background

Make loading tips more readable

---

lua/keymap/keyactions.lua

It couldn't find the file without the "/", so it didn't work anymore.
http://forums.faforever.com/viewtopic.php?f=3&t=14596

Fix zoompopper keyaction

---

lua/ui/lobby/lobby.lua

Lobby: don't stretch the country flags

---

lua/simInit.lua

To avoid issues with invalid ShareOption later on in the game. Fixes #2042

Make sure ShareOption is set to a proper value

---

lua/ui/lobby/lobby.lua

Fix lobby title cant be changed if set to empty string

---

lua/AI/sorianutilities.lua

The short story;
Tactical missiles hitting the ground instead of experimentals if the hitbox is to high:
After this fix, missiles will aim a bit behind the target to hit the Hitbox in midair:
And the long story;
I hooked the original sorian LeadTarget function for my smartmissile mod.
After some test i found out, that there are some bugs.
So i rewrote some parts of the function to make it work propper.
And it's maybe a good idea to put the new function into the maingame.
What i did:
First of all i cleaned the sorianutilities.lua file.
I did not only a syntax cleaning, i also removed all unused function from the file.
Most of them where copy+past garbage from the sorian AI mod.
I added warnmessage to all functions i removed at the end of the sorianutilities.lua
Then i modified the …

Advanced lead target

---

lua/defaultunits.lua

Fix error when CZAR is killed while carrying units

---

lua/options/options.lua

fixing a loc key 
See https://github.com/FAForever/fa/blob/develop/lua/ui/help/tooltips.lua#L810

Give factional_ui_fon_color title the correct loc key

---

lua/formations.lua

Naval formation size is now calculated once based on both surface ships and subs, rather than calculating it twice independently and choosing one.

Formations: Fix mixed naval formation sizing

---

lua/ui/game/objectiveDetail.lua

Failed bonus objectives were showing title and description

Properly hide bonus objectives

---

lua/AI/OpAI/NavalAttacks_save.lua

Fixes/Additions to OpAI Naval platoons

---

lua/sim/defaultweapons.lua

This fixes #2057. It works correctly in my tests but something doesn't feel quite right, so some public testing might be wise.

Fix overcharge queuing

---

units/XRL0403/XRL0403_unit.bp
units/XSL0401/XSL0401_unit.bp

Fixes #763 by adding LayerChangeOffset to the Megalith and Ythotha.

Fix Ythotha and Megalith visibility when in water

---

etc/faf/blacklist.lua

adds one more version of notify to the blacklist

blacklist notify v3.7

---

lua/keymap/keydescriptions.lua

since we have t3 maa in the default preset for hotbuild we should have it in the key description as well

add T3 MAA to the key description

---

changelog.md
lua/keymap/unitkeygroups.lua
units/XAB2307/XAB2307_unit.bp

change salvation to be experimental

---

units/XSS0201/XSS0201_unit.bp

fixes #1259
@shalkya wtf is that issue description? it took me twice as long to figure out what you mean than actually fixing it...

increase target check frequency of sera destro torpedo

---

projectiles/SIFInainoStrategicMissile02/SIFInainoStrategicMissile02_proj.bp

sera nuke impact sound que capitaliazation

---

units/URB2109/URB2109_unit.bp

add overwater targetbone to t1 cybran torplauncher

---

units/URL0001/URL0001_script.lua
units/URL0001/URL0001_unit.bp

fixes #1105
also sanitize the "CoolingUpgradeRemove" part of the script of the cybran acu
I tested it and it worked nicely, but this is a really important unit...

add dummy weapon to cybran acu for torpedo targeting

---

lua/BuildingTemplates.lua

Allows AI in campaign to rebuild upgraded engineer stations

Add engie stations into AI rebuild templates

---

lua/AI/OpAI/BaseManagerPlatoonThreads.lua

Coop only.
Added higher priority for engineering stations, support factories and harms.

Improve rebuild structure priorities

---

lua/sim/defaultweapons.lua

Fix energy weapons draining before unit completion. Fixes #2172

---

lua/ui/game/orders.lua

add timeout for overcharge ready sound

---

lua/ui/game/unitview.lua

use energyRequested intead of energyConsumed if energyRequested is available (same for massRequested and massConsumed)
improves the fix for #717 #2157
fixes #2197

improve consumption display on units

---

lua/ui/game/simdialogue.lua

Localize the title and use faction theme color for it.
Before:
After:

Fixes and improvements for Sim dialogue

---

units/URL0001/URL0001_script.lua
units/URL0001/URL0001_unit.bp

fixes #2180
this change could have some unwanted side effects (i.e. acu wandering off when its told to assist something)

Cybran acu gsr

---

lua/shield.lua

check if shield exists before creating impact effects

---

units/URL0001/URL0001_script.lua

set dummy weapon range on upgrade for cybran acu

---

lua/sim/Unit.lua

small fix for amphibious unit overwater vision

---

lua/ui/lobby/ModsManager.lua

Fix false positive "missing dependency" for UI mods when not host

---

units/UEA0305/UEA0305_unit.bp
units/XRA0305/XRA0305_unit.bp

adds stealth to the Wailer and removes its radar jamming ability
adds radar jamming to the Broadsword

Balance:T3gunshipchanges

---

units/XEA0002/XEA0002_unit.bp

increases the radar range from 70 to 150
adds omni range of 50
increases movment speed from 6 to 9

Balance:NovaxBuff

---

lua/sim/AdjacencyBuffs.lua
units/UAB1104/UAB1104_unit.bp
units/UAB1303/UAB1303_unit.bp
units/UEB1104/UEB1104_unit.bp
units/UEB1303/UEB1303_unit.bp
units/URB1104/URB1104_unit.bp
units/URB1303/URB1303_unit.bp
units/XSB1104/XSB1104_unit.bp
units/XSB1303/XSB1303_unit.bp

rebalance of t2 and t3 mass fabricators
values are stolen from EQ for now
might have to make adjustments according to feedback in time

Massfabrebalance

---

lua/sim/DefaultProjectiles.lua
lua/sim/defaultweapons.lua
projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua
projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua
projectiles/SDFLightChronatronCannon02/SDFLightChronatronCannon02_script.lua
projectiles/TDFOverCharge01/TDFOverCharge01_script.lua
units/UAL0001/UAL0001_unit.bp
units/UEL0001/UEL0001_unit.bp
units/URL0001/URL0001_unit.bp
units/XSL0001/XSL0001_unit.bp
units/XSL0301/XSL0301_unit.bp

Here's a modified version of Equilibrium's smart overcharge feature. This includes a required part of #2195 so there may be a conflict when merging.

Smart overcharge

---

units/XRB2308/XRB2308_unit.bp

add stealth to the ability list of the HARMS since it does have it

fix:Tooltip

---

changelog.md
lua/ui/lobby/changelog.lua
mod_info.lua

add missing stuff to the 3688 changelog (regen table and shield recharge)
add 3689 hotfix stuff (ctrl k vet fix, ACU vet gain fix, shield recharge fix)

add 3689 changelog/update versionnumber

---

lua/AI/AIBehaviors.lua
lua/ScenarioFramework.lua
lua/defaultunits.lua
lua/platoon.lua
lua/sim/Unit.lua
lua/simInit.lua
units/XSB2401/XSB2401_script.lua
units/XSL0401/XSL0401_Script.lua

Fix/wait Fixes #2268

---

units/XEB0104/XEB0104_unit.bp
units/XEB0204/XEB0204_unit.bp

Change Kennels clasiffication to Engineer

---

units/UAL0104/UAL0104_unit.bp
units/UEL0104/UEL0104_unit.bp
units/XSL0104/XSL0104_unit.bp

reduce aeon/uef T1 maa dmg to avoid killing one t1 bomber with a single t1 maa
increase sera T1 maa muzzle velocity to avoid missing shots on targets that move away from it

rebalance_T1_Maa

---

lua/sim/AdjacencyBuffs.lua

minor adjustments to t3 fabs (nerf for the adjacency on SMLs and mass storages)

t3 fabricator adjacency nerf

---

units/XSL0105/XSL0105_unit.bp
units/XSL0208/XSL0208_unit.bp
units/XSL0309/XSL0309_unit.bp

Better late than never
Fixes #2315

Remove Repairs/Reclaims ability from Sera Engineers

---

units/UAL0104/UAL0104_unit.bp
units/UEL0104/UEL0104_unit.bp
units/URL0104/URL0104_unit.bp
units/XSL0104/XSL0104_unit.bp

reduce mass cost and damage by ~10%

reduce T1 Maa mass cost and damage

---

lua/defaultunits.lua

Tele delay

---

projectiles/CAAAutocannon03/CAAAutocannon03_proj.bp
units/URS0303/URS0303_unit.bp

Give cybran carrier tracking projectile

---

units/XSL0101/XSL0101_unit.bp

Remove the maintenance cost for stealth+cloak and fix the selen radar being disabled during power stalls

Remove selen maintenance cost

---

lua/defaultunits.lua

Message was visible for everyone, now it is not.

Tele message fix

---

units/URL0402/URL0402_unit.bp

steal exotics eq ml tracking fix cause he is too much of a плохой человек to add it himself

ML Laser Tracking fix

---

units/XES0205/XES0205_unit.bp

Recharge time from 32 seconds to 40

increase shieldboat recharge time

---

etc/faf/blacklist.lua

one more version of icon support for the blacklist so ppl stop using it with faf

add another icon support mod to the blacklist

---

lua/AI/AIBaseTemplates/RushExpansionAirFull.lua
lua/AI/AIBaseTemplates/RushExpansionBalancedFull.lua
lua/AI/AIBaseTemplates/RushExpansionLandFull.lua
lua/AI/AIBaseTemplates/RushExpansionNaval.lua
lua/AI/AIBaseTemplates/RushMainAir.lua
lua/AI/AIBaseTemplates/RushMainBalanced.lua
lua/AI/AIBaseTemplates/RushMainLand.lua
lua/AI/AIBaseTemplates/RushMainNaval.lua
lua/AI/AIBaseTemplates/RushSetons.lua
lua/AI/AIBaseTemplates/TechExpansion.lua
lua/AI/AIBaseTemplates/TechExpansionSmall.lua
lua/AI/AIBaseTemplates/TechMain.lua
lua/AI/AIBaseTemplates/TechSmall.lua
lua/AI/AIBaseTemplates/TurtleExpansion.lua
lua/AI/AIBaseTemplates/TurtleMain.lua
lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua
lua/platoontemplates.lua

Issue #2317
Now the AI and SorianAI can build T3 mobile anti air land units.

Fix T3 land AA build platoons

---

etc/faf/mapblacklist.lua

remove "8 - Badlands_v4.v0001" from the mapblacklist as it is the most up-to-date version.
Btw i have not done any rebase or shit since ages. Hope won't be an issue.

remove "8 - Badlands_v4.v0001" from the mapblacklist

---

units/UAB1102/UAB1102_unit.bp

for reasons unknown to me the AI table in the unit bp messes up the targeting for units so i just removed it
(couldn't find any negative impact when doing so but feel free to double check)
fixes #2333

Aeon Hydro targetting fix

---

lua/SinglePlayerLaunch.lua
lua/system/Localization.lua
lua/ui/game/tooltip.lua
lua/ui/lobby/aitypes.lua
lua/ui/lobby/lobby.lua

Added function to load AI-data from AIs placed inside modfolder
Added tooltip and language loader function for AI lobby tooltips
Added preloading for AI lobby options
Updated lobby option behavior in case a new color/team/faction/AI is selected.
The old system was reloading the AI data on every option change.
Since i added disc access for finding AI-Mods this was getting to slow.
Now all AI data is loaded on the beginning of the lobby.lua file and stored inside a local for faster access.
Now there is less lag then before, so we can call this update or enhancement :)

Enhancement: This will enable the game to load custom AIs from Mod folder

---

init.lua
mod_info.lua

the repo contains changes to the props folder and yet, the game doesnt load the folder...

load props folder in the init file

---

lua/ui/game/layouts/unitview_left.lua
lua/ui/game/layouts/unitview_mini.lua
lua/ui/game/layouts/unitview_right.lua
lua/ui/game/unitview.lua

Create proper fuelbar display for shielded air units. https://github.com/FAForever/fa/issues/2312
Also will work for any mods that add shield air units.
The end result:

Fix issue #2312

---

lua/defaultunits.lua
units/UAL0001/UAL0001_unit.bp
units/UAL0301/UAL0301_unit.bp
units/UEL0001/UEL0001_unit.bp
units/URL0001/URL0001_unit.bp
units/XSL0001/XSL0001_unit.bp
units/XSL0301/XSL0301_unit.bp

Added TeleportDelay (seconds) to bp. Also changed delay from 15 to 10 seconds.

Tele delay value in bp

---

units/ZRB9502/ZRB9502_unit.bp

Now it works.
Special for Petric ;)

'Upgrades' hotkey & cyb t2 air fac

---

lua/shield.lua
lua/sim/Unit.lua

Personal shield fix

---

units/XSA0402/XSA0402_unit.bp

improve ahwassa bomb dropping

---

units/UAL0307/UAL0307_unit.bp
units/UEL0301/UEL0301_unit.bp
units/UEL0307/UEL0307_unit.bp
units/XSL0307/XSL0307_unit.bp

Mobile shields --> 0.15 (same as before)
UEF bubble SCU --> 0.2

rebalance mobile shield overspill

---

units/XSB2205/XSB2205_unit.bp

Now wreck appears on water (like other torp def wrecks).

Sera t2 torp def. Removing death animation 

---

lua/EffectUtilities.lua
lua/defaultunits.lua
lua/sim/Unit.lua

15 sec animation, no matter what the delay.
Any suggestions/advices/reviews are welcome, as always ;)

Better tele delay

---

changelog.md

fix was intended to make unit take damage on their health instead of shield.

correcting changelog

---

units/XSB2302/XSB2302_unit.bp

jonas tested it and it seems to fix the issue.

fix sera arty not shooting at its target

---

lua/shield.lua
lua/sim/Unit.lua

PR for correct branch*
Issue #2478

Shields fix ('develop')

---

lua/sim/DefaultProjectiles.lua
projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua
projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua
projectiles/SDFLightChronatronCannon02/SDFLightChronatronCannon02_script.lua
projectiles/TDFOverCharge01/TDFOverCharge01_script.lua

https://forums.faforever.com/viewtopic.php?p=164607#p164607

fix OC wrong energy drain

---

lua/ui/lobby/data/playerdata.lua
lua/ui/lobby/lobby.lua

Gets information from the client. Takes an avatar from the cache.
Lobby + Client "https://github.com/FAForever/downlords-faf-client/pull/942"

Avatar in lobby

---

lua/sim/Unit.lua
lua/ui/game/unitview.lua

"Mass killed" for full veted unit

---

lua/sim/Projectile.lua
units/UAB4201/UAB4201_unit.bp
units/UAS0202/UAS0202_unit.bp
units/UAS0302/UAS0302_unit.bp

Fix Aeon tmd deflects nuke (EQ)

---

lua/sim/Unit.lua

Copied from "No Friendly Fire Collision v2".
Thanks to JoonasTo

Removal of friendly collisions

---

units/UAB1103/UAB1103_unit.bp
units/UAB1202/UAB1202_unit.bp
units/UAB3101/UAB3101_unit.bp
units/UAB3102/UAB3102_unit.bp
units/UAB3201/UAB3201_unit.bp
units/UAB3202/UAB3202_unit.bp
units/UEB1103/UEB1103_unit.bp
units/UEB1202/UEB1202_unit.bp
units/UEB3101/UEB3101_unit.bp
units/UEB3102/UEB3102_unit.bp
units/UEB3201/UEB3201_unit.bp
units/UEB3202/UEB3202_unit.bp
units/UEB4202/UEB4202_unit.bp
units/URB1103/URB1103_unit.bp
units/URB1202/URB1202_unit.bp
units/URB3101/URB3101_unit.bp
units/URB3102/URB3102_unit.bp
units/URB3201/URB3201_unit.bp
units/URB3202/URB3202_unit.bp
units/URB4202/URB4202_unit.bp
units/URB4206/URB4206_unit.bp
units/XEB0104/XEB0104_unit.bp
units/XRB0104/XRB0104_unit.bp
units/XRB0204/XRB0204_unit.bp
units/XSB1103/XSB1103_unit.bp
units/XSB1202/XSB1202_unit.bp
units/XSB3101/XSB3101_unit.bp
units/XSB3102/XSB3102_unit.bp
units/XSB3201/XSB3201_unit.bp
units/XSB4202/XSB4202_unit.bp

so that you can queue up upgrade while the unit is being built.

 added CQUEMOV for upgradable building

---

lua/sim/ScenarioUtilities.lua

This fix about spawn wreckage on game start
If unit have death animation and spawn on land (or in water on depth<5), we use this death animation and skip it to unit final condition, then create wreackage in this condition as after death in game (by default, function just spawn unit, create wreckage, destroy unit).
If unit is "naval" on water or "air", we disable deathAnimation (coz some naval units haven`t animation but have link for animation in blueprint, this glitched and hold it on surface) and use random rotation for simulate sinking/falling.
Else we just create wreckage and destroy unit like in default function
default
this fix
[video](https://www.youtube.com/watch?v=3x-ChnKcpHQ)

Wreckage spawn like after death animation

---

projectiles/SIFSuthanusArtilleryShell02/SIFSuthanusArtilleryShell02_script.lua

Changes the static t3 sera arty projectile so it makes use of the shielddamage value that has already been in the unit bp
I assume gpg wanted to do this but either forgot about it or scrapped the idea entirely
gonna leave this open for now so i can do further testing about the exact damage that we'd want vs shields and make another commit later on
credits for the code go to @The-Balthazar

Sera arty dmg

---

units/XSA0202/XSA0202_unit.bp

Allows notha to kill uef t2 eco buildings in two shots.

buff notha bomb damage to 1250

---

projectiles/AIMAntiTorpedo01/AIMAntiTorpedo01_proj.bp
projectiles/AIMAntiTorpedo01/AIMAntiTorpedo01_script.lua
units/UAS0103/UAS0103_unit.bp

Buff rate of fire and projectile speed

Buff aeon frig torp defense

---

units/XAB3301/XAB3301_unit.bp

Add 10k energy storage to Eye.

add energy storage to Eye of Rhianne

---

units/XSL0401/XSL0401_Script.lua

fix the balance change that was not approved from https://github.com/FAForever/fa/pull/2539

make ally/owner triggers the storm by reclaiming

---

lua/SimCallbacks.lua
lua/ui/game/commandmode.lua
units/UAL0307/UAL0307_script.lua
units/UEL0307/UEL0307_script.lua
units/URL0306/URL0306_Script.lua
units/XSL0307/XSL0307_script.lua

---------------------------------------------------------------
Fix from EQ
https://github.com/Ithilis/Equilibrium/commit/e729f6d72244b7cf588c3767a723b330aac1a22c#diff-df0eb38b9064089cb5ba809139ab9e4e
All thanks to Exotic
---------------------------------------------------------------
#2277

Fix assist for mobile shields (EQ)

---

projectiles/AIFQuantumWarhead01/AIFQuantumWarhead01_proj.bp
projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_proj.bp
projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_proj.bp
projectiles/TIFMissileNuke01/TIFMissileNuke01_proj.bp
units/UAB2305/UAB2305_unit.bp
units/UEB2305/UEB2305_unit.bp
units/URB2305/URB2305_unit.bp
units/XSB2305/XSB2305_unit.bp

increases nuke missle bt by 1.75 and nuke launcher bp by 1.75 in order to nerf assist on nuke.

Nuke bp change

---

lua/ui/lobby/lobby.lua

Don't try to set invalid army color

---

changelog.md
lua/ui/lobby/changelog.lua
lua/ui/lobby/lobby.lua
lua/version.lua
mod_info.lua

brings the 3700 hotfix patch from deploy/fafdevelop to develop so we can proceed to master and then to deploy/faf

merge 3700 hotfix

---

projectiles/AIFMissileTactical01/AIFMissileTactical01_proj.bp
projectiles/CIFMissileTactical03/CIFMissileTactical03_proj.bp
projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_proj.bp
projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_proj.bp
projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_proj.bp
projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp
projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp

this way it seems less cancerous, but kind of a pain in the ass to make new PR, and not being able to update previous one.

changing tml missle cost

---

lua/ui/lobby/lobby.lua

takes some code from Kyr0s lobby mod to make the version number appear in a spot that is more visible in the game lobby

Relocate versionnr

---

changelog.md
lua/ui/lobby/changelog.lua
mod_info.lua

Updates the changelog for the github repo as well as for the in game lobby and bumps the game patch number

Bump version3701

---

lua/aibrain.lua

this change allows walls to be taken over in full share games like every other unit
fixes #2639

allow walls to be handed over in fullshare games

---

units/XEA0002/XEA0002_script.lua

Since the satellite can be destroyed we need to rebuild it for the AI

Fix for Novax not rebuilding satellite if controlled by AI

---

lua/UserSync.lua
lua/victory.lua

GPGNetSend is a UI function and won't work in Sim
Untested.

Move GameEnded call into the UI

---

units/XSB2301/XSB2301_unit.bp

changes the ballistic arc to be the same as on the cybran t2 pd
change was made by evildrew in his balance mod

Fix Sera T2 PD Aim

---

lua/aibrain.lua
lua/ui/lobby/lobbyOptions.lua

Fixes #2610
Like this @micheljung ?
To the test team: I didnt test it, just replaced all code that the git found, so it should not break anything, but you know what to do :) test :))

Use general on/off key for AI replacement option

---

lua/sim/Projectile.lua
units/UAB2305/UAB2305_unit.bp
units/UAS0304/UAS0304_unit.bp
units/UEB2305/UEB2305_unit.bp
units/UEL0001/UEL0001_unit.bp
units/UES0304/UES0304_unit.bp
units/URB2305/URB2305_unit.bp
units/URS0304/URS0304_unit.bp
units/XSB2305/XSB2305_unit.bp
units/XSB2401/XSB2401_unit.bp
units/XSS0302/XSS0302_unit.bp

this allows nuke weapons to have damage types other than nukes. for mod
support reasons and for pretty code reasons

Remove hardcoding on nuke weapon damage types

---

units/URS0201/URS0201_unit.bp

Changing salem's targetbone from 'Muzzle_Front' to 'Turret_Mount_Front'
http://forums.faforever.com/viewtopic.php?f=45&t=17066

Change Target Bone

---

units/UEB4301/UEB4301_unit.bp
units/URB4207/URB4207_unit.bp

buffs UEF T3 shield and CYB ED5 so they can tank a single Mavor shell

UEF and CYB T3 shield buff

---

units/UAL0001/UAL0001_unit.bp

Reduce First aeon acu shield recharge time from 90 to 75.

Aeon acu shield recharge time reduction

---

projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_proj.bp
projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp

increase acu tml missile buildtime

---

units/UAL0208/UAL0208_unit.bp
units/UAL0309/UAL0309_unit.bp
units/UEL0208/UEL0208_unit.bp
units/UEL0309/UEL0309_unit.bp
units/URL0208/URL0208_unit.bp
units/URL0309/URL0309_unit.bp
units/XSL0208/XSL0208_unit.bp
units/XSL0309/XSL0309_unit.bp

Now equal to T1 engineer speed.

buff t2 and t3 engineer speed

---

units/UAB4202/UAB4202_unit.bp
units/UEB4202/UEB4202_unit.bp
units/URB4202/URB4202_unit.bp
units/URB4204/URB4204_unit.bp
units/URB4205/URB4205_unit.bp
units/URB4206/URB4206_unit.bp
units/XSB4202/XSB4202_unit.bp

nerfs mainly recharge time and a bit bt+mass cost

nerfs T2 shields

---

units/URB4202/URB4202_unit.bp
units/URB4204/URB4204_unit.bp
units/URB4205/URB4205_unit.bp
units/URB4206/URB4206_unit.bp
units/URB4207/URB4207_unit.bp

fixing the insane price of assisting ed5, and the other cybran shield to some extend.
BP increase, so shield can upgrade as fast as before on their own.

BP and BT adjustement

---

lua/AI/AIBehaviors.lua
lua/AI/AttackManager.lua
lua/AI/aibuildstructures.lua
lua/AI/aiutilities.lua
lua/EffectUtilities.lua
lua/aibrain.lua
lua/defaultunits.lua
lua/platoon.lua
lua/sim/EngineerManager.lua
lua/sim/FactoryBuilderManager.lua
lua/sim/Unit.lua
lua/simInit.lua

Again a smal AI patch.
First of all, i removed all `IsOpponentAIRunning()` function calls.
It's simply not working. This call needs to be in every attackplatoon and inside the engineer and factorymanager to work reasonably. 
So i removed it for better performance and use it now for debugging sim code.
If we will ever decide to stop an AI in midgame, then we can do this by only blocking the platoonmanager and set all units on pause.
Platoons will no longer try to attack buildings while capture/reclaim is in progress.
AI's pathfinding cache will now be deleted if an AI is defeated to save some memory.
AI location distresscalls are now working (expansions can call for help bow)
And some mini bugfixes.
All changes are single tested and the whole PR is tested for over a week.
(works also well …

AI-Update V4

---

lua/sim/defaultweapons.lua
lua/ui/controls/worldview.lua
units/URL0401/URL0401_unit.bp

gives the scathis a constant not on distance depending AoE

constante scathis AoE

---

units/UAB0201/UAB0201_unit.bp
units/UEB0201/UEB0201_unit.bp
units/URB0201/URB0201_unit.bp
units/XSB0201/XSB0201_unit.bp

Reduce T2 land HQ buildtime by 15 seconds.

reduce T2 land HQ buildtime

---

units/UAL0001/UAL0001_unit.bp

increase hp for chrono

---

projectiles/aaphalanx01/AAPhalanx01_proj.bp
units/delk002/DELK002_unit.bp

Fix T3 UEF MAA missing (for real this time)

---

units/DEL0204/DEL0204_unit.bp

Damage increased 15  -> 18
Damage per gatling gun volley 225 -> 270

buff mongoose damage

---

lua/formations.lua

It changes second formation for strats (hold RMB + left click)
< 20 strats = 2 lines
more than 20 = 3 lines
https://youtu.be/KDxRhz5J-h4

Alternative formation for strats

---

units/UAB4202/UAB4202_unit.bp
units/UAL0307/UAL0307_unit.bp
units/UEB4202/UEB4202_unit.bp
units/UEL0307/UEL0307_unit.bp
units/URB4202/URB4202_unit.bp
units/URB4204/URB4204_unit.bp
units/URB4205/URB4205_unit.bp
units/XSB4202/XSB4202_unit.bp

updates values for static shields.

Adjust static shields build cost and time

---

units/XEA0002/XEA0002_script.lua

Only for idle or slowly moving Novax, otherwise it uses default animation.

More random falling animation for Novax

---

lua/AI/OpAI/BaseManager.lua
lua/AI/OpAI/BaseManagerPlatoonThreads.lua
lua/AI/OpAI/BasicLandAttack_save.lua
lua/AI/OpAI/NavalAttacks_save.lua
lua/sim/ScenarioUtilities.lua

OpAI Improvements

---

loc/FR/strings_db.lua
lua/ui/dialogs/teamkill.lua

The player needs to wait 3 seconds before clicking on Report. This change prevents people from making fake reports by accident.

Report time

---

units/XSL0101/XSL0101_script.lua

Selen bugfixes and improvements

---

units/XSB2302/XSB2302_unit.bp

comment out sera t3 arty shield damage

---

lua/ui/dialogs/teamkill.lua

as @speed2CZ pointed out
Tested and it works both when forgiving too fast and when forgiving slowly too.

Report dialog forgive button fix

---

lua/shield.lua

If you have any ideas how to improve performance for this hell or how to fix it in a different way, post it here.
*Only for static shields. We don't want to run it for mobile shields, right? :D Better hard nerf assist for them via bplueprint and RegenAssistMult.

Fix free assist for shields

---

units/ZXA0001/ZXA0001_unit.bp

Added INSIGNIFICANT flag over debug/dummy unit

---

lua/ui/dialogs/createunit.lua
lua/ui/dialogs/createunitfilters.lua

Supports 16 players.
Windows resize with player count.
Extrabutton for 3rdparty faction
Extrabutton for amphibious + hover units.
Extrabutton for ACU's, Engineer SACU's, and paragon
All buttons are reworked and are using now categories (if possible)
(.CategoriesHash.UEF instead of string.sub(unitID, 2, 2) == 'e')

Fix [ALT]+[F2] menu

---

lua/AI/AIAddBuilderTable.lua
lua/AI/aibuildstructures.lua
lua/AI/aiutilities.lua
lua/UserSync.lua
lua/aibrain.lua
lua/editor/UnitCountBuildConditions.lua
lua/platoon.lua
lua/sim/Builder.lua
lua/ui/lobby/lobby.lua

This patch has some bugfixed and gamespeed optimizations.
I also included the AI_Base_Monitor_Fix from RobD (also optimized)
Changelog:
------------------------------------------------------------------------------------
AIAddBuilderTable.lua
function AddBuilderTable()
-Fix: Only add StrategyBuilder if an Strategymanager exist (only Sorian)
-Fix: Changed error message to warn message for non critical error
------------------------------------------------------------------------------------
aibuildstructures.lua
function AIExecuteBuildStructure()
-Fix: Added "true/false" as return value in case a buildingplace was found or not.
-Opt: Added better debug messages in case the AI can't decide what to build (build template errors)
----------------------------------------------------------------- …

AI-Update V5

---

README.md

Added translation guidelines following discussion with IceDreamer

---

units/XSL0001/XSL0001_PhaseShield_mesh.bp

Fixed Sera ACU PhaseShield mesh
For #2807 so it can be used during warp in effect. Also if anyone ever
wants to add personal shield for the Sera ACU...

Fixed Sera ACU PhaseShield mesh

---

README.md

Grammar/spelling fixes.

---

projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua

Destroy Billy when hitting Aeon TMD flare

---

units/URS0201/URS0201_script.lua

Fixes #2638 
Test all possible combinations please, from water to land, from land to water, from water to orbit, you know...

Fix Salem floating when killed during landing

---

units/URB4206/URB4206_unit.bp
units/ZAB9602/ZAB9602_unit.bp

ED4 and Aeon T3 Support Air Factory were missing rebuild IDs.
Fixes #2663

Add missing rebuild IDs into BPs

---

effects/mesh.fx

The seraphim shader looks weird at the moment. Especially on maps with very bright lighting. I gave the shader a look closer to the original SCFA shader while preserving the ability to have the teamcolor influence the shader. Here is the corresponding forum thread: https://forums.faforever.com/viewtopic.php?f=2&t=17676
The shader is tested on many maps. It reacts nicely to the different environments.
The build shader now also utilizes the teamcolor.

update seraphim shader to be more realistic

---

units/UAB5202/UAB5202_unit.bp
units/UEB5202/UEB5202_unit.bp
units/URB5202/URB5202_unit.bp
units/XSB5202/XSB5202_unit.bp

Since its T1 now.
The balance team noobs forgot...

Change air staging icon to T1

---

units/UAA0304/UAA0304_Script.lua
units/UEA0304/UEA0304_Script.lua
units/URA0304/URA0304_Script.lua
units/XSA0304/XSA0304_Script.lua

Fix strats scripts

---

lua/AI/OpAI/NavalAttacks_save.lua

Add new naval platoon templates for the campaign AI

---

lua/sim/DefaultProjectiles.lua
units/XEA0002/XEA0002_script.lua

allows the sat to take dmg from anything

remove invulnerability from (novax) satellites

---

lua/sim/Unit.lua

now its cleaner, faster, and has better mod support.

Refactor updateBuildRestrictions

---

units/UEA0305/UEA0305_script.lua

fix #2859 
still didn't figure out how to show the jammer ring.

Broadsword jamming e consumption fix

---

units/UAS0305/UAS0305_unit.bp
units/UES0305/UES0305_unit.bp
units/URS0305/URS0305_unit.bp

allow to queue orders while being built

add cquemov to T3 sonars

---

units/XRB2309/XRB2309_unit.bp

removing it from unit database

add INSIGNIFICANTUNIT cat to dummy harms

---

units/XAB3301/XAB3301_unit.bp

fix eye not being build drag

---

lua/sim/Unit.lua

make repair cost 75% of the price of the unit

repair discount

---

units/XRL0302/XRL0302_unit.bp

mass cost buff from 300 to 250

beetle buff

---

units/XAL0203/XAL0203_unit.bp

reduce blaze cost and buildtime

---

units/XAA0202/XAA0202_unit.bp

swiftwind nerf

---

units/XSA0202/XSA0202_unit.bp

turn speed got changed previously, notha wasn't dropping every 2 turns.

make notha shoot constantly

---

units/UAL0307/UAL0307_unit.bp
units/UEL0307/UEL0307_unit.bp

they are strong in combo with T2/T3 land.

nerf T2 shields

---

units/UAA0101/UAA0101_unit.bp
units/UEA0101/UEA0101_unit.bp
units/URA0101/URA0101_unit.bp
units/XSA0101/XSA0101_unit.bp

increases hitbox of all t1 scouts 1.6->2.0, so that interceptors can hit them, when shoting on them from the front.

fixes scouts

---

lua/sim/score.lua
lua/ui/game/score.lua

The only important thing https://github.com/FAForever/fa/pull/2865#issuecomment-562934749
3 minor bug fixes are not worth mentioning.

Minor scoreboard fixes

---

lua/ui/dialogs/createunit.lua

Units spawn in the cursor position after pressing the left mouse button, which allows you to select an arbitrary point of spawning on the map.
The menu can be closed with the "Esc" key.

Improved convenience when using the unit creation menu

---

lua/AI/aiattackutilities.lua

Update for the AI pathfinding "A*(Star) search algorithm".
(An extension of "Edsger Dijkstra's" pathfinding algorithm used by "Shakey the Robot" in 1959)
Optimized for FAF/LUA:
Normally the pathfinding function is sorting all paths, so that the best path is sorted at the end of the table.
But we can also just loop over all paths and only store the key of the best path (table index).
If we do so, we reduce the highest pathcalculation peek from 192 to 107 milliseconds and
the average calculation time from 43 to 11 miliseconds.
After some optimizing the highest pathing time is 74 ms and the averange pathing time is 9.2 ms.
Makes the pathing function ~ 400% faster. :)
(and eliminate the 200-milisecond pathing sim-lag on maps with 800+ markers)
Some testing times on …

AI Patch V6

---

lua/sim/Buff.lua
units/XSL0001/XSL0001_script.lua
units/XSL0001/XSL0001_unit.bp

PRing what didnt make it into the last patch again

sera acu regen field rework

---

lua/defaultunits.lua
lua/sim/Unit.lua
lua/ui/game/unitview.lua
units/UAL0001/UAL0001_unit.bp
units/UEL0001/UEL0001_unit.bp
units/URL0001/URL0001_unit.bp
units/XSL0001/XSL0001_unit.bp

Vet changes 2

---

lua/sim/Prop.lua

Bump broken tree resource modifier

---

units/UAL0401/UAL0401_Script.lua
units/UAL0401/UAL0401_unit.bp
units/URA0401/URA0401_unit.bp
units/URL0402/URL0402_script.lua
units/URL0402/URL0402_unit.bp
units/XRL0403/XRL0403_script.lua
units/XRL0403/XRL0403_unit.bp
units/XSA0402/XSA0402_unit.bp
units/XSL0401/XSL0401_unit.bp

improve DeathWeapon of experimental and rebalance them

Death weapon balance

---

lua/defaultunits.lua
lua/sim/DefaultProjectiles.lua

Nuke missile kills non-experimental air units without explosion

---

lua/SimCallbacks.lua
lua/ui/game/gameresult.lua
lua/victory.lua

Issues: #2447, #2259, #2141, #1752
Used with "hook_ObserverFix.cpp" from https://github.com/FAETHER/FA-Binary-Patches/pull/8
Can not be accept separately.

Removed observing after death

---

lua/EffectUtilities.lua
lua/aeonunits.lua
lua/cybranunits.lua
lua/defaultunits.lua
lua/seraphimunits.lua

remove the building effect when the factory is paused

Pause facto effect fix

---

lua/sim/Unit.lua
units/DAA0206/DAA0206_unit.bp
units/UAB4201/UAB4201_unit.bp
units/UAB4302/UAB4302_unit.bp
units/UAL0307/UAL0307_unit.bp
units/UAS0305/UAS0305_unit.bp
units/UEB4201/UEB4201_unit.bp
units/UEB4302/UEB4302_unit.bp
units/UEL0307/UEL0307_unit.bp
units/URB4201/URB4201_unit.bp
units/URB4302/URB4302_unit.bp
units/URL0306/URL0306_unit.bp
units/XES0205/XES0205_unit.bp
units/XRL0302/XRL0302_unit.bp
units/XRS0205/XRS0205_unit.bp
units/XSB4201/XSB4201_unit.bp
units/XSB4302/XSB4302_unit.bp
units/XSL0307/XSL0307_unit.bp

this change apply to cybran land scouts, T1/T3 air scouts, stealth boat, mobile stealth, mobile shields, shield boat, tmd, smd, T1 transports, aeon T3 sonar, drones, mercy, beetle

remove vet bar for unvettable units

---

lua/cinematics.lua

Just a small improvement. The code in SimCamera supports this extra arg

Allow transition for 3rd person cam

---

lua/defaultunits.lua

thx to speed2
https://github.com/FAForever/fa/pull/2711#discussion_r362345142

Better code for nuke-air collisions

---

effects/emitters/aeon_commander_disruptor_01_emit.bp
effects/emitters/aeon_commander_disruptor_02_emit.bp
effects/emitters/aeon_commander_disruptor_hit_01_emit.bp
effects/emitters/aeon_commander_disruptor_hit_02_emit.bp
effects/emitters/aeon_commander_disruptor_hit_03_emit.bp
effects/emitters/molecular_ripper_01_emit.bp
effects/emitters/molecular_ripper_02_emit.bp
effects/emitters/molecular_ripper_03_emit.bp
effects/emitters/molecular_ripper_hit_01_emit.bp
effects/emitters/molecular_ripper_hit_02_emit.bp
effects/emitters/molecular_ripper_hit_03_emit.bp
effects/emitters/molecular_ripper_hit_04_emit.bp
effects/emitters/molecular_ripper_hit_05_emit.bp
effects/emitters/molecular_ripper_hit_06_emit.bp
effects/emitters/molecular_ripper_hit_07_emit.bp
effects/emitters/quantum_cannon_munition_03_emit.bp
effects/emitters/quantum_cannon_munition_04_emit.bp
lua/aeonprojectiles.lua
projectiles/LaserBotTerran01/LaserBotTerran01_proj.bp
projectiles/SDFChronatronCannon01/SDFChronatronCannon01_proj.bp

- add yellow dot for uef/sera acu projectiles when zoomed out
- make the aeon/cybran acu projectiles fx appear until 160 lod

Fix acu projectiles

---

lua/sim/Unit.lua
units/URL0402/URL0402_unit.bp
units/XRL0403/XRL0403_unit.bp

Fixes #2399 
correct the pr #2823

fix half built ML/mega wreck falling under the ground

---

units/XSB3202/XSB3202_unit.bp

- make it selectionable over engies
- also remove the useless BP

sera T2 sonar selection priority

---

etc/faf/mapblacklist.lua

blacklisting a hidden/unrated map that keeps getting hosted

add map to blacklist

---

units/UAB0202/UAB0202_unit.bp
units/UEB0202/UEB0202_unit.bp
units/URB0202/URB0202_unit.bp
units/XSB0202/XSB0202_unit.bp

**Mass** 630 ->710
**Energy** 12000 -> 15600
**BT** 1500 -> 1700

T2 air hq cost nerf

---

units/URL0101/URL0101_unit.bp

Related to #2953 
Give mole a dummy weapon so it doesn't suicide on attack move. Range tweaked so it stops just behind mantis

Mole dummy weapon

---

units/UAA0101/UAA0101_unit.bp
units/UAA0302/UAA0302_unit.bp
units/UEA0101/UEA0101_unit.bp
units/UEA0302/UEA0302_unit.bp
units/URA0101/URA0101_unit.bp
units/URA0302/URA0302_unit.bp
units/XSA0101/XSA0101_unit.bp
units/XSA0302/XSA0302_unit.bp

- undo the turnspeed nerf, so they can land
- nerf the max air by 1

fix air scout

---

lua/EffectUtilities.lua

Fix timing of the UEF build beams

---

lua/SimCallbacks.lua
lua/ui/dialogs/createunit.lua

Incorrect entries in the "count" and "veterancy" fields are excluded.
Added immediate creation of a unit on the right mouse button.
Added default values if the above fields are empty.

In cheat menu added the ability to spawn with veterans and improved usability.

---

units/UAS0103/UAS0103_unit.bp
units/URS0103/URS0103_unit.bp

Aeon Frigate sinks faster now
Cybran Frigate slower
Overall its +-similar for all faction. Each of the 3 animations has
different duration so it can still differ.

Improve Frigate sink animation rate

---

effects/emitters/cannon_muzzle_smoke_12_emit.bp
units/XRL0302/XRL0302_Script.lua
units/XRL0302/XRL0302_unit.bp

HE SNIPED THE RADAR
- HP 500 -> 350
- DMG 1499 ->1100
- E cost 1500 -> 1300
- Mass cost 250 -> 190
- BT 1000 ->700
- Permanent free non-toggleable cloak (might be swapped for stealth depending on how this goes)
- Permanent small purple cloak field vfx, periodic noticeable exhaust smoke emissions that allow spotting them without radar

Banel.. i mean beetle stuff

---

lua/ui/game/score.lua

Function _OnBeat was renamed to OnBeat and broke EcoManager mod.
This PR renames it back to _OnBeat for avoid incompatibilities.

Fixed mod compatibility

---

CONTRIBUTING.md

Text says:
`To contribute, please fork this repository and make pull requests to the develop branch.`
But that's not right, we are pulling against `FAForever:deploy/fafdevelop`

Fix target branch (in  CONTRIBUTING.md readme)

---

lua/ui/lobby/ModsManager.lua

**Repeatedly** disabling dependencies did not disable dependent mods.
Fixed Esc when open from **main menu**. Not lobby.

Fixed on/off of mods dependencies in ModsManager

---

units/UAA0310/UAA0310_unit.bp

changes czar movespeed back to 8

Czar movementspeed adjustment

---

units/UAB0304/UAB0304_unit.bp
units/UEB0304/UEB0304_unit.bp
units/URB0304/URB0304_unit.bp
units/XSB0304/XSB0304_unit.bp

increase BP of QG
120 BP -> 180 BP
Make building several QG worth it, reduce the need of engie for SCU spam and makes adjacency relevant.

rebalance Quantum Gateway

---

lua/ui/game/simdialogue.lua

Its about these dialogues:
that can be created and controlled from the map scripts.
Fix error when updating the dialogue text with no buttons.
Properly update the text colour when the text is updated.

Improve Sim Dialogue

---

lua/ui/lobby/autolobby.lua
lua/ui/lobby/lobby.lua

Fixed lobby player names

---

lua/ui/game/announcement.lua
lua/ui/game/confirmunitdestroy.lua

Improved message about banning ctrl+k in coop

---

lua/ui/game/score.lua

https://faforever.zulipchat.com/#narrow/stream/203498-qa-open-testing/topic/3712/near/190838716
https://faforever.zulipchat.com/#narrow/stream/203498-qa-open-testing/topic/3712/near/192188323
https://faforever.zulipchat.com/#narrow/stream/203498-qa-open-testing/topic/3712/near/192191805
The error appeared here https://github.com/FAForever/fa/pull/2982

Fixed circular dependency in scoreboard

---

etc/faf/blacklist.lua

add v9 of RKs -> v10 is in the vault
add 2 versions of QoP that are re-uploaded versions of V2 with some cheat in it

update mod blacklist

---

units/UAA0303/UAA0303_unit.bp
units/UEA0303/UEA0303_unit.bp
units/URA0303/URA0303_unit.bp
units/XSA0303/XSA0303_unit.bp

Undo ASF buildtime nerf

---

projectiles/AIFBombQuark01/AIFBombQuark01_proj.bp
projectiles/CIFProtonBomb01/CIFProtonBomb01_proj.bp
projectiles/SBOZhanaseeBomb01/SBOZhanaseeBomb01_proj.bp
projectiles/TIFSmallYieldNuclearBomb01/TIFSmallYieldNuclearBomb01_proj.bp
units/UAA0303/UAA0303_unit.bp
units/UEA0303/UEA0303_unit.bp
units/URA0303/URA0303_unit.bp
units/XSA0303/XSA0303_unit.bp

Here we go again :D 
Another attempt to make strats more consistent (started here https://github.com/FAForever/fa/pull/2570).
Now it's approved by balance team and I totally agree with this decision. So pls don't start this "you kill supcom by removing collisions" discussion from previous PR again (I mean you can, but I doubt it will have any effect)

Removal of strat bombs - ASF collisions

---

projectiles/CIFArtilleryProton01/CIFArtilleryProton01_script.lua

fix trees not being pushed away on first impact

readd forcethread

---

lua/defaultunits.lua

broken by this https://github.com/FAForever/fa/commit/2bc7e86fdb581a48937a397fe8b00a02b511ddd9

Tele delay fix

---

lua/ui/dialogs/createunit.lua

When opened it centered on the mouse cursor.
Tuning window size and spawn units timings.
Fixed bug when spawning from an observer.

Improved usability Cheat menu

---

lua/RemoteViewing.lua
lua/sim/VizMarker.lua

Fixed a bug that allowed the building to detect underwater units.
This issue has also been fixed: #3096

Quantum optics facility fix

---

units/XSL0301/XSL0301_script.lua
units/XSL0301/XSL0301_unit.bp

part of SCU rework - rebalances Sera SCU.

Sera SCU changes

---

lua/ui/game/tooltip.lua
lua/ui/lobby/lobby.lua

This functionality is now available in the singleplayer.
Disabled voices in lobby without FAF client.
Now when you press the "Fill Slots" button, the "Auto Teams" used.

Lobby enhancements + refactoring

---

loc/US/strings_db.lua
lua/ui/help/loadingtips.lua

Just a small change to the previous PR

Loading tips improvement

---

projectiles/AIFQuantumWarhead01/AIFQuantumWarhead01_proj.bp
projectiles/AIFQuantumWarhead03/AIFQuantumWarhead03_proj.bp
projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_proj.bp
projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_proj.bp
projectiles/SIFExperimentalStrategicMissile01/SIFExperimentalStrategicMissile01_proj.bp
projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_proj.bp
projectiles/SIFInainoStrategicMissile02/SIFInainoStrategicMissile02_proj.bp
projectiles/TIFMissileNuke01/TIFMissileNuke01_proj.bp
projectiles/TIFMissileNuke02/TIFMissileNuke02_proj.bp
units/UAB4302/UAB4302_unit.bp
units/UEB4302/UEB4302_unit.bp
units/URB4302/URB4302_unit.bp
units/XSB4302/XSB4302_unit.bp

Fix nuclear missle can be killed by satellite (and others).
As asked in #3146

Increase nuke and exp nuke hp 1000 times. Also increase SMD damage.

---

effects/mesh.fx

TA Shaders coded by Armored Fish for SCTA Mod for build animations.

Shaders Needed for SCTA Mod

---

schook/lua/UserSync.lua

Not sure why I didn't think of this before. We simply ignore any "defeat" results if we have already reported ourselves as being defeated. I'm using `GetFocusArmy` to get the army id of the player, not sure if there's a better function for that.
I think my other solution broke when it was combined with @KionX changes. This should be more robust. 
Tested in:

Issue/#3087 Fix all results being ignored

---

units/UAA0101/UAA0101_unit.bp
units/UAA0103/UAA0103_unit.bp
units/UEA0101/UEA0101_unit.bp
units/UEA0103/UEA0103_unit.bp
units/URA0101/URA0101_unit.bp
units/URA0103/URA0103_unit.bp
units/XSA0101/XSA0101_unit.bp
units/XSA0103/XSA0103_unit.bp

bombers
Breakoff distance 24 -> 32
E cost 2450 -> 2050
Mass cost 105 -> 90
BT 700 -> 500
Radar with a radius of 42 (old one was 65)
scouts
e cost 420 -> 580
mass cost 40 -> 50
bt 145 -> 200

T1 bomber and scout adjustments

---

lua/AI/OpAI/BaseManager.lua

This is all coop stuff.
Removed all hardcoded things.
It can now handle any faction and any upgrade.
Changing the upgrades during the game will now properly remove the old upgrades from the unit and start upgrading with the new ones.

Improve BaseManager unit upgrades

---

lua/aeonunits.lua

Remove useless GetBlueprint call

---

units/UAB4202/UAB4202_unit.bp
units/UAB4301/UAB4301_unit.bp

Now it matches other factions. Its still the slowest, but close to others. Since all others were pretty much the same time.
And it still looks good.

Speed up Aeon shields death animation

---

lua/terranunits.lua

It's done generally in defaultunits and it works just fine there. This code wasnt adding anything new.

Remove set up of build effect from TShield

---

lua/ui/lobby/changelog.lua

Reaction to: https://forum.faforever.com/topic/537/read-only-sections-on-the-forum/23
Looks like this:

Add link to the patchnotes to the changelog popup

---

lua/weather.lua
lua/weatherdefinitions.lua

Weather is available in Supreme Commander but not commonly used. A reason is that people don't know about it, it is not documented properly and then there is the issue with vision: if the markers are not in vision then you won't see any cloud at all.
This pull request refactors the weather lua files, they were a bit of a mess. There is a clear opt-out section, clear data transformations functions and overall it feels more solid. By default weather is now visible through the fog which is different behavior than the original behavior.
For more information on weather:
- https://forum.faforever.com/topic/277/about-weather-generating-clouds
For maps with weather:
- Rainmakers
- Hardshield Oasis
- Adaptive Pandemonium Pass
- Perrote Glacier
Edit: because these files are new to the repo you …

Weather in Supreme Commander

---

lua/ui/game/objectives2.lua

For https://github.com/FAForever/fa/pull/3112

Fixed unit cap displaying in coop

---

effects/QuantumWarhead/QuantumWarheadEffect01_proj.bp
projectiles/SIFExperimentalStrategicDeath01/SIFExperimentalStrategicDeath01_proj.bp
projectiles/SIFExperimentalStrategicDeath01/SIFExperimentalStrategicDeath01_script.lua
units/XSB2401/XSB2401_script.lua
units/XSB2401/XSB2401_unit.bp

make distortion field visible (will also impact aeon nukes)
add visual effect to T4 nuke launcher death explosion
20k damage inner ring of 15
5k damage outer ring of 20

death explosion t4 nuke launcher

---

units/UEB0102/UEB0102_script.lua
units/UEB0202/UEB0202_script.lua
units/UEB0302/UEB0302_script.lua
units/URB0102/URB0102_script.lua
units/URB0202/URB0202_script.lua
units/URB0302/URB0302_script.lua
units/ZEB9502/ZEB9502_script.lua
units/ZEB9602/ZEB9602_script.lua
units/ZRB9502/ZRB9502_script.lua
units/ZRB9602/ZRB9602_script.lua

Equalize airfac rolloff times

---

units/UAA0101/UAA0101_unit.bp
units/UEA0101/UEA0101_unit.bp
units/URA0101/URA0101_unit.bp
units/XSA0101/XSA0101_unit.bp

remove masscost from the previous nerf

t1 airscout masscost 50 -> 40

---

lua/ui/controls/acubutton.lua
lua/ui/lobby/lobby.lua

Add protection against kyros lobby workaround

---

lua/SimPing.lua

Issue https://github.com/FAForever/fa/issues/2259
Cheats should be off

Fixed set map markers

---

units/UAS0102/UAS0102_unit.bp

Damage 7 -> 6
MuzzleVelocity 45 -> 60

shard better hitting, less dps

---

lua/sim/DefaultProjectiles.lua
units/UAL0307/UAL0307_unit.bp
units/UEL0307/UEL0307_unit.bp
units/XSL0307/XSL0307_unit.bp

reintroduce OC killing mobile land shields if it depletes the shield

---

units/delk002/DELK002_unit.bp

Remove Aquatic Tag for Cougar

---

loc/US/strings_db.lua

There is no energy consumption. I guess it was removed at some point.

Fix Aeon ACU description

---

schook/lua/UserSync.lua

Reverting changes of https://github.com/FAForever/fa/pull/3166 which were the cause of the Draw Bug.
Reason: You can just remove it because that fix didn’t work at all.
https://faforever.zulipchat.com/#narrow/stream/203478-general/topic/DrawBug/near/230181105

Fixed Draw Bug

---

engine/Sim/CAiBrain.lua

Update description for
RemoveArmyStatsTrigger()

Update CAiBrain.lua (command description file)

---

lua/utilities.lua

https://github.com/FAForever/faf-coop-maps/issues/365

Fix GetRandomInt & GetRandomOffset2

---

lua/ui/lobby/lobby.lua

Old link was leading to the old forum.
New link goes: https://forum.faforever.com/topic/347/m-m-team-top-picks-map-submissions

New link for curated map button

---

.github/workflows/build.yaml
run_lua_tests.sh

Verify syntax using a custom modification of lua. Eventually I want to be able to run actual unit tests this way.
Also fixes a bug where files with spaces in the name would not be checked.
FAF lua code is here: https://github.com/FAForever/lua-lang

Use FAF lua instead of lua5.2

---

lua/ui/controls/worldview.lua
lua/user/prefs.lua

In some cases, much faster.
Fixed https://github.com/FAForever/fa/issues/3336

Optimize GetFromCurrentProfile

---

units/XRL0302/XRL0302_Script.lua

BeatleCloakMeshFx

---

units/UES0305/UES0305_unit.bp

Changes:
Add Jamming to UEF t3 Sonar
Maintenance Cost 500 -> 550

T3 Sonar rebalance

---

lua/ui/game/gameresult.lua
lua/ui/game/multifunction.lua

Fixed https://github.com/FAForever/fa/issues/3359

Disable ping buttons for defeated players

---

init_faf.lua

Variable can be set in faf_path.lua
Copied from #3177

Allow custom vault path

---

units/UES0305/UES0305_unit.bp

Merge T3 UEF Sonar's Sonar and Jamming button into a single one.
Fixes the issue of being able to have free sonar by turning off Jamming.

T3 UEF Sonar fix

---

units/UES0305/UES0305_unit.bp

it should be fine he said 
Spoiler: it was not fine

fix merge on sonar stuff

---

units/URL0401/URL0401_unit.bp

Fixes the slow animation rate of the Scathis that slipped through into the release because of me.

Fix Scathis unpack animation rate

---

lua/ScenarioFramework.lua

Should fix https://forum.faforever.com/assets/uploads/files/1632602982556-e9722363-5b8a-4f1a-9be1-6683283624f1-image.png
from https://forum.faforever.com/topic/2605/crashes/6?_=1632601054108
Untested

Fix giving units in shared armies settings

---

changelog-3724.md
lua/terranprojectiles.lua
projectiles/TDFPlasmaHeavy02/TDFPlasmaHeavy02_script.lua
projectiles/TDFPlasmaHeavy03/TDFPlasmaHeavy03_script.lua
projectiles/TDFPlasmaHeavy04/TDFPlasmaHeavy04_script.lua

temporarly fix proj

---

units/URA0401/URA0401_script.lua
units/URA0401/URA0401_unit.bp

Gives Soul Ripper personal stealth.

Soul Ripper buff

---

units/UAL0106/UAL0106_unit.bp
units/UEL0106/UEL0106_unit.bp
units/URL0106/URL0106_unit.bp

Adjust LAB hitboxes so that they can be hit more easily when un micro'ed by T1 tanks and other LABs.

Adjust LAB hitboxes

---

lua/ui/game/unitviewDetail.lua

Fixed TeleportDelay

---

lua/ui/help/loadingtips.lua

extremely unimportant loading tips typo

---

lua/defaultexplosions.lua

Fixes a few localized tables that should've remained global. Instead a local reference to the original table is made. Fixes mod dependencies.

Fix values being localized

---

lua/user/prefs.lua

moholog settings switched off by default

---

lua/ui/lobby/lobby.lua

@Garanas this one seems hard to test on FAF Dev Setup as Presets don't show up there seems to be faf specific.

Comment out Lobby Presets Button 

---

lua/ui/lobby/lobby.lua

Revert "Comment out Lobby Presets Button "

---

lua/ui/game/commandmode.lua

This essentially reverts #3500 but introduces some additional comments and makes it more maintainable for future developers. Is based on feedback by the community through Discord and the forums.

Adjust capping behavior

---

units/UAA0107/UAA0107_Script.lua
units/UAA0107/UAA0107_unit.bp
units/UEA0107/UEA0107_Script.lua
units/UEA0107/UEA0107_unit.bp
units/URA0107/URA0107_Script.lua
units/URA0107/URA0107_unit.bp
units/XSA0107/XSA0107_Script.lua
units/XSA0107/XSA0107_unit.bp

https://forums.faforever.com/viewtopic.php?f=67&t=19332
Adding dummy weapon to all Tech1 transporter to guide LABs weapon fire

Add dummy Weapon to Tech 1 transporter

---

lua/ui/lobby/lobby.lua

Numbers of players in lobby get functionality to swap players

Add functionality to swap players in lobby

---

lua/defaultunits.lua

Closes #3411. The tech 2 artillery look strange when being built in 45 degree angles.

Only allow 90 degree angles for tech 2 artillery

---

lua/sim/Unit.lua

Forgot to commit and push one last change to #3587 .

Fix 3587 by adding uncomitted changes

---

lua/sim/Unit.lua
lua/sim/weapon.lua
lua/system/Blueprints.lua

Fixes the issue of weapons being retrieved while the unit is dead. That should return nil instead.

Hotfix for #3587

---

lua/ui/game/construction.lua
lua/ui/game/unitview.lua
units/URL0001/URL0001_script.lua

Fix various issues 11

---

lua/terranunits.lua

Fixes the issue that when you build a kennel and queue the upgrade during the build that its drone doesn't spawn. Opens up the doors of the Kennel accordingly.

Fix Kennels 

---

lua/SimCallbacks.lua
lua/options/options.lua
lua/ui/dialogs/createprop.lua
lua/ui/dialogs/createunit.lua

This adds numerous features to the spawn menu including:
* A basic prop spawn mode
* Command feedback on unit spawn location
* Non-overlapping box-formation unit spawning (per selected ID)
* Support for n-columns in both filter and team lists
* Options for customising menu columns and filters
* Dynamic support for custom factions
* A toggle box for revealing hidden-from-spawn-menu units that defaults to off

Spawn menu moderate overhaul

---

lua/EffectTemplates.lua
lua/EffectUtilitiesSeraphim.lua
lua/spreadattack.lua
lua/ui/dialogs/disconnect.lua
lua/ui/lobby/autolobby.lua
lua/ui/lobby/lobbyOptions.lua

Adds the DisconnectionDelay to the auto lobby (ladder / tmm) and re-introduces a effect template for backwards compatibility.

Hotfix for release

---

lua/ui/game/commandmode.lua

Prevents malicious intent by ringing indefinitely.

Add delay to ringing

---

loc/RU/strings_db.lua
loc/US/strings_db.lua
lua/ui/lobby/lobby.lua

As part of the [Small suggestions topic](https://forum.faforever.com/topic/3206/small-suggestions-topic) but was send to me privately.
Todo:

Add enabled mods to tooltip

---

lua/ui/lobby/lobby.lua

Remove new lines when title is set

---

.github/ISSUE_TEMPLATE/feature_request.md
README.md

Improves the readme by encouraging contributors to discuss their pull requests via issues. Introduces a second issue template for feature requests.

Improve readme

---

lua/maui/layouthelpers.lua
lua/maui/window.lua

Includes a small fix that allows the Window UI class to properly react when the scale of the UI has been changed between two games.

Proper scaling of Window UI class 

---

lua/shield.lua
lua/sim/Projectile.lua
lua/sim/Unit.lua
projectiles/ShieldCollider/ShieldCollider_script.lua

Improves the performance of checking whether projectiles should collide or not.

Improve collision interactions of projectiles

---

lua/shield.lua

Fixes errors related to the new overspill mechanic related to personal shields.

Fix shield interaction issue

---

units/XSL0401/XSL0401_unit.bp

Change Death name from 'Collossus Death' to 'Ythotha Death'

Change Ythotha Death Name

---

lua/ui/uiutil.lua

Remove multiple lazyvar imports in UIutils.lua

Lazyvar imports

---

lua/ui/game/Profiler.lua
lua/ui/game/ProfilerElements.lua

Profiler UI improvement.
Profiler done with main window and scroll area highlighting rows on hover.

Profiler improvement

---

lua/defaultunits.lua
lua/sim/Profiler.lua

Various small changes to remove redundant code.

Refactoring

---

lua/keymap/keyactions.lua
lua/ui/game/MapUtilities.lua

Fixes the reference to the window creation and the hotkey description in the hotkey menu.

Fix map utilities window

---

lua/ui/lobby/lobby.lua

This PR adds team ratings (sum totals) for each team to the observer window.  It shows the unrounded displayed rating (mean - dev * 3) and then shows the base rating (mean) +/- uncertainty (3 * dev) in parentheses.
If there are two or fewer teams, they are listed before observers.  If there are more than two teams, they are all listed after observers.

Display team ratings in the observer window of the lobby

---

lua/sim/Unit.lua
lua/ui/lobby/lobby.lua
units/UAL0401/UAL0401_Script.lua

Fixes the dancing Galactic Colossus as seen in https://replay.faforever.com/16632732 and the broken UEF build animation as seen in https://replay.faforever.com/16640936.

Fix issues with 3732

---

lua/UTF.lua
lua/ui/lobby/lobby.lua
lua/ui/notify/customiser.lua
lua/ui/notify/notify.lua

Solution for notifications
and lobby kick.
TODO:
* ~~apply to current problems~~
* ~~better implementation~~?

String utils for storing in game.prefs

---

lua/sim/Unit.lua
lua/system/trashbag.lua

Refactored several trashbags in Unit.lua to use the TrashBag class. Testing seems to show no errors with this new implementation.

Issue 3727 replace table trashbags

---

lua/UTF.lua
lua/ui/lobby/lobby.lua
lua/ui/notify/customiser.lua
lua/ui/notify/notify.lua

Fix first-load issue with unicodes

---

lua/EffectUtilitiesUEF.lua

uef commander projectile fix a la jip

---

lua/system/Localization.lua

General performance improvements for the localization file. According to Balthazar this file is being called relentlessly and therefore any (small) gain is a gain. It will require more testing and a benchmark to confirm things are better.

Improve performance of localizations

---

lua/ui/lobby/chatarea.lua
lua/ui/lobby/lobby.lua

Some styling improvements for ChatArea of lobby

ChatArea styling

---

effects/Entities/UnitTeleport01/UnitTeleport01_script.lua
units/XSL0401/XSL0401_Script.lua

Fixes a few small issues:
- Allows the Ythotha lighting ball to spawn on death again
- Reduce fire damage radius of ACU spawn effect to destroy less tree groups

Fix for release 3732

---

lua/ui/lobby/chatarea.lua
lua/ui/lobby/lobby.lua

*Someday lobby would be fixed*

Lobby chat not showing last line (font edition)

---

lua/GameColors.lua
lua/ui/lobby/autolobby.lua
lua/ui/lobby/lobby.lua

Reverts the color changes as it was difficult for players to use them as a cue.

Reverts the color changes introduced by #3763 and #3706

---

lua/GameColors.lua

Color Selector Dropdown Order
LobbyColorOrder/TMMColorOrder

Better Rainbow

---

changelog.md
lua/ui/lobby/autolobby.lua
lua/ui/lobby/changelogData.lua
lua/version.lua
mod_info.lua
scripts/release-faf-develop.sh

Fixes the issue with matchmaking.

Release 3733

---

changelog.md
lua/ui/lobby/autolobby-classes.lua
lua/ui/lobby/autolobby.lua
lua/ui/lobby/changelogData.lua
lua/version.lua
mod_info.lua
scripts/release-faf-develop.sh

Fixes an issue with matchmaking.

Release 3734

---

lua/aibrain.lua
lua/defaultunits.lua
units/UAB1104/UAB1104_Script.lua

Changes the fabricator behavior to automatically enable / disable accordingly to the economy trend of the player. The production toggle completely disables the fabricator.

Alternative fabricator behavior

---

lua/aibrain.lua

Some debug code was left in and it now no longer affects AIs - they can manage their own fabricators.

Fix fabricator behavior

---

lua/ui/notify/notify.lua

Fix messages being called before init

---

loc/US/strings_db.lua

Updating Unit Description of SMD, T3 Mass Fabricator & T2 Mass Fabricator
@Garanas 2 Pull Requests and were not even halfway through the year 🤠

Updating LOC

---

lua/shield.lua

There was an issue with the internal state of the shield of the Continental. In turn, there's a state in which the continental can be invincible 😃 . This pull request fixes that issue.

Fix invincible transport

---

lua/ui/game/minimap.lua

Fixing https://github.com/FAForever/fa/issues/3828

Fix minimap LODs

---

lua/aibrain.lua
lua/defaultunits.lua

Tweaks the behavior to prevent desyncs. Improves the behavior in combination with overcharge.

Tweak automated fabricator behavior

---

lua/aibrain.lua

Fix mass fabs not working properly in multiplayer

Mass fabs fix

---

lua/ui/lobby/lobby.lua

This just cleans up the code a bit.

Eject Observer Refactor

---

lua/sim/Projectile.lua

Fixes a few small issues that creeped in over the projectile performance improvements.

Fix `OnCollisionCheck` and `OnCollisionCheckWeapon` functions for weapons

---

lua/sim/Projectile.lua

Every torpedo was an anti torpedo at the same time 😄 , that is fixed now.

Fix torpedo projectiles colliding with other torpedo projectiles

---

lua/ui/lobby/lobby.lua

Issue:
[game_17104954.log](https://github.com/FAForever/fa/files/8749744/game_17104954.log)

Fix lobby edit?

---

lua/sim/ScenarioUtilities.lua
lua/sim/Unit.lua

Adds the `IsCivilian = true` field to civilian units

---

lua/ui/game/economy.lua

Revert "Economy bar red warning texture fix"

---

lua/ui/dialogs/options.lua

Items in Option screens scrollable with mouse wheel. 
Result (needs audio):
https://user-images.githubusercontent.com/36369441/170889427-d73d1d5a-a147-4be1-ac4c-052d10bb8da9.mp4

Game option menu scrollable with mouse

---

lua/ui/help/tooltips.lua
lua/ui/lobby/lobby.lua

Fixes #3920
- Updated Naming of LOC in Lobby.lua
- Added New tooltip for patchnotes button

Add Tooltip to Lobby Patchnotes Button

---

lua/aibrain.lua
lua/shared/FabricatorBehaviorParams.lua
lua/sim/Unit.lua

Tweaks the behavior slightly, see the changes.

Tweak some of the fabricator parameters

---

.vscode/settings.json
projectiles/TIFMortar01/TIFMortar01_script.lua
projectiles/TIFNapalmCarpetBomb01/TIFNapalmCarpetBomb01_proj.bp
projectiles/TIFNapalmCarpetBomb01/TIFNapalmCarpetBomb01_script.lua
projectiles/TIFNapalmCarpetBomb02/TIFNapalmCarpetBomb02_proj.bp
projectiles/TIFNapalmCarpetBomb02/TIFNapalmCarpetBomb02_script.lua
projectiles/TIFSmallYieldNuclearBomb01/TIFSmallYieldNuclearBomb01_proj.bp
projectiles/TIFSmallYieldNuclearBomb01/TIFSmallYieldNuclearBomb01_script.lua
projectiles/TIMAntiMissile01/TIMAntiMissile01_script.lua
projectiles/TIMAntiTorpedo01/TIMAntiTorpedo01_script.lua
projectiles/TIMAntiTorpedo02/TIMAntiTorpedo02_script.lua
projectiles/TIMMissileIntercerptor01/TIMMissileIntercerptor01_script.lua
projectiles/TIMSonarBuoyCreator01/TIMSonarBuoyCreator01_script.lua
projectiles/TorpedoShipAeon01/TorpedoShipAeon01_script.lua
projectiles/TorpedoShipTerran01/TorpedoShipTerran01_script.lua
projectiles/TorpedoShipTerran02/TorpedoShipTerran02_script.lua
projectiles/TorpedoShipTerran03/TorpedoShipTerran03_script.lua
projectiles/TorpedoSubTerran01/TorpedoSubTerran01_script.lua

https://github.com/FAForever/fa/pull/3724
Optimize following projectiles. Unused code, added LODCutoff where applicable.
TIFMortar01
TIFNapalmCarpetBomb01
TIFNapalmCarpetBomb02
TIFSmallYieldNuclearBomb01
TIMAntiMissile01
TIMAntiTorpedo01
TIMAntiTorpedo02
TIMMissileIntercerptor01
TIMSonarBuoyCreator01
TorpedoShipAeon01
TorpedoShipTerran01
TorpedoShipTerran02
TorpedoShipTerran03
TorpedoSubTerran01

Optimize projectiles 01

---

lua/cybranunits.lua
lua/terranunits.lua

Fix UEF engineers not applying their water animation

---

lua/system/blueprints-lod.lua
lua/system/blueprints-weapons.lua
lua/ui/game/gamemain.lua

Reduces the LODCutoff curve for props, removes a LOG statement and increases the distance of experimental graphics.

Fixes various small issues

---

units/UES0401/UES0401_unit.bp

added ANTIAIR to categories
removed double ANTINAVY

UES0401 fix categories

---

effects/Entities/AeonAdjacencyNode/AeonAdjacencyNode_mesh.bp
effects/Entities/CybranAdjacencyNode/CybranAdjacencyNode_mesh.bp
effects/Entities/ForceField01/ForceField01_mesh.bp
effects/Entities/SeraphimAdjacencyNode/SeraphimAdjacencyNode_mesh.bp
effects/Entities/UEFAdjacencyNode/UEFAdjacencyNode_mesh.bp

sets all adjacency nodes cut offs to 300

lod cut offs of bp's working to fix #3940

---

scripts/release-faf-develop.sh

Fixes a series of typo's - I'm a horrible person.

Fix the deployment script

---

lua/ui/controls/combo.lua

fixed issue with single-item combo

---

lua/EffectUtilities.lua
lua/EffectUtilitiesGeneric.lua

Adds the optimized functions in part 1 of https://github.com/FAForever/fa/issues/3757 in `EffectUtilitiesGeneric.lua` and imports them to `EffectUtilities.lua`.
Also adds annotations to both files.
Looks like an optimization for `ApplyWindDirection` slipped in too.

Refactor effect utilities part 1

---

lua/aeonunits.lua
lua/kirvesbeams.lua
lua/seraphimunits.lua

Everything's better the second time around!

Re: Remove redundant functions

---

lua/AI/OpAI/AirAttacks_save.lua
lua/AI/OpAI/BaseManager.lua
lua/AI/OpAI/BaseManagerPlatoonThreads.lua
lua/AI/OpAI/BasicLandAttack_save.lua
lua/ScenarioFramework.lua
lua/ScenarioPlatoonAI.lua
lua/SimObjectives.lua
lua/aibrain.lua
lua/sim/ScenarioUtilities.lua
lua/ui/game/objectives2.lua
lua/ui/uimain.lua
units/OPE6003/OPE6003_unit.bp

Campaign AI improvements and fixes:
- Improved transport management.
- New platoon behaviour to enable stealth on Cybran units (will get slowly implemented into missions).
- Objective UI now shows game speed, just like skirmish score UI
- Fixed bug where it was possible to zoom in and out camera during some cimenatics.
- Fixes for platoon builders.
- Fixed bug where the AI would sometimes not upgrade factory to higher tech after rebuilding it.
- AI will rebuild every killed structure once on Easy difficulty
- Fixed size of tread marks for the Black Sun component truck

More fixes and improvements for the campaign AI

---

engine/Core.lua

`EnumColor` may want to instead be moved to a different file, rather than being shoved to the bottom.

Add color support

---

engine/Sim/Projectile.lua
engine/Sim/ReconBlip.lua

Annotate `engine/Sim/` batch 1

---

engine/Core.lua

Annotates the majority of functions in `engine/core.lua`

Annotate `engine/core.lua`

---

effects/Entities/SCUDeath01/SCUDeath01_script.lua

Closes https://github.com/FAForever/fa/issues/3433

Remove smoke ring on underwater SACU death

---

effects/range.fx

I missed one little thing. This will add a lot of FPS.

Again range shader optimize

---

lua/ScenarioFramework.lua

Part 2 of annotating the scenario framework. This one should be *much* more manageable...

Annotate scenario framework part 2

---

units/XSL0101/XSL0101_unit.bp
units/XSL0103/XSL0103_unit.bp
units/XSL0104/XSL0104_unit.bp
units/XSL0105/XSL0105_unit.bp
units/XSL0201/XSL0201_unit.bp

_Targeting bones of the Selen_
Note that it has no target bones, hence it is somewhere in the center of the collision box. All the other bones are animated.

Target bones - Seraphim Tech 1 Land

---

lua/sim/MatchState.lua
lua/sim/Unit.lua

Fix a typo with the new computation of resources

---

units/XRL0403/XRL0403_script.lua

Closes https://github.com/FAForever/fa/issues/2397

Adjust collision box of Megalith due to build animation

---

lua/defaultunits.lua

Closes https://github.com/FAForever/fa/issues/3042
A shield bug which can be reproduced by:
- Shield of structure takes damage
- Set engineers to assist the structure, healing the shield
- Upgrade the structure while the shield is being healed
- Bug as described
https://user-images.githubusercontent.com/15778155/183289862-772505f4-1244-4325-9444-af6b1b520dd6.mp4
_Without the fix applied, resources are consumed but not applied_
https://user-images.githubusercontent.com/15778155/183289863-a8aa8af1-fd9f-483f-98c1-90cd83b71cce.mp4
_With the fix applied, shield is assisted accordingly_

Fix a shield assist bug where resources were sent into Limbo

---

testmaps/PerfTestOriginal/perftest_aeon1plan.lua
testmaps/PerfTestOriginal/perftest_aeon1planlist.lua
testmaps/PerfTestOriginal/perftest_aeonplan.lua
testmaps/PerfTestOriginal/perftest_aeonplanlist.lua
testmaps/PerfTestOriginal/perftest_cybran2plan.lua
testmaps/PerfTestOriginal/perftest_cybran2planlist.lua
testmaps/PerfTestOriginal/perftest_playerplan.lua
testmaps/PerfTestOriginal/perftest_playerplanlist.lua
testmaps/PerfTestOriginal/perftest_uefplan.lua
testmaps/PerfTestOriginal/perftest_uefplanlist.lua

Fix the commented code for PerfTestOriginal

---

lua/editor/AMPlatoonHelperFunctions.lua
lua/editor/BaseManagerBuildConditions.lua
lua/editor/EconomyBuildConditions.lua
lua/editor/InstantBuildConditions.lua
lua/editor/MarkerBuildConditions.lua
lua/editor/MiscBuildConditions.lua
lua/editor/OtherArmyUnitCountBuildConditions.lua
lua/editor/PlatoonCountBuildConditions.lua
lua/editor/SorianBuildConditions.lua
lua/editor/SorianInstantBuildConditions.lua
lua/editor/ThreatBuildConditions.lua
lua/editor/UnitCountBuildConditions.lua

I've done what i think is right any that i'm unsure of i've left as any

code annotation for Editor directory

---

engine/Core.lua

Fix Jips Typo

---

engine/Sim/CBuilderArmManipulator.lua
engine/Sim/Entity.lua
engine/Sim/IEffect.lua
engine/Sim/Projectile.lua
engine/Sim/Unit.lua
engine/Sim/UnitWeapon.lua

Some more typos / duplicate lines

---

units/DAA0206/DAA0206_script.lua
units/DALK003/DALK003_Script.lua
units/DEL0204/DEL0204_Script.lua
units/DELK002/DELK002_script.lua
units/DRL0204/DRL0204_script.lua
units/DRLK001/DRLK001_Script.lua
units/DRLK005/DRLK005_script.lua
units/DSLK004/DSLK004_script.lua

Some CleanUp and Added Classes

---

lua/aeonunits.lua
lua/cybranunits.lua
lua/seraphimunits.lua

Added Classes to the aeonunits.lua , cybranunits.lua , seraphimunits.lua

Added Unit Classes

---

units/UEL0001/UEL0001_unit.bp
units/XSL0001/XSL0001_unit.bp
units/XSL0301/XSL0301_unit.bp

Makes all ACUs and SACUs that can make tac missile start construction by default.

Auto Tac Missile Start

---

lua/aeon_naval_weapons.lua
lua/aeonprojectiles.lua
lua/cybranprojectiles.lua
lua/defaultexplosions.lua
lua/defaultprops.lua

Done my best at commenting some of the file. If I've got some thing wrong let me know :)

Some more Code Annotation stuff

---

lua/ui/game/construction.lua

Fixes quick dialog locking screen when removing upgrade of a unit being destroyed.

Upgrade lock

---

lua/defaultunits.lua

Annotated most of the file any that I was unsure of have left as Unknown

Annotations for defaultunits.lua

---

lua/sim/Unit.lua
units/UAS0401/UAS0401_unit.bp

Fixes the fast death animation of the tempest and fixes really slow animations from not animating at all. The code converted the values to and from integers 😄 
Closes #3821 
https://user-images.githubusercontent.com/15778155/185495944-4557b215-4c2c-4303-8c4e-47c6a386f656.mp4

Fix the death animation of the tempest

---

lua/GenericDebris.lua
lua/objectiveArrow.lua
lua/terranprojectiles.lua
lua/terranweapons.lua

added missing classes for intellisense

---

lua/defaultunits.lua

Related to #4138 , which was still using the old cache.

Fix HQs not working

---

lua/aeonweapons.lua
projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_proj.bp
projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_proj.bp
projectiles/TIFMissileCruise04/TIFMissileCruise04_proj.bp

Slows down the tractoring of units for the colossus and removes the buff to missiles of cruisers. The latter is discussed with the balance team, the former is obvious after watching some replays 😄

Fix the balance of some of the adjusted mechanics

---

lua/ui/lobby/ModsManager.lua
lua/ui/lobby/lobby.lua

Mods manager improvements

---

lua/ScenarioFramework.lua

Finishes up the scenario framework annotations. A little bit of refactoring, particularly in the offmap scripts--I tested it though and it works fine.

Refactor scenario framework part 3

---

lua/sim/PrefetchUtilities.lua
lua/sim/Profiler.lua
lua/sim/Projectile.lua
lua/sim/Prop.lua
lua/sim/ScenarioUtilities.lua
lua/sim/ScriptTask.lua
lua/sim/StrategyBuilder.lua
lua/sim/StrategyManager.lua
lua/sim/VizMarker.lua
lua/sim/score.lua
lua/sim/simuistate.lua

This Tackles the following files
- PrefetchUtilities.lua
- Profiler.lua
- Prop.lua
- ScenarioUtilites.lua
- ScriptTask.lua
- StrategyBuilder.lua
- Strategymanager.lua
- VizMarker.lua
- score.lua
- simuistate.lua

Annotation work /File Cleaning part 3

---

lua/sim/ScenarioUtilities.lua

Let wreckage to spawn as usual

---

lua/ui/game/cursor/depth.lua
lua/ui/game/cursor/hover.lua
lua/ui/game/gamemain.lua

Attempts to fix this:
```
warning: ...orever\gamedata\lua.nx5\lua\ui\game\construction.lua(91): Attempt to set attribute 'HandleEvent' on nil
warning: stack traceback:
warning:         [C]: in function `error'
warning:         ...ata\faforever\gamedata\lua.nx5\lua\system\config.lua(14): in function <...ata\faforever\gamedata\lua.nx5\lua\system\config.lua:13>
warning:         ...orever\gamedata\lua.nx5\lua\ui\game\construction.lua(91): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: ?
warning:         ...ata\faforever\gamedata\lua.nx5\lua\system\import.lua(91): in function `import'
warning:         ...ata\faforever\gamedata\lua.nx5\lua\system\import.lua(76): in function `import'
warning:         ...forever\gamedata\lua.nx5\lua\ui\game\commandmode.lua(12): …
```

Attempt at fixing the issues with the depth scanning

---

lua/SimHooks.lua

Re-allow the use of debug drawing tools for AI-related games.

Allow the debug draw tools to work in AI-related games

---

lua/sim/defaultweapons.lua

Found together with @Hdt80bro , in extension of #4207

Fix another issue with the new bomber trajectory computations

---

engine/Core.lua
engine/Sim.lua
engine/Sim/CAiBrain.lua
engine/Sim/Unit.lua
engine/User/CMauiEdit.lua
engine/User/UserUnit.lua
lua/maui/text.lua
lua/options/options.lua
lua/sim/Builder.lua
lua/sim/BuilderManager.lua
lua/sim/MarkerUtilities.lua
lua/sim/Unit.lua

Intelisence minor fixes

---

init.lua
init_faf.lua
init_fafbeta.lua
init_fafdevelop.lua
init_shared.lua
lua/ui/game/gamemain.lua
lua/ui/game/reclaim.lua

Optimizes Labels display to reduce FPS drops. 
* Selects only reclaim props in view for project
* Combines nearest props depending on camera zoom

Optimize Reclaim Labels attempt 69

---

lua/keymap/keymapper.lua
lua/system/Localization.lua
lua/ui/lobby/lobby.lua
lua/ui/menus/main.lua

Allows for key actions to be localization directives like `"<LOC loadingtip>Press {k toggle_key_bindings} to open the key mapper"`

Add key action localization directives

---

engine/AnnotationCommon.lua
engine/User.lua
engine/User/CMauiEdit.lua
lua/maui/bitmap.lua
lua/maui/button.lua
lua/maui/checkbox.lua
lua/maui/control.lua
lua/maui/cursor.lua
lua/maui/dragger.lua
lua/maui/frame.lua
lua/maui/group.lua
lua/maui/mesh.lua
lua/maui/scrollbar.lua
lua/ui/controls/border.lua
lua/ui/controls/checkbox.lua
lua/ui/controls/mappreview.lua
lua/ui/controls/ninepatch.lua

This uses annotations from the layout pattern PR

Annotate UI Controls part 1

---

engine/Library.lua
engine/Sim.lua
lua/system/Blueprints.lua
lua/system/class.lua
lua/system/dkson.lua
lua/system/performance.lua
lua/tests/lazyvar_test.lua
lua/ui/campaign/campaignmanager.lua
lua/ui/campaign/campaignmovies.lua
lua/ui/campaign/operationbriefing.lua
lua/ui/campaign/selectcampaign.lua
lua/ui/controls/combo.lua
lua/ui/controls/specialgrid.lua
lua/ui/dialogs/AIUtilitiesView.lua
lua/ui/dialogs/console.lua
lua/ui/dialogs/createprop.lua
lua/ui/dialogs/createunit.lua
lua/ui/dialogs/disconnect.lua
lua/ui/dialogs/eschandler.lua
lua/ui/dialogs/hotstats.lua
lua/ui/dialogs/keybindings.lua
lua/ui/dialogs/mapselect.lua
lua/ui/dialogs/myeffecthelpers.lua
lua/ui/dialogs/options.lua
lua/ui/dialogs/profile.lua
lua/ui/dialogs/replay.lua
lua/ui/dialogs/saveload.lua
lua/ui/dialogs/score.lua

Small changes to files to help with the Intellisense Kind of got carried away Oops

More minor changes

---

lua/ui/dialogs/createunit.lua
lua/ui/game/reclaim.lua

Adds in colored reclaim labels based on value

---

lua/shared/RecallParams.lua

Adjusts the recall parameters as discussed on Zulip.

Recall parameters

---

lua/aeonweapons.lua

Fix issues with the colossus where air units remain alive and another issue where the effects on the arms linger on.
https://user-images.githubusercontent.com/15778155/193397397-72fdc891-33d4-4653-8c9e-6da9aeb576e2.mp4
I do have to admit that the drunk gunships look good 😄

Fix issues with air units being tractored

---

lua/SimHooks.lua

During AI games cheating in this form is irrelevant anyhow - there is no rating being adjusted.

Allow debug drawing functions to be used during AI games

---

init_fafdevelop.lua

https://github.com/FAForever/fa/commit/139639792f9e832f3c9a58a457f0af2895d9a24e

Returns DevData back

---

lua/ui/game/chat.lua
lua/ui/game/ping.lua

Adds in a text message that clearly shows who wrote the marker. You can click on the text message to go to the marker.
https://user-images.githubusercontent.com/15778155/194757010-ed619656-8faf-4b8c-96d5-772c96639056.mp4

Improve markers with text

---

lua/defaultantiprojectile.lua
projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_proj.bp

this change adds an adds an additional category to billy nuke,used in the redirect function.

makes loyalists not redicret billy nukes

---

units/XEL0209/XEL0209_unit.bp

Enable sparkies to build t1/t2 UEF radar and sonar
(replacement of #4197)

Let Sparkies build radar and sonar

---

units/XEA3204/XEA3204_unit.bp
units/XEB0104/XEB0104_unit.bp
units/XEB0204/XEB0204_unit.bp

Decreases kennel mass cost by 20%
Decreases drone rebuild mass and energy costs by 60%
Decrease drone rebuild time by 33.33%
Increases drone elevation from 2 to 3
(replacement of #4198)

Nerf Kennel Costs

---

lua/SimCallbacks.lua
lua/shared/NavGenerator.lua
lua/sim/NavDebug.lua
lua/sim/NavGenerator.lua
lua/sim/NavUtils.lua
lua/ui/game/NavGenerator.lua

Add query to retrieve label of area

---

lua/sim/NavGenerator.lua

The compression threshold is used to prevent small neighbors that usually have little impact on the final paths, while they drastically push the memory requirements for the navigational mesh.
With this pull request we make it dynamic: 
- 5x5, 10x10, 20x20 maps have a 2x2 threshold for land, amph and hover. Naval has a 4x4 threshold
- 40x40, 80x80 maps have a 4x4 threshold for land, amph and hover. Naval has a 8x8 threshold
The idea behind it is that usually as maps increase in size the number of narrow corridors is essentially reduced to zero.

Nav mesh - introduce dynamic compression threshold

---

effects/mesh.fx

Update the shaders so that they can be removed from the Nomads directory:
- https://github.com/FAForever/nomads/blob/develop/effects/mesh.fx
This has been a source of issues the entire year, and as we're working on PBR shaders we'll have only more and more issues. 
I've copied everything starting here:
- https://github.com/FAForever/nomads/blob/develop/effects/mesh.fx#L6962-L9005

Update nomads shaders

---

lua/keymap/hotbuild.lua
lua/ui/game/commandmode.lua

Fix error when spawning in units

---

lua/ui/game/reclaim.lua

I missed a sign when originally implementing the dynamic colors. It sounds like we have other feedback for the color scaling though.

Adjust Reclaim Label Colors

---

lua/ui/game/diplomacy.lua

Fix the broken resource sharing panel

---

lua/ui/game/gamemain.lua

There are quite a few network parameters that we can tweak using the console. This pull request attempts to find values that better suit today's network capacities.

Tweak network parameters

---

lua/aibrain.lua

Long story short this PR fixes the broken PickEnemyLogic and GetAllianceEnemy functions in the default AI.
Issues were 
Dead armies could be selected as enemies.
The functions performed threat checks on self and allies which don't work. 
The GetAllianceEnemy function used GetHighestThreatPosition in a way that doesn't work.
I've modified the logic to work correctly for self and allies using blueprint threat data around start positions and used the threat table generated for the GetAllianceEnemy function.
Note : Sorian uses its own PickEnemyLogic function so it will remain broken. I'm pretty sure its identical to the default except it sends a chat message.
**Testing changes**
To test these changes you will need to log the PickEnemyLogic function and the …

AI - Fix PickEnemyLogic and GetEnemyAlliance.

---

.vscode/settings.json
engine/Library.lua
lua/system/import.lua
lua/ui/game/commandmode.lua
lua/ui/game/gamemain.lua

Introduces `lazyimport` function for creating module instance without importing it til it is needed.

Lazy import

---

lua/ui/controls/worldview.lua

Safe to say that it didn't work out quite that well. Originates from #4474

Remove CTRL to issue move commands that ignore everything

---

lua/ui/campaign/_head_test.lua

For easy testing of all mission VOs

Improve head test

---

effects/terrain.fx
units/UAB1303/UAB1303_unit.bp
units/UEB1303/UEB1303_unit.bp
units/URB1303/URB1303_unit.bp
units/XAB3301/XAB3301_unit.bp
units/XSB1303/XSB1303_unit.bp

Closes https://github.com/FAForever/fa/issues/4494

Fix incorrect `UpgradesFrom` fields

---

lua/ui/lobby/lobby.lua

Fix scaling of lobby map preview tooltip

---

engine/Core/Blueprints/PropBlueprint.lua
lua/SimUtils.lua
lua/proptree.lua
lua/sim/Prop.lua
lua/system/Blueprints.lua
lua/system/blueprints-props.lua
lua/ui/dialogs/createprop.lua
lua/ui/game/reclaim.lua
lua/wreckage.lua

Overall reduces the number of table fields that props create over their life span. I'll write out the exact changes soon.
Removes the following fields:
- `SyncData` when the prop can not have a label (usually individual trees)
- `Dead` was set when `OnDestroy` was called. This is an unreliable method regardless - instead it now just calls `BeenDestroyed`
- `IsWreckage` is now set in the metatable
- `CanBeKilled` if a prop is invulnerable (it has the property 'INVULNERABLE') then it is assigned a separate prop class instead
- `CanTakeDamage` see above
- `hasLabel` was set if prop has a label, but the existence of `SyncData` replaces that
- `CollisionRadius` was used by wrecks to catch an issue with sharing unfinished units. There is a separate solution for this
- `CollisionSizeX` see above …

Reduce memory allocations of props

---

lua/simInit.lua

@relent0r it appears co-op had the same issues 😄

Break cycles in dependencies

---

lua/AI/AIAddBuilderTable.lua
lua/AI/OpAI/AirAttacks_EditorFunctions.lua
lua/AI/OpAI/AirScout_EditorFunctions.lua
lua/AI/OpAI/BasicLandAttack_EditorFunctions.lua
lua/AI/OpAI/BomberEscort_EditorFunctions.lua
lua/AI/OpAI/HeavyLandAttack_EditorFunctions.lua
lua/AI/OpAI/LandAssault_EditorFunctions.lua
lua/AI/OpAI/LeftoverCleanup_EditorFunctions.lua
lua/AI/OpAI/NavalAttacks_EditorFunctions.lua
lua/AI/OpAI/NavalFleet_EditorFunctions.lua
lua/AI/OpAI/NavalOpAI.lua
lua/AI/OpAI/OpBehaviors.lua
lua/AI/OpAI/ReactiveAI.lua
lua/AI/OpAI/lightairattack_EditorFunctions.lua
lua/AI/aiarchetype-managerloader.lua
lua/AI/aiattackutilities.lua
lua/RuleInit.lua
lua/terranunits.lua
lua/userInit.lua

Mainly Files from AI\OpAI with a few other files from lua\

More Intellisense Stuffs

---

lua/options/options.lua
lua/ui/game/selection.lua
lua/ui/help/tooltips.lua

Not exactly ideal, but I suppose we should've reviewed the settings better before merging them 😄

Fix option keys and improve their naming scheme

---

lua/sim/NavGenerator.lua
lua/sim/Unit.lua
lua/system/utils.lua

This is useful to understand the impact of tables (or values in general) - a long missing factor in our hunt towards better performance. Looking forward to feedback on this function.

Introduces function to determine allocated bytes for any value

---

projectiles/TANAnglerTorpedo01/TANAnglerTorpedo01_script.lua
projectiles/TANAnglerTorpedo06/TANAnglerTorpedo06_script.lua
projectiles/TDFFragmentationGrenade01/TDFFragmentationGrenade01_script.lua
projectiles/TDFGauss01/TDFGauss01_script.lua
projectiles/TDFGauss04/TDFGauss04_script.lua
projectiles/TDFGauss05/TDFGauss05_script.lua
projectiles/TDFPlasmaHeavy03/TDFPlasmaHeavy03_script.lua
projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
projectiles/TIFMissileCruise02/TIFMissileCruise02_script.lua
projectiles/TIFMissileCruise03/TIFMissileCruise03_Script.lua
projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua
projectiles/TIFMissileCruise05/TIFMissileCruise05_Script.lua
projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_Script.lua
projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
projectiles/TIMSonarBuoyCreator01/TIMSonarBuoyCreator01_script.lua
projectiles/TestProjectile01/TestProjectile01_script.lua
projectiles/TorpedoShipTerran02/TorpedoShipTerran02_script.lua

Projectile Refactoring 7

---

projectiles/CIFProtonBomb01/CIFProtonBomb01_script.lua
projectiles/CIMAntiMissile01/CIMAntiMissile01_script.lua
projectiles/CIMAntiTorpedo01/CIMAntiTorpedo01_script.lua
projectiles/CIMAntiTorpedo02/CIMAntiTorpedo02_script.lua
projectiles/CIMAntiTorpedo03/CIMAntiTorpedo03_script.lua
projectiles/FireSparks/FireSparks_script.lua
projectiles/Kamikaze01/Kamikaze01_script.lua
projectiles/LaserBotTerran01/LaserBotTerran01_script.lua
projectiles/MissileCruiseSubTerran01/MissileCruiseSubTerran01_script.lua
projectiles/MissileCruiseTerran01/MissileCruiseTerran01_Script.lua
projectiles/MissileJetTerran01/MissileJetTerran01_script.lua
projectiles/SAABlazarAutoCannon01/SAABlazarAutoCannon01_script.lua
projectiles/SAABlazarAutoCannon02/SAABlazarAutoCannon02_script.lua
projectiles/SAABlazarAutoCannon03/SAABlazarAutoCannon03_script.lua
projectiles/SAABlazarAutoCannon04/SAABlazarAutoCannon04_script.lua
projectiles/SAAHotheDecoyFlare01/SAAHotheDecoyFlare01_script.lua
projectiles/SAALosaareAutoCannon01/SAALosaareAutoCannon01_script.lua
projectiles/SAALosaareAutoCannon02/SAALosaareAutoCannon02_script.lua
projectiles/SAALosaareAutoCannon03/SAALosaareAutoCannon03_script.lua
projectiles/SAALosaareAutoCannon04/SAALosaareAutoCannon04_script.lua
projectiles/SAAOlarisAAArtillery01/SAAOlarisAAArtillery01_script.lua
projectiles/SAAOlarisAAArtillery02/SAAOlarisAAArtillery02_script.lua
projectiles/SAAOlarisAAArtillery03/SAAOlarisAAArtillery03_script.lua
projectiles/SAAOlarisAAArtillery04/SAAOlarisAAArtillery04_script.lua
projectiles/SAAOlarisAAArtillery05/SAAOlarisAAArtillery05_script.lua
projectiles/SAAOlarisAAArtillery06/SAAOlarisAAArtillery06_script.lua
projectiles/SAAShleoAAGatlingGun01/SAAShleoAAGatlingGun01_script.lua
projectiles/SAAShleoAAGatlingGun02/SAAShleoAAGatlingGun02_script.lua

Batch 4 Of Projectiles refactoring

Projectiles Refactoring 4

---

lua/AI/AIBehaviors.lua
lua/AI/OpAI/BaseManager.lua
lua/AI/OpAI/BaseManagerPlatoonThreads.lua
lua/AI/OpAI/BomberEscort_EditorFunctions.lua
lua/AI/OpAI/OpBehaviors.lua
lua/AI/aiarchetype-managerloader.lua
lua/AI/aiattackutilities.lua
lua/AI/aibuildstructures.lua
lua/AI/aibuildunits.lua
lua/AI/aiutilities.lua
lua/editor/EconomyBuildConditions.lua
lua/editor/MarkerBuildConditions.lua
lua/editor/MiscBuildConditions.lua
lua/editor/SorianBuildConditions.lua
lua/editor/SorianInstantBuildConditions.lua
lua/editor/ThreatBuildConditions.lua
lua/editor/UnitCountBuildConditions.lua
lua/shared/color.lua

Intellisense Update to AI Files

Last Intellisense Update of 2022

---

lua/sim/NavGenerator.lua

Fixes typing issues introduced by #4560 and layer issues introduced by #4536. The closer you look, the more they start to pop up 😄 .
Introduces the `Root` attribute to leaves, so that they can always backtrack to the most upper node of their compression tree.

Fix minor issues and introduce access to root

---

lua/sim/Unit.lua

Fix initial regen value not showing

---

lua/options/options.lua
lua/ui/help/tooltips.lua

The mod is not deprecated - there is no technical reason to do so.

Integrate 'NoShake' UI mod

---

lua/aeonprojectiles.lua
lua/cybranprojectiles.lua
lua/terranprojectiles.lua
projectiles/AANDepthCharge02/AANDepthCharge02_script.lua
projectiles/CANKrilTorpedo01/CANKrilTorpedo01_script.lua
projectiles/CANTorpedoNanite03/CANTorpedoNanite03_script.lua
projectiles/TANAnglerTorpedo04/TANAnglerTorpedo04_script.lua
projectiles/TANAnglerTorpedo05/TANAnglerTorpedo05_script.lua
projectiles/TANAnglerTorpedo06/TANAnglerTorpedo06_script.lua

Fix various typo's and duplicated engine calls over the hierarchy.

Fix issues with torpedoes

---

units/UAL0208/UAL0208_unit.bp
units/UAL0309/UAL0309_unit.bp
units/UEL0208/UEL0208_unit.bp
units/UEL0309/UEL0309_unit.bp
units/URL0208/URL0208_unit.bp
units/URL0309/URL0309_unit.bp
units/XSL0208/XSL0208_unit.bp
units/XSL0309/XSL0309_unit.bp

Increase BP of T2 and T3 engineers to increase their efficiency compared to T1 engies.
T2 12.5 -> 13 (10.4 -> 10 m/BP)
T3 30->32.5 (10.4 -> 9.6 m/BP)

Adjust engineers

---

units/UAB2303/UAB2303_unit.bp
units/UEB2303/UEB2303_unit.bp
units/URB2303/URB2303_unit.bp
units/XSB2303/XSB2303_unit.bp

Increase Firing Randomness of all T2 artilleries by 0.25
Buff Miasma AoE by 0.25
Normalize mass cost and m/e ratio

Adjust T2 static Artillery

---

lua/AI/AIBuilders/SorianStrategyBuilders.lua
lua/AI/OpAI/BaseManager.lua
lua/AI/aibuildstructures.lua
lua/AI/aiutilities.lua
lua/ScenarioPlatoonAI.lua
lua/platoon.lua

The use of `lazyimport` appears to break hooking.

Fix hooking issues for mods

---

effects/Explosion/Explosion01_a_script.lua
effects/Explosion/Explosion01_b_script.lua
effects/Explosion/Explosion01_c_script.lua
effects/Explosion/Explosion01_d_script.lua
effects/Explosion/Explosion01_script.lua
effects/Nuke/Shockwave01_script.lua
lua/AI/AIBuilders/SorianStrategyBuilders.lua
lua/AI/sorianutilities.lua
lua/editor/AMPlatoonHelperFunctions.lua
lua/editor/BaseManagerBuildConditions.lua
lua/editor/InstantBuildConditions.lua
lua/editor/OtherArmyUnitCountBuildConditions.lua
lua/editor/PlatoonCountBuildConditions.lua

- Fix Naming of Explosion effects
- removed unessary empty lines

Code Tidy-up

---

projectiles/AIFQuantumWarhead01/AIFQuantumWarhead01_proj.bp
projectiles/AIFQuantumWarhead03/AIFQuantumWarhead03_proj.bp
projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_proj.bp
projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_proj.bp
projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_proj.bp
projectiles/TIFMissileNuke01/TIFMissileNuke01_proj.bp
projectiles/TIFMissileNuke02/TIFMissileNuke02_proj.bp
units/UAB2305/UAB2305_unit.bp
units/UAS0304/UAS0304_unit.bp
units/UEB2305/UEB2305_unit.bp
units/UES0304/UES0304_unit.bp
units/URB2305/URB2305_unit.bp
units/URS0304/URS0304_unit.bp
units/XSB2305/XSB2305_unit.bp

- Cut [nerf](https://github.com/FAForever/fa/pull/4108) to silo/sub cost in half
-  Nerf missle e cost to 5k per sec from 4.5k

Adjust Nukes

---

units/UAB2302/UAB2302_unit.bp
units/UEB2302/UEB2302_unit.bp
units/URB2302/URB2302_unit.bp
units/XSB2302/XSB2302_unit.bp

- E cost of T3 arty is multiplied by 1.5.
- E cost to reload the arty is multiplied by 2. (Confirmed not to take longer than arty reload with full adjacency)

T3 Arty Adjustment

---

lua/aeonweapons.lua

Spot the differences 😄 !
https://user-images.githubusercontent.com/15778155/214688360-1a3c30fc-d9ec-4279-a52b-6a1e84080927.mp4

Properly apply charge animation of Emissary

---

lua/EffectUtilities.lua

Relates to https://github.com/FAForever/fa/pull/4635
https://user-images.githubusercontent.com/15778155/214910663-098979e2-d0a1-497f-a118-c70d4a0f8e4c.mp4

Dynamic adjacency direction

---

effects/mesh.fx

https://user-images.githubusercontent.com/15778155/214900254-c39c437d-6629-4029-befe-87518ca9f14e.mp4

Fix incorrect substitution in shader

---

lua/defaultcomponents.lua
lua/system/blueprints-units.lua
units/UEL0307/UEL0307_script.lua

Closes https://github.com/FAForever/fa/issues/4666

Fix logging of intel and Parashield not having its effects

---

units/DEL0204/DEL0204_unit.bp
units/XES0102/XES0102_unit.bp
units/XRB0104/XRB0104_unit.bp
units/XRB0204/XRB0204_unit.bp
units/XRB0304/XRB0304_unit.bp

Some units had the wrong faction set for as their shader.

Fix incorrect shader selection

---

lua/sim/Unit.lua
lua/sim/weapon.lua

The following fields of the Unit class become optional:
- `SoundEntity` 
- `EngineFlags` 
The following fields of the Unit class are removed:
- `Audio`
- `MovementEffects`

Revert a few decisions made the past year

---

engine/Core/Blueprints/UnitBlueprint.lua
lua/defaultcomponents.lua
lua/sim/Unit.lua
lua/system/blueprints-units.lua
lua/ui/controls/worldview.lua
lua/ui/game/unitview.lua

Closes #4135 .
Completely re-implements the veterancy system, while keeping all the existing functionality. This doesn't only solve the performance problems as described by #4135, it also fixes a significant memory leak 😄 !
In the old implementation a unit `x` keeps a strong reference to every unit that dealt damage to `x`. A unit usually deals damage to multiple units and receives damage from multiple units. This mimics a direction graph of strong references. And because the references are strong the garbage collector will wait with collecting old instances of units until all the active references are gone. But because usually there are always some units leftover after an engagement there will always be some active refeference. Especially when there is an ACU involved 😄 !
To visualize …

Re-implement veterancy system

---

lua/keymap/keyactions.lua
lua/keymap/keydescriptions.lua
lua/keymap/misckeyactions.lua
lua/ui/controls/worldview.lua
lua/ui/game/commandmode.lua

Introduces the hard move as first implemented by the `Random UI Improvements` mod of Strogo

Add hard move feature

---

lua/SimCallbacks.lua
lua/keymap/misckeyactions.lua
lua/ui/controls/worldview.lua

This version should be more similar to the one made by Strogo

Second attempt for hard move implementation

---

lua/system/blueprints-units.lua

See also: https://forum.faforever.com/topic/5447/developers-iteration-i-of-2023/46

Take into account omni intel

---

lua/defaultcomponents.lua
lua/defaultunits.lua
lua/sim/Unit.lua

Closes #4707 and aircraft now disperse experience properly

Fix issues with re-implementation of veterancy

---

lua/defaultunits.lua

Closes #4708
This is a work around, we'll need to find a better approach 😄

Fix units showing initially hidden bones

---

units/UAL0208/UAL0208_unit.bp
units/UAL0309/UAL0309_unit.bp

Add missing max reverse speed field to allow reverse movement

---

changelog-dev.md
changelog.md
lua/ui/game/reclaim.lua
lua/ui/lobby/autolobby.lua
lua/ui/lobby/changelogData.lua
lua/version.lua
mod_info.lua
scripts/release-faf-develop.sh

Adds a reminder to set the executable before a release.
Fixes a typo in the changelog
Fixes an issue with autolobby

Changelog 3752

---

lua/sim/NavGenerator.lua

As reported by @maudlin27 
It now works as expected:

Prevent culling of labels with resources

---

lua/sim/Unit.lua

Change up the order back to the old situation

---

lua/defaultunits.lua
lua/shared/quaternions.lua

Closes #4751
With thanks to some quaternion magic we can apply _both_ orientations 😄 !

Keep orientation of structure as assigned in the editor

---

lua/sim/Unit.lua
lua/ui/game/gamemain.lua

Tunes down the network parameters, the initial experiment was too aggressive.

Adjust network parameters

---

lua/ui/game/objectives2.lua
lua/ui/game/orders.lua
lua/ui/game/pingGroup.lua

See also: https://forum.faforever.com/topic/5639/attack-move-hotkey/7

Fix typo with attack move cursor

---

lua/defaultcomponents.lua

It was upgrading the wrong threshold 😄 !

Fix transferred units receiving full vet

---

engine/Core/Blueprints/UnitBlueprint.lua
lua/SimUtils.lua

Fix bug where orientations are applied multiple times

---

lua/ui/game/tabs.lua

Do not disable tabs when you're in a replay

---

lua/ui/lobby/lobbyOptions.lua

Share unit cap by default

---

projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua
projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua
projectiles/SDFLightChronatronCannon02/SDFLightChronatronCannon02_script.lua
projectiles/TDFOverCharge01/TDFOverCharge01_script.lua

Relates to #4599
Compute damage of overcharge before applying it.

Fix overcharge always dealing 15K damage

---

lua/maui/statusbar.lua

Improves annotations while improving the performance of the interface, such as:
- https://github.com/FAForever/fa/wiki/Performance-and-hash-operations

Refactor `statusbar.lua` to improve performance and readability

---

lua/lazyvar.lua
lua/ui/game/worldview.lua

Initial setup to refactor LazyVars so that they re-use memory instead of allocating new memory all the time.

Refactoring LazyVars

---

effects/Entities/DEBRISMISC010/DebrisMisc010_proj.bp
effects/Entities/DebrisBoneAttachChassis01/DebrisBoneAttachChassis01_proj.bp
effects/Entities/DebrisBoneAttachHigh01/DebrisBoneAttachHigh01_proj.bp
effects/Entities/DebrisBoneAttachLow01/DebrisBoneAttachLow01_proj.bp
effects/Entities/DebrisMisc01/DebrisMisc01_proj.bp
effects/Entities/DebrisMisc02/DebrisMisc02_proj.bp
effects/Entities/DebrisMisc03/DebrisMisc03_proj.bp
effects/Entities/DebrisMisc04/DebrisMisc04_proj.bp
effects/Entities/DebrisMisc05/DebrisMisc05_proj.bp
effects/Entities/DebrisMisc06/DebrisMisc06_proj.bp
effects/Entities/DebrisMisc07/DebrisMisc07_proj.bp
effects/Entities/DebrisMisc08/DebrisMisc08_proj.bp
effects/Entities/DebrisMisc09/DebrisMisc09_proj.bp
effects/emitters/destruction_explosion_debris_trail_01_emit.bp
lua/EffectTemplates.lua
lua/aibrains/operation-ai.lua
lua/sim/DefaultProjectiles.lua
lua/sim/Projectile.lua

Improves the effects surrounding debris. Last year we optimized them but we didn't quite fully understood what is and is not expensive. One thing that is, on average, not too expensive is the use of emitters. This (re-)introduces:
- A trail for the debris
- An impact effect for the debris
The impact effect has a similar feel to the impact on water for debris. With future pull requests we can tune the color of the land debris depending on the terrain type. That is not supported at the moment
https://user-images.githubusercontent.com/15778155/226862443-1cd02335-4400-4949-855d-4fcc17f65187.mp4
https://user-images.githubusercontent.com/15778155/226862446-409a7e24-4c03-4044-87af-d6800b3b1dfc.mp4

Improve effects of debris

---

lua/defaultcomponents.lua

As described in: https://github.com/FAForever/fa/wiki/Performance-and-hash-operations

Reduce hash operations in the shield effects component

---

lua/sim/MarkerUtilities.lua

Closes #4833
Maps the key `Start Location` to `Spawn` to support old code conventions

Add support for `Start Location` marker type

---

effects/Entities/UnitTeleport01/UnitTeleport01_script.lua
effects/Entities/UnitTeleport02/UnitTeleport02_script.lua
effects/Entities/UnitTeleport03/UnitTeleport03_script.lua

Added this to separate PR to not make Jip upset to updating #4579.
This will then make the effects Folder have no flags by the intelisence plugin

Minor Entities Tweaks

---

lua/version.lua

Allows mods to add conditions specifically for this game version, as requested by @Uveso

Bump development version for mods

---

effects/mesh.fx

Some comparison pics featuring Transient Mirth, Funeral Plains and Syrtis Mayor. Before and after, as usual.

Tweak PBR shader to be darker in the shadows

---

lua/sim/NavDatastructures.lua
lua/sim/NavUtils.lua

Minor performance improvements for the navigational heap and navigational utilities.

Minor performance improvements for navigational mesh

---

lua/aibrain.lua
lua/aibrains/base-ai.lua
lua/sim/NavGenerator.lua

Closes #4924 
The relevant functions and fields were missing, likely lost in transition.

Fix bug with campaign pings

---

lua/aeonweapons.lua

Prevents an edge case where the unit can become invulnerable. As the unit enters the claws it now aligns with the orientation it will be dropped into

Fix issues with the colossus 

---

effects/terrain.fx

Add missing terrain shader changes

---

lua/AI/GridBrain.lua

Involves a feature taken from https://github.com/FAForever/fa/pull/4839 .

Add support to keep track of assigned scouts

---

units/UAS0103/UAS0103_unit.bp
units/URS0103/URS0103_unit.bp

Reverting Mass Cost from Previous Patch

---

units/XRB2309/XRB2309_unit.bp

Compiled with the intended Changes but also added a 3 Regen rate to the harms with the hp nerf as it make sense as Cybran is all about the regen on their buildings

Harms Nerf

---

effects/mesh.fx

The fog coloration seems to happen in the engine and for whatever reason it doesn't work with ps_3_0. So we have to revert to ps_2_a

Revert to ps_2_a

---

units/UAB3102/UAB3102_unit.bp
units/UAB3202/UAB3202_unit.bp
units/UEB3102/UEB3102_unit.bp
units/UEB3202/UEB3202_unit.bp
units/URB3102/URB3102_unit.bp
units/URB3202/URB3202_unit.bp
units/XSB3102/XSB3102_unit.bp
units/XSB3202/XSB3202_unit.bp

Sonar Changes

---

units/UAS0102/UAS0102_unit.bp

Shard Adjustment

---

engine/Sim.lua
lua/defaultexplosions.lua
units/UAL0401/UAL0401_Script.lua
units/UEL0401/UEL0401_script.lua
units/URL0402/URL0402_script.lua
units/XRL0403/XRL0403_script.lua

Old Fatboy effects:
https://github.com/FAForever/fa/assets/15778155/6d60975b-5592-43b4-a182-ee1be544ac08
New Fatboy effects:
https://github.com/FAForever/fa/assets/15778155/868f8fbd-5159-499a-b6c0-5acb82aed9e1

Improve the death threads of various experimental units

---

units/UAL0001/UAL0001_script.lua
units/UAL0001/UAL0001_unit.bp

Closes #5014 
Base Range
E/M/BT Cost -30%
Range 30
Advanced Range
E Cost +33%
M/BT  +50%
New Range 35

Split Aeon Gun Range Upgrade

---

lua/aibrains/platoons/platoon-base.lua
lua/defaultunits.lua
lua/sim/Unit.lua

Fixes a bug introduced by #4921 where air units could become immobile 😄

Fix air units being stuck on the air staging platform

---

units/UAA0304/UAA0304_unit.bp
units/UEA0304/UEA0304_unit.bp
units/URA0304/URA0304_unit.bp
units/XSA0304/XSA0304_unit.bp

Reload 5 -> 8 Seconds 
Does not include indicator when bomb is dropped.

Strat Bomber Nerf

---

units/UAA0304/UAA0304_unit.bp
units/UEA0304/UEA0304_unit.bp
units/URA0304/URA0304_unit.bp
units/XSA0304/XSA0304_unit.bp

Completes #5048 
- Mass: 2,1k > 1.9k
- Energy: 144k > 180k
- Build Time: 9.6k > 12k

Strat changes

---

lua/terranprojectiles.lua

With thanks to this forum post:
- https://forum.faforever.com/topic/6198/enable-wasp-projectile-impact-effects-against-air-units

Add missing impact effect for Wasp projectiles

---

units/URS0305/URS0305_unit.bp

Buffed the stealth Radius, and lowered the Energy consumption
Closes #5064

Cybran T3 sonar buff

---

lua/AI/AIBehaviors.lua
lua/AI/Transportutilities.lua
lua/platoon.lua

This PR removes some debugging logs for the AI that might be confusing users that are trying to troubleshoot issues.
While they are useful for AI developers they are not required for functionality.
I have commented out a couple as I would like to retain them for future debugging.

disable AI logs and add debug checks for transport logs.

---

lua/aeonweapons.lua
lua/sim/weapon.lua
units/URL0001/URL0001_script.lua
units/URL0001/URL0001_unit.bp

Closes #5054 and https://github.com/FAForever/fa/issues/5015

Cybran Acu Changes

---

units/UAL0001/UAL0001_unit.bp

fix new aeon upgrade to be removed

---

lua/terranprojectiles.lua

Use alternative unit effect for projectiles of the Wasp

---

units/URL0306/URL0306_unit.bp

Increased Deceiver stealth range by 15%

---

lua/MODS.LUA
lua/system/Blueprints.lua

Updates the documentation found in `MODS.LUA`, including old unimplemented features / bad documentation, new features FAF added, and touches on some of the interoperability with the FAF client.

Update mod information for FAF

---

lua/aibrains/index.lua
lua/simInit.lua

Pre-Patch release validation.
This PR fixes the normal AI loading as the key was set incorrectly for the brain index load. 
It also removes the medium and easy aix variants from the index list as they dont exist to avoid any future confusion.
The easy AI still needs to be fixed before this PR goes in.

Fix normal AI key on index selection. Remove unused entries.

---

lua/AI/GridPresence.lua
lua/AI/GridReclaim.lua
lua/AI/GridRecon.lua
lua/SimCallbacks.lua
lua/aibrains/components/economy.lua
lua/sim/MapUtilities.lua
lua/sim/MarkerUtilities.lua
lua/sim/Profiler.lua

All the introduced (debug) functionality for the AI did not have cheat guards!

Add various cheat guards for introduced debug functionality

---

lua/sim/Unit.lua

Update Naval reclaim

---

units/UEL0001/UEL0001_unit.bp

completes #5095
Regen Rate: 42 > 60
Recharge Time: 175 > 90

Uef bubble shield adjustment

---

projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_proj.bp
projectiles/CIFMissileTactical01/CIFMissileTactical01_proj.bp
projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_proj.bp
projectiles/TIFMissileCruise03/TIFMissileCruise03_proj.bp
projectiles/TIFMissileCruise05/TIFMissileCruise05_proj.bp

Revert "Missile adjustments"

---

lua/system/Blueprints.lua

Completes https://github.com/FAForever/fa/issues/5052

Global vision range buff

---

lua/aibrains/easy-ai.lua
lua/sim/ScenarioUtilities.lua
lua/simInit.lua

With #5092 we introduced a bug where people would no longer be hostile to each other. There's an odd flow for skirmish maps where everyone starts off as enemies and then the teams (as defined in the lobby) are allied up together

Fix a bug with alliances

---

lua/shared/RecallParams.lua

Adjusted accordingly to this discussion:
- https://forum.faforever.com/topic/5608/adjust-recall/58

Adjust recall to require the last three players of a team to agree

---

units/URL0306/URL0306_unit.bp

This reverts commit 36a74eed6b7b0f6a92aee514e79b6b4182d340ed.

Revert "Increased Deceiver stealth range by 15% (#5081)"

---

lua/SimCallbacks.lua
lua/keymap/debugKeyActions.lua
lua/keymap/keydescriptions.lua
lua/sim/NavDebug.lua
lua/sim/NavDebug/DirectionsFrom.lua
lua/sim/NavUtils.lua
lua/ui/game/NavDebug/DirectionsFrom.lua

Adds a small debugging window for the `DirectionsFrom` function from `NavUtils.lua`. The result is visualized using the drawing functions. It allows you to toy with the parameters to view the results
https://github.com/FAForever/fa/assets/15778155/93c430e8-bd3a-46f5-a072-640c28e4048b

Setup for a separate debug window for functions of NavUtils

---

units/UEA0001/UEA0001_unit.bp
units/UEA0003/UEA0003_unit.bp
units/XEA3204/XEA3204_unit.bp

https://discord.com/channels/197033481883222026/1121169759187255398

Allow UEF drones reclaim during patrol/attack-move

---

lua/sim/MapUtilities.lua
units/ZXA0001/ZXA0001_unit.bp

Fixes minor errors introduced by #5169

Fix errors that originate from formatting

---

units/UAA0304/UAA0304_unit.bp
units/UEA0304/UEA0304_unit.bp
units/URA0304/URA0304_unit.bp
units/XSA0304/XSA0304_unit.bp

Mass cost buff

---

units/DAA0206/DAA0206_unit.bp

Mercy Tweeks

---

projectiles/AIFGuidedMissile02/AIFGuidedMissile02_Script.lua
units/DAA0206/DAA0206_unit.bp

Completes #5195
- replaced new mercy projectile with old mercy projectile
- damage increase to mercy still makes it do 600 dmg all together

Mercy undershooting fix

---

projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua
projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_Script.lua
projectiles/TIFMissileCruise03/TIFMissileCruise03_Script.lua
projectiles/TIFMissileCruise05/TIFMissileCruise05_Script.lua

- fixed mml's overshooting when targeting a target that is at a very close range

Close range mml fix

---

lua/system/blueprints-units.lua
lua/ui/game/rangeoverlayparams.lua

This fixes the missing `Interface` field of blueprints and the missing shield radius rings in-game

Fix small hiccups with interface text and shield previews

---

lua/ui/notify/defaultmessages.lua

- Updated the Naming of Regen Aura to the Actual upgrades name

Updating Notify naming

---

lua/SimCallbacks.lua
lua/defaultcomponents.lua

Originates from:
- https://forum.faforever.com/topic/6281/bug-map-doesn-t-expand-on-black-day-mission-x1ca_01

Fix a bug when trying to give unit a veterancy level of 0

---

lua/aibrains/campaign-ai.lua

Originates from:
- https://discord.com/channels/197033481883222026/1128722785364090940/1128722785364090940

Add missing field for campaign AI

---

lua/cybranunits.lua

From Discord:
- https://discord.com/channels/197033481883222026/1124462048764493844
https://github.com/FAForever/fa/assets/15778155/60290c99-4b53-4718-b129-d0179885925f

Fix a bug that allows you to get a refund

---

effects/mesh.fx

I tested it on funeral plains and it works as expected.

Fix shield visibility on land maps

---

units/XSB1202/XSB1202_script.lua

See also the bug report channel on Discord:
- https://discord.com/channels/197033481883222026/1125926692335124500
With thanks to Sladow for reporting the problem

Stop idle animation when upgrading

---

lua/SimCallbacks.lua

There are many ways to break the game when distributing build orders. There are a few good reasons:
- (1) It is **a lot easier** to create many, many orders by using templates or through drag building 
- (2) The order appears to be more expensive then other orders to issue
- (3) The build preview is expensive on your framerate
- (4) The order can't be 'batched' because of the internal implementation in the engine
What matters most is (3), which is caused by (4). A build preview doesn't appear to be rendered in batches by the engine. As a result, every build order creates an unbatched build preview. And we can't batch orders because of (4). Therefore this is a special snowflake: regardless of what happens, we should try to reduce redundancy to a minimum. And by special snowflaking it like …

Add a special snowflake implementation for build orders

---

lua/SimCallbacks.lua

Instead of using a generic solution we manually process the build orders. The reasons are described in #5272 . We now guarantee that there are no duplicate orders being applied. We also guarantee the best use of the fact that the order table and the unit table are ordered to some degree.
To me there is not much more we can do to make this work better.
https://github.com/FAForever/fa/assets/15778155/fff437ba-b80c-44eb-ba8d-37caa74632ec

Additional special snowflaking to mobile builder orders

---

lua/SimCallbacks.lua

We'll be working with batches a lot and this generalizes that concept. The function `ComputeBatchCounts` with `h = 10` and `l = 4` will generate `{3, 3, 2, 2}` which represents the number of units in each batch. The function `PopulateBatch` can then be used to pick a few elements from a larger set.
And a neat benefit is that we can pass them a cache to prevent unnecessary memory allocation. As a result we get efficient code, while it is also easier to read.

Add utility function to work with batches

---

lua/ui/game/commandmode.lua
lua/ui/game/commands/generated-templates-data.lua
lua/ui/game/commands/generated-templates.lua

Feedback originates from [Discord](https://discord.com/channels/197033481883222026/1135896582529757184/1136763874574606396)

Process feedback on alternative capping feature

---

lua/ui/game/commandmode.lua
lua/ui/game/commands/generated-templates-data.lua
lua/ui/game/commands/generated-templates.lua

Useful for the point defense + walls template, for example

Allow for predefined templates that trigger on empty space

---

lua/keymap/keyactions.lua
lua/ui/game/commands/context-based-templates-data.lua
lua/ui/game/commands/context-based-templates.lua

The feature is not referred to as `Context based templates` , which is more fitting than `Generative templates`

Rename the feature and add support for custom factions

---

lua/SimCallbacks.lua

@ChessBerry mentioned that stacking occurred as soon targets would start being destroyed. With this pull request we attempt to change that by reversing the order that the commands are issued to units depending on the batch number. Odd numbers go clockwise, even numbers go counter-clockwise.
Old situation, where you get a lot of 'stacking' into one direction
new situation, where stacking happens less quickly because you help the 'other' direction by destroying the next target too

Improve full redundancy of orders

---

lua/sim/commands/distribute.lua
lua/sim/commands/ring-extractor.lua

Add an MIT license at the top of two recently introduced files.

Add licenses to the top of the file

---

lua/aibrains/platoons/platoon-base.lua
lua/defaultunits.lua
lua/sim/Unit.lua

Disables the intel and maintenance of units that reside in aircraft carriers.

Disable intel of cargo of aircraft carriers

---

effects/terrain.fx

Final tweaks to the terrain shader

---

effects/terrain.fx

You can test the changes using `Auralian - The Core v19`. Also fixes some compression problems with the map, the game somehow interprets the values different and as a result the map looks different too 😄

Document terrain shaders and streamline how they interpret properties

---

lua/EffectTemplates.lua

Re-introduces some fields even though they are dangerous to use. See also https://github.com/FAForever/fa/pull/5353

Re-introduce fields that mods may be missing

---

lua/keymap/keyactions.lua
lua/lazyvar.lua
lua/sim/commands/distribute-queue.lua
lua/ui/dialogs/keybindings.lua
lua/ui/game/commands/context-based-templates.lua
lua/userInit.lua

Improving the Key Bindings menu

---

lua/defaultunits.lua

See also:
- https://forum.faforever.com/topic/6467/no-privacy-for-mex-points
There's `CreateLightParticle` and `CreateLightParticleIntel`, where the last one takes into account intel 😄

Fix light particles through fog and destroying invulnerable props

---

engine/User.lua
lua/keymap/keyactions.lua
lua/keymap/keydescriptions.lua
lua/options/options.lua
lua/ui/game/commandmode.lua
lua/ui/game/hotkeys/capping.lua
lua/ui/help/tooltips.lua

Adds a separate game option to cap extractors with 4 or 8 mass fabricators. The hotkey now ignores the game options.

Add more game options and improve the hotkey

---

lua/AI/Grid.lua
lua/AI/GridPresence.lua
lua/defaultunits.lua
lua/shared/NavGenerator.lua
lua/shared/color.lua
lua/sim/MarkerUtilities/Expansions.lua
lua/sim/NavDatastructures.lua
lua/sim/NavGenerator.lua
lua/sim/NavUtils.lua
lua/system/Blueprints.lua
lua/ui/game/cursor/depth.lua
lua/ui/game/reclaim.lua
lua/ui/lobby/lobby.lua
lua/ui/lobby/trueskill.lua
lua/ui/notify/notify.lua
lua/ui/notify/notifyoverlay.lua
lua/utilities.lua
units/UEL0401/UEL0401_script.lua

Removes some patterns that we applied that are incompatible with LuaJit:
- `^` operator is now equivalent to `math.pow` instead it being a bit operator
- `>>` `<<` and `&` bit operators no longer exist

Improve compatibility with LuaJit implementation

---

lua/keymap/debugKeyActions.lua
lua/keymap/keyactions.lua
lua/keymap/misckeyactions.lua
lua/system/performance.lua
lua/ui/game/tooltip.lua
lua/ui/lobby/ModsManager.lua
lua/ui/lobby/sim-performance-popup.lua

Introduces a debugging / experimental UI for the performance metrics that we gather with #4114

Add performance metric debug window

---

units/UAA0104/UAA0104_unit.bp
units/UEA0104/UEA0104_unit.bp
units/URA0104/URA0104_unit.bp
units/XSA0104/XSA0104_unit.bp

Decrease the MaxAirspeed of all T2 Transports from 14.3 to 13.5

---

init.lua
init_faf.lua
init_fafbeta.lua
init_fafdevelop.lua
init_shared.lua

See also: https://github.com/FAForever/fa/pull/5426

Further improve compatibility with LuaJit implementation

---

units/XSS0103/XSS0103_unit.bp

They are now reliable to hit with beam weapons and have various target bones to make the game feel more immersive

Fix small details of the Seraphim frigate

---

lua/EffectTemplates.lua
lua/cybranprojectiles.lua
units/URS0103/URS0103_unit.bp

Adds better targeting bones that are well within the collision box of the unit.

Fix small details of the Trident Class

---

lua/sim/MarkerUtilities.lua
lua/sim/MarkerUtilities/Expansions.lua

Drat version to generate spawns like expansion markers

---

units/DEA0202/DEA0202_unit.bp

Process balance suggestions on the Janus

---

units/UAB0202/UAB0202_unit.bp
units/UAB0302/UAB0302_unit.bp
units/UEB0202/UEB0202_unit.bp
units/UEB0302/UEB0302_unit.bp
units/URB0202/URB0202_unit.bp
units/URB0302/URB0302_unit.bp
units/XSB0202/XSB0202_unit.bp
units/XSB0302/XSB0302_unit.bp

Process balance suggestions on air factories

---

units/URL0001/URL0001_script.lua

LOG left in URL0001_script.lua, ignore if you meant to leave it in there

LOG left in Cybran ACU enhancement script

---

lua/DefaultUnits/Factory.lua

With thanks to https://github.com/FAForever/fa/issues/5436 we can now efficiently assign some orders to individual units. That removes the need for the global field `RolloffUnitTable`. Instead of re-computing the roll off point upon finishing we instead cache the roll of position in the factory that is building the unit. That removes the need for the global field `RolloffPositionTable`. 
We now roll off the unit the direction it is facing in. There's no separate spin at the end of the build sequence like we had before, which looked bad especially for large units
https://github.com/FAForever/fa/assets/15778155/a6c922d7-b7e8-4527-b419-915e128e6398

Remove global state surrounding roll off for units

---

lua/sim/components-projectile/SemiBallisticComponent.lua
lua/sim/components-projectile/TacticalMissileComponent.lua
projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_Script.lua
projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua

As mentioned in https://github.com/FAForever/fa/pull/5498 , a draft example of how such a range factor can work out in practice
https://github.com/FAForever/fa/assets/15778155/9adefce3-4193-49e8-acda-76e299efb38f

Add a bit of a fudge factor to the arc of tactical missiles

---

lua/sim/NavGenerator.lua

Clarifies what the navigational mesh is checking for when it computes the pathability of a layer.

Clarify what the pathing matrices are checking for

---

lua/sim/DefaultUnits/StructureUnit.lua

Clamps the skirt that we're flattening to the playable area. Fixes bugs as mentioned on the forum:
- https://forum.faforever.com/topic/6583/invisible-wall-appears-on-map-blocks-units

Fix a bug where the map is (partially) turned flat

---

units/UAA0310/UAA0310_script.lua
units/UAA0310/UAA0310_unit.bp
units/UAS0303/UAS0303_script.lua
units/UES0401/UES0401_script.lua
units/URS0303/URS0303_script.lua
units/XSS0303/XSS0303_script.lua

Re-introduces the mobile factory aspect of the CZAR. Still requires a bit of tuning, especially the idea of @BlackYps to have the ability to determine the location of the selection area is useful for the CZAR.

Re-introduce mobile factory to CZAR

---

effects/emitters/seraphim_lancer_missile_exhaust_fxtrail_01_emit.bp
effects/emitters/seraphim_lancer_missile_exhaust_polytrail_01.bp
effects/emitters/seraphim_lancer_missile_hit_01_unit.bp
effects/emitters/seraphim_lancer_missile_hit_02_flat_unit.bp
effects/emitters/seraphim_lancer_missile_hit_02_unit.bp
effects/emitters/seraphim_lancer_missile_hit_04_unit.bp
effects/emitters/seraphim_lancer_missile_hit_06_emit.bp
effects/emitters/water_pie_tactical.bp
effects/emitters/watersplash_tactical.bp
effects/emitters/watertower_tactical.bp
lua/EffectTemplates.lua
lua/seraphimprojectiles.lua
projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_Script.lua
projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_proj.bp
projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_Script.lua
projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_proj.bp
projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_Script.lua
projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_proj.bp
projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_Script.lua
projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_proj.bp
projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_proj.bp
projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_script.lua
projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_proj.bp
projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_script.lua
units/XSL0111/XSL0111_unit.bp

Processes the arcs of the Seraphim tactical missiles.
_More to write later_

Process Seraphim tactical missiles in great detail

---

lua/cybranprojectiles.lua
lua/sim/defaultweapons.lua
lua/sim/projectiles/components/SemiBallisticComponent.lua
lua/sim/projectiles/components/SplitComponent.lua
lua/sim/projectiles/components/TacticalMissileComponent.lua
projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua
projectiles/CIFMissileTactical01/CIFMissileTactical01_proj.bp
projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
projectiles/CIFMissileTactical02/CIFMissileTactical02_proj.bp
projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
projectiles/CIFMissileTactical03/CIFMissileTactical03_proj.bp
projectiles/CIFMissileTacticalSplit01/CIFMissileTacticalSplit01_Script.lua
projectiles/CIFMissileTacticalSplit01/CIFMissileTacticalSplit01_proj.bp
units/URL0111/URL0111_unit.bp

Same as #5525 and #5515 
Improves the effects surrounding the missiles. The (balance-related) statistics are a lot less adjusted. The way missiles split is now different, it is more smooth than before:
https://github.com/FAForever/fa/assets/15778155/f9d79bb8-ad76-4381-96d3-09d375f58c69

Process Cybran missiles in great detail

---

units/UEL0401/UEL0401_unit.bp

**Changes:**
Fatboy: BackUpDistance 15 --> 30
Same reasoning as in #5472.

Fatboy: Increase its BackUpDistance from 15 to 30

---

lua/ui/game/tabs.lua

In-game Menu opening is pretty fast now, but closing it is excruciatingly slow, especially when accidentally opening the menu in heat of the action. This patch changes menu opening and closing speed to time-based (about 0.575 seconds) instead of size-based delay.

Make menu popout-speed faster

---

lua/ui/dialogs/hotstats.lua

For some weird reason the scoreboard performance is significantly better if the bitmaps are stored and accessed through a temporary variable. Also moved the mouse hover information code to start so it is visible without having to wait full graph generation.
Following are scoreboard comparison videos of the same 5min 5vs5 AI game. The graph generation doesn't change much, but UI responsivity is significantly better:
Viewing the embedded 4k videos might not work. Re-encoding them into into 720p with worse quality results in file sizes too large to upload here. They should be viewable when saved using a videoplayer that supports AV1.
Old: `https://github.com/FAForever/fa/assets/5271115/a9fa6464-3288-4d32-9336-e99e82313ded`
https://github.com/FAForever/fa/assets/5271115/a9fa6464-3288-4d32-9336 …

Scoreboard graph optimization and cleanup

---

units/XSL0001/XSL0001_unit.bp

Fixed Transports in the game to not ignore sera's ACU regen field

---

projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_proj.bp

Prevents missiles from killing eachother, like other faction MML (#5203).

Apply `NOSPLASHDAMAGE` category to sera MML missiles.

---

units/UEL0304/UEL0304_unit.bp
units/URL0304/URL0304_unit.bp
units/XSL0304/XSL0304_unit.bp

Double the unpack rate for tech 3 mobile artillery.

Process balance changes on tech 3 mobile artillery

---

units/DAA0206/DAA0206_unit.bp

Increase KTurnDamping of the Mercy so it no longer swaggers across the map like a freshly paid sailor

Fix mercy fishtailing

---

lua/defaultexplosions.lua
lua/sim/units/WallStructureUnit.lua

https://github.com/FAForever/fa/assets/15778155/f8e8f790-4cac-433e-ac17-7dd35be461b4

Simplify the death thread of walls

---

engine/Core/Blueprints/UnitBlueprint.lua
lua/SimCallbacks.lua
lua/defaultcomponents.lua
lua/system/blueprints-units.lua
lua/ui/game/orders.lua
units/UAA0310/UAA0310_script.lua
units/UAS0303/UAS0303_script.lua
units/UES0401/UES0401_script.lua
units/URS0303/URS0303_script.lua
units/XSS0303/XSS0303_script.lua

- Adds the SimCallback and checks for the StatToggle boolean
- Switches AutoDeploy from ScriptBit to StatToggle
- DRYies out the carrier deploy/storage logic to all use an OnStopBuild function from ExternalFactoryComponent (not all external factories have storage, but all factories with storage are external factories)

Adds stat toggle infrastructure and switches AutoDeploy to use it

---

lua/sim/defaultweapons.lua
lua/ui/game/nukelaunchping.lua

Adds IsAlly check before target location info is passed to the UI.

Close NukePing cheat vector

---

lua/aibrains/adaptive-ai.lua
lua/aibrains/medium-ai.lua
lua/aibrains/rush-ai.lua
lua/aibrains/tech-ai.lua
lua/aibrains/turtle-ai.lua
lua/sim/NavUtils.lua

Forgot to include this function with the refactoring of #5579

Fix `GetPositionsInRadius` to use the new format

---

lua/defaultcomponents.lua
lua/sim/Projectile.lua
lua/sim/units/ExternalFactoryUnit.lua
lua/sim/units/components/TransportUnitComponent.lua

As reported on [Discord](https://discord.com/channels/197033481883222026/1168673064406499429)

Fix a bug where factory modules would bug out campaign objectives

---

units/UAL0001/UAL0001_unit.bp
units/UEL0001/UEL0001_unit.bp
units/URL0001/URL0001_unit.bp
units/XSL0001/XSL0001_unit.bp

Closes https://github.com/FAForever/fa/issues/5602

Fix the energy requirements of Overcharge

---

lua/sim/NavDebug.lua
lua/sim/NavDebug/DirectionsFrom.lua
lua/sim/NavUtils.lua

Closes https://github.com/FAForever/fa/issues/4894 and https://github.com/FAForever/fa/issues/4383

Process requests of Relent0r for nav mesh utils

---

lua/sim/NavUtils.lua

Interestingly enough the following is not the same:
```lua
local test = { }
for k = 1, 10 do
test[k] = 1
end
for k = 5, 10 do
test[k] = nil
end
LOG(table.getn(test)) -- 5
```
```lua
local test = { }
for k = 1, 10 do
table.insert(test, 1)
end
for k = 5, 10 do
test[k] = nil
end
LOG(table.getn(test)) -- 10
```

Fix a bug with the navigational mesh

---

units/DAA0206/DAA0206_unit.bp

Increase Mercy damage

---

lua/sim/AdjacencyBuffs.lua

 Reduce the T3 pgen adjacency

---

engine/Core/Blueprints/UnitBlueprint.lua

Update the UnitBluprint.lua file so that the annotation works on Enhancements in the ACU Blueprint files

UnitBluprintAnnotation Work

---

effects/Entities/SBOOhwalliBombEffectController01/SBOOhwalliBombEffectController01_proj.bp
projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_proj.bp
projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_script.lua

https://github.com/FAForever/fa/assets/15778155/950aa288-9463-4f7d-b848-583f7fe9d1fb

Apply primary damage of the Ahwassa after 2.5 seconds

---

lua/sim/score.lua
lua/ui/dialogs/hotstats.lua

Created the previous PR too soon, closed it and couldn't seem to update it after forcing pushing, so this in PR attempt #2.
Highlights the active player's graph in the score screen. This one has Bessima, the green player highlighted:
Also has code cleanups.

UI - score graph player highlight, try #2

---

lua/sim/Unit.lua

Related to https://github.com/FAForever/fa/pull/1241
https://github.com/FAForever/fa/assets/15778155/95d28970-0296-42f7-89c1-c25edbba64ed

Fix the assist / repair focus for factories that are building units

---

effects/water2.fx

I noticed that the sun looked too dim on the water, so I implemented the proper pbr setup and lo and behold, the sun reflection now has a proper punch. An added benefit is that the falloff of the reflection also looks much nicer now.
There is a fallback, so we don't change all the maps in existence. They use the sun to highlight the waves a little, luckily we can easily distinguish the two cases, because for some odd reason the default sun angle is below the horizon.
Before
After:

Water reflection

---

lua/shield.lua

We can fix this by introducing a delay of one tick before we set the mesh of the shield. This is a visual change - functionally the shield is the same.
https://github.com/FAForever/fa/assets/15778155/aa49935a-d9fa-492d-80ab-07e285e042f3

Fix shields warping across the map

---

effects/Entities/BeetleDebris01/BeetleDebris01_proj.bp
effects/Entities/BeetleDebris01/BeetleDebris01_script.lua
lua/EffectTemplates.lua
units/XRL0302/XRL0302_Script.lua
units/XRL0302/XRL0302_unit.bp

Overrides the navigator behavior of the Beetle to try to pass through the target instead of moving up to the target
https://github.com/FAForever/fa/assets/15778155/e3dfc04d-ede5-47f6-8063-f53b3015784f
https://github.com/FAForever/fa/assets/15778155/00bd5d70-4770-4a08-8447-d35b51c4bcbd

Override navigator behavior of the Beetle

---

lua/aibrain.lua
lua/aibrains/base-ai.lua
lua/aibrains/easy-ai.lua
lua/aibrains/managers/base-manager.lua
lua/aibrains/managers/engineer-manager.lua
lua/aibrains/managers/factory-manager.lua
lua/aibrains/managers/structure-manager.lua
lua/aibrains/platoons/platoon-adaptive-silo.lua
lua/aibrains/platoons/platoon-base.lua
lua/aibrains/platoons/platoon-simple-engineer.lua
lua/aibrains/platoons/platoon-simple-structure.lua
lua/sim/BuilderManager.lua
lua/sim/Unit.lua
lua/simInit.lua

The goal is to create a separation of concern between the unit script and scripts related to the AI.

Pass unit events to the brain

---

lua/ui/dialogs/hotstats.lua

Now score UI is visible and useable on all resolutions and UI scale values. Tested on windowed mode on 4k monitor.
There's some minor glitching while in windowed mode and the window is resized, but nothing that cycling to a different score mode and back won't easily fix.
Also fixed a bug in interacting in charts.

Fix score graph scaling

---

projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_script.lua
projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_script.lua
projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_Script.lua
projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua

It was reported on Discord that Billy was missing water targets, so I went to fix that but also found a few other missiles that can't impact water.

Fix Cybran nuke sub and SCU/ACU TML/Billy not impacting water

---

engine/Sim/Projectile.lua
lua/sim/weapons/BareBonesWeapon.lua
lua/sim/weapons/DeathNukeWeapon.lua
lua/sim/weapons/DefaultBeamWeapon.lua
lua/sim/weapons/DefaultProjectileWeapon.lua
lua/sim/weapons/KamikazeWeapon.lua
lua/sim/weapons/OverchargeWeapon.lua
lua/sim/weapons/SCUDeathWeapon.lua

_Continuation of https://github.com/FAForever/fa/pull/5670_

Create separate classes for all base weapons

---

units/UAS0102/UAS0102_unit.bp

**Changes**
SizeZ of the Shard: 1.65 --> 1.75

Fix the Shard being able to evade beam weapons

---

lua/sim/projectiles/aeon/AMissileSerpentineProjectile.lua
lua/sim/projectiles/components/TacticalMissileComponent.lua
projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_script.lua
projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua

Implements the idea that missiles should stop zig zagging as they approach their target from https://github.com/FAForever/fa/pull/5788.

Improve hit ratio of missiles that zig zag

---

engine/Core.lua
lua/sim/Projectile.lua

Logic changes are cherry-picked from #5788, all credits to @lL1l1

Add new track target ground logic

---

lua/ui/game/unitview.lua

Add decimal places for the BuildRate stat in the UI

---

lua/sim/Unit.lua

Reduce the value of wrecks from units on the seabed

---

lua/sim/NukeDamage.lua
lua/sim/Projectile.lua
lua/sim/weapons/cybran/CDFMissileRedirectWeapon01.lua
projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua

As reported [on Discord](https://discord.com/channels/197033481883222026/1199336388261322822) by Amygdala

Fix a bug when the Billy is redirected

---

lua/sim/units/CommandUnit.lua
lua/sim/weapons/OverchargeWeapon.lua
lua/ui/game/orders.lua

Make AutoOC as units stat, that doesn't rely on Sync table magic. ~~Can't actually tell if this one will fix auto oc not working, at least it must show it is turned off.~~ Fixed Auto OC not working too.

More Robust Auto OC toggle

---

lua/system/repr.lua
lua/ui/lobby/aitypes.lua
lua/ui/lobby/data/playerdata.lua
lua/ui/lobby/lobby.lua

Alternative implementation of the rating bit of https://github.com/FAForever/fa/pull/5850

Allow AI to have some definition of rating

---

lua/aibrains/platoons/platoon-adaptive-attack.lua
lua/aibrains/platoons/platoon-adaptive-raid.lua
lua/aibrains/platoons/platoon-simple-raid.lua
lua/sim/NavDebug.lua
lua/sim/NavDebug/GetPositionsInRadius.lua
lua/sim/NavUtils.lua

Continuation of https://github.com/FAForever/fa/pull/5861

Add an alternative, more detailed way to compute positions in radius

---

lua/defaultexplosions.lua

Reduce the scorch mark lifetime of burnt trees down to two minutes

---

lua/keymap/debugKeyActions.lua
lua/keymap/keyactions.lua
lua/shared/Subject.lua
lua/ui/dialogs/connection/ConnectionDialog.lua
lua/ui/dialogs/connection/ConnectionDialogData.lua
lua/ui/dialogs/connection/ConnectionDialogDot.lua
lua/ui/game/gamemain.lua
lua/ui/override/SessionClients.lua

If you do not press the hotkey then it doesn't do anything. Merging this in to make it easier to test with other players.
https://github.com/FAForever/fa/assets/15778155/9e096dff-088c-4833-a19b-89709d70438b

Add a connection matrix dialog

---

lua/defaultantiprojectile.lua

This was reported in the general chat, I can't find it anymore but thanks for reporting it!

Fix Volcano being able to redirect a strategic missile

---

lua/sim/units/StructureUnit.lua

As reported on [Discord](https://discord.com/channels/197033481883222026/1195334371243204608)
https://github.com/FAForever/fa/assets/15778155/83bd4642-bd20-468c-8a12-1f4abfae51ef

Fix losing progress on strategic missile launchers

---

lua/sim/units/SeaUnit.lua
units/UES0103/UES0103_script.lua
units/UES0103/UES0103_unit.bp

Tackles the script related problems in https://github.com/FAForever/fa/issues/5889
https://github.com/FAForever/fa/assets/15778155/a9c7014b-af78-47d6-be96-3509a66a1e38

Improve scripted events of the Thunderhead Class

---

units/URA0304/URA0304_unit.bp

T3 Cybran Strat bomber - ANTIAIRWEAK added

---

units/XEA0306/XEA0306_unit.bp

"WEAKANTIAIR",
"WEAKDIRECTFIRE",
added

T3 UEF Connie Weak AA and DR added

---

units/UAA0104/UAA0104_unit.bp

T2 AEON Transport AA Weak added

---

units/XSA0104/XSA0104_unit.bp

T2 Sera Transport WEAK AA AND DF added

T2 Sera Transport WEAK AA AND DF added

---

units/XRA0305/XRA0305_unit.bp

T3 Cybran Gunship AA weak added

---

units/URA0104/URA0104_unit.bp

Adds WEAKDIRECTFIRE/WEAKANTIAIR to Cybran T2 transport

Adds WEAKDIRECTFIRE/WEAKANTIAIR to Cybran T2 transport

---

effects/emitters/cybran_missile_hit_04_emit.bp
effects/emitters/cybran_missile_hit_05_emit.bp
effects/emitters/cybran_missile_hit_06_emit.bp
lua/EffectTemplates.lua
projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua

https://github.com/FAForever/fa/assets/15778155/8eecf4ce-8a66-43b6-b800-deff63aa0f12

Update the effects of Cybran tactical missiles

---

units/URS0302/URS0302_unit.bp

Evaluate and rework the categories of cybran naval units

---

lua/ui/game/clientutils.lua
lua/ui/game/gamemain.lua

Print chat message when game is paused / unpaused

---

changelog/3802.md
lua/SimCallbacks.lua
lua/sim/Unit.lua
lua/userInit.lua

Introduces basic checks and messages to reduce the overhead of moderators to check reports.

Process moderator requests

---

.github/pull_request_template.md

Template changes to make writing the PR easier by taking up less space in the text editor and giving some guidance for new contributors.
I used this template to write this PR.
This PR is pointed at the [feature/pull-request-template](https://github.com/FAForever/fa/tree/feature/pull-request-template) branch.

PR Template Improvement suggestions

---

changelog/3804.md
lua/version.lua
mod_info.lua

Set up the changelog for future PRs to use.

Setup for game version 3804

---

changelog/3801.md

3801: Minor fixes for the changelog

---

changelog/3806.md
lua/version.lua
mod_info.lua

Initial preparations for the next release.
- Update the version number.
- Create a file for the changelog.

Initial preparations for game version 3806

---

changelog/3808.md
lua/version.lua
mod_info.lua

Initial preparations for the next release.
- Update the version number.
- Create a file for the changelog.

Initial preparations for game version 3808

---

lua/sim/commands/area-reclaim-order.lua

Extension of https://github.com/FAForever/fa/pull/6049 and https://github.com/FAForever/fa/pull/6051. The radius is increased to 4 but the number of additional reclaim orders is limited to 6.
https://github.com/FAForever/fa/assets/15778155/271aebc6-5712-42b5-9909-6d8f4d040d79
Issue reclaim orders and verify the results.

Improve the behavior of area reclaim

---

changelog/3809.md

As per the title. Requires #5874 and #5895 to be merged
@Garanas What do you think about the formatting?

Add two balance-related PRs to the changelog

---

lua/user/prefs.lua

Fixes bugs that were introduced by #5871 . Caching the preference file is significant, but apparently the existing implementation introduces all sorts of buggy behavior.
Start a skirmish game, create a template and then start a new skirmish game in the same game session. The template should now still exist.
Try to change the resolution. The message to verify the changes should now pop up.
It was apparently a greedy change of me 😃 and we should probably hot fix this.

Remove caching of the preference file

---

loc/US/strings_db.lua

Update the description in accordance with #6131.

Update the description of the UEF ACU's Shield Field upgrade

---

changelog/snippets/balance.6140.md

Create a changelog snippet for #6140

---

changelog/snippets/other.6156.md
lua/sim/units/StructureUnit.lua

Mention that it is only called for adjacent structures in the same army.
Put a LOG in the function and notice that it is only called when same-army structures are built adjacent.

Update `OnAdjacentTo` annotation comment

---

changelog/snippets/other.6147.md
effects/water2.fx

There is probably not much to say about this

Improve comments in water2.fx

---

changelog/snippets/fix.6168.md
units/UAS0203/UAS0203_unit.bp
units/UAS0304/UAS0304_unit.bp
units/UES0304/UES0304_unit.bp
units/URS0304/URS0304_unit.bp
units/XAS0204/XAS0204_unit.bp
units/XRS0204/XRS0204_unit.bp

Allow various submarines without deck guns to surface again

---

changelog/snippets/other.6174.md
engine/User.lua
engine/User/CDiscoveryService.lua
engine/User/CLobby.lua
lua/ui/lobby/lobbyComm.lua

Cherry-picks the annotations from #5461 as I do not expect to finish that any time soon. Once merged we can close the other pull request.
There are only annotation changes.

Cherry-pick lobby annotations

---

.github/workflows/changelog.yaml
.github/workflows/wiki-generate-changelogs.yaml
changelog/snippets/combine.sh

An example workflow to update the changelogs in the wiki.
See also: 
- https://github.com/FAForever/fa/pull/6177

Setup to generate the changelogs and auto-update the wiki

---

changelog/snippets/balance.6179.md
units/XSL0202/XSL0202_unit.bp

Improve the microabilty of the ilshy
```
TurnRate: 45 > 90
```

Ilshy Turn Rate Buff

---

.github/workflows/wiki-generate-blueprints.yaml
.github/workflows/wiki-generate-icons.yaml
changelog/snippets/other.6188.md

Extension of #6188 
Fixes various small issues that prevented the action from running. I'm not sure why it was fine in the branch and then not fine once merged. Maybe because it originates from a fork?

Fix small bugs in the wiki generation script

---

lua/SimSyncUtils.lua
lua/UserSync.lua
lua/aibrain.lua

Fixes sound regression introduced in #6143

Fix sound regression

---

changelog/snippets/other.6229.md
engine/Core.lua

There are many examples of MATH_Lerp being used with this override.

Annotate `MATH_Lerp(s, sMin, sMax, a, b)`

---

changelog/snippets/balance.5895.md
changelog/snippets/balance.5901.md
changelog/snippets/balance.6103.md
changelog/snippets/balance.6202.md
changelog/snippets/features.6033.md
changelog/snippets/features.6169.md
changelog/snippets/fix.6028.md
changelog/snippets/fix.6121.md
changelog/snippets/fix.6157.md
changelog/snippets/fix.6159.md
changelog/snippets/fix.6185.md
changelog/snippets/fix.6192.md
changelog/snippets/graphics.6154.md
changelog/snippets/other.5668.md
changelog/snippets/other.6042.md
changelog/snippets/other.6067.md
changelog/snippets/other.6086.md
changelog/snippets/other.6091.md
changelog/snippets/other.6109.md
changelog/snippets/other.6139.md
changelog/snippets/other.6147.md
changelog/snippets/other.6174.md
changelog/snippets/other.6188.md
changelog/snippets/other.6223.md

Various smaller fixes/improvements to the changelog snippets

---

changelog/snippets/fix.6290.md
units/UAL0307/UAL0307_unit.bp

As per this title. Necessary, as its hitbox has been increased in #6227.

Define the Asylum's footprint in its .bp

---

changelog/snippets/other.6316.md
lua/ui/game/worldview.lua

Adds a function that gets the moused over WorldView.
Using the function returns the view as expected.
Will be used by area attack dragger in #6317.

Implement GetMousedOverWorldView

---

changelog/snippets/features.5586.md
lua/options/options.lua
lua/ui/game/hotkeys/context-based-templates.lua
lua/ui/help/tooltips.lua

Reverts FAForever/fa#5586
The pull request in question introduces a bug that prevent people from launching the game. 
In addition, the hooks of functions of another module should not be necessary.

Revert "add option to show user defined templates instead of default onland/onwater templates"

---

lua/sim/Prop.lua
lua/sim/Unit.lua

As requested by the balance team.

Revert the reclaim rate changes

---

docs/_config.yml

Fix The Doc Site Logo & Fav Icon

Fix Site Logo & Site Fav icon

---

.github/workflows/docs-url-check.yaml

URLs tend to become unresponsive as time passes. With this GitHub action we'll be notified of that when URLs in our documentation become unresponsive.

Adds a workflow to automagically verify the URLs in the documentation

---

.github/workflows/docs-url-check.yaml
docs/development-start-here/lua-setup.md
docs/development/setup.md

Automagically verify URLs in documentation

---

.github/workflows/docs-spelling-check.yaml
docs/deployment.md
docs/development-start-here/lua-debugger.md
docs/development-start-here/lua-setup.md
docs/development-start-here/lua-syntax.md

Introduces an action to verify the spelling of our documentation pages.

Add a workflow to check for spelling

---

.github/workflows/docs-spelling-check.yaml
docs/development-start-here/lua-contexts.md

Documents the various Lua contexts that are available in the game.

Add information related to the Lua contexts of the game 

---

docs/README.md
docs/_config_debug.yml
docs/documentation.md

Introduce a debug configuration that allows us to override the properties of the configuration for production. All the properties in the configuration can be read through `{% site.XYZ %}`.

Introduce a debug configuration

---

.github/workflows/deploy-faf.yaml
.github/workflows/deploy-fafbeta.yaml
.github/workflows/deploy-fafdevelop.yaml

A continuation of #6393. Sadly, we need to create a commit here. If we do not do so then the changes do not end up on the deployment branch.

Add a commit to store the changes in the workflow file

---

.github/workflows/deploy-faf.yaml
.github/workflows/deploy-fafbeta.yaml
.github/workflows/deploy-fafdevelop.yaml

Extension of https://github.com/FAForever/fa/pull/6401

Fix the commit hash not being substituted properly

---

docs/_posts/2024-07-07-3810.md

A few important balance changes were missing from `2024-07-07-3810.md` (found here: https://faforever.github.io/fa/changelog/3810). To rectify this, I simply copy and pasted the balance section of `3810.md`.

Update the balance section of `2024-07-07-3810.md` to match that of `3810.md`

---

engine/User/CMauiBitmap.lua

adds doc for `CMauiBitmap:SetColorMask`.

Document CMauiBitmap:SetColorMask

---

changelog/snippets/other.6498.md
units/UEL0001/UEL0001_script.lua

This Pull Request refactors the Enhancement handling logic in the script by replacing the long `if/else` chain with a modular approach where each enhancement has a dedicated function. This change aims to improve code maintainability and readability.
The current implementation stores enhancements in a lengthy `if/else` chain, making it difficult to manage and understand. After discussing four potential approaches for improvement in Discord, we concluded that the existing method (Option 1) is not viable due to the difficulty in maintaining and extending it. Here’s a summary of each option and the reasoning behind our choice:
1. **Current Implementation (if/else chain)**: Difficult to maintain and understand. Not viable.
2. **Enhancement Upgrades Table within Class with Key Lookup**: …

Enhancement Script Change (UEF-ACU)

---

changelog/snippets/other.6438.md
lua/utilities.lua

Fixes a typo from #6438 where I forgot to write the variable names.
Carefully read and made sure it is indeed the correct formula.
The function is not used anywhere as it was added recently.
~~- [ ] Changes are annotated, including comments where useful~~

Fix syntax error in utilities.lua DotP

---

units/UEL0201/UEL0201_unit.bp

Increase damage of Striker by 10

---

units/UEL0201/UEL0201_unit.bp

Reverts FAForever/fa#6540
Risus non fames hendrerit convallis; nisl etiam ex auctor. Hac in pharetra quis praesent vehicula. Integer vulputate id sodales egestas laoreet. Dis vulputate quisque tempor vitae suspendisse platea integer. Volutpat dapibus habitant mauris montes commodo hac sociosqu. Consectetur ex mollis libero volutpat hac quam velit himenaeos. Hac fermentum class dictum, lobortis diam facilisi interdum sit cras. Nunc bibendum lobortis congue dignissim sapien luctus. Praesent maecenas platea curabitur ut pharetra; at quis suspendisse.
Litora nibh interdum class dis posuere purus. Per at amet gravida netus; hac parturient. Semper conubia dictum ante tristique duis senectus. Mus aptent leo leo etiam convallis leo. Pretium imperdiet pulvinar viverra placerat nam imperdiet …

Revert "Increase damage of Striker by 10"

---

changelog/snippets/other.6577.md
engine/User.lua

Annotate `AddBlinkyBox`, now we know what it does!
https://github.com/user-attachments/assets/db36d2e2-657d-4425-979e-a17562054c26

Annotate `AddBlinkyBox`

---

changelog/snippets/other.6598.md
engine/Core/Blueprints/UnitBlueprint.lua
lua/sim/units/AirTransportUnit.lua

Add TransportSpeedReduction to unit BP documentation.
Should've been part of #6309, but it was missed.

Add TransportSpeedReduction to unit BP doc

---

changelog/fix.6547.md
changelog/snippets/sections/other.6458.md
docs/_posts/2024-11-29-3813.md

Removes the misplaced snippet from #6458 and adds it to the appropriate changelog.
~~- [ ] Changes are annotated, including comments where useful~~
~~- [ ] Changes are documented in the changelog for the next game version~~

Fix a misplaced snippet

---

changelog/snippets/performance.6666.md
lua/maui/edit.lua
lua/maui/itemlist.lua
lua/maui/text.lua

Removes duplicated closures in controls.
Game UI is created without errors.

Remove duplicated closures in controls

---

changelog/snippets/fix.6698.md
lua/ui/controls/worldview.lua

Update hover cursor texture only when changed
