lua/WeaponPriorities.lua, lua/sim/CategoryUtils.lua
Investigated weapon priority issues after reports of the advanced targeting priorities mod being broken.
Tested and noticed they worked correctly for certain units (t1 tanks) but not others (acu, experimentals). dug in a bit and saw it must be a difference between the limited category parser and the full category parser.
confirmed by switching them around that the issue was in the parser used, guessing this was an autocomplete typo after splitting up the category parsing into full and limited sections in #4338.
=> Weapon Priority Fix

lua/ui/lobby/changelog.lua
As part of a request of a community member.
=> Make changelog slightly transparent

lua/EffectUtilitiesUEF.lua, lua/ui/game/commandmode.lua
Fixes these issues, where the beams are in the factory. The functions need to wait until the end of the current tick to make sure the unit that they are building is in the correct position.
=> Fix issue with cheat window and UEF build animation

lua/options/options.lua, lua/ui/controls/worldview.lua, lua/ui/game/commandmode.lua
As requested by people - not everyone thought this was as useful. People also often end up thinking they can no longer attack individual units. That isn't correct, you still can like usual - it just appears that you can't anymore.
=> Add toggle to enable / disable always showing splash damage

units/UEL0303/UEL0303_unit.bp, units/URL0303/URL0303_unit.bp, units/XSL0202/XSL0202_unit.bp
If the footprint is undefined it is derived from the collision box. As a consequence, the footprint of Titans, Loyalists and Ilsavohs were pushed from 1x1 to 2x2 by accident. This pull request reverts them back to 1x1.
=> Revert accidental footprint changes to Titan, Loya and Ilsha

lua/ui/lobby/lobbyOptions.lua
#4324
This PR changes the default AIX values from 2.0 to 1.5. It has been noted by many new players that the default values are stupidly difficult and many don't realise they can be changed. Lowering the default values will provide new players an easier time moving from non cheating to cheating AI and will also avoid the experience becoming even worse when we get the AI performing better. 
I opted not to change the default OMNI settings yet as I don't have a meaningful intel improvement for the AI so this would potentially be too much of a negative change should I not get the work completed before the next release.
Start a skirmish lobby with AIX as the AI, set all values to default. Note the default value for the cheat and build multipliers. Start game and confirm that the AI is using …
=> Change default aix multiplier values.

lua/simInit.lua, lua/ui/lobby/lobby.lua
Enables prefetching of the session and the prefetching of unit assets. 
A consequence of prefetching the session is that mods that populate `PreGameData` in the prefs file, like strategic icon mods, require a restart to be updated. The reason for this is simple: the prefs file is not updated until the lobby starts. That happens rarely though, one doesn't switch icon mods that often. 
There is no consequence of prefetching the unit assets, besides less stutters during the game.
=> Prefetch session and unit assets

lua/simInit.lua
We didn't fully understand the behavior and as a result the game would keep loading and loading in the assets. During testing this didn't happen. But during live games some people keep loading and loading (and crash, at roughly the same time) while other people do not.
Alas, it did help with making the game smoother. But we need a better understanding before we can continue.
=> Revert changes to prefetch set

effects/mesh.fx, lua/sim/NavDatastructures.lua, lua/sim/NavGenerator.lua, lua/sim/NavUtils.lua, tests/test_NavDatastructures.lua
Closes #4295 
Main goad of the #4295  was to improve performance of the Heap datastructure, how it went?
Well, I got about ~~11% of performance improvement~~ 60% after @Garanas suggestions, tested using following scenario:
```lua
...
---@param heap NavPathToHeap
local function AddAndPop(heap)
for i = 1, 5000, 1 do
for _ = 1, 4, 1 do
heap:Insert(AsLeaf(math.random()))
end
for _ = 1, 1, 1 do
heap:ExtractMin()
end
end
heap:Clear()
end
...
```
- As suggested in the issue `ExpectedCost` was replaced with `TotalCost`
- `Heapify` and `Rootify` functions in NavDatastructures have been replaced by their iterative versions.
- Adjusted UTs to use `TotalCost` instead of `ExpectedCost`
=> Improve performance of the Heap data structure

lua/AI/AIBuilders/AIDefenseBuilders.lua, lua/AI/AIBuilders/AIEconomicBuilders.lua, lua/AI/AIBuilders/AIFactoryConstructionBuilders.lua, lua/AI/AIBuilders/AIIntelBuilders.lua
This PR replaces strings in the default AI's AvoidCategory and AdjacencyCategory properties from builders to userdata. This saves the AI from having to parse all the strings before using them, decreasing function calls.
**Test setup for the changes**
Run an AI skirmish game and confirm no category errors.
Proof read my category maths
=> Default AI string removal from builders

engine/Core/Blueprints/UnitBlueprint.lua, lua/AI/AIBuilders/AIIntelBuilders.lua, lua/aibrain.lua, lua/defaultunits.lua, lua/editor/UnitCountBuildConditions.lua
@relent0r with regards to our discussion about radar management, I'd take the approach of this pull request.
Roughly speaking it:
- (1) Keeps track of radars at each tech level
- (2) Adds a build condition to check for nearby radars of 1 tech higher
(1) is cheap performance wise as usually a player (and an AI) will not have hundreds of radars. (2) is cheap because once you have an omni somewhere it usually covers the entire map. Meaning the condition will usually only pass for one radar. Except for 20x20 maps, where radars near the edge may also get a green light for an upgrade. Which is what you'd want, as then you carefully expand the radar presence.
Note that (2) should likely be a build condition of some kind, but I'm not familiar enough with those to make that work. I imagine a …
=> Keep track of radar structures

lua/aibrain.lua, lua/platoon.lua
Closes #4411 
This PR is designed for the next major patch release, should not be included in a hotfix.
This PR changes adds an ArmyPool detection to the PlatoonDisband function. It is being put in place to stop units from accidentally disbanding the ArmyPool.
This is a relatively brute force method but any units trying to disband the army pool should not be treated as playing nice. I've added a warning for the AI developer so they will know when one of their units are doing this.
Note : because this sets the bool in the InitializeSkirmishSystems function then this has no impact to Sorian.
Start a skirmish with the default AI. If a units or platoon trys to disband the ArmyPool it will be blocked and a warning will be logged.
From my own testing I saw some interesting results. On a map …
=> add logic for army pool detection and disband blocking

lua/AI/AIBuilders/AIEconomicBuilders.lua
This PR tunes the default AI's power builders and supporting builders.
Add second instance of T1 pgen builder. While technically not correct, the AI has a tendency to assign power jobs to engineers that are not within a viable radius of the base, with only a single instance this can lead to big delays in building a T1 pgen which when approaching a stall can be game ending. So having a second builder gives it redundancy in those situations.
Reintroduce T1 engineer power assist. This was previously disabled and misconfigured. I've configured it correctly so that the engineers will be more responsive once an assisted pgen is completed. Previously they would have a static 60 second assist timer which meant that once the pgen was completed they would sit there for …
=> AI Tuning for early power

units/XEL0209/XEL0209_unit.bp
Adjusted the old way of adding radar and sonar to just adding all `INTELLIGENCE` buildings, this includes stealth gens.  Added t1 factories.
Updates buildables:
=> Allow Sparkys to Build Stealth and T1 Factories

lua/aibrain.lua
This PR fixes a small typo in the path check thread running on the AI that caused an if statement to always return false. From a functionality perspective it wasn't visible as it just meant that the AI would constantly recheck pathing on maps (like Air Wars) with no land or amphibious paths available. Not many maps have this scenario.
**Testing changes**
Testing just requires logging the loop if statement check to make sure the thread wouldn't recheck paths on specific maps.
=> fix typo in path check thread for AI.

lua/AI/AIBaseTemplates/ChallengeExpansion.lua, lua/AI/AIBaseTemplates/ChallengeMain.lua, lua/AI/AIBaseTemplates/NormalMain.lua, lua/AI/AIBaseTemplates/RushExpansionAirFull.lua, lua/AI/AIBaseTemplates/RushExpansionAirSmall.lua, lua/AI/AIBaseTemplates/RushExpansionBalancedFull.lua, lua/AI/AIBaseTemplates/RushExpansionBalancedSmall.lua, lua/AI/AIBaseTemplates/RushExpansionLandFull.lua, lua/AI/AIBaseTemplates/RushExpansionLandSmall.lua, lua/AI/AIBaseTemplates/RushExpansionNaval.lua, lua/AI/AIBaseTemplates/RushMainAir.lua, lua/AI/AIBaseTemplates/RushMainBalanced.lua, lua/AI/AIBaseTemplates/RushMainLand.lua, lua/AI/AIBaseTemplates/RushMainNaval.lua, lua/AI/AIBaseTemplates/RushSetons.lua, lua/AI/AIBaseTemplates/TechExpansion.lua, lua/AI/AIBaseTemplates/TechExpansionSmall.lua, lua/AI/AIBaseTemplates/TechMain.lua, lua/AI/AIBaseTemplates/TechSmall.lua, lua/AI/AIBaseTemplates/TurtleExpansion.lua, lua/AI/AIBaseTemplates/TurtleMain.lua, lua/AI/AIBuilders/AIAirAttackBuilders.lua, lua/AI/AIBuilders/AIEconomicBuilders.lua, lua/AI/AIBuilders/AIFactoryConstructionBuilders.lua, lua/AI/PlatoonTemplates/EngineerPlatoonTemplates.lua, lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua, lua/editor/MiscBuildConditions.lua, lua/editor/UnitCountBuildConditions.lua
This PR tunes the default AI's factory builders and removes the pointless complexity of the original.
Remove some of the factory builder groups and make sure the main factory builder group provides the same functionality. 
Add a minimum factory builder so that on land maps where the AI has pathing to the enemy it will get 4 land factories quicker. This is still checking the factory cap on the base template so certain AI personalities like easy will remain with a low count.
Decrease the mass to factory requirements for the main bases for the T1 phase so the AI will get the minimum factory counts up in the early game rather than having to wait for the mid T2 phase.
Makes changes to some base templates where the number of land factories was too low.
Changes the eco …
=> AI Factory Builder Retune phase 1

lua/AI/AIBehaviors.lua, lua/AI/AIBuilders/AIEconomicBuilders.lua, lua/AI/AIBuilders/AIFactoryConstructionBuilders.lua, lua/aibrain.lua, lua/editor/MiscBuildConditions.lua, lua/editor/UnitCountBuildConditions.lua, lua/sim/EngineerManager.lua, lua/sim/FactoryBuilderManager.lua
This PR contains the following changes.
- Fix issues with forcepathlimit. I shifted this to the MIBC previously without realising it had dependencies on UCBC. Have shifted back.
- Change CDRCompletion function to be no longer forked. The ACU was causing issues with structure completion due to this being forked. I've set this to no longer fork. It will limit the number of the times the acu can be interrupted. But the alternative is alot of extra logic
- Add the IMAP configuration values to the brain. These will be used for ring based imap selection in the future. I didn't realise that I hadn't done this yet.
- Replace the default hydro marker condition with Sorians. This is due to the condition only checking for a marker within a certain distance and not if its …
=> AI Manage Engineer Guard removal, cdr completion, forcepathlimit fix

engine/Core/Blueprints/UnitBlueprint.lua, lua/defaultunits.lua, lua/formations.lua, lua/sim/Unit.lua, lua/sim/defaultweapons.lua, lua/system/blueprints-units.lua, units/UAA0310/UAA0310_script.lua, units/XSL0401/XSL0401_Script.lua
Partially reverts #3678, which originated from #3579. The initial issue description was off, and as a result we were allocating a dozen of new tables that were duplicates on each unit. And as the game progresses, this can easily accumulate into tens of thousands of tables that are just duplicates.
The original idea was to make the tables easier accessible. But now that we have the blueprint stored in the unit, instead of via an engine call back, all the information we were caching is already close in scope.
This pull request removes a lot of redundant table operations, further reducing the memory footprint of a unit.
On top of that, introduces a simple way to retain mod compatibility:
```lua
if next(__active_mods) then
SPEW("Sim mod detected - adding in missing fields to the unit class to …
```
=> Further reduce memory footprint of units

lua/aibrain.lua
This PR refactors the GetEconomyOverTime function so that it returns the same data as previously. When the EconomyMonitor was rewritten this function was never updated as it wasn't used across the default codebase but it was later found that a 3rd party mod used it. Its unknown what others might so I've updated it to return the correct data instead of throwing a nil exception.
**Test setup for changes**
Get something to perform the function call during an AI skirmish game. It will return a table with the AI's current over time metrics based on the original data setup.
=> AI refactor GetEconomyOverTime to work with new EconomyMonitor metrics

lua/AI/AIBuilders/AIEconomicBuilders.lua, lua/AI/AIBuilders/AIExperimentalBuilders.lua
This PR does a small tune on the default AI assist builders. Its goal is to provide a slightly higher economic trigger threshold on the builders so that the AI won't try and dump a bunch of assisting engineers into something (power building is a bit of an exception here) when its already stalling mass. We also re-enable a couple of previously disabled assist builders and keep them on a small timer.
All up this is not a noticeable change but is a way to trying to keep the AI's economy stalling as much in the mid-late game.
There are also some minor changes to experimental platoon formers such as decreasing the priority. For land experimentals it was set to 10,000 which indicates someone trying to fix an unrelated problem with priorities. If testing shows this has …
=> AI Tune assist builders

lua/platoon.lua
This PR changes how the default ReturnToBaseAI function sets its destination. Previously it would return to the base position, which is the center of the base. This causes issues when a platoon returns to base multiple times within quick succession leading to platoons moving closer to the center point. Which in turn will cause pathing issues in the late game within the base and contribute to the classic symptom of AI's units being stuck in the base.
The platoons will now return to the base rally point. As long as the rally point is in the front of the base(there is another PR in that makes this more likely) then units will not traverse through the AI base to get to the return to base position or moving from the base position to where ever they are going.
**How …
=> AI - Change ReturnToBaseAI to use factorymanager rallypoint

lua/AI/AIBuilders/AIAirAttackBuilders.lua, lua/AI/AIBuilders/AILandAttackBuilders.lua, lua/AI/AIBuilders/SorianAirAttackBuilders.lua, lua/AI/AIBuilders/SorianLandAttackBuilders.lua, lua/editor/ThreatBuildConditions.lua
This PR changes how the EnemyThreatGreaterThanValueAtBase functions. Originally if no rings were specified it would default to 10. The map is split into 16 x 16 grids. So 10 rings is 10 grid squares around the position. Which is about 3/4 of any map. This is a bit silly since this is often used for response builders which are only interested in around the AI's base.
It will now lookup the brains dynamic rings value and add one which changes depending on the map. This will suit most maps except maybe 80km.
I've also reconfigured the builders which had static values to either be dynamic or use large numbers when the builder type called for it.
While not the most accurate method to validate enemy threat it is the cheapest. So we'll re-evaluate how effective this is …
=> AI - Set EnemyThreatGreaterThanValueAtBase to use dynamic rings value

lua/sim/MarkerUtilities.lua
Closes #4453
```
INFO:  - Spawn: table: 19880FC8
INFO:  -    Count: 1
INFO:  -    Markers: table: 19880D48
INFO:  -       1: table: 13B58050
INFO:  -          color: ff800080
INFO:  -          name: ARMY_1
INFO:  -          orientation: table: 13B58028
INFO:  -             1: 0
INFO:  -             2: 0
INFO:  -             3: 0
INFO:  -             type: VECTOR3
INFO:  -          position: table: 18B0E280
INFO:  -             1: 178.5
INFO:  -             2: 47.776359558105
INFO:  -             3: 182.5
INFO:  -             type: VECTOR3
INFO:  -          prop: /env/common/props/markers/M_Blank_prop.bp
INFO:  -          type: Blank Marker
```
=> Add 'Spawn' to search for spawn markers that are in use by players

lua/AI/aiattackutilities.lua
This PR removes some bad logic from the GetBestThreatTarget function which the attackforceai uses.
The logic in question created a target acquisition failure loop in the late game. The platoon would try and search for a target. It would get a primary or secondary threat. Then it would check for enemy threat in the positions.
If the enemy was weaker or there was no intel to provide Land/Antisurface threat numbers back then the platoon would deem itself too powerful and ignore the position. Then the platoon would merge into a larger platoon and perform the same check.
It would eventually enter an endless cycle of deeming all other threat unworthy depending on what the enemy was doing and end up with large groups of units bunched up at a base position.
To simplify …
=> AI - Remove IgnoreWeakerTargetsRatio from attackforceai target logic

lua/sim/Unit.lua
Not having the second argument in the terrain type be `true` causes it to destroy any c-objects on the mesh to be destroyed. This includes weapons, thrusters, sliders, and so on. It's an unused feature, but is fully implemented aside from this one typo.
=> Fixed default terrain type skin function

lua/AI/aiutilities.lua, lua/aibrain.lua, lua/sim/FactoryBuilderManager.lua
This PR implements a small utility function for the AI to help it perform a few task.
The ShiftPosition function will lerp towards or away from a position based a distance specified. It will be used for simple position shifts and also for avoiding enemy units when that logic is implemented.
The MapCenterPoint attribute is added to the AI brain so that is can easily query it for position references. This will be used for a few things.
The rallypoint logic change. When a map does not contain any rally point markers currently the AI will pick a random position at 30 units somewhere from the current. When used for rally points it means that it can often be placed in front, behind or to the side of a base. Apart from the extra time spent moving it also means that …
=> AI utility function and rallypoint set change

init.lua, init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua
Apparently reading it non-binary like can change the encoding:
- https://forums.solar2d.com/t/how-to-read-file-in-utf-8-mode/341199
As a result, the preference file could be encoded with ANSI if there are special characters in it. Some mods use the copyright symbol, which can end up in the preference file. As a result, the client would no longer be able to read the preference file properly and it would cause all the issues that people have been experiencing with trying to start a game.
=> Fix encoding issues

lua/AI/AIBuilders/SorianStrategyBuilders.lua, lua/aibrain.lua, lua/editor/SorianBuildConditions.lua, lua/platoon.lua
**Description of the changes**
I realised that the .Result attribute for player brain 'defeat' was changed to .Status and 'Defeat' but none of the AI was updated.
This PR changes the checks to be .Status and 'Defeat'
I'd like someone to sanity check this is correct as we now have other status like recalled etc. It may not be an issue if the 'Defeat' will be the only other status where the game will continue.
=> AI - fix incorrect .Result checks and replace with .Status

lua/ui/lobby/chatarea.lua
Fixes #4480
200% scale
Before:
After:
=> Fix scaling of lobby chat messages

units/UEA0003/UEA0003_unit.bp
`C-D2 "Rover"` produces no resources, so should not have this attribute. The only units that should have it are the ACUs and sACUs.
Closes #4498
=> Remove `NaturalProducer` from `C-D2 "Rover"`

units/XSB3202/XSB3202_unit.bp
Removed ability for a Rebuildbonus as suggested by @haifron by removing.
https://github.com/FAForever/fa/blob/develop/units/XSB3202/XSB3202_unit.bp#L128-L130
Spawn in a Engineer and a Sonar, destroy the sonar and rebuild it in the same spot.
=> Fix: Remove ability for rebuild bonus #4493

units/UAL0001/UAL0001_unit.bp, units/UAL0105/UAL0105_unit.bp, units/UEL0001/UEL0001_unit.bp, units/XSL0001/XSL0001_unit.bp, units/XSL0105/XSL0105_unit.bp, units/XSL0208/XSL0208_unit.bp, units/XSL0309/XSL0309_unit.bp
`NeedToFaceTargetToBuild` defaults to `false` when not set in a bp. These lines are therefore unnecessary.
**Additional Information**
They are only there as these attributes were changed from `true` to `false` in 7f3824270 (september 3 2011) to incorporate features from a mod called "CBFP" (community bug fix patch) to: "make the engineers build faster".
**My testing**
I tested this & it runs fine, and the units' build behaviour is the same as before (which makes sense given only some ACUs even have this line & we clearly know they build the same).
1. spawn each of the units whose bps have been changed:
`UEL0001`, `UAL0105`, `UAL0001`, `XSL0105`, `XSL0208`, `XSL0309`, `XSL0001`
2. Order them to build something behind them
3. They should not (do not) turn around (although the `BuildBone` …
=> Remove redundant lines in engineer blueprints

lua/AI/AIBaseTemplates/NavalExpansionLarge.lua, lua/AI/AIBaseTemplates/RushExpansionNaval.lua, lua/AI/AIBaseTemplates/TurtleExpansion.lua, lua/AI/AIBuilders/AINavalBuilders.lua, lua/AI/AIBuilders/AISeaAttackBuilders.lua, lua/AI/PlatoonTemplates/SeaPlatoonTemplates.lua, lua/AI/aiattackutilities.lua, lua/aibrain.lua, lua/editor/MiscBuildConditions.lua, lua/platoon.lua
This PR retunes some aspects of the AI naval play. 
- Fixes a an errors where the AI would not upgrade beyond T2 if the navalrush ai was selected.
- The AI would use the Turtle expansion base template for naval expansions, naval area markers are now excluded.
- Allows the adaptive AI to use the NavalExpansionLarge base template, previously it would build the naval factory and then do nothing else.
- Decrease factory counts on the expansion builder for T1 Naval so the AI did not ruin its economy.
- Add logic for detecting which mass markers could be hit by frigates and if there are under water mass markers. Happy for someone to help make this better. Its weakness currently is that it will detect a position in water but not understand the water depth so it may …
=> AI Naval tuning

lua/ui/lobby/lobbyOptions.lua
I saw this mentioned here but couldn't find an open issue/pr for the change. https://github.com/FAForever/fa/issues/4324#issuecomment-1304788478
This PR changes the range of selectable aix cheat values to include negative multipliers. 0.5->0.9.
This also required a change to the default selection value as 5 entries are being added to the start of the list. The same default of 1.5 is retained.
This will allow players to choose a harder cheating aix in terms of resources, but lowering their build speed to allow more time for the player to react. Alternatively a player could restrict an aix's resources but retain its build speed.
Open a lobby and observe the default value has retained at 1.5 and now values less than 1.0 are selectable.
Open a skirmish match with aix and observe their …
=> Allow negative aix cheat multipliers

loc/guidelines.md, lua/keymap/keyNames.lua, lua/keymap/keybindResources.md, lua/keymap/properKeyNames.lua
- Added the virtual key (VK) code `DF` to `keyNames.lua` & its name to `properKeyNames.lua`. It's used on [these keyboards](https://kbdlayout.info/features/virtualkeys/VK_OEM_8). Also see [this list of virtual key codes](https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes).
I tested it and now I can bind commands to this key.
The key is the backtick `` ` `` on the UK keyboard layout (and I think it's the exclamation mark `!` on the french keyboard and dash/minus `-` on the spanish one).
- I also added a `keybindResources.md` file to `/lua/keymap` to help anyone in future find out exactly what any VK code refers to, on any keyboard layout.
1. set keyboard layout to UK
2. enter hotkeys menu, and select a keybind option
3.  type `` ` ``
4.  "Backtick" should appear as …
=> Added missing VK code for keybinds

lua/options/options.lua, lua/sim/Prop.lua, lua/ui/game/reclaim.lua
Allows a user to define the batching threshold. Previously this was set to when you can issue reclaim orders, which is about 150.
Based on this suggestion:
- https://forum.faforever.com/topic/5135/i-am-loving-the-new-reclaim-batching-in-2022-10-0/9
=> Allow users to define batching threshold

lua/shared/NavGenerator.lua, lua/sim/NavDebug.lua, lua/sim/NavGenerator.lua, lua/sim/NavUtils.lua
Units tend to get themselves to edge cases quite quickly. As a result a query for a path can easily end up failing because the origin location is not 'valid', even though it technically is valid.
Specifically, this pull requests adds in:
- (1) Neighbors for invalid leaves
- (2) Special utility functions to retrieve grid and leaf
- (3) Further reduction of navigational mesh resolution
In case of (1), a leaf that is invalid does not look for corner elements. As an example, it only searches for:
```text
0|x|0
x| |x
0|x|0
```
While the corners are not considered valid.
=> Improve the retrieval of the (nearest) valid leaf of a position

lua/sim/NavGenerator.lua
Significantly reduces the memory requirements of the navigational mesh when a map has no water.
=> Completely cull amphibious and hover grids on map with no water

lua/sim/Unit.lua, lua/sim/defaultweapons.lua, lua/sim/weapon.lua
Removes three unique trashbags instances for each weapon, and instead references the trashbag of the unit again. This was introduced a few months ago to fix an issue with weapon manipulators being destroyed before the unit is turned into a prop. At the time I was unable to find a better solution. In retrospect, memory-wise it was a poor direction to take.
=> Remove unique trashbags instances of weapons

lua/sim/NavUtils.lua
As per #4555 the navigational mesh tries to look for neighboring leaves if the current leaf is not valid. There was a mistake in that code where it used the position of the leaf, instead of the position provided. It now works better.
=> Fix an edge case at the boundary between two areas

lua/sim/NavGenerator.lua, run_lua_syntax_checker.sh
Slightly decreases the time it takes to generate the navigational mesh by using class constructors that properly pre-allocate the tables and prevent the generic `...` from allocating when creating a class. There is still more room to gain by making a distinction between a node and a leaf. But at the moment there is no such distinction code-wise, hence we'll leave it at this.
The `(min, max)` time before and after applying this pull request.
Open Palms: `(0.431, 0.447)` -> `(0.424 -> 0.435 )`
Seton's Clutch: `(1.40, 1.41)` -> `(1.39, 1.40)`
=> Introduces custom classes to initiate the data structures

lua/sim/NavGenerator.lua
The function responsible is written recursively and can therefore end up in a stack overflow.
=> Temporarily disable always computing the allocated size of navigational mesh

projectiles/ADFOverCharge01/ADFOverCharge01_script.lua, projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua, projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua, projectiles/SDFLightChronatronCannon02/SDFLightChronatronCannon02_script.lua, projectiles/TDFOverCharge01/TDFOverCharge01_script.lua
This could prevent them to be initialized properly.
=> Fix order of execution of overcharge projectiles

lua/defaultunits.lua, lua/sim/Unit.lua, lua/terranunits.lua, projectiles/CIFEMPFluxWarhead02/CIFEMPFluxWarhead02_script.lua, units/UAL0401/UAL0401_Script.lua, units/UEB4203/UEB4203_script.lua, units/UEL0208/UEL0208_script.lua
```
WARNING: Error running OnStartBuild script in Entity uel0208 at 23982f08: ...gramdata\faforever\gamedata\lua.nx5\lua\sim\unit.lua(2862): attempt to call method `GetBlueprint' (a nil value)
...gramdata\faforever\gamedata\lua.nx5\lua\sim\unit.lua(2862): in function `OnStartBuild'
...data\faforever\gamedata\lua.nx5\lua\defaultunits.lua(2273): in function <...data\faforever\gamedata\lua.nx5\lua\defaultunits.lua:2269>
```
=> Fix various issues found during playtesting

units/UEL0103/UEL0103_unit.bp, units/XSL0103/XSL0103_unit.bp
This change was introduced to adjust the total damage done by T1 artilleries at a time when aoe weapons dealt 2 extra damage to break trees. This has been changed since but we forgot to revert this alongside it.
=> Revert damage change of T1 artilleries

units/UAA0310/UAA0310_unit.bp, units/URA0401/URA0401_unit.bp, units/XSA0402/XSA0402_unit.bp
Reduce the death damage of air T4s. Their ability to kill heavily shielded targets by simply dying and hitting them provided the defending player with little counter-play. They still need to deal a considerable amount of damage to not break the immersion of the game but these values will be further reduced if deemed necessary.
=> Reduce the death damage of air T4s

units/UEL0303/UEL0303_unit.bp, units/URL0303/URL0303_Script.lua, units/URL0303/URL0303_unit.bp
Titans:
Decrease HP by 200
Loyalists:
No longer disable weapons while charging, and decrease the time it takes for the charge to kick in (4 -> 3 seconds)
After T3 rebalance Titans with their fast recharging shields became a bit too oppressive and they are currently stronger than loyalists. A small HP nerf should put the unit in the right place while not taking away from its specialty of constantly dashing in and out and letting its shield recharge.
Loyalists' ability has been underwhelming and thus it's getting a well-deserved buff, we hope this will be enough to make mixing in Loyalists in your army in later stages a more viable option instead of being a gimmick that is rarely used.
=> Adjust titans and loyalists

units/UAB2301/UAB2301_unit.bp, units/UEB2301/UEB2301_unit.bp, units/URB2301/URB2301_unit.bp, units/XSB2301/XSB2301_unit.bp
The economy Stats of a lot of units are all over the place currently with ratios between factions being close but not the same for no apparent reason (Take the Sera and Aeon PD which have the same cost but Sera randomly costs 26 more BT). This PR brings them more in line while having minimal impact on the Balance.
=> Normalize Economy stats of T2 PDs

units/UAA0104/UAA0104_unit.bp, units/UEA0104/UEA0104_unit.bp, units/URA0104/URA0104_unit.bp, units/XSA0104/XSA0104_unit.bp, units/XSA0202/XSA0202_unit.bp
T2 transports dealt 25 damage on crash even though the T1 transports dealt 100. With these changes, we also hope to nerf T1 arty drops since now the arties will die if the transport's wreck lands on top of them.
Notha for some reason had 25 crush damage instead of 200 like the other T2 F/B
=> Adjust death damage of t2 air units

lua/aeonweapons.lua, lua/cybranweapons.lua, lua/terranweapons.lua, projectiles/ADFShieldDisruptor01/ADFShieldDisruptor01_script.lua, projectiles/AIFFragmentationSensorShell01/AIFFragmentationSensorShell01_script.lua, projectiles/AIFFragmentationSensorShell02/AIFFragmentationSensorShell02_script.lua, projectiles/AIFMiasmaShell01/AIFMiasmaShell01_script.lua, projectiles/CDFTracker01/CDFTracker01_script.lua
These instances would not call the base class, only to continue passing some new table that ends up being unused. It was likely left over code for this function in [defaultdamage.lua](https://github.com/FAForever/fa/blob/deploy/fafdevelop/lua/sim/DefaultDamage.lua#L82-L103), as that is the only place where a property named `Frequency` is accessed. The full (deprecated) function is the following, used for area damage that scales over time.
```lua
-- SCALABLE RADIUS AREA DOT
-- - Allows for a scalable damage radius that begins with DamageStartRadius and ends
-- - with DamageEndRadius, interpolates between based on frequency and duration.
---@param entity Entity
function ScalableRadiusAreaDoT(entity)
local spec = entity.Spec.Data
-- FIX ME
-- Change this to get position from the entity, once …
```
=> Remove overwritten instances of `CreateProjectileForWeapon`

lua/ui/game/construction.lua, lua/ui/game/selectionsort.lua
Also closes https://github.com/FAForever/fa/issues/4601 . The reset was caused by the option `gui_all_race_templates`, which represents `All Faction Templates`. The sequence was:
- Click structure to build
- Update UI: no templates, so 1 less active tab
- Add templates from all faction templates option
- Update UI: templates, so 1 more active tab
As a result, the construction menu 'changed' from 5 to 4 tabs, and then back from 4 to 5 tabs. Because the number of tabs changed the default tab (which is the highest tech, up to tech 3) was reselected. The code is quite spaghetti, but it was missing the sauce. So to fix it we add an if statement that skips checking for a change in templates.
The 'quick fix' for those that encounter this is to give each faction at least 1 template that you made …
=> Fix reset of construction menu when selecting a structure

units/UAA0304/UAA0304_unit.bp, units/UEA0304/UEA0304_unit.bp, units/URA0304/URA0304_unit.bp, units/XSA0304/XSA0304_unit.bp
Adjusts the elevation from `20` to `14`. All the other units could really use a checkup too, they are all over the place. Some transports have an elevation of around 10, others of around 18. The latter lands slower and is a lot more difficult to hit.
In general I'd say:
- Tech 1 at a height of 10 - 12, with an exception for scouts (maybe 14)
- Tech 2 at a height of 12 - 14
- Tech 3 at a height of 14 - 16, with an exception for scouts (maybe 18)
- Tech 4 is at a height of 16 - 18
But that is for the future.
=> Adjust elevation of strategic bombers to make them easier to hit

lua/EffectUtilities.lua
All adjacency beams currently take energy from what they are adjacent of, instead of providing it to 😄 !
https://user-images.githubusercontent.com/15778155/214690159-a962d71d-993f-41d9-91ae-2db53dd87435.mp4
=> Fix direction of adjacency beams

lua/defaultunits.lua
Previously the orientation was set when the unit starts being built. But when units are spawned in they never get built, and therefore they would not orientate properly. Now structures will always orientate if they are set to do so.
=> Orientate structures to match terrain when created

units/DAA0206/DAA0206_unit.bp
The mercy was allowed to target units on the `Air` layer (i.e flying units) while it was on `Land`/`Water` i.e landed. Now it cannot.
I wasn't able to get it to actually hit an flying unit, but you could give it an order to attack them & it would just cancel the order after taking off, which could lead to players thinking they've given a valid order but they'd misclicked on an air unit.
=> Minor fix to mercy targeting

lua/AI/AIBuilders/AIAirAttackBuilders.lua, lua/defaultcomponents.lua, lua/defaultunits.lua, lua/proptree.lua, lua/sim/Unit.lua, units/UEL0401/UEL0401_unit.bp
An interesting one, every time a unit would: 
- Transition to or from 'Stopping' movement state
- Transition to a new terrain type
- Get beamed up / down from a transport
A unit with treads would:
- Re-allocate the `TreadThreads` table multiple times
- Kill all treads, if they exist
- Allocate new threads, if we need them
And then something like this happens, that constantly triggers the transition events:
https://user-images.githubusercontent.com/15778155/214961016-2da33897-3604-48df-ade9-14eb819cac83.mp4
On top of that, this pull request decreases the time that a splat (a tread mark) exists by tech while increasing the LOD by tech. See also: 
- https://github.com/FAForever/fa/pull/4640/files#diff-4efe2c03fd02522260393e6dde9105da93b49718bc4100b67d194f8b06084c35R34-R46
=> Improve memory management of treads

lua/defaultcomponents.lua, units/URL0104/URL0104_unit.bp
The code no longer checked if the interval was one that makes sense: anything smaller than 1 would cause an infinite loop. It now guarantees that it is at least 1.
Related to:
https://forum.faforever.com/topic/5556/beginning-gameplay-freeze-error-message/4?_=1675201056209
With thanks to @maudlin27
=> Fix infinite loop of treads

lua/aeonweapons.lua
Compensates for the GC's claws working correctly. To accomplish this the claws are changed to not instantly kill units that enter them, now they do 720 damage per second until the unit is killed. The pull velocity remains the same. This results in the gc being slightly better than its original form before the claw change.  All data used to come to this conclusion can can be found [here](https://docs.google.com/spreadsheets/d/1zmevPyRNKlI2gxxqL646FgmVULIta2bRDR_0A4iJCYA/edit?usp=sharing). These numbers have not yet been passed by Tagada and are subject to change. Below are examples of my testing.
https://replay.faforever.com/18584864
=> GC Claw Adjustment

lua/sim/Unit.lua
In some (rare) scenarios will get errors when one of the values is nil
=> Redundancies to errors and effect cleanup

lua/sim/Buff.lua
```
WARNING: Error running lua script: ...gramdata\faforever\gamedata\lua.nx5\lua\sim\buff.lua(190): access to nonexistent global variable buffTable
[C]: in function `error'
...ata\faforever\gamedata\lua.nx5\lua\system\config.lua(55): in function <...ata\faforever\gamedata\lua.nx5\lua\system\config.lua:54>
...gramdata\faforever\gamedata\lua.nx5\lua\sim\buff.lua(190): in function <...gramdata\faforever\gamedata\lua.nx5\lua\sim\buff.lua:186>
```
=> Fix missed replacement

engine/Core/Blueprints/ProjectileBlueprint.lua, engine/Core/Blueprints/UnitBlueprint.lua, lua/SimCallbacks.lua, lua/aibrain.lua, lua/defaultunits.lua, lua/sim/ScenarioUtilities.lua, lua/system/blueprints-lod.lua, lua/tarmacs.lua
This pull request consists of three parts:
- (1) Dynamically computes the LODs of units
- (2) Dynamically determine the LODs of tarmacs of units
- (3) Fix tarmacs switching up when structure starts / stops upgrading
(1) is only partially complete, a second pull request will finalize it. In this pull request we force the re-computation of all LODs of all units. It uses a similar approach to props, as found in: https://github.com/FAForever/fa/pull/3662 . The second pull request will only compute the LOD value of units that have none, after which we remove all the pre-defined cutoffs of units and props. That way mods we do not 'enforce' these rules on mods.
(2) is a visual thing, where previously:
- (a) Cutoff was the same for different types of decals
- (b) Cutoff was the same, regardless …
=> Dynamically compute LODs of units like we do with props

lua/simInit.lua
```
warning: ...ance\mods\rngai\lua\intelmanagement\intelmanager.lua(7): access to nonexistent global variable GetClosestPathNodeInRadiusByLayerRNG
warning: stack traceback:
warning:         [C]: in function `error'
warning:         ...ata\faforever\gamedata\lua.nx5\lua\system\config.lua(55): in function <...ata\faforever\gamedata\lua.nx5\lua\system\config.lua:54>
warning:         ...ance\mods\rngai\lua\intelmanagement\intelmanager.lua(7): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: ?
warning:         ...ata\faforever\gamedata\lua.nx5\lua\system\import.lua(61): in function <...ata\faforever\gamedata\lua.nx5\lua\system\import.lua:41>
warning:         ...ata\faforever\gamedata\lua.nx5\lua\system\import.lua(155): in function `import'
warning: …
```
=> Add more imports to break cycle in import dependencies

lua/sim/Unit.lua
Forgot to remove the actual table that we took so much effort to get rid of with #4576 😄 !
The table is populated, but unused, when (sim) mods are in-game. For some odd reason there are mods (looking at you, SCTA) that thought it was a great idea to manipulate this table directly. If the table doesn't exist then the scripts will crash.
=> Remove the intel disables table, it is no longer used by base game

lua/aibrain.lua, lua/sim/ScenarioUtilities.lua
Add `LOG(string.format("%d with %s for value %s", self.Army, reconType, tostring(val)))` to `OnIntelChange` of the brain class. It constantly triggers for all four intel types throughout the entire game for every unit created or destroyed.
=> Fix vision bug for neutral factions where they see the entire map

engine/Core/Blueprints/UnitBlueprint.lua, lua/defaultunits.lua, units/UAB5101/UAB5101_unit.bp, units/UEB5101/UEB5101_unit.bp, units/URB5101/URB5101_unit.bp, units/XSB5101/XSB5101_unit.bp
A unit now only orientates to the terrain if it wants to flatten the skirt, with the exception of the player-buildable walls. Units are also no longer orientated when they are build on essentially flat ground.
=> Fix terrain alignment issues

lua/options/options.lua, lua/ui/controls/worldview.lua, lua/ui/game/gamemain.lua, lua/ui/game/selection.lua, lua/ui/help/tooltips.lua
I personally preferred alt move to always turn into an attack move order, but I was unaware of side effects that players reported, like when they used alt in combination of a hotkey. Therefore it is now optional
Fixes a bug where the splash damage decals could linger on the map
Fixes a bug with various settings that did not toggle properly
=> Fix lingering decals and add toggle for force alt move

lua/defaultunits.lua, units/UAB2101/UAB2101_unit.bp, units/UEB2101/UEB2101_unit.bp, units/URB2101/URB2101_unit.bp, units/XSB2101/XSB2101_unit.bp
Excludes non-land based structures and the orientation is only not applied when the structure is on perfectly flat ground.
=> Fix issues with terrain alignment of structures

lua/ScenarioFramework.lua, lua/sim/Unit.lua
I suspect this is what could block recall from finishing up, causing the 'look ma, I'm invulnerable' bug when recalling. One should always check if the units still exist after waiting 😄 
Also adds a fix for units being flagged as indestructible to still... being able to get destroyed.
```
WARNING: Error running lua script: ...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(4297): Game object has been destroyed
[C]: in function `SetAmbientSound'
...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(4297): in function `StopUnitAmbientSound'
...a\faforever\gamedata\lua.nx2\lua\effectutilities.lua(1459): in function `DestroyTeleportChargingEffects'
...gramdata\faforever\gamedata\lua.nx2\lua\sim\unit.lua(4864): in function `CleanupTeleportChargeEffects' …
```
=> Add guards for recall

lua/sim/Prop.lua
This was a visual bug, the moment the wreck updates it has the correct value again
=> Fix reclaim values of wrecks

projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
An interesting find: if something has no collision box then it appears to be skipped when a weapon scans for targets.
=> Give the Aloha missile its vulnerability back

lua/ui/game/gamemain.lua
With thanks to Wotan (on Discord) we continue experimenting with the network parameters. In todays episode we force the game to resend packages more often, which should reduce the time it takes for the game to notice a package is lost
=> Adjust network parameters in an attempt to reduce lag

lua/ui/game/commandmode.lua
Closes #4754
The code in question was related to the hard move feature, but is not used in the end. Should not have been merged
=> Fix hot build being reset upon a build order

lua/sim/defaultweapons.lua
The bug was introduced by e297c4adf712b6692cec166db63e2ac65a64a298 , and has been an issue for months now. Updates the annotation of the beam weapon
=> Prevent beam weapons from continuously restarting when ground firing

lua/sim/NavUtils.lua, lua/ui/game/NavGenerator.lua
Closes #4687
It is not a perfect fix, but there are no perfect solutions when you make an approximation that can be as coarse as the navigational mesh at times.
When we try to find the leaf we're on we'll take into account a distance such that we do not end up finding a valid leaf while we're on the other side of a gigantic invalid leaf. See also the issue
Where white means that no label is found
=> Introduce an upper limit in distance when searching for neighbors

lua/sim/Prop.lua
Some cheeky props have no reclaim values and do not originate from a unit, but are 'reclaimable'. We add guards to make sure the reclaim procedure can complete. The gun of an ACU is disabled as it reclaims, and without this guard it would no longer enable again.
Prop in question: `/wreckage/props/Aeon/UAL0202_Wreckage_prop.bp`
=> Fix props with no reclaim values

lua/aeonweapons.lua
This can happen in the edge case where you have a amphibious unit (like a percival, blaze) that is being tractored in but when it is 'crushed' the claw is underwater. Therefore the dummy projectile does not trigger the 'OnImpact' function, as a result the unit remains alive and is invulnerable from that point onwards.
In this particular edge case the unit is just flat out destroyed and leaves no wreckage.
See also: https://replay.faforever.com/19381505
=> Fix tractor beams being able to make units invulnerable

lua/SimCallbacks.lua, lua/defaultunits.lua, lua/sim/NavDebug.lua, lua/sim/NavGenerator.lua, lua/simInit.lua, lua/ui/game/NavGenerator.lua
The nav window now requests the statistics of the current generated navigational mesh. We also fix the order of execution so that the extractors are created _before_ we create the navigational mesh, that way we can take them into account properly 😄 !
=> Fix various issues with the navigational mesh

lua/ui/game/buildmodedata.lua
This is a copy from https://github.com/FAForever/fa/pull/4769 with the correct base
Fixes some issues with buildmode:
- Fixed typo for UEF SACU Intel Jammer-preset
- Added shortkey for T2 & T3 Land, air & naval factories
- Added shortkey for SACU-presets in Quantum Gateways
- Changed shortkey for Engineering stations to 'Q', as it was conflicting with the air factories
- Removed 'dab2102' from T1 Aeon, as that unit doesn't exist.
=> Update build mode

lua/aibrain.lua, lua/editor/MiscBuildConditions.lua
This PR adds a base ai check to the CanPathToCurrentEnemy function that is run during AI initialization.
This is to prevent the navmesh getting loaded when 3rd party AI's are using the default BaseMonitorInitialization thread
=> Add check to prevent canpathtoenemy from running for non baseai

lua/UserSync.lua, lua/ui/game/massfabs.lua, lua/ui/game/recall.lua
Was watching a cast and noticed that the panel sticks around after switching to observer.
=> Hide mass fabricator and recall panel as you switch to observer

lua/maui/window.lua
The windows have opacity / transparency controls. These would also affect the draggers. The window now enforces that the draggers remain invisible (alpha set to 0)
=> Fix lingering bitmap draggers on chat and console window

lua/AI/OpAI/BaseManagerPlatoonThreads.lua
As an example, take the co-op map Red Flag:
```
opai = SeraphimM2SouthBase:AddOpAI('M2_Seraph_Sonar_South',
{
Amount = 1,
KeepAlive = true,
MaxAssist = 1,
Retry = true,
}
)
```
There is no AI defined here, and the manager would throw an error upon importing.
=> Add check whether platoon function is available

lua/UserSync.lua, lua/defaultunits.lua, lua/ui/game/gameresult.lua
Currently the user layer does not know who performed a kill on an ACU.
This information however is not supposed to be hidden, as it is clearly a UI related thing.
This information actually used to be available, until this big change broke this unintentionally:
https://github.com/FAForever/fa/pull/4016
This leads to a side effect, that e.g the Supreme Scoreboard Mod assumes that every kill was a ctrl+k, even if it was a normal kill.
Most of the streamers use this mod, and rely on this information, especially if there is a lot of going on. Like in 8vs8 games.
Using this change the Supreme Scoreboard Mod can also be fixed very easily to show the kills once again correctly.
Please look at the changes and tell me if fits the behavior of existing code.
I basically copied the existing …
=> Forward ACU kills to the user layer

lua/AI/Grid.lua, lua/AI/GridReclaim.lua, lua/aibrain.lua, lua/sim/Prop.lua, lua/simInit.lua, lua/wreckage.lua
Introduces a basic data structure to keep track of reclaim. The data structure mimics the iMAP configuration of the map. 
As reclaim is changed the data structure receives a signal to update the cell. The cell update is deferred by a few ticks to catch any other changes. Every five ticks (0.5 seconds) the data structure updates all changed cells. With four AIs and a lot of fighting on Open Palms the update of cells take less than a millisecond to complete. 
https://user-images.githubusercontent.com/15778155/225286939-ffdbaf06-3513-4096-a80a-7e42a477e688.mp4
A brain can register itself to receive a signal when a cell is updated. Updates are received via:
```lua
---@param self AIBrain
---@param grid AIGridReclaim
---@param cell AIGridReclaimCell
OnReclaimUpdate = function(self, grid, cell) …
```
=> Initial setup for a reclaim tracking system for AIs

effects/mesh.fx
This was forgotten, because the czar uses its own shader instead of the standard Aeon one.
=> Add PBR shader for czar

units/UEB4301/UEB4301_script.lua, units/URB4202/URB4202_script.lua, units/URB4204/URB4204_script.lua, units/URB4205/URB4205_script.lua, units/URB4206/URB4206_script.lua, units/URB4207/URB4207_script.lua, units/XES0205/XES0205_script.lua, units/XSB4202/XSB4202_script.lua, units/XSB4301/XSB4301_script.lua, units/XSL0307/XSL0307_script.lua
#4628 
Refactored following units to use the new  ShieldEffectsComponent:
UEB4301, URB4202, URB4204, URB4205, URB4206, URB4207, XES205, XSB4202, XSB4301
Added bone name as to the cybran shield-gens and UEF-shield boat, so OnShieldEnabled function knows which bone to attach the emitters to.
=> Refactor Shield-Structure/Units to use ShieldEffectsComponent #4628

lua/AI/AIBehaviors.lua, lua/AI/aiattackutilities.lua, lua/AI/aibuildstructures.lua, lua/AI/aiutilities.lua, lua/AI/sorianutilities.lua, lua/defaultexplosions.lua, lua/editor/UnitCountBuildConditions.lua, lua/ui/maputil.lua
closes #4717 
This PR changes some of the vars that were accidentally set as global to locals. The main reason is to avoid concurrent AI from getting incorrect values for various vars when they are running functions.
Test setup for the changes
Confirm that all vars that have been changed to local are valid.
Observe AI games, Sorian is the most impacted AI from the changes. But it impacts the normal AI as well. There are some edge cases where two AI would call functions and have the local vars overwritten by a global in the same file.
=> Change global vars to local where appropriate 

lua/editor/UnitCountBuildConditions.lua
This PR changes fixes an issue detected in the forcepath limit condition. The condition is designed to check how many factories the AI currently has so it can force a limit on maps where you want to limit them based on if the AI can path to the enemy. The issue was that it was not taking into account factories that are currently being built by engineers. So there were cases where the AI would have over the factory limit due to ones currently building but would not know it when building more.
Test setup for the changes
Within the ForcePathLimit funciton in the unitcountbuildconditions.lua file.
Add a log to line 1457 and 1470, the function is designed to break out if its already got more than the unitCount parameter, if it doesn't then it will look at currently …
=> add factory being built to forcepath limit condition.

units/UAB5202/UAB5202_unit.bp, units/UEB5202/UEB5202_unit.bp, units/URB5202/URB5202_unit.bp, units/XSB5202/XSB5202_unit.bp
**Economy:**
Buildtime of all Air Staging Facilities: 450 --> 350
FAF changed the tech level of air staging facilities to tier 1, however their build time remained very high (450), even though at 175 mass they are not particularly expensive. To put this into perspective: A tech 1 land factory costs 240 mass, but a tech 1 engineer still builds it 30 seconds faster than an air staging facility. With these changes, air staging facilities now have a build time to mass cost ratio of 2/1.
=> Air Staging build time changes

lua/system/utils.lua
An assembly implementation is usually faster than one in Lua. Especially when the Lua implementation adds a lot of additional overhead by checking the type 😄
=> Replace `table.getsize` and `table.empty` with assembly alternatives

lua/terranweapons.lua
These units have no unpacking sequence or have no effects that are run during the sequence.
=> Remove dead code from `TerranWeapons.lua`

lua/AI/PlatoonTemplates/EngineerPlatoonTemplates.lua, lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua
Description.
This PR fixes a couple of platoon templates that were accidentally pulling the cybran engineer drone into them.
One of them I have completely removed engineers from as it had a rather silly premise. It expected an engineer to join an attack platoon. Then move to a start location, disband the platoon then have the engineer 'happen' to pick up a start location expansion builder. It had a small chance of succeeding. There are better ways of protecting an engineer that is expanding.
fixes #4844
=> fix platoon former for engineers

lua/aibrains/base-ai.lua, lua/editor/UnitCountBuildConditions.lua, lua/sim/Builder.lua, lua/sim/BuilderManager.lua, lua/sim/EngineerManager.lua, lua/sim/FactoryBuilderManager.lua, lua/sim/PlatoonFormManager.lua, lua/sim/StrategyManager.lua, lua/system/GlobalBuilderTemplate.lua
Improves the annotations of the builder manager and refactors the file to make it more intuitive to understand for new contributors.
The entire flow was undocumented. All functions have correct annotations and additional comments where necessary.
These properties were used by all instances.
These merely clutter the code base
Improve performance of:
=> Annotate and refactor the builder manager of AIs

lua/sim/defaultweapons.lua, lua/system/class.lua
A state was unable to call the correct base class. We introduce a `__base` field to each state so that it can do so. This fixes the bug where the beam of the colossus can linger on after tractoring a unit.
=> Fix state being unable to call the base class

effects/mesh.fx
This makes shadows a bit more prominent for all factions so they better align with the shadows on the terrain, makes Aeon a bit more glowy and more reflective and fiddles with seraphim units.
=> PBR tuning

engine/Sim/Unit.lua, lua/SimUtils.lua, lua/sim/Unit.lua
Relates to: https://github.com/FAForever/FA-Binary-Patches/pull/15
Allows a (strategic) missile launcher to recover the progression of a missile when the unit is gifted.
=> Recover missile progress when gifting a unit

lua/SimCallbacks.lua, lua/sim/NavDebug.lua, lua/sim/NavUtils.lua, lua/ui/game/NavGenerator.lua
Adds ghosting of paths that are created. The feature is only enabled when the corresponding UI window is. The current implementation does **not** work for replays.
=> Add path visualisation for navigational mesh

lua/aibrains/base-ai.lua
fixes #4878
Description.
This PR fixes a logic flaw in the function FindClosestBuilderManagerPosition where it was not validating if the base managers existed before making function calls to them. It also removes the use of a continue statement since its not required.
=> fix logic for getting closest manager.

effects/mesh.fx
Some rocks were using a shader that didn't calculate shadows, making them look odd when they received shadows from units. So I fixed it.
=> Cast shadows on all props

units/DRLK005/DRLK005_unit.bp, units/XRL0003/XRL0003_unit.bp, units/XRL0004/XRL0004_unit.bp, units/XRL0005/XRL0005_unit.bp
gives crab eggs the same buildsortpriority as the unit it is for thanks to evildrew for pointing this out
=> build sort priority of crab eggs

lua/AI/AIBuilders/AIEconomicBuilders.lua
This PR fixes an issue with the default AI reclaim builders that would target hydro carbons when they are not supposed to which would result in the hydros getting reclaimed then rebuilt over and over.
fixes #4887
=> Fix - AI pgen reclaim builders to ignore hydros

effects/mesh.fx
As described in #4696 this is needed for correct water refractions.
=> Add glowMinimum to fix water refractions

lua/sim/NavUtils.lua
This new function does not try to find the nearest valid neighbor. It always returns the label of the leaf that the position is in.
=> Add `GetTerrainLabel` for label at the given position

lua/sim/NavUtils.lua
Partially implements #4894 . All possible error states are part of the annotation system. To sum them up:
- `SystemError`: These should not occur. If this happens then something odd happened
- `NotGenerated`: Navigational mesh is not generated
- `InvalidLayer`: Unknown layer, candidates are: `Land`, `Hover`, `Naval`, `Air` and `Amphibious`
- `OutsideMap`: Point is outside of the map
- `OriginOutsideMap`: Origin is outside of the map
- `OriginUnpathable`: Origin is unpathable
- `DestinationOutsideMap`: Destination is outside of the map
- `DestinationUnpathable`: Destination is unpathable
- `Unpathable`: Path from origin to destination is unpathable (labels do not match)
=> Add simplified error messages

units/URB4206/URB4206_unit.bp, units/URB4207/URB4207_unit.bp
The ED4 & ED5 has the T2 Shield Strategic Icons this changes them to the T3 Variant
=> Fix Cybran T3 Shield Strategic Icons

lua/ui/game/gamemain.lua
A common nuisance among map authors is the flickering of decals. It turns out that there are console commands to influence the clipping behavior. Requires the extended graphics to be enabled.
Current behavior:
https://github.com/FAForever/fa/assets/15778155/1dc54d44-7a8b-40ee-acf3-9c6fbdcea74f
New behavior:
https://github.com/FAForever/fa/assets/15778155/0620efda-2f52-48b1-8cc7-6f4bf184be65
This doesn't work for all maps. As an example: Corona Hourglass is still affected by this behavior
=> Add experimental approach to reduce decal flickering

lua/ui/game/gamemain.lua
We've been working with the default network settings for years and they have been sufficient all that time. This pull request further reduces the changes that we've made.
These numbers are multiplied by the number of clients. In a 12 player game you have 11 open connections, each pushing several kilobytes of data. We reduce the traffic with this pull request, reverting back to a more sane number.
=> Revert some of the network settings

lua/sim/NavGenerator.lua
The air layer is always valid to path. There is no need to compress it. We now skip the compression and just instantiate a leaf. A minor performance improvement.
=> Flatten the air layer instead of compressing it

lua/aibrains/platoons/platoon-base.lua, lua/defaultunits.lua, lua/sim/Unit.lua
Introduces various callbacks and platoon events that were missing, including:
- `OnTransportAttach`
- `OnTransportDetach`
- `OnTransportAborted` 
- `OnTransportOrdered`
- `OnAttachedKilled`
- `OnStartTransportLoading`
- `OnStopTransportLoading` 
Additional, adds the following missing events to the new platoon template:
- `OnStorageChange`
- `OnAddToStorage`
- `OnRemoveFromStorage`
They are all annotated. The comments describe when you can expect the event to trigger.
=> Introduce various transport and carrier callbacks

lua/sim/NavGenerator.lua
Introduces basic support for the playable area of a map. It does not re-generate the navigational mesh when the playable area is changed. The playable area is ignored for a non-skirmish (read: campaign) map. It takes a few assumptions:
- The code assumes the playable area is set immediately in the map script, with no delays. This is usually the case
- The code assumes that the navigational mesh is generated _after_ the map scripts have run. This is the case when you generate the navigational mesh in the recent introduced `OnBeginSession` callback of the brain. See also https://github.com/FAForever/fa/blob/nav-mesh/playable-area/lua/aibrains/easy-ai.lua#L52-L70
As an example of the result:
=> Take into account playable area for skirmish maps

lua/sim/NavUtils.lua
Introduces two new functions to `/lua/sim/navutils.lua`:
- `IsInPlayableArea`
- `IsInBuildableArea`
These can help to determine whether a given point is in the playable area.
=> Add functions to query playable and buildable area

init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua
All init files have logic to prevent sound banks being mounted onto the same path. This logic was supposed to work on the file names, but it did not take into account the folder structure. It was busted, it should be:
```
INFO: /sounds/AEONSelect.xwb
INFO: /sounds/AmbientTest.xwb
INFO: /sounds/CYBRANSelect.xwb
INFO: /sounds/Explosions.xwb
INFO: /sounds/ExplosionsStream.xwb
INFO: /sounds/FMV_BG.xwb
INFO: /sounds/Impacts.xwb
INFO: /sounds/Interface.xwb
INFO: /sounds/Music.xwb
INFO: /sounds/Op_Briefing.xwb
INFO: /sounds/SeraphimSelect.xwb
INFO: /sounds/UAA.xwb
INFO: /sounds/UAADestroy.xwb
INFO: /sounds/UAAWeapon.xwb
INFO: /sounds/UAB.xwb
INFO: /sounds/UAL.xwb
INFO: /sounds/UALDestroy.xwb
INFO: /sounds/UALWeapon.xwb
INFO: /sounds/UAS.xwb
INFO: /sounds/UASDestroy.xwb
INFO: …
```
=> Fix blocking of innocent sound banks

effects/water2.fx
Experimental changes to increase texture quality. In the water shader we can play around with mipmaps to bring more consistent results. It's especially noticeable with the refractions on close to medium zoom levels or when you tilt the camera a lot and observe the sea surface.
For the terrain we can change the texture scale to improve the texture resolution on close zoom levels.
=> Texture quality experiments

effects/water2.fx
Currently the sun reflection can be seen on the entire water surface. This is implausible, because units on the water should block out the sun reflection where the unit reflection is visible. This PR fixes that.
=> Improve sun reflections

engine/Sim/CAiBrain.lua, lua/AI/GridPresence.lua, lua/SimCallbacks.lua, lua/aibrains/easy-ai.lua, lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/sim/NavGenerator.lua, lua/sim/NavUtils.lua, lua/ui/game/GridPresence.lua
Introduces a grid-based data structure that allows an AI to understand his presence on a map. The grid takes into account whether it can path to a given location. The grid uses the `Hover` layer to determine pathability. A small peak:
This is from the perspective of the blue player. Green means it is considered safe. Red means it is considered hostile. Yellow means it is considered contested - it doesn't necessarily belong to either player.
The initial phase of the data structure is based on what mass points have structures on top or around it. This takes into account intel - if the AI is unaware of structures then it won't take them into account. The second phase is a randomized breath first search. The search is randomized to prevent an initial order (top left to bottom right) to …
=> Introduce grid that allows an AI to understand map presence

units/UAS0103/UAS0103_unit.bp, units/URS0103/URS0103_unit.bp
Adjust Aeon and Cybran frig E/BT cost to properly account for the mass correction in #4947.
=> Correcting Aeon and Cybran Frig BT/E Cost

lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/keymap/misckeyactions.lua
This is useful to create comparison pictures across game sessions. As an example:
- https://wiki.faforever.com/en/nvidia-settings
=> Add hotkeys to store the current camera position in the preference file

effects/mesh.fx
The currently used shaders could do with some water effects as well. This implementation is more simple as I have to accomodate for the way the water ramp is applied to the terrain and I don't want to change that for existing maps. But it works well enough.
=> Apply water color to wreckages, props, shield and unit shaders

lua/keymap/debugKeyActions.lua, lua/keymap/keyactions.lua, lua/keymap/keycategories.lua, lua/keymap/keymapper.lua, lua/system/utils.lua
The old style is:
```lua
['escape'] = {action = 'UI_Lua import("/lua/ui/uimain.lua").EscapeHandler()',
category = 'ui', order = 1,},
['pause'] = {action = 'UI_Lua import("/lua/ui/game/tabs.lua").TogglePause()',
category = 'ui', order = 3,},
['cap_frame'] = {action = 'Dump_Frame',
category = 'ui', order = 4,},
```
The new style is:
```lua
['select_upgrading_extractors'] = {
action = 'UI_Lua import("/lua/keymap/misckeyactions.lua").SelectAllUpgradingExtractors()',
category = 'selection',
},
['select_air'] = {
action = 'UI_SelectByCategory +excludeengineers AIR MOBILE',
category = 'selection',
},
```
With that we now have:
- The 'order' field is not used in FAForever, and therefore removed
- The table is visually unpacked, instead of cramped across two lines
When an invalid key is found the …
=> Improves the code style for key actions

effects/emitters/seraphim_regenerative_aura_02_emit.bp
Bug provided by @Spikey84 on [Discord](https://discord.gg/pK94Dk9hNz)
Old situation: effect is hovering over water surface:
New situation: effect is where the unit is
=> Allow Seraphim regeneration effect below water surface

lua/SimCallbacks.lua, lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/keymap/misckeyactions.lua
Removes the following key actions:
- (`recheck_targets_of_weapons`) `Recheck targets of weapons of selected units`
The average unit rechecks the targeting of its weapons regardless.
- (`filter_highest_engineer_and_assist`) `Filter the selection to the most advanced engineer, all other engineers assist that engineer`
The implementation is undesired. It issues orders for the given player. The key action was introduced to help a player quickly select the highest tech engineer from a selection. The alternative is that the player filters the selection using subgroups. Specifically the following combination:
- (1) (`split_engineer_tech`) `Divides a selection over SACUs, tech 3, tech 2 and tech 1 engineers`
- (2) (`split_next`) `Select the next subgroup, or the original selection if there is no …
=> Clean up key actions

effects/terrain.fx
Instead of layering two textures at different scales we now sample at the same scale but with two different rotations. Then we blend between them with a relatively sharp transition to make the visual texture repetition go away.
=> Pbr terrain improvement

lua/sim/Unit.lua, lua/wreckage.lua, units/URL0402/URL0402_script.lua, units/URS0201/URS0201_script.lua, units/XRL0403/XRL0403_script.lua
Reduce the amount of reclaim that units and structures leave behind based on their tech level.
Tech 1 - 0.9 * 0.9 (81%)
Tech 2 - 0.9 * 0.8 (72%)
Tech 3 - 0.9 * 0.7 (63%)
Experimental - 0.9 * 0.6 (54%)
=> Adjust reclaim values of mobile units based on tech tier

lua/RemoteViewing.lua, units/XAB3301/XAB3301_unit.bp
The Quantum Optics would turn itself back on after 10 seconds when turned off by a player. The problem existed since the new intel framework. It wouldn't call the intel enabled / disabled because technically the unit *itself* has no intel
=> Fix the Quantum Optics of being self conscious

lua/terranunits.lua
Closes #4897
The drones are flagged to prevent them from being picked up by weapons scanning for targets when they dock in the Kennel. The flag was not removed when they took off. It is now, allowing weapons to properly engage the drones again
=> Fix Rover drones being untargetable

lua/sim/NavGenerator.lua
We now collect information while we pre-analyze a cell. This allows us to make better decisions to just flatten a cell. As an example: there is no need to analyze a cell for land capabilities when it entirely consists of water. This saves roughly 5% to 10% on the computation time. It has less of an impact on larger maps as the dominant factor on larger maps is the raw quantity of heightmap samples.
Old situation:
```
Alpha Quarantine:
DEBUG: NavGenerator - culled 424 labels
DEBUG: Generated navigational mesh in 5.720215 seconds
DEBUG: Allocated megabytes for navigational mesh: 24.007584
DEBUG: Allocated megabytes for labels: 0.198051
Seton's Clutch - FAF version:
DEBUG: NavGenerator - culled 197 labels
DEBUG: Generated navigational mesh in 2.016846 seconds
DEBUG: Allocated megabytes for …
```
=> Further improve the performance of the navigational mesh

lua/defaultunits.lua, lua/sim/Unit.lua
Closes #5029 and https://github.com/FAForever/fa/issues/3641
With thanks to @Strogoo for his [engine patch](https://github.com/FAForever/FA-Binary-Patches/pull/15) we can now create a work around to allow adjacency to update the costs of producing a missile. Previously this would only happen when constructing a new missile. This is still the case, but through the engine patch we can restore the progression on the construction.
https://github.com/FAForever/fa/assets/15778155/5929ad56-ea53-4000-a58c-9da49086c86d
=> Apply adjacency buffs to missile being built

lua/defaultunits.lua, lua/sim/Unit.lua, units/UAA0310/UAA0310_script.lua, units/XSA0402/XSA0402_script.lua
Closes https://github.com/FAForever/fa/issues/4976
This does not implement the wave as suggested by the issue. It requires quite a bit more work, but this pull request on its own achieves the described effect.
=> Allow death weapons to knock over trees

units/UEL0001/UEL0001_script.lua
Closes #5035 
This provides the same behavior of the Kennel drones to the Shoulder drones: when weapons scan for targets they will be ignored if they are docked. It doesn't prevent them to be targeted entirely. A user can still order an attack command on them
https://github.com/FAForever/fa/assets/15778155/7924a447-9810-4cdd-904e-63c2a8085fbe
=> Prevent weapon scanning of picking up docked shoulder drones

lua/aibrains/base-ai.lua, lua/platoon.lua
This PR removes an unused instance of the PBMGetLocationRadius function in the AI reclaim function.
It also readds the function back to the base-ai brain to stop failures in AI engineer calls that are failing due to it not existing anymore.
=> Readd PBMGetLocationRadius base-ai brain.

lua/sim/BuilderManager.lua
This PR updates the BuilderManager logic to handle the builder delay logic.
Updates the IsPlattonBuildDelayed to no longer update the brain table for the delay. This was causing any builder that passed through the builder manager to update.
It shifts the delay update to the builder return logic statement. This means that only the builder that is selected will be updated.
Testing 
In order to validate this logic you will need to 
add logs to line 299 that will tell you when a builder fails the delay check.
add logs to line 226 and 234 to log when the delay is added.
The delay is triggered when a builder gets triggered multiple times. The goal of the delay is to stop a situation where an engineer gets a job and starts moving to the builder location, then another engineer gets the same job …
=> update IsPlattonDelay logic to work correctly in BuilderManager

lua/ui/game/multifunction.lua
Makes right-clicking the team colors buttons act as a toggle for the team colors options panels instead of always creating a new one.
This is only phase 1 of the planned changes - the window doesn't interact well with saving state or the UI, but that isn't something that will get fixed before the release.
=> Prevent infinite creation of team mode options

lua/AI/AIBaseTemplates/ChallengeMain.lua, lua/AI/AIBaseTemplates/NormalMain.lua, lua/AI/AIBuilders/AIAirAttackBuilders.lua, lua/AI/AIBuilders/AIEconomicBuilders.lua, lua/AI/AIBuilders/AIFactoryConstructionBuilders.lua, lua/AI/Transportutilities.lua, lua/AI/aiattackutilities.lua, lua/AI/aiutilities.lua, lua/aibrains/base-ai.lua, lua/editor/MiscBuildConditions.lua, lua/platoon.lua, lua/sim/FactoryBuilderManager.lua
This PR makes the following changes.
Updates the new transport logic to leverage a flag called TransportRequested when more transports are needed.
Previously it used the default NeedTransports flag but this has been found to cause issues with 3rd party AI that are still using the old transport logic due to a callback updating the flag while the old transport code is in a time wait loop.
I've updated all the corresponding functions and build conditions to match and marked the originals as deprecated.
It also fixes a small issue with the FindNearestBaseIdentifier in the base-ai class so that the position search will still work if no factory manager is available (this was already corrected in the easy-ai but not brought across).
It also makes a small update to the TechMain and TurtleMain AI …
=> Add new TransportRequested flag for 3rd party AI compatiblity support.

lua/defaultunits.lua, lua/sim/Unit.lua, units/UEL0301/UEL0301_script.lua
As described on the forums:
- https://forum.faforever.com/topic/6190/developers-iteration-ii-of-2023/10
Fixes the following error that happens when a unit tries to occupy a slot on a transport that is already occupied:
```
warning: Error running OnStopTransportBeamUp script in Entity url0107 at 2c7a6e08: g:\code\relent0r\fa\lua\system\trashbag.lua(74): attempt to loop over local `self' (a nil value)
g:\code\relent0r\fa\lua\system\trashbag.lua(74): in function <g:\code\relent0r\fa\lua\system\trashbag.lua:66>
g:\code\relent0r\fa\lua\sim\unit.lua(4339): in function <g:\code\relent0r\fa\lua\sim\unit.lua:4336>
[C]: in function `IssueClearCommands'
g:\code\relent0r\fa\lua\sim\unit.lua(4320): in function <g:\code\relent0r\fa\lua\sim\unit.lua:4316>
```
And fixes the problem where …
=> Fix bug with build drones becoming immobile

lua/sim/ScenarioUtilities.lua, lua/sim/VizMarker.lua, units/URS0201/URS0201_script.lua
Intel triggers are relatively expensive. We previously used an intel trigger to reveal civilians, which was adjusted with https://github.com/FAForever/fa/pull/4697. Instead of using an intel trigger we would wait at most a (few) seconds we'd set the alliance to provide vision, wait a few ticks, and reset the alliance. The reset would override the alliance a map script defined. And this happens on for example the map `Tower Defense Survival`.
With this pull request we leave the alliance for what it is and instead we put a vision marker on every unit of a civilian army.
=> Fix an alliance bug with revealing civilians

projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_proj.bp, projectiles/CIFMissileTactical01/CIFMissileTactical01_proj.bp, projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_proj.bp, projectiles/TIFMissileCruise03/TIFMissileCruise03_proj.bp, projectiles/TIFMissileCruise05/TIFMissileCruise05_proj.bp
Issue #5097
@Garanas 
Flapjack
```
Acceleration: 3->2
Max Speed: 12->18
No Change on hitting targets
No changes to how TMD's interact with missile
```
Spearhead:
```
Acceleration: 3->2
Max Speed: 12->18
No Change on hitting targets
No changes to how TMD's interact with missile
```
Evensong:
```
Acceleration: 2->1.5: 
Max Speed: 8->12
have trouble hitting small targets (t1 pd, t1 aa), about 1/4 missiles miss. Fixed by reducing max zigzag value. 5->3 fixes this issue. (didn't include in pull request)
No changes to how TMD's interact with missile
```
Viper
```
acceleration 3->2
Max Speed: 12->18
No Change on hitting targets
Missiles tend to split when hitting aeon tmd bubble significantly more with speed increase.
No difference with any other TMD
```
Ythisah
```
Acceleration 4->3
max speed: …
```
=> Missile adjustments

units/UAL0001/UAL0001_unit.bp, units/URL0001/URL0001_script.lua
Getting the Advanced Quantum Disruptor no longer break upon removal.
Removing the Cloaking Generator now properly removes the Nano regeneration bonus.
=> Fix new enhancement removal

lua/aibrains/base-ai.lua, lua/defaultcomponents.lua, lua/sim/ScenarioUtilities.lua, lua/sim/Unit.lua
We deprecated the `OnUnitKilled` callback thinking that it wasn't being used. But - as with anything after more than 10 years - it was being used by for example the Zone Control maps. The callback is now being called again and you can earn cash in Zone Control 😄
=> Re-introduce the 'OnUnitKilled' callback

lua/sim/FactoryBuilderManager.lua
This PR modifies the AI FactoryFinishBuilding callback in the factory manager to check if a transport pool exist before trying to assign transports that are built into the pool. This is to avoid compatibility issues with 3rd party AI.
=> change FactoryFinishBuilding callback to use transportpool flag

lua/aibrains/base-ai.lua
This PR changes some of the new base-ai callbacks so they will check if the engineer manager exists before trying to call a function against it.
Callback list updated:
OnUnitStopBuilding
OnUnitStartBuilding
OnUnitDestroyed
OnUnitStopBeingBuilt
OnUnitStartBeingBuilt
Test.
Run an AI game and wait until there is a decent number of units. Then kill one of the AI's. Previously you would get callback errors on unit deaths due to the engineer manager having been destroyed. Now you should get none.
=> Update base-ai callbacks to reference engineer manager correctly.

lua/simInit.lua, lua/ui/game/gamemain.lua
There has been a lot of attempts to utilize prefetching. One of them being #4406. For a long time this was very much guess work and we made a few mistakes while experimenting. But lately I found out about the console commands that are related to resources:
- `res_AfterPrefetchDelay`
- `res_PrefetcherActivityDelay` 
- `res_EnablePrefetching`
- `res_SpewLoadSpam` 
And in particular the last one is critical: it tells us _exactly_ when and what the game is loading an asset and how it is loading it! With that we managed to learn one important rule:
- All assets remain in memory as long as **they are in active use**
And that sounds logical, but what matters is that assets are actively unloaded as they are no longer used. The one exception is assets used by emitters: they remain loaded. But …
=> Targeted prefetching of assets

units/XSB1101/XSB1101_unit.bp
Completes #4335
-Removed death animation to make pgn wreckage after death consistent.
=> Update Seraphim T1 pgn wreck

lua/sim/MarkerUtilities.lua, lua/sim/MarkerUtilities/Expansions.lua
Expansion markers were created on occupied spawn locations. As a result the AI could end up expanding... in its own main base 😄 !  Also fixes an issue where some AIs expect certain convention in the marker fields. We're fixing that by just copying the information over
=> Fix a bug with expansion markers and marker field names

lua/AI/aiattackutilities.lua
This PR reverts the default transport functions to use the default pathing. It causes issues with 3rd party AI that are leveraging these functions but not the navmesh.
The default AI leverages a different transport function so these are now purely legacy.
=> revert default transport functions to default pathing functions.

engine/User.lua, lua/ui/controls/filepicker.lua
Specifically the following could happen:
```
INFO:  - directory: C:\Users\Jip\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\replays\
INFO:  - extension: SCFAReplay
INFO:  - files: table: 11812460
INFO:  -    1: table: 11812488
INFO:  -       1: LastGame
INFO:  -       2: temp
INFO:  -    FAF_Az0t: table: 118129B0
INFO:  -       1: LastGame
INFO:  -    Jip: table: 118124B0
INFO:  -       1: LastGame
INFO:  -       2: temp
INFO:  -    a: table: 11812A00
INFO:  -       1: LastGame
INFO:  -    b: table: 11812A28
INFO:  -       1: LastGame
INFO:  -    be: table: 11812A50
INFO:  -       1: LastGame
INFO:  -    jip-dev: table: 11812A78
INFO:  -       1: 210710-0104 Painted Desert
INFO:  -       2: LastGame
INFO: jip
```
The last line represents the name of the profile, …
=> Fix a bug with the file picker being case sensitive

lua/ui/dialogs/score.lua, lua/ui/game/tabs.lua
The rehost functionality has been broken for quite some time. See also: 
- https://github.com/FAForever/fa/issues/2724 
- https://github.com/FAForever/fa/issues/4855. 
This can confuse people, as shown by:
- https://forum.faforever.com/topic/2373/ai-development-guide-and-m27ai-v71-devlog/180
For now we'll disable the rehost functionality. You can still re host manually
=> Disable the rehost functionality

lua/AI/PlatoonTemplates/AirPlatoonTemplates.lua, lua/AI/PlatoonTemplates/EngineerPlatoonNewTemplates.lua, lua/AI/PlatoonTemplates/EngineerPlatoonTemplates.lua, lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua, lua/AI/PlatoonTemplates/SeaPlatoonNewTemplates.lua, lua/AI/PlatoonTemplates/SeaPlatoonTemplates.lua, lua/AI/PlatoonTemplates/StructurePlatoonTemplates.lua, lua/platoon.lua
This PR reverts platoon templates back to where they were prior to the base ai work being started. It then created new template files for any that have been changed and move the new template into them.
This should resolve issues where mods replace existing platoon templates.
To Test : 
Run a game of nomads with AI added. It AI should now start building its base normally.
Issues noticed with nomads specifically.
There is a duplicate of the template called `T2MassHuntersCategory`
The platoon template for T4ExperimentalSea in nomads is invalid and it will overwrite the default which will break the platoon former once one gets built.
=> Fix for mods that replace default platoon template files

units/XSL0305/XSL0305_script.lua, units/XSL0305/XSL0305_unit.bp
Prior to this, the Seraphim sniper bot implemented its sniper mode as a separate weapon on the same turret. Having these two separate weapons meant that, through careful toggling and management of the firing cycles, more damage than was intended could be extracted from both of them at once.
Now, the sniper mode changes the behavior of the main gun instead of enabling the sniper gun. The sniper gun (and dummy weapon) is kept for compatibility as a sort of data container, though the weapon callbacks no longer go through it.
=> Fix sniper bot weapon abuse

lua/cybranunits.lua
From Discord:
- https://discord.com/channels/197033481883222026/1125926692335124500
https://github.com/FAForever/fa/assets/15778155/1c8a5715-8214-4fdb-8d75-3cc727b4566b
With thanks to Sladow for reporting it
=> Fix a bug where the Cybran extractors would not turn off their animation

lua/system/blueprints-ai.lua
This PR corrects a couple of issues with the blueprint threat assignment logic where 
No surface threat was being assigned to indirect fire units.
Surface threat was being applied to nuke weapons.
The logic is support to provide economic threat to things like static T3 artillery and Nukes etc so that AI would understand that they are not a direct risk to units but are valuable to target. This is used by detecting the weapon.ArtilleryShieldBlocks attribute on unit weapons.
The consequence of this is that T1/T3 mobile artillery and T2 MML's get no surface threat assigned to them. This makes them invisible from the AI's threat perspective. Which will lead to things like an ACU thinking it can attack a infinite number of T1 artillery with no risk, or not considering T2 MML a risk to its base …
=> AI - Fix no threat being assigning to mobile indirect fire units

lua/aibrain.lua
Originates from this forum post
- https://forum.faforever.com/topic/6302/don-t-destroy-all-units-upon-recall
All units now remain alive for 10 additional seconds. This is long enough to preserve the units at the end of a regular setup while still allowing units to be destroyed eventually for unusual setups such as FFA.
=> Wait 10 seconds before killing remaining units after recall

lua/SimCallbacks.lua, lua/keymap/keyactions.lua, lua/keymap/keycategories.lua, lua/keymap/keydescriptions.lua, lua/keymap/misckeyactions.lua
With https://github.com/FAForever/fa/pull/4994 we removed two hotkeys. We're returning one of them: the ability to quickly select the highest tech and have everything else assist one of the high tech engineers.
Includes a suggestion of @ChessBerry to select all the high tech engineers, instead of just one
=> Re-introduce a hotkey that people were using a lot

units/XSS0103/XSS0103_unit.bp
**Shleo AA AutoGun**
Damage 2 --> 3
RateOfFire 3 --> 2
The DPS is identical, but the weapon's impact on performance is reduced greatly. Visually, there is very little difference.
Closes #5239
=> Reduce the performance impact of the Seraphim frigate's AA solution

effects/emitters/X1Mercy_cloud_emit.bp, projectiles/AIFGuidedMissile01/AIFGuidedMissile01_Script.lua, projectiles/AIFGuidedMissile01/AIFGuidedMissile01_proj.bp, projectiles/AIFGuidedMissile02/AIFGuidedMissile02_Script.lua, projectiles/AIFGuidedMissile02/AIFGuidedMissile02_proj.bp, units/DAA0206/DAA0206_unit.bp
The effect is now well visible when zoomed out. It creates less particles. The projectiles of the Mercy are immune to its own splash damage, and the projectiles no longer hit _exactly_ where you aimed, but instead scattered a little bit as you'd expect. And last but not least: the unit now does the intended damage
https://github.com/FAForever/fa/assets/15778155/69e3a5c8-233c-41b3-b66b-892b9ad62f3e
=> Fix issues with the Mercy

lua/SimCallbacks.lua
The order of the `units` array that we receive in a sim callback depends on the `EntityId` of a unit. For synthetic cases this order is well-defined, but for the average normal use case it is far from it. Therefore we sort the units based on distance to the first reliable point that we can find. 
Note: the bombers in the video are out of fuel 😄 
https://github.com/FAForever/fa/assets/15778155/6b1ecc99-e367-4ea8-a6a0-4eb8c46fd93a
=> Give units a sense of order when distributing orders

lua/SimCallbacks.lua
The complexity of the function is based on the number of orders in a group. If `k` is the number of orders in a group then the orders we end up creating is `O(k^2)` when we do batching. Eventually all orders that aim at entities will use batching. The average user is impeccable at clicking. But those that are not may create duplicated orders where they click an attack order on the same unit multiple times. Given the complexity this can create a lot of unintended orders. Therefore we try and filter them out.
=> Cull duplicated orders in groups of orders

lua/defaultcomponents.lua
Bug report originates from Discord:
- https://discord.com/channels/197033481883222026/1133373766051836035
See also the Cybran ACU at around minute 13:40:
- https://youtu.be/e6FYy2XGSo4?t=818
The work progress remains untouched when recharging intel when there is a work item. Work items are populated when an enhancement starts and cleared when an enhancement stops.
=> Prevent intel from hijacking the progress bar during an enhancement

lua/SimCallbacks.lua, lua/sim/Unit.lua
Using the generalizations provided in #5278 we can now more easily batch other order types. This drastically reduces the number of orders we issue.
A concern of @Strogoo was that the batching of a move order would cause the units to 'pause' before moving, like when you do as a player when you click a move order. This doesn't happen to be the case. Units are also not moving in formation, they still all want to traverse to the same location (where the order is). Therefore the result is the same, but with drastically less orders 😄 !
Another interesting find is that even though the table that `GetEntityById` returns contains only an engine reference, we can still run entity functions. One such function is being able to retrieve the position of the entity. We use the position to give a sense …
=> Add batching with or without full redundancy for more orders

lua/formations.lua, units/DRLK001/DRLK001_unit.bp, units/DSLK004/DSLK004_unit.bp
Manually adds the `WEAKDIRECTIRE` category to the Bouncer and the Lightning tank, and uses the category to exclude units from the `DIRECTFIRE` category when computing the formation of a unit.
=> Fix tech 3 mobile anti air being at the front of a formation

lua/AI/OpAI/BaseManagerPlatoonThreads.lua
Adds platoon form callbacks for campaign conditional builds, those are used for single units like experimentals or sonars that needs to be built by engineers.
Callback can be defined as a function or table with path and function name. (it's the same as for OpAI)
Example of how to use it:
```LUA
opai = M1RhizaBase:AddOpAI('M1_Sonar',
{
Amount = 1,
FormCallbacks = {
Test1,
{'/maps/X1CA_Coop_003/X1CA_Coop_003_m1rhizaai.lua', 'Test2'},
},
KeepAlive = true,
MaxAssist = 1,
Retry = true,
}
)
```
=> Add platoon form callbacks for conditional builds

lua/ui/game/commandmode.lua
This change got pushed into the release branch by accident when releasing the latest hotfix. In general, this particular cap wasn't experienced as being useful. It is also mentioned to be a noob trap.
We remove it for now so that we have the old behavior here again. The next hotfix we may introduce it, but with the ability to toggle it off.
=> Remove ability to cap air factories

lua/sim/Unit.lua
Add a guard to check whether it is an entity. 
```
WARNING: Error running lua script: ...gramdata\faforever\gamedata\lua.nx5\lua\sim\unit.lua(4774): Expected a game object. (Did you call with '.' instead of ':'?)
[C]: in function `GetPositionXYZ'
...gramdata\faforever\gamedata\lua.nx5\lua\sim\unit.lua(4774): in function `GetCommandQueue'
...nder forged alliance\mods\m28ai\lua\ai\m28orders.lua(171): in function `UpdateRecordedOrders'
```
=> Check whether the target is at least an entity

engine/Sim/Entity.lua, lua/SimCallbacks.lua, lua/sim/Unit.lua
Adds missing annotations to the unit command queue. Updates the type of `EntityId` which is always a string, even though it looks like a number.
=> Add annotations for the command queue

lua/defaultcollisionbeams.lua, units/XSL0402/XSL0402_script.lua
The bug that we fix here is that the Ythotha storm is rather calm when there are only allied or no units around it. It would essentially only attack hostile units. The bug was introduced by https://github.com/FAForever/fa/pull/4863
Because of states the actual hierarchy is not always processed. The functions `OnGotTarget` and `OnLostTarget` are prime candidates for that, so are various states.  In #4863, we fixed that beams would linger on by creating a way to execute the actual hierarchy. But for beam weapons this means that it ends up calling `OnLostTarget` of the default projectile weapon, which ends up returning the weapon to the idle state. And in the idle state the beam is removed again.
An allied unit, or a patch of ground, is considered to be a target it immediately loses. And …
=> Fix the Ythotha storm ignoring allies and empty space

lua/SimUtils.lua, lua/defaultunits.lua
Closes #5293 
One reference in https://github.com/FAForever/fa/pull/4820 was not taken into account. Structures that are gifted are now properly orientated
=> Fix orientation of a unit after being gifted

lua/keymap/keydescriptions.lua, lua/sim/Unit.lua
Closes #3832
Engineers that are paused stop everything, except reclaiming. Reclaiming is now 'stopped' too. It allows you to pause the flow of resources without cancelling the command queue.
With thanks to @Strogoo for https://github.com/FAForever/FA-Binary-Patches/pull/19
=> Toggle reclaim effects when units are (un)paused

effects/terrain.fx
Reintroduces the scale of the upper albedo as a switch for which shader to use. To my understanding the AlbedoTile variables basically store how often the texture is supposed to show up on the map. If we check for < 1.0 that means the texture would not even fit on the map. Hopefully nobody set his texture scales to these nonsensical values, so we don't break any existing maps. I am pretty confident in this, because in the ozonex editor you would have to set the scale to greater than 256 and the editor doesn't allow this.
This different value in the editor is because the scale in the editor is basically "how big should your texture be in ogrids"
I am not sure if I agree with the addition of the Terrain001NormalsPS. Yes, it makes the layer masks more consistent, but it prevents us from …
=> Reintroduce upper albedo scale as shader switch

effects/terrain.fx
This change got lost when merging the map shader PRs.
If we enable our alternative water absorption calculations we don't necessarily want to change the decal lighting calculations to switch to the PBR workflow. This could break specular reflections on maps that e.g. use the Terrain003 shader.
Inside of CalculateLighting we still check for the experimental shader switch to change the water color calculations if necessary.
=> Only switch the water calculations

lua/SimCallbacks.lua, lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/keymap/misckeyactions.lua, lua/sim/commands/orders-distribute.lua
The default distribute orders hotkey now takes the command queue of the unit that is nearest to the mouse location. This allows you (as a player) to have some control over what queue is being distributed.
Introduces a new hotkey that allows you to distribute the queue of the unit you're hovering over.
https://github.com/FAForever/fa/assets/15778155/7c8374aa-7f78-4c2c-bf98-afbd8471687f
=> Give more control over what orders end up being distributed

lua/sim/NavGenerator.lua
Fixes issue where navmesh wouldnt generate properly for non-square maps, like M2 of the Seraphim campaign
Previously the navigational mesh would compress locations based on the map size, but was only taking the x map size.  On a rectangular map where x is smaller than y (i.e. the actual map size, not just the playable area), this would lead to labels being generated for only part of the map.
The following is what the land grid looked like on M2 of the Seraphim campaign (which is a rectangular map):
This is the result after this change on the same map/replay:
Testing on a couple of other maps (using different colouring for different plateaus) it still looks ok.
#
One issue to note on dual gap is it's still seeing locations outside the playable area as pathable (I'd thought the issue had …
=> Navigational mesh - Rectangle maps

units/UAS0303/UAS0303_unit.bp, units/UEL0401/UEL0401_unit.bp, units/UES0401/UES0401_unit.bp, units/URS0303/URS0303_unit.bp, units/XSS0303/XSS0303_unit.bp
Reduces the build rate of tech 3 carriers to match the build rate of a tech 3 air factory. Reduces the build rate of the Atlantis to be 150% of the build rate of a tech 3 air factory. Reduces the build rate of the Fatboy to be 150% of the build rate of a tech 3 land factory. The original build rates were a bit out of proportion now that those same units can navigate and build at the same time.
`uas0303: 180 -> 120`
`urs0303: 180 -> 120`
`uxs0303: 180 -> 120`
`ues0401: 240-> 180`
`uel0401: 180 -> 135`
=> Reduce build rates of mobile factories to match regular factories

units/ZXA0002/ZXA0002_unit.bp
`STRUCTURE` category was messing with the AI.
`MOBILEFACTORY` is now obsolete, since `MOBILE * FACTORY` does the magic
It goes with https://github.com/FAForever/faf-coop-maps/pull/416
=> Change external factory categories to fix AI

engine/Sim/Unit.lua, units/UAS0401/UAS0401_script.lua
The roll off order was given in a thread, which runs at the end of the current tick. By then the factory rally point queue is already applied to the unit
=> Fix the roll off order for the Tempest

lua/defaultexplosions.lua, units/XSB1103/XSB1103_unit.bp, units/XSB1202/XSB1202_unit.bp, units/XSB1302/XSB1302_script.lua, units/XSB1302/XSB1302_unit.bp
In general speed up the (generic) death animations of structures. Removes the death animation of Seraphim extractors. That way all extractors that are killed are turned into a wreck at a similar (or the same) rate.
A consequence is that the wreck may contain flying / hovering parts. But it is barely noticeable from the 'usual' camera angle and if you do turn the camera then just remind yourself that wrecks of hover units are flying / hovering too 😃
=> Speed up death animations of structures

lua/keymap/keyactions.lua, lua/keymap/keymapper.lua, lua/ui/dialogs/keybindings.lua
Add the ability to attach a URL that navigates to the [FAForever](https://wiki.faforever.com/en/home) wiki. As an example: 
- https://wiki.faforever.com/en/Play/Game/Hotkeys/OrdersQueueManipulation
=> Introduce URLs to the FAForever wiki to explain hotkeys

projectiles/ADFQuadLaserLight01/ADFQuadLaserLight01_proj.bp, units/XAA0305/XAA0305_unit.bp
**Changes:**
Added a slight amount of homing to the Restorer's air to ground weapon
MuzzleVelocity 40 --> 35 to prevent the unit from missing low height units
=> Restorer: Fix, so it no longer misses low height units

projectiles/SDFHeavyPhasicAutogun02/SDFHeavyPhasicAutogun02_proj.bp, units/XSA0203/XSA0203_unit.bp
**Changes:**
Added a slight amount of homing to the Vulthoo
MuzzleVelocity 40 --> 35 to prevent the unit from missing low height units
=> Vulthoo: Fix, so it no longer misses low height units

projectiles/CDFLaserDisintegrator04/CDFLaserDisintegrator04_proj.bp, units/XRA0305/XRA0305_unit.bp
**Changes:**
Added a slight amount of homing to the Wailer's air to ground weapon
MuzzleVelocity 40 --> 35 to prevent the unit from missing low height units
=> Wailer: Fix, so it no longer misses low height units

projectiles/TDFPlasmaHeavy02/TDFPlasmaHeavy02_proj.bp, units/UEA0305/UEA0305_unit.bp
**Changes:**
Added a slight amount of homing to the Broadsword's and Continental's air to ground weapons
MuzzleVelocity 40 --> 35 to prevent the unit from missing low height units (Broadsword only)
=> Broadsword and Continental: Fix, so they no longer miss low height units 

units/XRA0105/XRA0105_unit.bp
**Changes**
MuzzleVelocity 55 --> 35 
High values make units miss/shoot through low height units. It is especially bad with the Jester, it misses a Fervor more than it manages to hit it.
Pointed at fafdevelop, as it is relatively urgent and has little implications balance wise (it has homing).
=> Jester: Fix, so it no longer misses low height units

units/UAS0102/UAS0102_unit.bp
The Shard had a very spread out formation for a unit of its size, this change addresses this and enables it to deal more concentrated DPS when used in groups.
=> Tighter formation for the Shard

projectiles/TDFRiot01/TDFRiot01_proj.bp, units/UEA0203/UEA0203_unit.bp
**Changes:**
Added a slight amount of homing to the Stinger and C14 Star Lifter
MuzzleVelocity 40 --> 35 to prevent the unit from missing low height units (Stinger only)
Health = 880 --> 920 (Stinger only)
Tries to fix the Stinger (and the C14 Star Lifter) missing units it really shouldn't miss. It also gains a slight buff to its hit points in line with its faction's theme.
=> Stinger and C14 Star Lifter: Fix, so they no longer miss low height units

lua/ui/game/selection.lua
As reported on [Discord](https://discord.com/channels/197033481883222026/1140812102110556260). Structures that upgrade now keep their original control groups.
=> Restore control groups of upgrading structures

effects/terrain.fx
One thechnique is still using ps_3_0, which is unnecessary and possibly increasing loading times, so we fix that
=> Downgrade ps_3_0 shader

effects/water2.fx
This was introduced before I learned about about the option to enable anisotropic filtering in the nvidia settings.
Anisotropic filtering properly solves the problem that I tried to solve in #4900, namely the texture quality in the distance when the camera is tilted.
In combination with anisotropic filtering my approach leads to severe aliasing, so we need to revert this.
It's hard to show it in screenshots, but the aliasing is pretty obvious when tilting the camera and then moving a little
=> Revert the wave texture lod bias

lua/defaultunits.lua
Closes https://github.com/FAForever/fa/issues/5039
I'm not sure if this is what we should do, but it does work. The dive feature of a unit is temporarily disabled while diving.
https://github.com/FAForever/fa/assets/15778155/8603ffa2-89f1-482c-9e62-b2a3a0798b40
=> Remove the dive button while diving

lua/sim/NavUtils.lua
This was the original behavior before we changed it with https://github.com/FAForever/fa/pull/5297
=> Always add the destination to the path

lua/keymap/alternativeKeyMap.lua, lua/keymap/defaultKeyMap.lua, lua/keymap/hotbuildKeyMap.lua, lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/sim/NavUtils.lua
In an attempt to make it easier to migrate to the new implementation
=> Re-use the old spread attack key identifiers

effects/mesh.fx
This enables switching between linear and exponential water absorption based on the value of lightMultiplier.
The upcoming terrain shaders will use exponential water absorption. The challenge now is to use the right absorption in the mesh shader. Originally we thought about having a map script change the unit shaders accordingly, but this gets messy because we have a lot of different shader techniques that would need to be changed and there are also prop and wreckage shaders. All of these would need a second variant, so we can switch them out. All of this only became necessary because the mesh shader doesn't know which terrain shader is being used.
Instead I came up with a different idea. There is in fact another variable that the map author can use to relay this information. The …
=> Enable switching between linear and exponential water absorption

engine/Sim.lua, lua/SimHooks.lua, lua/sim/commands/copy-queue.lua, lua/sim/commands/ring-extractor.lua, lua/sim/commands/shared.lua
Implements the changes of https://github.com/FAForever/FA-Binary-Patches/pull/29 and applies it to the Ring Extractor, Distribute Orders and Copy Orders features.
The assembly change fixes the performance problem where each build order would create a separate built preview. Built previews are transparent and therefore expensive on your framerate. With the assembly change we can assign 1 build order to a group of engineers, instead of assigning a separate build order to each engineer.
=> Implement alternative of `IssueBuildMobile`

units/URL0303/URL0303_Script.lua, units/URS0201/URS0201_script.lua, units/XRL0403/XRL0403_script.lua, units/XSB3202/XSB3202_script.lua
fixed warnings caused by unit scripts when nil values are loaded from blueprints
=> fixed unit scripts if blueprints are missing values

lua/sim/commands/ring-with-fabricators.lua, lua/sim/commands/ring-with-storages.lua, lua/sim/commands/shared.lua
Sorts the build orders created due to ringing by distance to the nearest, highest tech engineer. This should reduce the amount of waiting because engineers need to clear the build site.
https://github.com/FAForever/fa/assets/15778155/5104adad-9de7-418c-b97a-93d0858504f9
=> Sort the build orders by distance

engine/Sim/CAiBrain.lua, lua/sim/commands/ring-with-fabricators.lua, lua/sim/commands/ring-with-storages.lua, lua/sim/commands/shared.lua
Applies a similar cache pattern that is used by the distribute orders feature. Moves the data structure for build skirts from array of structures to structure of arrays, see also:
- https://en.wikipedia.org/wiki/AoS_and_SoA
=> Reduce memory allocations when ringing structures

lua/ui/game/cursor/depth.lua, lua/ui/help/tooltips.lua
new look
First two dots are at fixed depth (0.5 and 1.5) up to 3 dots appear afterwards and their distance scales based on water depth.
New description
=> Change depth indicator to multiple dots again and update description

engine/Core.lua, engine/User.lua, engine/User/UserUnit.lua, lua/keymap/keyactions.lua, lua/keymap/keydescriptions.lua, lua/ui/game/commandmode.lua, lua/ui/game/hotkeys/upgrade-structure.lua, lua/userInit.lua
A mouse-context sensitive hotkey that allows you to issue upgrades to structure without selecting them. When you upgrade a factory with multiple upgrades (hq or support) then it prefers to upgrade to a support factory.
https://github.com/FAForever/fa/assets/15778155/7f7c62ca-00ec-4013-aa6c-4e7738d4172f
=> Hotkey to upgrade unit you're hovering over

effects/terrain.fx
Fixes the longstanding issue with the water coloration creeping up the shore on steep cliffs.
With the new water shader it was even more obvious on low camera angles.
=> Fix water color above water

lua/aibrains/campaign-ai.lua
The issue was raised in the Coop Discord.
The campaign AI's PBM automatically grabs factories in range of a build location to build units, this includes the external factory component of mobile factory units. This breaks a lot of missions where units like Tempests, and Fatboys are built inside bases, and weren't meant to produce units by the mission makers.
This pull request is meant to fix that, by simply excluding the `EXTERNALFACTORYUNIT` category when the AI is assigning its factories to make use of them. Quantum Gates included, just to be sure.
Both the issue, and fix can be tested in any mission, by simply spawning in a Fatboy or such inside an AI base, and observing if its factory component is assigned any orders by the AI.
=> Fix the Campaign AI's PBM automatically grabbing Mobile Factories

lua/AI/GridDeposits.lua, lua/AI/GridPresence.lua, lua/aibrains/base-ai.lua, lua/sim/NavGenerator.lua, lua/sim/NavUtils.lua
Closes #5226 
Introduces the resource deposit grid with two queries:
- `GetResourcesWithinDistance` Returns all deposits that are within a given pathing distance to the start location
- `GetResourcesWithinRadius` Returns all deposits that are within a given radius, ignoring other conditions
Visual examples of `GetResourcesWithinDistance`:
https://github.com/FAForever/fa/assets/15778155/18e5194f-93c1-4433-9769-2463f2d37ace
https://github.com/FAForever/fa/assets/15778155/52fdc48c-e0d2-41c6-aab0-9e6895f9bc14
=> Resource deposit grid for AIs

units/UAL0401/UAL0401_Script.lua
fixes #4470 
took me almost a year but i was pretty busy with studying, so kinda late but here we go.
I adjusted the Collisionshape of the gc when building and reset it when the unit is finished.
To test this just spawn in some t3 engineers and build a gc, you can see the hitbox extending over all target Bones now,
when the building is finished it returns to the original Colisionshape.
=> Galactic colossus hitbox#4470

lua/sim/MarkerUtilities.lua
The old implementation would consider all non-occupied spawn locations as a large expansion. This was in conflict with how it worked before and existing AI logic would trip over it. All spawns are now considered as spawn locations.
When a spawn location is occupied the field `IsOccupied` is true, otherwise it is set to false.
=> All spawn locations are now populated with spawn markers

lua/AI/aibuildstructures.lua, lua/AI/aiutilities.lua
This PR updates the default AIGetMarkerLocations to use the cached markers and AIFindFurthestStartLocationNeedsEngineer to use the `Spawn` marker name instead of the default `Blank Marker` names.
This will fix a problem where the functions were not returning markers when the `Start Location` type was used unless the MarkerChain table was being referenced.
=> Update Spawn marker types for default AI functions

lua/ui/game/orders.lua
Can select multiple pods/pod platforms when multiples of their counterpart is selected. Stock behavior remains unchanged.
=> Multiple pod orders

lua/AI/AIBuilders/AIDefenseBuilders.lua, lua/AI/AIBuilders/AIEconomicBuilders.lua, lua/AI/AIBuilders/AIEconomyUpgradeBuilders.lua, lua/AI/AIBuilders/AILandAttackBuilders.lua, lua/AI/PlatoonTemplates/EngineerPlatoonTemplates.lua, lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua, lua/AI/Transportutilities.lua, lua/AI/aiattackutilities.lua, lua/AI/aiutilities.lua, lua/aibrains/adaptive-ai.lua, lua/aibrains/easy-ai.lua, lua/aibrains/index.lua, lua/aibrains/platoons/platoon-adaptive-attack.lua, lua/aibrains/platoons/platoon-adaptive-raid.lua, lua/aibrains/platoons/platoon-adaptive-reclaim.lua, lua/aibrains/platoons/platoon-adaptive-silo.lua, lua/aibrains/platoons/platoon-base.lua, lua/keymap/debugKeyActions.lua, lua/platoon.lua, lua/sim/NavUtils.lua, lua/ui/game/AIPlatoonInfo.lua
This PR converts introduces an adaptive raiding state machine and engineer reclaim state machine. (replaces a previous pr that I messed up)
It adds an inject function into the platoon.lua starting line 4901. This is temporary pending @Garanas doing something better.
Adds platoon templates for state machines and updates builders.
Adds an adaptive specific brain lua and updates the index.lua file.
Adds a utility function for checking threat then units to get correct threat number. Note does not get a position of said threat, may be temporary.
TODO:
Run some AI games using the adaptive AI across various map types and validate that the platoons / units are running correctly. Currently alot of logging is included to show state machine switching and error states.
=> AI - State Machine implementation

engine/Sim.lua, lua/AI/AIBehaviors.lua, lua/AI/OpAI/BaseManager.lua, lua/AI/OpAI/BaseManagerPlatoonThreads.lua, lua/AI/OpAI/OpBehaviors.lua, lua/AI/Transportutilities.lua, lua/AI/aibuildstructures.lua, lua/AI/aiutilities.lua, lua/ScenarioFramework.lua, lua/ScenarioPlatoonAI.lua, lua/SimCallbacks.lua, lua/SimHooks.lua, lua/aeonweapons.lua, lua/aibrain.lua, lua/aibrains/campaign-ai.lua, lua/defaultcomponents.lua, lua/defaultunits.lua, lua/platoon.lua, lua/seraphimunits.lua, lua/sim/Unit.lua, units/UAA0310/UAA0310_script.lua, units/UAS0303/UAS0303_script.lua, units/UAS0401/UAS0401_script.lua, units/UES0401/UES0401_script.lua, units/URA0001/URA0001_script.lua, units/URS0303/URS0303_script.lua, units/XEB2402/XEB2402_Script.lua, units/XSS0303/XSS0303_script.lua
This idea started with https://github.com/FAForever/fa/issues/5398 where we introduce alternatives to global functions that work for just a single unit, instead of a group of units. The goal is to prevent the allocation of a table with a single array entry in it when we need to apply the function to a single unit.
We can apply the same approach to the simulation. We introduce alternatives that work on a single unit and re-use a single table to efficiently manage memory without the developer being aware of it.
=> Table allocation free versions of sim commands

units/UES0401/UES0401_unit.bp
**Changes:**
Atlantis: BackUpDistance 15 --> 30
The Atlantis had a rather low BackUpDistance of 15. This meant, that in order to retreat slightly, it usually had to turn by 180 degrees and then drive forwards. This made the unit feel clunky to micro.
=> Atlantis: Increase its BackUpDistance from 15 to 30

engine/Core/Blueprints/ProjectileBlueprint.lua, engine/Sim/Projectile.lua, lua/sim/Projectile.lua, lua/sim/weapon.lua, units/UAB2204/UAB2204_unit.bp, units/UAS0202/UAS0202_unit.bp, units/UEB2204/UEB2204_unit.bp, units/UES0202/UES0202_unit.bp, units/URB2204/URB2204_unit.bp, units/URS0202/URS0202_unit.bp, units/XSB2204/XSB2204_unit.bp
All projectiles that track (usually, SAM-like weapons and torpedo's) can now retarget after they lost a target. The projectile retargets to the new target of the weapon it is launched from. This guarantees that the target is valid category wise and that the target is in range of the weapon
The target check interval for certain units is relatively low. But in order for projectiles to reliably find a new target the check interval needs to be at least a second
Features for another pull request:
- Limit the number of times that a projectile can retarget before self-destructing
- Look into target check interval of units with projectiles that retarget
=> Projectiles that retarget autonomously

lua/sim/Projectile.lua, lua/system/Blueprints.lua, lua/system/blueprints-weapons.lua
By limiting the target check interval we make it easier for projectiles to find new targets
=> Limit target check interval of weapons that can retarget

lua/SimCallbacks.lua, lua/ui/dialogs/createunit.lua, lua/ui/game/commandmode.lua
Since the `ShowRaisedPlatforms` command appears to do nothing, this adds a toggle option to the cheat spawn menu to outline raised platforms with beams.
=> Raised Platform visualisation for cheat spawn menu

effects/mesh.fx
There was feedback that the cybran units look too bland. Adding a bit of the red specular channel brings back some of the albedo variation. This works because originally the specular red channel added sunreflection, essentially making the albedo brighter. We have already encountered this on the Aeon units, where adding the specular red channel to the albedo greatly homogenized their look. Here we use this trick to bring back some detail that got lost.
It also makes metal parts look brighter, which is a nice touch as they were a bit too dark before.
=> Tune Cybran albedo

effects/mesh.fx
I forgot that we still need to add the emission, even if we don't do any water processing. This lead to inadvertantly turning of the emission on maps without water.
=> Add missing emission on maps without water

effects/mesh.fx
Here comes another shader fix xD
Adjusting the red specular channel for cybran units produced the side effect that on medium fidelity (that setting that is supposed to be close to the steam fa shader) all units looked overly bright, as seen here:
Originally they looked like this:
We can bring them in line with the original look with a small change, which leaves us with this result, which is pretty close:
This enables easier comparisons between the PBR shader and the original shader and preserves the original shader better for people that prefer that look. PBR shaders are unaffected by this PR.
=> Fix look of cybran units on medium fidelity

lua/DefaultUnits/ExternalFactory.lua, lua/defaultcomponents.lua
Mobile factories can no longer self destruct (on accident). They can also no longer be reclaimed. They now also start off with the same fire state as regular factories (attack ground).
=> Fix small details related to the mobile factory

lua/DefaultUnits/Mobile.lua
When a unit is built by a factory it inherits the fire state of that factory. However, when a mobile unit is created the fire state was overwritten to always be the attack ground fire state
All factories default to the attack ground fire state. A user can now switch that to the return fire state or the no fire state and units will inherit that accordingly.
=> No longer force the fire state of mobile units to ground attack

engine/Core/Blueprints/UnitBlueprint.lua, engine/Core/Blueprints/WeaponBlueprint.lua, lua/DefaultUnits/Air.lua, lua/shield.lua, lua/sim/Unit.lua, lua/system/blueprints-projectiles.lua, lua/system/blueprints-units.lua, projectiles/AANDepthCharge01/AANDepthCharge01_proj.bp, projectiles/AANDepthCharge02/AANDepthCharge02_proj.bp, projectiles/AANDepthCharge03/AANDepthCharge03_proj.bp, projectiles/AIFBombQuark01/AIFBombQuark01_proj.bp, projectiles/CIFProtonBomb01/CIFProtonBomb01_proj.bp, projectiles/SANHeavyCavitationTorpedo01/SANHeavyCavitationTorpedo01_proj.bp, projectiles/SBOZhanaseeBomb01/SBOZhanaseeBomb01_proj.bp, projectiles/TIFSmallYieldNuclearBomb01/TIFSmallYieldNuclearBomb01_proj.bp
Removes the `DoNotCollideList` and generated fields from the unit and projectile blueprints. It is a bit silly in the nature of a physics simulation to begin with, but due to https://github.com/FAForever/FA-Binary-Patches/pull/48 collisions can trigger quite a bit more often. Therefore a generic solution with a complexity of `O(n)` is not desirable as the `OnCollisionCheck` is now a critical path for performance
The second step towards making collision detection less expensive due to https://github.com/FAForever/FA-Binary-Patches/pull/48
=> Allow projectiles of strategic bombers to ignore ASF

lua/keymap/hotbuild.lua, lua/ui/controls/worldview.lua
Fixes a subtle, but very annoying bug related to using hot build to queue units in a factory. You can now reliably use the release of any non-left button of the mouse to exit the cycle preview. When exiting, the `HandleEvent` of the worldview is properly reset, previously it would be assigned the _result of the old `HandleEvent`_, which is really not what you want 😃 
It now also properly registers _any left click_. The old implementation would only register non-double clicks, but usually you'll have a lot of those as you want to quickly queue up units
When you exit the cycle preview using right-click it no longer registers it as a command issues (which is a rally point in 99.9% of the cases)
=> Fix not capturing the right click when exiting hot build

engine/Core/Blueprints/UnitBlueprint.lua, lua/defaultcomponents.lua, lua/system/blueprints-units.lua, lua/ui/lobby/lobby.lua, units/UAA0310/UAA0310_script.lua, units/UAA0310/UAA0310_unit.bp, units/UAS0303/UAS0303_unit.bp, units/UAS0401/UAS0401_unit.bp, units/UEL0401/UEL0401_unit.bp, units/UES0401/UES0401_unit.bp, units/URS0303/URS0303_unit.bp, units/XSS0303/XSS0303_unit.bp
Introduces a separate field in the blueprint to pass blueprint fields to the external factory. The fields supported at the moment are related to the selection size and location.
=> Separate blueprint fields for an external factory

lua/armordefinition.lua, lua/sim/DefaultUnits/StructureUnit.lua, lua/sim/DefaultUnits/WallStructureUnit.lua, units/UAB5101/UAB5101_unit.bp, units/UEB5101/UEB5101_unit.bp, units/URB5101/URB5101_unit.bp, units/XSB5101/XSB5101_unit.bp
With thanks to https://github.com/FAForever/FA-Binary-Patches/pull/48 walls can now properly block projectiles. With this pull request we double-down on that by introducing a wall overspill mechanic in combination with a 0.1 ogrid increase of height for the walls. On flat ground a pitbox now reliably blocks projectiles of any tech 1 medium tank.
=> Introduce a wall overspill mechanic

effects/Entities/TacticalDebris01/TacticalDebris01_proj.bp, effects/Entities/TacticalDebris01/TacticalDebris01_script.lua, effects/Entities/TacticalDebris02/TacticalDebris02_proj.bp, effects/Entities/TacticalDebris02/TacticalDebris02_script.lua, effects/Entities/TacticalDebris03/TacticalDebris03_proj.bp, effects/Entities/TacticalDebris03/TacticalDebris03_script.lua, effects/emitters/tactical_debris_distortion_01_emit.bp, effects/emitters/tactical_debris_fire_01_emit.bp, effects/emitters/tactical_debris_smoke_01_emit.bp, effects/emitters/tactical_debris_smoke_02_emit.bp, effects/emitters/tactical_debris_smoke_03_emit.bp, effects/emitters/tactical_debris_smoke_04_emit.bp, effects/emitters/tactical_debris_trail_01_emit.bp, lua/EffectTemplates.lua, lua/aeonprojectiles.lua, lua/cybranprojectiles.lua, lua/terranprojectiles.lua
Adds more types of debris to tactical missiles that end up being intercepted. Involves trails that are especially good looking on Cybran tactical missiles. The debris that is on fire can set trees ablaze. Because of faction diversity; Seraphim missiles do not leave any type of debris when intercepted
https://github.com/FAForever/fa/assets/15778155/6b829b15-731c-411f-91c8-6c906f0edddf
https://github.com/FAForever/fa/assets/15778155/39429fa0-908a-4fea-92eb-ed9e02c0727c
https://github.com/FAForever/fa/assets/15778155/759f40eb-ed3b-4f12-9416-3f74b94cb24f
https://github.com/FAForever/fa/assets/15778155/e4fbb4e4-c9da-4c39-af1a-913e33ea3988
=> Add more diverse debris to tactical missiles

lua/ui/dialogs/score.lua
Currently there is no way to set volume for ambient sounds. (I did try `SetVolume("Ambient"/"AmbientTest", 0)`). Now at least won't play the ambient sound in scoreboard if music is off.
=> Mute scoreboard background ambient if music is off

units/URL0303/URL0303_unit.bp, units/XSL0305/XSL0305_unit.bp
They are shown as yellow indirect-fire rings.
Annoyingly sera snipers overlap the indirect fire ring on top of the sniper mode's direct fire ring, but only when selected; if you turn on indirect fire rings in the strategic overlay options (top left corner where the minimap/pings/player colors/eco overlay are), direct fire rings overlap on top of indirect fire rings instead.
Resolves #5400.
=> Display Sera Sniper/Loyalist secondary ranges

lua/ui/game/hotkeys/context-based-templates.lua
When using context based templates you can start creating extractors by hovering over a deposit. The radius used to be fixed to 1.5 (extractors) and 3.0 (hydrocarbon plants). It now includes a factor based on the zoom of your camera. This makes it easier to cycle through extractors and / or a hydrocarbon plant based templates while zoomed out.
=> Make it easier to start building extractors while zoomed out

lua/options/options.lua, lua/ui/game/commandmode.lua, lua/ui/help/tooltips.lua
A small feature for the list of the 'assist to' features. With this change you can assist an engineer but instead of applying an assist order you copy and apply the command queue of that engineer to your selection.
This is similar to the [Copy orders](https://wiki.faforever.com/en/Play/Game/Hotkeys/OrdersQueueManipulation#copy-orders) feature except that this does not require a hotkey 😃
=> Assist to copy the command queue of an engineer

units/UAB5101/UAB5101_unit.bp, units/UEB5101/UEB5101_unit.bp, units/URB5101/URB5101_unit.bp, units/XSB5101/XSB5101_unit.bp
In addition to https://github.com/FAForever/fa/issues/5514 and because of https://github.com/FAForever/FA-Binary-Patches/pull/48 where we tackled the order of collisions for projectiles.
For all walls:
- Hitpoints: Reduced from `X` to `500`
- Energy cost: Increased from `10` to `20`
- Mass cost: Increased from `2` to `3`
- Build time: Reduced from `20` to `15`
=> Process the balance changes to walls

units/UAB2304/UAB2304_unit.bp, units/UEB2304/UEB2304_unit.bp, units/URB2304/URB2304_unit.bp, units/XSB2304/XSB2304_unit.bp
Increase the build time of stationary tech 3 anti air. They now require more build power to spam in large numbers. 
For all stationary SAMs:
- Build time: Increased from `1195` to `1400`
=> Process build time changes for stationary tech 3 anti air

units/XAA0306/XAA0306_unit.bp
Closes https://github.com/FAForever/fa/issues/5539
By increasing the break off distance the solace has the space it requires to maneuver between bombing runs
=> Increase break off distance for Solace for better bombing runs

lua/sim/defaultweapons.lua, units/XEL0306/XEL0306_unit.bp
Not properly checking and confirming that a weapon can fire has some clear consequences. It was fun while it lasted 😃 . 
Fixes a bug where the Spearhead would skip an attack cycle by default by using the packing state of a weapon. If a weapon is already unpacked then it won't try to unpack again.
=> Fix flak acting like a gattling cannon

units/XSL0001/XSL0001_unit.bp
This was not the case previously.
=> Fix: Enable the Sparky to be buffed by the RegenAura-upgrades

lua/sim/commands/shared.lua
Adds a guard to check if the entity / prop / unit still exists before trying to issue a reclaim order to it.
```
Main thread
@c:\programdata\faforever\gamedata\lua.nx2\lua\simcallbacks.lua 52
"DistributeOrders", Table, Table, 2292.209717, Func:@c:\programdata\faforever\gamedata\lua.nx2\lua\simcallbacks.lua 505
@c:\programdata\faforever\gamedata\lua.nx2\lua\simcallbacks.lua 56
Table, Table, CObject:.?AVUnit@Moho@@ ID:6291915 BpName:xsl0309
@c:\programdata\faforever\gamedata\lua.nx2\lua\simcallbacks.lua 521
Table, CObject:.?AVUnit@Moho@@ ID:6291915 BpName:xsl0309, true, true, CObject:.?AVCAiBrain@Moho@@, Table, 61.5, 695.5, Table, Table, nil, Table, Table, Table, Table, Table, 12, 9, CFunc, Table, 1, Table, 4, Table, "Reclaim", Func:@c:\programdata\faforever\gamedata\lua.nx2\lua\sim\commands …
```
=> Add a guard before applying the reclaim order

lua/sim/NavGenerator.lua
Current statistics (Seton's Clutch - FAF Version):
```
DEBUG: NavGenerator - Flattened 414 sections
DEBUG: NavGenerator - culled 193 labels
DEBUG: Generated navigational mesh in 1.527344 seconds
DEBUG: Allocated megabytes for navigational mesh: 18.959351
DEBUG: Allocated megabytes for labels: 0.175751
DEBUG: Number of labels: 242.000000
DEBUG: Number of cells: 127056.000000
```
New statistics (Seton's Clutch - FAF Version):
```
DEBUG: NavGenerator - Flattened 414 sections
DEBUG: NavGenerator - culled 193 labels
DEBUG: Generated navigational mesh in 1.560547 seconds
DEBUG: Allocated megabytes for navigational mesh: 17.666992
DEBUG: Allocated megabytes for labels: 0.175751
DEBUG: Number of labels: 242.000000
DEBUG: Number of cells: 47966.000000
```
Roughly reduces the memory footprint by …
=> Reduce memory footprint of navigational mesh by ~ 10%

units/UAA0103/UAA0103_unit.bp
Copies sera bomber values. I noticed you have to f10 -> "restart game" to have the `SizeX/Y/Z` changes apply.
Here are two pictures with tests of ~100 bombers.
Before (all the bombers flying low are stuck flipping over trying to aim at the move waypoint):
After (the bombers don't fly nearly as low nearly as often, and they correct their trajectory+height quickly):
=> Fix aeon bomber getting stuck flipping

projectiles/TDFFragmentationGrenade01/TDFFragmentationGrenade01_proj.bp
Microfix that allows the grenades to be distinguished from the gatling gun bullets in strategic view.
=> Increases size of mongoose grenade strategic icon

projectiles/AIFBombGraviton01/AIFBombGraviton01_proj.bp, projectiles/CIFNeutronClusterBomb01/CIFNeutronClusterBomb01_proj.bp, projectiles/SBOOtheTacticalBomb01/SBOOtheTacticalBomb01_proj.bp, projectiles/TIFNapalmCarpetBomb01/TIFNapalmCarpetBomb01_proj.bp
Currently it's possible to boost sera and aeon bomber bomb velocity so they drop 3x faster than normal and make it practically impossible for engis to dodge them, and that is achievable with some sandbox practice using the plane height indicator game setting and groundfiring 1-2.5 units in front of the bomber. It is also a bit too effective to be fair compared to cybran and uef bombers.
As the main change, this fixes super speedy bomb drops.
*I mostly tested sera, because aeon has practically the same weapon but gets stuck randomly.*
Approximate drop times in seconds for sera bomber:
| type of drop | before nerf | after nerf |
| --------------- | ------------ | ---------- |
| best case| 0.5 | 0.9 |
| good skill | 0.6-0.7 | 1.0-1.1 |
| improving skill | 0.8-0.9 | 1.2 |
| basic skill | …
=> Adjust t1 bomb max speeds.

effects/terrain.fx, effects/water2.fx
I had to partially revert the fix that got rid of the water coloration on steep cliffs. When only checking for the terrain height we can get artifacts in shallow water when zooming out far because of the terrain tesselation. Then random segments of the water disappear. So as a compromise we only get rid of the start of the coloration. This is enough for reasonably steep cliffs while it minimizes the tesselation artifacts to a level that is not distracting.
The advanced shaders now use the previously unused channel in our mapwide texture for the water depth. This enables us to put the mapwide albedo "decal" into a normal slot that was already free, but we couldn't access it because of the limit of how many different textures we can sample. Now that we got rid of the need to sample the …
=> Terrain advancements

engine/Sim/CPlatoon.lua, lua/aibrains/platoons/platoon-adaptive-attack.lua, lua/aibrains/platoons/platoon-adaptive-guard.lua, lua/aibrains/platoons/platoon-adaptive-raid.lua, lua/aibrains/platoons/platoon-adaptive-returntobase.lua, lua/aibrains/platoons/platoon-base.lua, lua/aibrains/platoons/platoon-simple-raid.lua, lua/sim/NavDatastructures.lua, lua/sim/NavDebug.lua, lua/sim/NavDebug/DirectionTo.lua, lua/sim/NavGenerator.lua, lua/sim/NavUtils.lua, tests/test_NavDatastructures.lua
As an extension of #5574 we can now generate a coarse grid of the navigational mesh that we can use to navigate. The navigational mesh still exists - the coarse grid is generated on top of it.
For the average 10x10 map the setup generates in less than 0.4 seconds. For the average 20x20 map the setup generates in roughly 1.2 to 1.5 seconds. We can now use the coarse grid for navigation to speed up computations
=> Introduce a coarse navigational grid

lua/sim/Projectile.lua, lua/sim/defaultweapons.lua
As reported on [Discord](https://discord.com/channels/197033481883222026/1168238017572511865).
The problem was that the beam could hit multiple missiles at once. It would then be able to intercept the 'wrong' missile
=> Fix a bug with zappers intersecting the wrong missile

effects/terrain.fx
We should try to standardize the different shaders as much as possible, to make switching them easier. Now every shader expects the map-wide albedo texture in the albedo slot of stratum 7.
=> Always store the mapwide albedo texture in the albedo slot

engine/Core/Blueprints/ProjectileBlueprint.lua, lua/sim/Projectile.lua, projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_proj.bp, projectiles/SBOZhanaseeBomb01/SBOZhanaseeBomb01_proj.bp, projectiles/SBOZhanaseeBomb01/SBOZhanaseeBomb01_script.lua
Closes https://github.com/FAForever/fa/issues/4404
Re-introduces the Seraphim-specific scorch splats for the Seraphim tech 3 bomber. Introduces a new projectile blueprint field that you can use to ignore the default scorch splats
=> Re-introduce the Seraphim-specific scorch splats

lua/sim/units/FactoryUnit.lua
Allow engineers to change their orientation as they are finished constructing. With this exception we prevent the first engineer being poorly orientated and as a result add several seconds to your build order
=> Add an exception to the roll off point of engineers

units/UEL0301/UEL0301_unit.bp
For consistent look keeping the Backpack bone showing when the SACU has the bubble shield make sense and shouldn't be removed
=> Show the Backpack on SCU BubbleShield

lua/simInit.lua
These were found by @Hdt80bro and I was testing them while being checked out on #5525 . These three parameter changes are likely the cause of the path finding hiccups that people are experiencing. We're removing them again, so that they default back to the values defined by the engine.
=> Remove pathing parameters that should not have been merged in

engine/Sim/Projectile.lua, lua/sim/Projectile.lua, lua/sim/projectiles/DebrisProjectile.lua, lua/sim/projectiles/EmitterProjectile.lua, lua/sim/projectiles/MultiBeamProjectile.lua, lua/sim/projectiles/MultiCompositeEmitterProjectile.lua, lua/sim/projectiles/MultiPolyTrailProjectile.lua, lua/sim/projectiles/NukeProjectile.lua, lua/sim/projectiles/OnWaterEntryEmitterProjectile.lua, lua/sim/projectiles/OverchargeProjectile.lua, lua/sim/projectiles/SingleBeamProjectile.lua, lua/sim/projectiles/SingleCompositeEmitterProjectile.lua, lua/sim/projectiles/SinglePolyTrailProjectile.lua, lua/sim/projectiles/components/DebrisComponent.lua
According to @KionX one of the most expensive operations is the `GETTABLE` operation. A recent, very obvious example of this was done by @Pokute in https://github.com/FAForever/fa/pull/5524 . In this example we apply the same idea, but at a smaller scale 😃 .
The class hierarchy relies on calling the base class. As a quick example:
```
Projectile.OnCreate(self)
(UPVALUE) ^
```
I've marked the `.` as that indicates a `GETTABLE` operator. we use it to retrieve the same function of the base class. This involves a `GETTABLE` operator at every class that overrides a given function. The reference to the `Projectile` class is stored in an upvalue. Why would we not use that upvalue to just store a reference to the function of the base class?
Previously this would not always be possible. But With …
=> Reduce overhead of the projectile hierarchy

projectiles/TDFGauss01/TDFGauss01_proj.bp, projectiles/TDFGauss01/TDFGauss01_script.lua, projectiles/TDFGauss02/TDFGauss02_proj.bp, projectiles/TDFGauss02/TDFGauss02_script.lua, projectiles/TDFGauss03/TDFGauss03_proj.bp, projectiles/TDFGauss03/TDFGauss03_script.lua, projectiles/TDFGauss04/TDFGauss04_proj.bp, projectiles/TDFGauss04/TDFGauss04_script.lua, projectiles/TDFGauss05/TDFGauss05_script.lua
I have no idea why some did and others did not have these threads running for each projectile they create. It appears entirely redundant.
=> Remove redundant thread creations for gauss-like projectiles

lua/maui/effecthelpers.lua
The old way could result in big and inconsistent drifts in alpha on framerate drops. The new code doesn't rely on what the alpha was during the previous frame.
=> UI Pulse rework - make it resilient to low framerate.

lua/sim/score.lua, lua/ui/dialogs/hotstats.lua
The end-of-game score graphs had buggy starts and ends. The start was actually the first saved datapoint at 00:30 instead of 00:00 and thus the scores never started from zero. The final graph segment between the last save datapoint and the end-of-game datapoint, which usually had a duration less than the default 30 seconds, had incorrect rendering.
Additionally the end-of-game datapoint was not taken into account when calculating the maximum values for graphs. Thus the graph could render outside the background.
Example of old graph:
Example of fixed graph:
This PR has a possible breaking change: Score history data now has an additional data point at 00:00, instead of the first one being at 00:30. If some mod uses this data, it might get confused.
=> Score graph start end fix

units/UAA0107/UAA0107_unit.bp
**Changes**
SizeX: 1.8 --> 2.2
SizeY: 0.9 --> 1.3
SizeZ: 1.8 --> 2.2
This attempts to fix the bug where interceptors shoot in front of the Chariot and miss it. In my tests, these changes fixed this in most cases. They can still miss it when it starts and lands, even with the increased Y-size, although this is reduced with these values. Let me know if the increase in Y-size is too much in your opinion.
Pointed at fafdevelop.
=> Increase the Chariot's hitbox to fix interceptors missing it

init.lua, init_faf.lua, init_fafbeta.lua, init_fafdevelop.lua, init_shared.lua
When a system has too many logical cores then we hit problems with floating point imprecision. We're simply unable to 'disable' the first two logical cores because of that. At the moment it works like this:
- When someone has 24 or more logical cores than the first 2 logical cores and any logical core starting at the 25th are disabled.
- When someone has 6 or more logical cores than the first 2 logical cores are disabled.
=> Fix floating point imprecision for processors with a lot of cores

lua/sim/Projectile.lua, lua/sim/defaultweapons.lua
With thanks to https://github.com/FAForever/fa/issues/5576
I recall the bug being reported on Discord but I can't find it anymore. The weapons are disabled to prevent them from keeping a lock on a projectile while the weapon is reloading. This mechanism was using the thread of the `RackSalvoFiringState` state. But - if for any reason - the weapon state would change then the thread would be killed and the weapon would remain disabled forever.
This can occur rather frequently for units with multiple weapons.
=> Fix anti-projectile weapons being disabled forever

units/URL0306/URL0306_unit.bp
#5142 has no effect because the radar intel grid has a resolution of 4x4. This increases the range to 24, which is divisible by 4 so it has an effect.
=> Fix Deceiver Range Buff

units/DRLK001/DRLK001_unit.bp, units/DSLK004/DSLK004_unit.bp, units/URL0104/URL0104_unit.bp
Cybran T1 MAA was considered a T1 Tank, and Cybran/Sera T3 MAA didn't get formation categories. Now they're all properly considered as T1AA or T3AA in formations.lua.
=> Fix AA formations for directfire-capable land AA

lua/sim/Unit.lua
Currently presets give experience from their enhancements' mass twice. This fixes that bug.
It was caused by addressing an array with a key instead of traversing it and looking for the required value.
=> Fix presets giving double veterancy

lua/system/blueprints-units.lua, lua/ui/game/unitview.lua
Resolves #5379.
The mantis should have buildpower, the thaam shouldn't. Test:
```
CreateUnitAtMouse('xsl0201', 0,   -1.50,    0.00, -0.00030)
CreateUnitAtMouse('url0107', 0,    1.50,    0.00,  0.00013)
```
=> Fix Mantis build power display

units/XSL0304/XSL0304_unit.bp
Fixes #4889.
As for animations, the weapon clips into the body when firing backwards regardless of 40 or 50 pitch range, so it's not an issue.
=> Let Suthanus fire backwards

lua/system/blueprints-units.lua
Fixes #5724. Mousing over units in the build bar with the unit selected (not the external factory) displays correct buildrates.
<details>
<summary> Spawn test units command: </summary>
``` CreateUnitAtMouse('urs0303ef', 0,   25.84,  -18.40, -0.00000)
CreateUnitAtMouse('uel0401', 0,    9.09,   25.80,  1.30232)
CreateUnitAtMouse('uel0401ef', 0,    4.39,   24.50,  1.30232)
CreateUnitAtMouse('xab1401', 0,   -4.16,   27.02, -0.00160)
CreateUnitAtMouse('ues0401ef', 0,  -16.66,  -21.53, -0.00000)
CreateUnitAtMouse('ues0401', 0,  -16.66,  -12.48, -0.00000)
CreateUnitAtMouse('uas0303', 0,   -4.16,  -11.98, -0.00000)
CreateUnitAtMouse('urs0303', 0,   25.84,   -9.98, -0.00000)
CreateUnitAtMouse('xss0303', 0,   11.84,  -10.98, -0.00000)
CreateUnitAtMouse('uas0303ef', 0,   -4.16,  -21.19, -0.00000) …
```
=> Don't remove unit buildrate after processing external factory

effects/terrain.fx
The fix for the water bleeding was inadvertantly only applied to maps using the TTerrain shader, so the vast majority of maps were left out. The effect can be seen for example on project albus.
The height and roughness textures had ugly seams where the texture repeats. These are now fixed.
The calculation of the texture splatting was reworked. The bluriness can now be changed without biasing where the texture shows up.
The bluriness can now be controlled by the red value of the SpecularColor.
Also adjusts the values for blending textures as these seemed nicer to me.
Value of 0.06 for bluriness:
Value of 0.25 for bluriness:
No maps use these advanced shaders so far, so there is no direct effect on the community.
I had to comment out the TerrainPBR shader as it is now over the instruction …
=> Terrain bugfixes and small improvements

lua/sim/Unit.lua
Last fix didn't work because the `continue` was moved inside a new loop. The original method also doesn't work when enhancements are removed from a preset.
Now there shouldn't be any difference in wrecks or vet amounts for manually enhanced SACUs or preset SACUs or a mix of the two.
=> actually fix double veterancy and make wrecks copy enhancement costs

lua/system/Blueprints.lua, units/UAL0301/UAL0301_script.lua, units/UAL0301/UAL0301_unit.bp, units/UEL0301/UEL0301_unit.bp, units/URL0301/URL0301_unit.bp, units/XSL0301/XSL0301_unit.bp
Presets that are made for fighting now have the same selection priority as combat units and can be selected together with them even when not holding shift.
SACU presets that are not made to be used like other combat units are left unchanged.
Presets adjusted to be selectable like combat units: 
UEF: BubbleShield, Combat, Rambo
AEON: NanoCombat, Rambo, ShieldCombat, SimpleCombat
CYBRAN: AntiAir, Cloak, Combat, Rambo, Stealth
SERA: AdvancedCombat, Combat, NanoCombat, Rambo
Presets unchanged and still selectable like default SACUs and engies: 
UEF: Engineer, IntelJammer, RAS
AEON: Engineer, RAS
CYBRAN: Engineer, RAS
SERA: Engineer, Missile
=> Adjust SACU preset selectionpriority for combat

lua/sim/defaultweapons.lua, lua/sim/weapons/uef/TIFCarpetBombWeapon.lua
Resolves #2407.
Greatly improves the bomb dropping pattern of the Janus and Scorcher by making them drop their entire salvo onto one location instead of constantly tracking their target and dropping each individual bomb onto the current predicted target location.
It does change balance for both bombers.
To test, turn on NoDamage in the console, spawn 10 bombers, and spawn a Harbinger as a target for you to micro. The Harbinger turns quickly so it can show off bomb dodging but isn't so fast that the bombing attempt fails like the Spirit. Notice how the Janus doesn't leave giant fiery rings when bombing a turning target.
https://github.com/FAForever/fa/assets/82986251/e17f1c57-8a12-4f36-84a0-49dd0ab74fce
https://github.com/FAForever/fa/assets/82986251/0d2cdb82-fa63-4ba8-82ad-f0d9d0ff3a15 …
=> Fix Janus and Scorcher tracking bombs

units/URL0401/URL0401_unit.bp
Prevents Scathis being selected instead of engineers or alongside combat units.
Resolves #4892.
=> Reduce Scathis selection priority to structure level

units/XES0205/XES0205_script.lua, units/XES0205/XES0205_unit.bp
- Fix the ls_ weapon appearing in the armament details. Dummy weapons should not have a WeaponCategory.
- Re-add the range ring that weapon is meant to display to represent the shield range on the water surface.
- Adds a dummy weapon so it doesn't drive into the enemy when on attack move. The range of the weapon is set up so that the shield should be 5 units in front of frigates that are within firing range.
With frigates, destroyers, and bulwarks on attack  move you should get a setup somewhat like this:
=> Improve Bulwark UI and give it a dummy weapon

lua/sim/units/cybran/CBuildBotUnit.lua
Was caused by #5672. I copy-pasted the missing `OnCreate` function for build bots, and now they work. I found the issue independently, but it was also reported earlier on discord.
We both have a similar crash log from the debugger, this is my log:
```
ACCESS_VIOLATION: Read from 0x00000008
Stacktrace: 0x005F5D3E 0x005F5B8A 0x005F9CD9 0x00958CE2 0x005947A2 0x006FE171 0x0040A8C5 0x0040A8C5
.?AVUnit@Moho@@
.?AVCUnitRepairTask@Moho@@
.?AVRUnitBlueprint@Moho@@
.?AVCArmyStats@Moho@@
.?AVCArmyImpl@Moho@@
MiniDump:
From 0x005F5CFE to 0x005F5D7E
C3740583C0FCEB0233C08B108BC88B423C6A2DFFD084C00F84050600008B45083BC3740583C0FCEB0233C03998580500000F84A80600008B4D008B8134050000
8B5008F30F1044241C895424248B400CF30F104C2424894424288B45083BC3F30F59C8F30F114C2424F30F104C2428F30F59C8F30F114C2428740583C0FCEB02 …
```
=> Fix crash when cybran build bots assist a silo

engine/User.lua, lua/ui/game/gamemain.lua, lua/ui/game/unitview.lua, lua/userInit.lua
There are four cfunctions that allow you to interact with the build queue:
- (1) `ClearCurrentFactoryForQueueDisplay(): nil`: clear the internal build queue
- (2) `SetCurrentFactoryForQueueDisplay(userUnit) : UIBuildQueue`: define the internal build queue 
- (3) `DecreaseBuildCountInQueue(index, count):nil`: decrease count at index of internal build queue
- (4) `IncreaseBuildCountInQueue(index, count):nil`: increase count at index of internal build queue
The first problem is that they interact with some global object that is defined with (2). The functions (3) and (4) rely on that global object. With (1) the global object is reset. The jargon for this is 'global state' and it is considered a [bad practice](https://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-s …
=> Fix bug that can make build queue unresponsive

effects/mesh.fx, effects/terrain.fx
I noticed a problem with our new fancy water: the water depth for the terrain shader is limited to 1 maximum as we read that from a texture and the texture can't provide values greater than 1. With the exponential absorption that means we are stuck with ~90% absorption, which is a problem if someone wants to create really murky water. What I did is that we simply multiply the scale by two, then we can reach ~98% absorption, which should be enough.
If a map is supposed to have pretty clear water, then the abyss depth can be set to be significantly lower than the lowest terrain.
Maps using the linear water absorption are unaffected
=> Double the exponential absorption rate of water

engine/Core/Blueprints/UnitBlueprint.lua, lua/keymap/debugKeyActions.lua, lua/shared/aichunktemplates.lua, lua/ui/game/aichunktemplates.lua
The chunk templates will eventually replace the base templates. It is similar, if not equal, to the templates used by the LOUD community. 
We use the navigational mesh to divide a map into squares. These 'chunks' templates represent what an AI could populate (in terms of structures) in one of those squares.
We can then create templates that are similar to build templates that fit in exactly one of those squares. As an example:
Each of those squares represents a chunk. A chunk of an AI base. We can create many variations of each size of a chunk to make sure one base is unlike the other. 
The idea is that the AI will claim additional chunks as it tries to build structures. This way the AI can expand the base and gain more ground.
We need chunks to prevent the AI from exhaustively searching …
=> Initial setup for the new chunk template concept

projectiles/CDFProtonCannon01/CDFProtonCannon01_proj.bp, projectiles/CDFProtonCannon01/CDFProtonCannon01_script.lua
This was included in the steam version of the game too, maybe GPG wanted destroyers to be able to shoot slightly underwater, which is why Valiant's projectiles aren't destroyed on water in GPG? Exodus can hit non-strategic subs with its 1.4 splash after all, while all other factions (including Sera's lasers) have only 1 splash, so they can't hit subs.
=> Fix Salem's main gun being able to shoot underwater in close range

projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_proj.bp, projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_proj.bp
They unnecessarily show up in the weapon stats.
=> Remove unused cost stats from Seraphim naval TML

lua/ui/game/unitviewDetail.lua
_Continuation of #5779_
- Charge time was being counted even if it was less than the fire rate cooldown. This image is of the Ascendant (aeon mobile flak). It should be 0.5 reload time.
- Charge time should also be counted every rack firing, for example the cybran TML was saying it had 6.0 reload time, but in reality it is 10.0. Now it says 9.9, because inexplicably, after reloading, it waits 2 ticks from idle to idle.onfire instead of 1 tick.
- Avoid incorrectly saying a unit fires a salvo for units like mantis and blaze who have multiple racks but are only controlled by fire rate. Mantis showing a salvo:
=> Further tweaks to weapon details

engine/User.lua, lua/options/options.lua
Closes https://github.com/FAForever/fa/issues/5793
I thought that the `set` function was run when a new game starts. But apparently it does not 😃
=> Fix strategic icon scale not applying correctly

lua/ui/game/orders.lua, units/URL0001/URL0001_script.lua, units/URL0001/URL0001_unit.bp, units/URL0301/URL0301_script.lua, units/URL0301/URL0301_unit.bp
- Fixes the toggle stealth button disappearing when you select a deceiver and a different stealth unit. Same issue occurs when selecting a personal shield unit with a shield structure.
- Stealth and cloak upgrades for ACU/SACU use separate togglecaps so they can be separately toggled.
- Stealth and cloak upgrades for ACU/SACU now use appropriate icons and help texts instead of only cloak:
Cloaking icon:
Personal stealth icon:
- Changes frequent warn to spew.
=> Small UI Fixes for Cybran Stealth

lua/keymap/hotkeylabels.lua
The toggle intel hotkeys work on toggling scrying, so I added the label.
The hotkey label requires a game setting to be turned on and looks like this:
=> Fix toggle intel hotkey label not appearing for toggle scry

lua/RemoteViewing.lua
_continuation of #5743_
The remote viewing script as a whole is a bit of a mess, but this attempts to address the clunky UX of trying to activate the ability when you have less than 10k energy in storage by being a drain event and a wait instead of a check and a take event.
~~Current issue with it though, is that this breaks the UI for the maintenance drain. (At least on the Steam version; the drain still happens, but it doesn't show on the unit.)~~
=> Eye of R-word target location cost rework

lua/aibrains/adaptive-ai.lua, lua/aibrains/medium-ai.lua, lua/aibrains/rush-ai.lua, lua/aibrains/tech-ai.lua, lua/aibrains/turtle-ai.lua
This PR fixes an issue with the BaseType that is set on AI bases when they are created.
Due to the marker name being used instead of the type the AI could never understand that it already had Naval bases which caused it to constantly make new ones. On naval maps this results in too many naval expansions being created.
This will have also caused issues with some of the UnitCountBuildConditions that also relied on this property being a specific string rather than a marker name.
This was deceptively hard to track down :)
The ramification of this change is that the AI's naval expansion will be weaker now as its not tuned correctly. It won't ruin its economy and cause the game slow downs on naval maps.
=> Fix incorrect property being set on BaseTypes

units/XEL0305/XEL0305_unit.bp
- Remove `COMMAND` which it cannot use because it does not have `SNIPEMODE` category.
- Prioritize structures over T1 mobile units because of its extremely low fire rate, in the same way as snipers.
=> Make Percival prioritize structures over T1 units

units/UAB4201/UAB4201_unit.bp
It could trigger on missiles that it can't possibly catch. The radius in which it can catch missiles is 22 ogrids.
https://github.com/FAForever/fa/assets/15778155/4746d18e-6b8b-46b2-aaba-c8419cf2c1b5
=> Reduce maximum attack radius of the Volcano

lua/ui/game/hotkeys/context-based-templates-data.lua, lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToEye.lua, lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToSoothsayer.lua, lua/ui/game/hotkeys/context-based-templates-data/CapOpticsWithPower.lua, units/XAB3301/XAB3301_unit.bp
It is always a good idea to cap these structures with t1 pgens:
- 1.43x more efficient than t3 pgens at 990 energy for 900 mass.
- Volatility isn't an issue at all for eye, and soothsayer can only be hit by the top and bottom pgens' death explosions, but it has only 500 HP anyway.
=> Add power generator templates for Eye and Soothsayer

changelog/3779.md, lua/SimCallbacks.lua, lua/options/options.lua, lua/sim/commands/shared.lua, lua/ui/game/commandmode.lua, lua/userInit.lua
Extends the ability to assist-to upgrade tech 1 extractors to also apply to tech 2 extractors. Adds the ability to assist-to upgrade radars tech 1 and tech 2 radars. Tech 2 extractors and radars only trigger when they receive _some_ adjacency bonus.
Fixes a bug where the unit would not be paused due to network lag.
Fixes a bug where the unit would be paused before the upgrade is applied, and therefore effectively not upgrade.
Adds various annotations to the user commands data structures.
=> Expand the assist-to functionality

lua/sim/Unit.lua, lua/sim/score.lua, lua/sim/units/AirUnit.lua, lua/system/dkson.lua
Fixes #5813. Caused by #4466.
The data is only collected at the end of the game as suggested in #4466.
@Askaholic do you want all the extra unit data? I noticed that transports, engineers, and SACU blueprint data can be interpreted, but it isn't used for anything. Also SACU presets have a different blueprint ID from the base SACU so they wouldn't work anyway. The transport and SACU achievements are done with the category data instead of blueprint data.
=> Fix achievements JsonStats message

lua/debug/uidebug.lua, lua/shared/statistics.lua
This PR orients itself on other, modern FPS counters, like the one Steam provides.
- The counter now takes up much less screen space
- The numbers do not constantly jump around anymore, as fixedFont is used instead of bodyFont
- Unnecessary decimal places have been removed
- The counter does not obstruct other UI-elements anymore
To access the FPS counter in-game, go to: Key Bindings --> Debug --> "Toggle the display of frames rendered per second"
=> Rework the FPS counter to be less obstructive and more modern

units/XEB2306/XEB2306_unit.bp
Point defenses usually don't friendly fire to allow them to be used as teleport defense/base defense in general. Ravager counterintuitively does allow friendly fire, which can cause a disheartening situation where your own Ravagers kill your SMD or game ender.
=> Remove friendly fire from Ravager

lua/ScenarioFramework.lua, lua/sim/Unit.lua, lua/sim/units/AirTransportUnit.lua, lua/sim/units/AirUnit.lua, lua/sim/units/MobileUnit.lua, projectiles/Sinker/Sinker_script.lua
If an aircraft/transported unit creates a wreck outside the playable area, the wreck position is moved back inside.
=> Fix offmapping wrecks

lua/options/options.lua, lua/ui/game/score.lua, lua/ui/override/ArmiesTable.lua, lua/ui/override/SessionClients.lua, lua/user/prefs.lua
Allows you to hide player names in the game. This is a local change, the client and/or other players are not aware of it and will see/show the actual player names.
=> Add feature to hide player names locally

lua/sim/NavUtils.lua
Reduces the table trashing that occurs when retrieving nearby sections. The improvements applies to:
- `GetPositionsInRadius`
- `DirectionsFrom`
- `DirectionsFromWithThreatThreshold`
=> Improve performance of navigational functions

lua/ui/lobby/lobby.lua
An attempt to combat the following situation where a lobby is crashed by embedding (a large amount of) characters into afield that is supposed to be used for the number of games:
=> Introduce additional lobby guards

lua/platoon.lua
This PR fixes an issue with the NavalForceAI platoon where it would make submarines surface when they were already submerged due to the IssueDive command acting as a toggle.
=> fix submarines surfacing at start of navalforceai 

lua/ui/lobby/lobby.lua
Makes the new AI rating estimate compatible with the hover-over text and game quality %
For simplicity standard deviation is set at 0
=> Ai rating trueskill

lua/ui/game/minimap.lua
Before this PR, you had to re-pin the minimap every game, as its pin-status would not be saved into your game.prefs file.
=> Fix the status of the minimap's pin feature not being saved into the game.prefs file

engine/User.lua, lua/keymap/hotbuild.lua, lua/ui/controls/worldview.lua, lua/ui/game/chat.lua, lua/ui/game/commandmode.lua, lua/ui/game/construction.lua, lua/ui/game/score.lua, lua/ui/game/unitview.lua, lua/ui/lobby/lobby.lua, lua/ui/lobby/lobbyComm.lua, lua/ui/notify/notify.lua, lua/ui/notify/notifyoverlay.lua, lua/ui/override/SessionClients.lua, lua/user/prefs.lua
The preference file can be accessed with `GetPreference`, updated with `SetPreference` and written to the disk with `SavePreferences`. These functions have some interesting side effects:
```lua
--- Retrieves a value in the memory-stored preference file. The value retrieved is a deep copy of what resides in the actual 
--- preference file. Therefore this function can be expensive to use directly - if you're not careful you may be allocating kilobytes worth of data!
---
--- You're encouraged to use `/lua/user/prefs.lua` to interact with the preference file.
---@param string string
---@param default any?
---@return any
function GetPreference(string, default)
end
```
```lua
--- Updates a value in the memory-stored preference file.
---
--- You're encouraged to use `/lua/user/prefs.lua` to …
```
=> Tackle performance issues when accessing the preference file

units/XEB0204/XEB0204_unit.bp
This previously only worked when the unit preview was disabled.
=> Enable the Tech 3 Kennel to be dragged when spawning it via the Alt + F2 menu

units/UAA0303/UAA0303_unit.bp, units/XAA0202/XAA0202_unit.bp
As reported on [Discord](https://discord.com/channels/197033481883222026/1204224371757944872), the Corona was not using the aiming solution. Therefore it would have a tough time aiming for units that are landed.
=> Fix Corona and Swiftwind having a tough time aiming at landed units

engine/Core.lua, lua/ScenarioFramework.lua, lua/sim/Unit.lua, lua/wreckage.lua
Most notable for units that have sink animations. This was because the world transform of a unit would be ignored while copying the pose for the wreck. The pose is now always copied when the unit is inside the map. For units that are outside the map you can't visually see the final pose and therefore it's less relevant.
Bug was introduced by https://github.com/FAForever/fa/issues/5832
https://github.com/FAForever/fa/assets/15778155/39d4cbc6-9155-42c2-a3cc-33c2c03e2310
=> Fix wrecks of sinking units ending up below the terrain

lua/sim/units/SubUnit.lua, units/UAS0203/UAS0203_unit.bp, units/UAS0304/UAS0304_unit.bp, units/UES0304/UES0304_unit.bp, units/URS0304/URS0304_unit.bp, units/XAS0204/XAS0204_unit.bp, units/XRS0204/XRS0204_unit.bp
A lot of submarines do not have a deck-gun, which makes surfacing them detrimental and a noob-trap. This PR removes the dive button for these units. Note, that Strategic Missile Submarines can launch missiles while submerged, surfacing them is not necessary.
=> Remove the dive button for units that do no not need it

lua/shared/teleport.lua, lua/ui/controls/reticles/teleport.lua
- Icons instead of text
- Display Energy cost/second
- Round time to 0.1 (0.01 does not fit in game ticks)
Before <br> ![4](https://github.com/FAForever/fa/assets/82986251/3b193dfa-ab52-4179-90ea-e52a1df12381) |After <br>  ![6](https://github.com/FAForever/fa/assets/82986251/8604a4f6-b93b-4f5c-befb-336156408fda) 
|:--:|:--:|
=> Improve Teleport Reticle Cost Display

lua/shared/teleport.lua
Teleport destination effects specifically. 0.4 is 10/25, based off the old 10 delay/25 total teleport time.
=> Fix teleport effects not appearing at short ranges with variable cost

engine/Core/Blueprints/UnitBlueprint.lua, lua/shared/teleport.lua, lua/ui/controls/worldview.lua, units/UAL0001/UAL0001_unit.bp, units/UAL0301/UAL0301_unit.bp, units/UEL0001/UEL0001_unit.bp, units/URL0001/URL0001_unit.bp, units/XSL0001/XSL0001_unit.bp, units/XSL0301/XSL0301_unit.bp
Adjusts the costs so that all teleports will take at least 15 seconds and consume at least 10k energy per second.
https://github.com/FAForever/fa/assets/15778155/85ee3767-bd4e-4375-84e0-cddd059c1711
=> Adjust the variable teleport costs

lua/sim/Prop.lua, lua/sim/Unit.lua
Relates to #5931 .
Refactors how the reclaim costs are computed, which then turned up an interesting 'bug' of the code: in practice it will never use the mass build cost but always the energy build cost of a unit because there are no units that cost more mass than they cost energy 😃
=> Refactor how the reclaim costs are computed

units/XSL0401/XSL0401_unit.bp
- Now faces towards its target when attacking to prevent the common situation of only one arm shooting at the target.
- Remove ACU priority from the Phason Beam Generator (the death-ball-shooting eye weapon) so that it doesn't waste its 1200 DPS on ACUs in experimental battles.
- Use flak priorities instead of T1 AA priorities on the secondary AA.
=> Improve Ythotha targeting

lua/ui/lobby/UnitsRestrictions.lua
Considering Novax's unique role as a support/precision artillery + intel unit, it shouldn't be covered by the air restriction. As for people who play with no air and are used to Novax being restricted, there is already a specific satellite restriction for Novax.
=> Remove Novax from air restrictions

engine/Core/Categories.lua, lua/formations.lua, units/UES0103/UES0103_unit.bp, units/UES0201/UES0201_unit.bp, units/UES0202/UES0202_unit.bp, units/UES0203/UES0203_unit.bp, units/UES0302/UES0302_unit.bp, units/UES0305/UES0305_unit.bp, units/XES0307/XES0307_unit.bp
Related to https://github.com/FAForever/fa/issues/5919
Introduces the WEAK... categories to various units. Also removes the NUKE category from the strategic bomber as it is... not a strategic unit.
What I found interesting is that the `ANTINAVY` category actually means `anti submarine`. Weapons that are anti navy are torpedo-like weapons.
=> Evaluate and rework the categories of UEF naval units

units/UEA0103/UEA0103_unit.bp, units/UEA0104/UEA0104_unit.bp, units/UEA0304/UEA0304_unit.bp, units/UEA0305/UEA0305_unit.bp
Related to #5919 
Introduces the `WEAK...` categories to various units. Also removes the `NUKE` category from the strategic bomber as it is... not a strategic unit. 
~~What I found interesting is that there's very little to no distinction between regular bombers and torpedo bombers. I was thinking of introducing a `TORPEDO` category to the torpedo bomber to make it more distinguishable. Now, of course - mods that are unmaintained will not follow this practice and therefore it would only apply to units we ship with FAForever directly.~~
edit: apparently the `ANTINAVY` category means 'something that fires torpedo's according to torpedo weapons and the categories of naval units, as seen in https://github.com/FAForever/fa/pull/5929. As a result, introducing `TORPEDO` is not necessary because …
=> Evaluate and rework the categories of UEF air units

lua/WeaponPriorities.lua
Writing a weapon priorities string in a readable format currently requires
```lua
priorityString = "COMMAND, STRATEGIC, MASSFABRICATION, " ..
"ENERGYPRODUCTION, MASSEXTRACTION, " .. 
"INTELLIGENCE"
```
which is clunky with all the concatenations. This PR makes it possible to write it much simpler as:
```lua
priorityString = [[COMMAND, STRATEGIC, MASSFABRICATION,
ENERGYPRODUCTION, MASSEXTRACTION,
INTELLIGENCE]]
```
=> Filter all whitespace from UI weapon priority strings

units/UAL0301/UAL0301_unit.bp, units/UEL0301/UEL0301_unit.bp, units/URL0301/URL0301_unit.bp, units/XSL0301/XSL0301_unit.bp
In the current branch, the projectile lifetime of three of the four SACUs is extremely low. This means, that at the edge of their effective ranges, their shots disappear in front of units before they can hit them. This is especially bad for the Seraphim SACU, as that one does not have an AOE upgrade (ignoring OC). The projectile lifetime for the Cybran SACU was excessive, so I reduced it to be more reasonable.
**Changes:**
ProjectileLifetimeUsesMultiplier: 1.15 --> 1.3 (Aeon; Seraphim; UEF)
ProjectileLifetimeUsesMultiplier: 2.4 --> 1.4 (Cybran) 
A higher multiplier is required for the Cybran SACU, as its projectile's muzzle velocity is lower.
Only relevant with the respective range-increasing upgrades.
=> Fix SACUs having less effective range due to low projectile lifetimes

units/URS0305/URS0305_unit.bp, units/XSB3202/XSB3202_unit.bp
**Flood XR:**
SizeX: 0.8 --> 0.9
SizeZ: 0.8 --> 0.9
**Shou-esel**
SizeX: 0.9 --> 1.2
SizeZ: 0.7 --> 1
Removed the `SHOWQUEUE` category
=> Fix the Cybran T3 and the Seraphim T2 Sonars being able to evade beam weapons

units/UAA0107/UAA0107_unit.bp, units/XSA0104/XSA0104_unit.bp, units/XSA0107/XSA0107_unit.bp
Fixes #2037.
Their footprints were much smaller than their hitboxes, so they wouldn't move far enough from the construction site, and would repeatedly lift off and land back in the same exact place until the construction order gave up.
=> Fix Aeon T1 and Seraphim T1/T2 transports blocking construction

lua/sim/Unit.lua
Resolves #5837. T1-T3 units in factories still spawn a wreck above 50% completion progress.
=> Make unbuilt structures and experimentals not spawn a wreck

lua/SessionInit.lua
From #5946.
It avoids arbitrary output from longer fields like the description. I have noticed a 1-2 second lag spike because of the large amount of text printed to the log, especially with mods including changelog fields in their mod.info (supreme scoreboard).
Example output:
```
INFO: Active mods in session:
INFO:         "Selection Deprioritizer"       v06 (bc7731b6-1416-11ea-8d71-362b9e155667) by partytime, changes by CodingSquirrel and Myxir
INFO:         "ZeP_MiniMapZoom"               v02 (5F593E02-FEF3-487C-916F-D6020903054B) by Ze_PilOt
INFO:         "Penguin's Icon Mod"            v02 (3ccc4eca-0cb1-11ec-ac65-a37599393411-02) by Emperor_Penguin
INFO:         "Ranges"                        v11 (71a26460-ec4e-11ea-adc1-0242ac120003) by Myxir, Anihilnine, BlackYps, Prophet
INFO: …
```
=> Reduce log spam from mod loading

engine/Core/Blueprints/WeaponBlueprint.lua, units/XSL0401/XSL0401_unit.bp
Reverts #5916 because AttackAngle caused Ythotha to constantly rotate, which looked ugly. Instead, uses a reduced `SlavedToBodyArcRange` to turn towards the enemy for all weapons to fire, while not constantly turning to maintain an exact angle. 32 arc range instead of 45 to give weapons plenty of space to lead their target.
AttackAngle is more for weapons that can't all fire forwards, like Fatboy and battleships, so using it for Ythotha was incorrect in the first place.
=> Correctly make Ythotha turn towards its target

units/UEL0401/UEL0401_unit.bp
An `AttackAngle` of 10 allows 3 weapons to fire only if the target is stationary. An in-game example of weapons not firing because of this would be a galactic colossus moving perpendicular to and towards the Fatboy at long range, which causes the back weapon to not fire. 20 angle is in the middle of the angle limits, so it should more often allow 3 cannons to fire, depending on unit speed/distance. It does solve the example with the GC.
https://github.com/FAForever/fa/assets/82986251/ed25d07d-00f6-480e-ae7c-7ad530f633cf
<details> <summary>Angle limits math image</summary>
Bone yaw + turret yaw + turret yaw range = actual yaw range. Then intersect all the ranges. The `HeadingArcRange` values are greater than the yaw ranges, so they have no effect and I didn't include them in this image. …
=> Improve Fatboy attack angle and give it a longer projectile lifetime

changelog/3802.md, lua/sim/Unit.lua
Fix for a bug where all experimental units have no wrecks.
Spawned in an experimental units and self-destructing them.
Related to: https://github.com/FAForever/fa/pull/5947
=> Fix experimental wrecks disappearing

changelog/3802.md, lua/userInit.lua
Adds a chat message send to all allies when a player self-destructs units. The chat message is also visible in the game log that is shown in the client, which is useful for moderators.
Spawn in and self destruct the units.
=> Add a message when units are self-destructed

changelog/3802.md, lua/SimCallbacks.lua, lua/ui/game/ping.lua, lua/userInit.lua
Adds a hidden chat message when a player creates a ping. The chat message is visible in the game log that is shown in the client, which is useful for moderators.
Create various pings and review the created sim callbacks.
=> Add a moderator message when pings are created

changelog/3802.md, lua/sim/commands/shared.lua
Reclaim orders are now applied similar to move orders are, there is no redundancy anymore. For a large chain of orders the full redundancy may cause a loss of orders.
https://github.com/FAForever/fa/assets/15778155/7e53be5d-dd4b-40c6-8dc8-b82911e6eaa0
As reported by Fichom on [Discord](https://discord.com/channels/197033481883222026/1212473389688823870)
=> Remove full redundancy from reclaim commands

units/UAA0310/UAA0310_unit.bp
This PR adds the ANTINAVY category to the CZAR to match its sub threat capabilities.
Validation of not causing obvious issues
@Garanas I'm not sure if this can cause issues with existing formation logic etc. The default AI already excluded experimentals for its air based antinavy platoon templates so there are no issues there. 
fixes #5988
This issue came about when creating an improved state machines for air based experimentals, it was found that the czar could not detect its anti naval capabilities using unit categories when flying over water so it could not be determined to attack naval units should it want to.
=> add antinavy category to CZAR UAA0310

engine/User.lua, lua/SimCallbacks.lua, lua/SimPing.lua, lua/SimSync.lua, lua/UserSync.lua, lua/keymap/misckeyactions.lua, lua/userInit.lua
Add better support for events that are interesting for moderators.
=> Simplify the setup for moderator events

changelog/3804.md, units/URS0202/URS0202_unit.bp
Currently, the Siren Class cruiser has the `REPAIR` category - presumably because it's an air staging platform that can repair aircraft. What this actually does is let it repair other units like an engineer, despite having no visual indication or defined build rate - it defaults to 1 and is incredibly slow. If this was intended, it would have been more clear with an appreciable build rate and effect (maybe even an animation, unit description line, or unit ability), but given the context, it appears to be a simple oversight.
*Notice the orange progress bar and 1 power drain - the damaged cruiser used to be at 30% health but is now at 32%*
=> Remove Siren `REPAIR` category

changelog/3804.md, units/XRL0305/XRL0305_unit.bp
The incorrect category I guess is from either copy-pasting the loyalist when GPG made the unit or a misunderstanding of how the torpedo defense should be categorized.
=> Remove `ANTIMISSILE` category from Brick

changelog/3804.md, units/UAS0102/UAS0102_unit.bp, units/UAS0103/UAS0103_unit.bp, units/UAS0201/UAS0201_unit.bp, units/UAS0202/UAS0202_unit.bp, units/UAS0203/UAS0203_unit.bp, units/XAS0204/XAS0204_unit.bp, units/XES0102/XES0102_unit.bp, units/XRS0205/XRS0205_unit.bp, units/XSS0201/XSS0201_unit.bp, units/XSS0202/XSS0202_unit.bp, units/XSS0304/XSS0304_unit.bp
Removes the `BUILTBYEXPERIMENTALSUB` category from various units.
The Tempest can still build these units just fine. Except units like the Seraphim cruiser of course, interestingly enough, this unit also had the category.
According to @The-Balthazar on Discord, this category is unused.
=> Remove the 'BUILTBYEXPERIMENTALSUB' category from various units

changelog/3804.md, units/UAA0310/UAA0310_unit.bp
This PR changes the previously added category of ANTINAVY to WEAKANTINAVY.
After some discussion I realised that non primary weapon types for units should have the weak variant of the category.
=> CZAR categories - remove antinavy and add weakantinavy

changelog/3804.md, lua/ui/game/hotkeys/context-based-templates.lua, units/XEB0204/XEB0204_unit.bp, units/XRB0204/XRB0204_unit.bp, units/XRB0304/XRB0304_unit.bp
Related to [this bug report on Discord](https://discord.com/channels/197033481883222026/1219563479581720577). The bug was that a tech 1 engineer can not create the storage template when trying to cap a tech 2 extractor because the tech 2 extractor would block the template as a tech 1 engineer can't build it. We fix that by trying to build the unit it upgrades from, or by trying to build the unit it originates from.
Next to that we extend the feature by allowing it to act like a color picker - if we're hovering over a unit or a build order and we can't find matching templates then we'll try to enter command mode with a build order for the given unit and/or blueprint order. This is inspired by the featured of @4z0t mentioned on the …
=> Fix a bug and extend the context based templates feature

changelog/3805.md, engine/Core/Blueprints/UnitBlueprint.lua, lua/ui/game/hotkeys/context-based-templates-data/AppendExtractorWithStorages.lua, lua/ui/lobby/changelogData.lua, lua/version.lua, mod_info.lua, units/UAB1202/UAB1202_unit.bp, units/UEB1202/UEB1202_unit.bp, units/URB1202/URB1202_unit.bp, units/XSB1202/XSB1202_unit.bp
Apparently the `UpgradesFromBase` is not just a field that is only read by Lua. It is also read by the engine and it can cancel an upgrade in the simulation. All intermediate units need the same field, which is what was lacking for tech 2 mass extractors because of https://github.com/FAForever/fa/commit/d0009a9b3cd7a71fb487859954a9fd331e105507 .
Spawn in and/or build extractors and try to upgrade them.
=> Add the `UpgradesFromBase` field to the tech 2 mass extractors

changelog/3806.md, units/XSB0102/XSB0102_unit.bp, units/XSB0202/XSB0202_unit.bp, units/XSB0302/XSB0302_unit.bp, units/ZSB9502/ZSB9502_unit.bp, units/ZSB9602/ZSB9602_unit.bp
`FlattenSkirt` needs to be set to `true`, as it is for all other Air Factories. Resolves #5460.
#4584 set this value to `false`.
=> Fix Seraphim Air Factories being harder to place than other factories

changelog/3806.md, lua/userInit.lua
When you observe a game and/or run a replay the unit to watch the build queue of would not be cleared out properly. As a result you'd randomly see build icons pop up where the construction menu is.
Introduced by: #5761
Run a game as an observer, see if `construction.lua/SetSecondaryDisplay` is called or not. It should not be called when you're an observer and your focus army is -1.
=> Fix lingering build queue icons

changelog/3807.md, loc/US/strings_db.lua, lua/ui/game/unitviewDetail.lua, units/UAL0001/UAL0001_unit.bp, units/UAL0301/UAL0301_unit.bp, units/UEL0001/UEL0001_unit.bp, units/XSL0001/XSL0001_unit.bp, units/XSL0301/XSL0301_unit.bp
**1. The `Range` and `Reload` stats should not be displayed for `Teleport in` weapons, as they do not make sense here. Also remove the `Reload` stat from `Kamikaze` weapons.**
The old output for `Teleport in` weapons:
```
Teleport in (Teleport) (Manual Fire)
Damage: 100, Splash: 4, Range: 0 - 1, Reload: 1.$
```
The new output for `Teleport in` weapons:
```
Teleport in (Teleport) (Manual Fire)
Damage: 100, Splash: 4
```
**2. Move the `Teleport in` weapons of Personal Teleporters to `Upgrades`, as this form of damage is only accessible via the enhancement after the initial gate-in.**
**3. Clarify the number of available enhancements.**
**4. Change the color of the DamageType `Overcharge` to green; change the color of Kamikaze weapons to a deeper shade of red.**
**5. Exclude countermeasures …
=> Various smaller fixes for unitviewDetail.lua

changelog/3807.md, lua/ui/notify/customiser.lua
Fixes a Discord bug report [(Notify menu missing Seraphim T4)](https://discord.com/channels/197033481883222026/1224605381116956762) by adding a nil check.
Nomads makes Notify save the following data in `game.prefs`:
```lua
Notify_Messages_ESC = {
...
experimentals = {
...
xnl0401 = '\\u41\\u74\\u6C\\u61\\u73',
xna0403 = '\\u43\\u72\\u61\\u77\\u6C\\u65\\u72',
xnl0402 = '\\u42\\u65\\u61\\u6D\\u65\\u72',
},
...
},
```
When back in FA, Notify fails to create the setting lines past the Novax line for the experimentals tab in the "Notify Management" window because it fails to find an alias for the Nomads blueprint ids from ClarityTable. This could be solved by adding the data to the `defaultmessages.lua` file (Nomads does), but then the Nomads experimentals would appear as options despite the …
=> Fix custom data in game.prefs breaking Notify management window

engine/Sim.lua, lua/SimCallbacks.lua, lua/proptree.lua, lua/sim/commands/area-reclaim-order.lua, lua/ui/game/commandmode.lua
Introduces an area-like reclaim command as a side effect to the standard reclaim command. Future iterations will allow the user to tweak (or disable) the behavior. The implementation is similar to an actual area reclaim command in BAR: the implementation attempts to add additional reclaim commands to props and/or structures that are similar to the entity that received the original reclaim command. 
The behavior is at the moment:
- For units, all adjacent units of the same type
- For tree (groups), all other tree groups in a very small radius that overlap
- For rocks and wrecks, all other rocks and wrecks in a decent radius that overlap
https://github.com/FAForever/fa/assets/15778155/fb00a688-2c7f-4fd2-bf08-c7052523a4a3
Click around and issue reclaim orders.
This is experimental.
=> Implement a basic area reclaim command

changelog/3809.md, units/UAB4202/UAB4202_unit.bp, units/UEB4202/UEB4202_unit.bp, units/UEB4301/UEB4301_unit.bp, units/XSB4202/XSB4202_unit.bp, units/XSB4301/XSB4301_unit.bp
**Tech 2 Shield Generators**
BuildRate: 13.66 --> 0 (Aeon) 
BuildRate: 12.98 --> 20 (Seraphim)
BuildRate: 19.95 --> 20 (UEF)
**Tech 3 Shield Generators**
BuildTime: 5841 --> 5800 (Seraphim)
BuildTime: 4988 --> 5000 (UEF)
- Time to upgrade a Seraphim Tech 2 Shield Generator: 04:50 (from 07:30).
- Time to upgrade a UEF Tech 2 Shield Generator: 04:10 (unchanged).
- The Aeon Shield Generator loses its BuildRate, as it cannot upgrade.
=> Rationalize the economy stats of various Shield Generators

env/Lava/Props/Trees/Dead01_s1_prop.bp, env/Lava/Props/Trees/Dead01_s2_prop.bp, env/Lava/Props/Trees/Dead01_s3_prop.bp, env/Lava/Props/Trees/Groups/Dead01_Group1_prop.bp, env/Lava/Props/Trees/Groups/Dead01_Group2_prop.bp, env/Lava/Props/Trees/LV_Dead01_s1_prop.bp, env/Lava/Props/Trees/XDead01_s1_prop.bp, env/Lava/Props/Trees/xDead01_s2_prop.bp, env/Lava/Props/Trees/xDead01_s3_prop.bp
This is an experimental change to allow studying the engineer behaviour when trees have no mass.
I only included the dead trees so far, these are an issue on Badlands, where they are interspersed with important rocks.
I can trivially add this change for other trees if wanted, because I had chatGPT write me a nice script to automate it.
This approach is way easier for testing than having to edit the armature as done in #6063 
This is intended to be used for testing on fafdevelop, it's not ready to be included in game patch at the moment.
=> Remove mass from dead trees and tree groups

env/Lava/Props/Trees/Dead01_s1_prop.bp, env/Lava/Props/Trees/Dead01_s2_prop.bp, env/Lava/Props/Trees/Dead01_s3_prop.bp, env/Lava/Props/Trees/Groups/Dead01_Group1_prop.bp, env/Lava/Props/Trees/Groups/Dead01_Group2_prop.bp, env/Lava/Props/Trees/LV_Dead01_s1_prop.bp, env/Lava/Props/Trees/XDead01_s1_prop.bp, env/Lava/Props/Trees/xDead01_s2_prop.bp, env/Lava/Props/Trees/xDead01_s3_prop.bp
Reverts FAForever/fa#6087 because this is already done with a mod in the vault.
Also it's "based on a misunderstanding and is not needed."
> BlackYps commented https://github.com/FAForever/fa/pull/6096#issuecomment-2066216851
I pinged you in discord, but actually keep this closed. It was based on a misunderstanding and is not needed
=> Revert "Remove mass from dead trees and tree groups"

changelog/3810.md, projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_script.lua
Fixes #6074.
Spawn an Ahwassa and a friendly ASF. Groundfiring the bomb at the ASF deals 1101 damage (10% of 11000).
=> Inherit all damage data in Ahwassa bomb script

changelog/3810.md, units/XSB1303/XSB1303_script.lua
Hopefully this also fixes this warning I sometimes see in replays, but I cannot promise it:
```warning: ToggleEnergyExcessUnitsThread: ...\gamedata\units.nx2\units\xsb1303\xsb1303_script.lua(35): attempt to call method `SetSpinDown' (a nil value)```
=> Fix a typo in the script file of the Seraphim Tech 3 Mass Fabricator

changelog/3810.md, changelog/snippets/balance.6141.md, units/DRL0204/DRL0204_unit.bp
**Hoplite: T2 Rocket Bot**
MuzzleVelocity: 20 --> 25
As discussed with the balance team.
=> Increase the muzzle velocity of the Hoplite's rockets

engine/Core.lua, engine/Sim/CAiBrain.lua, engine/Sim/CPlatoon.lua, engine/Sim/Unit.lua, lua/AI/AIBehaviors.lua, lua/AI/OpAI/BaseManager.lua, lua/AI/aibuildstructures.lua, lua/AI/sorianutilities.lua, lua/aibrain.lua, lua/aibrains/base-ai.lua, lua/aibrains/campaign-ai.lua, lua/shared/NavGenerator.lua, lua/sim/Builder.lua, lua/sim/Unit.lua, lua/system/utils.lua
Modifies several auxiliary files referenced by platoon.lua to accomplish annotation and warning fixes.
focus:
- Vector x/y/z fields and table.copy return type overload
- AIBrain field annotations (incl CustomUnits table)
- Unit field annotations
- EngineerBuilder field annotations
- @class ThreatFunctions table annotation (for NavGenerator)
- @class Marker table annotation (position marker used by AI)
- @class ScoutLocation table annotation (scout position marker used by AI)
- boolean->nil return type conversions where appropriate
- marks params/return values as optional when appropriate
- type corrections (ex: filename -> FileName)
=> platoon.lua annotation and warning fixes [auxiliary files]

changelog/snippets/fix.6157.md, lua/ui/lobby/lobby.lua
The function `string.len` computes the number of bytes, not the number of characters. Therefore one can have a relative long name even though it's only three characters. As a few examples that are in the database at this moment:
```
♂
☾⋆⁺
™¶€
•••
ФБК
еба
ΔLT
ΐ1
ƒ
Æ
º*º
±
©
J¢p
```
=> Allow up to 6 bytes in the clan name

engine/Core.lua, lua/ScenarioFramework.lua, lua/SimPing.lua, lua/SimPingGroup.lua, lua/aibrain.lua, lua/defaultantiprojectile.lua, lua/sim/MatchState.lua, lua/sim/ScenarioUtilities.lua, lua/sim/Unit.lua, lua/sim/weapons/DefaultProjectileWeapon.lua, lua/sim/weapons/OverchargeWeapon.lua, lua/simInit.lua, lua/ui/controls/worldview.lua, lua/ui/dialogs/saveload.lua, lua/ui/game/chat.lua, lua/ui/game/construction.lua, lua/ui/game/gamemain.lua, lua/ui/game/multifunction.lua, lua/ui/game/reclaim.lua, lua/victory.lua
Several functions define anonymous thread functions like `ForkThread(function() ... end)` which are low-hanging fruit to adding customization points by naming them. These threads are something that, were a mod were to want to change, would require replacing the entire function in addition to the thread function. This is unnecessary on our part, and increases such a mod's stiffness - which I have seen cause at least some parts of one mod to cease to function. While this won't help with anything already written, it is possible to prevent future bit rot.
=> Pull threads out of functions

changelog/snippets/fix.6185.md, engine/Core/Blueprints/ProjectileBlueprint.lua, engine/Sim/Projectile.lua, lua/sim/weapons/DefaultProjectileWeapon.lua, projectiles/AIFFragmentationSensorShell01/AIFFragmentationSensorShell01_proj.bp, projectiles/AIFFragmentationSensorShell01/AIFFragmentationSensorShell01_script.lua, projectiles/AIFFragmentationSensorShell02/AIFFragmentationSensorShell02_proj.bp, projectiles/AIFFragmentationSensorShell02/AIFFragmentationSensorShell02_script.lua
Issue:
Salvation undershoots, sub-fragment and sub-sub-fragment code is generally brittle and not blueprint dependent.
Fixes:
1. Adds a `FragmentRadius` blueprint value to the AIFFragmentationSensor projectile blueprints, and links the fragment initial velocity to the blueprint `InitialSpeed` value.
2. Calculates the ballistic acceleration of the (progressively slower) sub-fragments so they don't fall short of the target.
Tangentially related fixes:
- Fixes an error where the wrong reference was passed to the Econ thread in `DefaultProjectileWeapon.lua`
=> Salvation Undershoot Fix

lua/ui/lobby/lobby.lua
##Issue
If a sub-1.0 AiX modifier is chosen, the rating impact was modified by 1 / (AiX - 1) previously.  So for example, a 0.9 rating modifier would have 10 times the normal modifier applied as a negative amount, wheras a 0.6 modifier would have 4 times the normal modifier applied as a negative amount.  In other words, a 0.9 AiX would have a far worse rating than a 0.6 AiX.
This removes the code applying this - there is no need for such a modification.
Created a lobby and used 0.9 and 0.6 AiX modifiers.
For example, with this change, M28's ratings are (on a 5km map):
0.9 AiX: 521 rating
0.6 AiX: 156 rating
Without this change, M28's ratings are:
0.9 AiX: -3279 rating
0.6 AiX: -595 rating
=> Fix AI rating for sub-1.0 ratings

changelog/snippets/fix.6175.md, lua/ui/lobby/UnitsTooltip.lua
Fixes #5424 by rewriting unit tooltips using the Layouter. In addition, fixes localized empty strings appearing as empty parentheses in unit names (for example UEF mex in RU/US were "T3 Mass Exctractor ()"), and changes the buildtime display to just buildtime ticks instead of a convoluted MM:SS format.
100%: 
80%: 
150%:
Go to options -> interface -> UI Scale -> 150% and then open a skirmish -> options -> restrictions and mouse over the units in a circle to make sure all 4 variants of the tooltip work as expected (variants that move which corner of the tooltip is attached as to avoid going off the screen). Repeat for 80% and 100% scale.
=> Rework UnitsTooltip to use Layouter to fix its UI scaling

changelog/snippets/fix.6115.md, lua/ui/game/unitviewDetail.lua, units/DSLK004/DSLK004_unit.bp
BeamLifetime is in tenths, but was being rounded to ones BeamCollisionDelay could be set to weird numbers (ex: DSLK004). Continuation of #6115
Check the lightning tank's damage value in the UI, it should be 1400. Zapper remains at 1 damage.
=> Fix rounding in beam damage calculation

changelog/snippets/fix.6209.md, lua/system/Blueprints.lua
Water vision defaults to 10, which causes intel size warnings in the log every time blueprints are reloaded. For example:
```
warning: Intel radius of spawn_dummy_24_0-1_22 (= 10) for WaterVisionRadius does not match intel grid (4 ogrids), should be either 8 or 12
```
Reloading a blueprint no longer causes 40 lines of warnings about spawn dummy water vision not matching intel grid resolution.
=> Fix log spam from spawn dummies when reloading blueprints

changelog/snippets/balance.6211.md, units/XRA0305/XRA0305_unit.bp
It is very common for the Wailer's AA-missiles to expire before they are able to reach their target. This is because their MuzzleVelocity is extremely low (`13`) and their ProjectileLifetime (`2`) is not long enough for the acceleration stat of the projectile (see below) to have a meaningful impact. 
This PR gives them a higher lifetime, so the missiles have more time to reach a higher velocity. Their MuzzleVelocity is also increased, to slightly increase their effectiveness.
**Changes:**
MuzzleVelocity: 13 --> 22
ProjectileLifetime: 2.0 --> 2.4
The Wailer's AA-solution can now hit other air units more reliably. The missiles deal very low damage, so the balance impact of this is almost non-existent.
Relevant physics stats of the projectile (CAAMissileNanite03_proj; unchanged):
``` …
```
=> Buff/fix the Wailer's AA-missiles

engine/Sim/Unit.lua, engine/User.lua, lua/sim/Unit.lua
1. Adds annotations + description for user side `DeleteCommand` (novel!)
2. Add missing fields + moves class annotation definition of `UnitCommand` (table element returned by (`Unit:GetCommandQueue`) to file where the `GetCommandQueue` reference is defined.
=> Command Queue Annotations

changelog/snippets/features.6169.md, lua/sim/Unit.lua, lua/sim/commands/abort-navigation.lua, lua/sim/units/uef/TConstructionPodUnit.lua, lua/terranunits.lua, units/UEA0001/UEA0001_script.lua, units/UEA0003/UEA0003_script.lua, units/UEL0001/UEL0001_script.lua, units/UEL0301/UEL0301_script.lua
Continuation of #6169 which was accidentally made on the main branch.
=> Assisting engineers track new construction orders

changelog/snippets/fix.6216.md, lua/ui/game/unitview.lua
Non-startup layouts (when you change the layout with alt-up or alt-down) don't dock unit tooltip correctly, here the tooltip has sunk beneath the construction control:
Unlike other controls, unitview.lua does not fetch the current layout every time it uses it. Instead, https://github.com/FAForever/fa/commit/241c13cf4198d6aa81f70251eae615627a934451 introduced an optimization to only load the layout on startup into a variable and then call its methods through the variable. The optimization was motivated by the fact that unitview calls the layout methods in an OnFrame function and fetching it on each frame would be expensive.
The main fix is to update the layout variable in SetLayout().
In addition to that:
* Set the initial value of the variable to nil since we don't depend on whatever the …
=> Fix unit tooltip docking for non-startup layouts

.github/workflows/spookydb-update.yaml, .github/workflows/unitdb-update.yaml, changelog/snippets/other.6223.md
Adds two workflows to automatically update the unit viewers when content is pushed to `deploy/faf`
- [SpookyDB](https://faforever.github.io/spooky-db/#/)
- [UnitDB](https://unitdb.faforever.com/)
Run the workflows and review the actions.
- Action that correctly updates SpookyDB: https://github.com/FAForever/fa/actions/runs/9331392303
- Action that correctly updates UnitDB: https://github.com/FAForever/fa/actions/runs/9331576973
With thanks to @Sheikah45, @relent0r and @MrRowey for their time and effort to related contributions and pair programming!
=> Create workflows to update unit viewers

.github/workflows/changelog.yaml, .github/workflows/wiki-generate-blueprints.yaml, .github/workflows/wiki-generate-changelogs.yaml, .github/workflows/wiki-generate-icons.yaml
The responsibility is reduced to just converting and uploading the converted icons as an artifact. This allows it to be re-used in other workflows.
=> Generalize workflow to convert and upload (strategic) unit icons

lua/ui/game/gameresult.lua, lua/userInit.lua
Moderator events are now delayed by 2 seconds by default. This is to prevent the generation of events as players are trying to disconnect. During local testing the events would show for the player leaving, but not for the players still in-game.
Adds a new moderator event: everything that is passed into `GpgNetSend` is also turned into a moderator event. This way we know what people are (not) sending to the server.
Run local multiplayer games.
Related to https://github.com/FAForever/faf-java-commons/issues/121
=> Update and add moderator events

.github/workflows/test.yaml, .github/workflows/update-fafdevelop.yaml
This workflow will sync `deploy/fafdevelop` with whatever is on `develop` every Thursday at 21:00.
Part of switching back to using `develop` as our default branch.  This workflow reduces the burden on the game team to keep `deploy/fafdevelop` in sync.
=> Add a workflow to periodically update `deploy/fafdevelop`

changelog/snippets/fix.6234.md, lua/sim/Unit.lua
Fixes a [bug reported on discord](https://discord.com/channels/197033481883222026/1234260183719608392). Caused by 97cb6ecfab.
Partially building a unit and reclaiming it returns all the resources used.
=> Fix reclaiming unbuilt units not giving back resources

changelog/snippets/fix.6232.md, projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
Instead of homing in on their target, the depth charges simply drop to the bottom of the ocean after they hit the water. This renders them practically useless.
This PR enables the Czar's depth charges to track their target again. Once they have entered the water that is.
=> Enable the Czar's depth charges to function again

changelog/snippets/fix.6224.md, units/URL0001/URL0001_unit.bp
Adds `EnabledByEnhancement = "Teleporter",` to the teleport weapon of the Cybran ACU, so it is displayed under 'Upgrades' and not 'Basics' when `Show Armament Detail in Build Menu` is enabled in the settings.
This is already the case for the other ACUs.
=> Fix the Cybran ACU's teleport weapon being displayed under 'Basics' in uvd

changelog/snippets/fix.6222.md, lua/ui/lobby/lobby.lua
Fixes #6219. Also fixes being able to try to kick the team rating row when there are 3+ teams.
Open two instances of the game. Host multiplayer LAN on a specific port, and connect to localhost:thatport on the other instance (automatic port and discovery doesn't seem to work). Move the second player to observer, and add AIs to change the team sizes (set auto teams to None). Test being able to pop up the kick dialogue only when clicking the observer in all combinations of spawns fixed/not fixed and having 0-3 teams.
=> Fix not being able to kick observers in team games

.github/pull_request_template.md, changelog/snippets/ai.6083.md, changelog/snippets/balance.6202.md, changelog/snippets/features.5948.md, changelog/snippets/fix.6142.md, changelog/snippets/other.6147.md, wiki/changelog-fafdevelop.sh
- Rearrange changelog headings slightly, `balance` and `features` are now mentioned first.
- Minor fixes/improvements to the changelog snippets.
- Very minor update to the PR-template.
=> Further tweaks to the changelog

changelog/snippets/fix.6215.md, lua/sim/units/MobileUnit.lua
fixes #2725
Prevent mobile units (engineers) from building enemy buildings. This typically happens when two engineers of the same faction are given a build order to the same resource spot.
Spawn two engineers of a given faction, give them an order to build a mex/hydro on the same spot. Previously whichever engineer arrived second would assist with constructing the enemy structure; now they clear their command queue instead.
=> Add IsAlly check to MobileUnit OnStartBuild

changelog/snippets/fix.6245.md, lua/ui/dialogs/mapselect.lua
Makes the warning that you get when a map's scenario file has incorrect map/save/script files defined more clear.
Also fixes the error when that part of the code runs and tries to call non-existent methods with `mapplayers` and `mappsize`, which aren't used anywhere in the file.
Message before:
```
warning: No scenario map file defined
warning: Error running OnRelease script in <deleted object>: ...\fa\lua\ui\dialogs\mapselect.lua(429): attempt to call method `SetText' (a nil value)
...\fa\lua\ui\dialogs\mapselect.lua(429): in function `PreloadMap'
...\fa\lua\ui\dialogs\mapselect.lua(438): in function `OnClick'
...\fa\lua\ui\dialogs\mapselect.lua(491): in function `OnClick'
...\fa\lua\maui\button.lua(118): in function <...\fa\lua\maui\button.lua:112>
```
New message:
``` …
```
=> Improve details of warnings when map files are missing

changelog/snippets/fix.6256.md, projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
Fixes a typo that made Billy nuke deal 25 damage on the outer radius instead of 250.
Units on the outer range take 250 damage.
=> Fix Billy dealing wrong outer ring damage

changelog/snippets/balance.6252.md, changelog/snippets/fix.6252.md, tests/blueprint/unit.spec.lua, units/UAA0310/UAA0310_unit.bp, units/UEB2204/UEB2204_unit.bp, units/UEL0202/UEL0202_unit.bp, units/URS0202/URS0202_unit.bp, units/XAA0305/XAA0305_unit.bp, units/XRL0403/XRL0403_unit.bp, units/XSA0203/XSA0203_unit.bp
Fixes the fire rate test to account for banker's rounding (tie break towards even numbers), and corrects erroneous fire rate changes from #5845.
Set my ACU's fire rate to 4/0.8 and added a log statement when the projectile is created to make sure it fires every 2/12 ticks.
=> Fix issues with fire rate test related to rounding tie-breaking towards evens

.github/DEPLOYMENT.md, .github/workflows/deploy-faf.yaml, .github/workflows/deploy-fafbeta.yaml, .github/workflows/deploy-fafdevelop.yaml
Adds additional workflows to manage the deployments to the various deployment branches. All maintainers can trigger these workflows, ideally the workflow to `deploy/faf` requires an approval of at least one different maintainer.
To deploy to the FAF game type should require approvals from at least a different maintainer that triggered the deployment.
=> Add additional deployment workflows and documentation

changelog/snippets/fix.6258.md, lua/ShieldAbsorptionValues.lua, lua/shield.lua
Sets shield absorption of overcharge damage type to 1.0 by default. So that units do not take damage from OC when standing at the edge of a shield.
Shoot a UEF bubble shield or any static shield and they take 400/800 damage without letting through any damage to nearby units underneath.
Cherry picked from #6257, further details on the armor multiplier comment there.
=> Make shields absorb full overcharge damage

changelog/snippets/fix.6243.md, lua/ui/game/layouts/unitview_left.lua, lua/ui/game/layouts/unitview_mini.lua, lua/ui/game/layouts/unitview_right.lua, lua/ui/game/unitview.lua
The top part of the tooltip is the queue. It can be enabled in Options->Interface->Additional Information->Show Factory Queue on Hover.
The issue is that the _left and _right layouts are missing the layouting logic for the queue.
Fix:
* Moved code that handles internal layout/graphics of unit tooltip queue from unitview_mini.lua SetLayout() to unitview.lua CreateQueueGrid(). This leaves only the two LayoutHelper calls that "dock" the queue display to the unit tooltip itself. Even though this docking should be the same for all layouts it makes sense to duplicate them in all SetLayout() implementations from the readability standpoint.
* Moved the code that assigns themed textures to controls.queue.SetThemeTextures(). Added a call to SetThemeTextures()
* Duplicated the logic that docks unit …
=> Fix production queue tooltip in non-default layouts

changelog/snippets/features.6282.md, engine/User/UserUnit.lua, lua/ui/game/unitview.lua
Displays the mass/energy production of a unit as a decimal value in the unit viewer, with appropriate precision for the number. This makes the effects of adjacency more visible. 
Idea first popped up on [Discord](https://discord.com/channels/197033481883222026/1224799508249055395/1226247496112799855), but this uses the new engine patch for `GetRolloverInfo` (https://github.com/FAForever/FA-Binary-Patches/pull/75) instead of the `UserUnit:GetEconData` that I'm assuming was used in that example.
Before testing, make sure to go to the client and launch a FAF Develop lobby to download the latest exe.
Spawned an air grid with fabs/radars/storages and moused over the various buildings and over the factories building different units to make sure that how the numbers are displayed makes sense. …
=> Display economy values as decimals in unit viewer

lua/system/blueprints-units.lua
Caused by #6273. Intel was not being put into the intel tables used for the intel state table because of a bad order of operations on some booleans.
`UI_Lua LOG('number' ~= 'table')` prints true, while `UI_Lua LOG(not 'number' == 'table') prints false. Enemy radar blips show up ingame.
~~- [ ] Changes are annotated, including comments where useful~~
~~- [ ] Changes are documented in the changelog for the next game version~~ Not necessary.
=> Fix intel state not being assigned

lua/system/utils.lua
Fixes in-game blueprint reloading crash caused by #6273 ([specific diff](https://github.com/FAForever/fa/pull/6273/files?diff=unified&w=0#diff-36fc4661c2ca0ef4424b14ce65a6831bb9c6b5b78cf99ae96d9051263f71c676L311-R311)) from `blueprints-units.lua:311` due to spawn dummies having `CommandCaps = "0"`. Instead of checking for nil, checks for the value to be a table.
The function could use a better annotation if possible.
The game no longer crashes when reloading blueprints during a session.
~~- [ ] Changes are documented in the changelog for the next game version~~ Not necessary.
=> Improve guards for `table.copy` to fix blueprint reloading crash

changelog/snippets/fix.6285.md, lua/ui/game/hotkeys/context-based-templates-data/AppendAirGrid.lua
https://github.com/FAForever/fa/assets/15778155/3dc4217c-f710-4498-a1d8-a9a08e832389
Drag-build an air grid template.
=> Fix sub-optimal drag build of the air grid template

changelog/snippets/ai.6286.md, lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua, lua/platoontemplates.lua
This PR fixes a small error in the AI platoon build templates. The T2LandAmphibious was set to build the Aeon Aurora instead of the Blaze.
Validated that the correct unit was being built post change
According to the file history this error has been there for YEARS :D I even went back and checked the original SCFA lua files, the error was present then too.
=> AI - Fix incorrect unit set in T2LandAmphibious factory build template

changelog/snippets/graphics.5810.md, effects/terrain.fx
I discovered that rotating some texture layers makes the repeating texture pattern less visible.
Now not all textures are aligned in the same direction and the 30° rotation from the horizonal/vertical grid also seems to make it harder for the eye to notice repeating features.
The effect is not amazing, but it's almost free, so it still seems like a good deal.
The only question is, on which shaders do we want to apply that?
Before:
After:
=> Rotate every other texture layer

changelog/snippets/fix.6293.md, lua/aeonweapons.lua, lua/cybranweapons.lua, lua/seraphimweapons.lua, lua/terranweapons.lua
Xtreme Wars was unable to hook the aeon weapons file because of a missing field that was not carried over in https://github.com/FAForever/fa/pull/5659.
The game doesn't instantly give errors when you play Aeon with Xtreme Wars enabled.
=> Fix mod backwards compatibility in Aeon weapon files

effects/emitters/aeon_chrono_dampener_large_02_emit.bp, effects/emitters/aeon_chrono_dampener_large_04_emit.bp
Due to #5883, Chrono's effects are visible through fog of war.
Use LOD instead of making the effects always visible. The 1100 LOD makes it always visible from a max zoomed out view on a 10 km map, and for 20 km maps, visible if about 1/4th of the map is visible. This is appropriate for the huge AoE Chrono has: it's larger than a nuke's inner radius. It's still weaker than a nuke, so it doesn't have unlimited LOD.
I used the emitter editor to make the changes so the file format is changed.
Build a chrono ACU and have it groundfire. Zoom out to see the effects are visible at a reasonable zoom level. Switch to civilian army and turn on fog of war to check that the effects don't emit if the ACU is not visible.
=> Use LOD instead of always emitting for Chrono visuals

changelog/snippets/fix.6311.md, units/UAA0310/UAA0310_script.lua, units/UAA0310/UAA0310_unit.bp, units/XSA0402/XSA0402_script.lua, units/XSA0402/XSA0402_unit.bp
Ahwassa/CZAR deals 1000 damage in 5 radius due to a line in its script, which makes that information unknown to the user because it is not in the blueprint.
Removes the scripted damage and adds it to the blueprint. This results in:
- high damage area radius: 5 -> 10 (Ahwassa) / 15 (CZAR)
- high damage area damage through Seraphim T3 shields: 1000 (constant) + 2800 (reduced by shields) -> 3800 (reduced by shields)
- The shield choice is relevant because shields can reduce crash damage by up to 20% of their max HP. That means the max crash damage reduction in normal games is `21k * 0.2 = 4200`. 3800 damage under shields keeps the ability to one shot SMDs with crash damage.
- high damage against unshielded targets: remains the same
Crashing these air T4s through shields deals expected …
=> Move hidden crash damage out of Ahwassa and CZAR scripts

changelog/snippets/fix.6291.md, lua/ui/game/layouts/unitview_left.lua, lua/ui/game/layouts/unitview_mini.lua, lua/ui/game/layouts/unitview_right.lua
Before:
After:
I have changed the unit view positioning in replays for the mini layout to the same as the right layout, which is effectively an identical layout because they differ only in:
1) The orders control position but there is no orders control in replays.
2) The clipping issue itself, which I assume is not intended :)
In order to achieve that, I have added a condition that checks whether the orders control exists.
Additionally, I have moved imports in layouts to the top of the file since that is tradition, it avoids import duplication in some cases and it is theoretically faster (it saves up to 30% processing time of the PositionWindow() method, but that still amounts to nothing in the grand scheme of things).
No changes to non-replay positioning of the mini layout:
Replay …
=> Fix unit view clipping in replays for the mini layout

changelog/snippets/other.6310.md, lua/simInit.lua, lua/system/logger.lua, lua/ui/game/gamemain.lua, lua/userInit.lua
Removes the sim-based game time logger. Introduces a ui-based game time logger. This allows us to make the logging more relevant by including the session time and the heap usage.
Start a game and observe the log. It should contain entries such as:
- `DEBUG: Session time: 00:35:01	Game time: 00:09:33	Heap: 288.0M / 253.2M`
It's also a great reminder to take a break as a developer when the session time reaches more than two hours. This is a common feature in games such as the [Anno series](https://www.reddit.com/r/anno/comments/10bjtbl/anyone_has_the_list_of_2_hours_reminders/) which we now make available for developers. Time to stretch those legs!
=> Enhance the periodic logging to help understand memory usage

changelog/snippets/features.6095.md, lua/ui/controls/draggers/radial.lua
The radial dragger appears under the mouse when the mouse stays still.
Hides the dragger on init if minimum distance > 0.
The radial dragger does not appear for attack move when the mouse isn't moved.
=> Fix radial dragger appearing when mouse isn't moved

engine/Core/Blueprints/WeaponBlueprint.lua
I asked @Hdt80bro about it and he doesn't know why the annotation was written this way. It's well known that all weapons can fire in cylinders and that spherical range doesn't exist in the game.
=> Correct the annotation for MaxHeightDiff

changelog/snippets/fix.6335.md, lua/platoon.lua
Previous change meant :GetPlan() no longer worked on platoons
The pull request 6083 changed various parts of platoon.lua:
https://github.com/FAForever/fa/pull/6083/files
One of these was changing "if not self[plan] then return end" to:
"if not plan or self[plan] then return end"
I.e. it was aborting if self[plan] was not nil, when the intent was presumably to abort if it was nil
Without this change - tested on M27, it has an error that breaks the mod (since it relies on :GetPlan() which returns nil for its platoons); Also confirmed such an error didn't occur on the FAF release in April 2024 (before PR 6083).
With this change - re-ran a replay where M27 was broken and it works again.
=> Fix platoon bug introduced in 6083

changelog/snippets/fix.6321.md, units/XSB2401/XSB2401_script.lua
Fixes the visual issue where the missile stays underground after being transferred, even though the missile can be partially/fully built.
Play with an AI on my team then spawn a Paragon, Yolona, and a bunch of hives then transfer the Yolona around to see that the missile stays in the correct position after transfer.
=> Update Yolona's missile position after changing army

changelog/snippets/fix.6342.md, lua/aibrains/components/StorageManagerBrainComponent.lua
Fixes a rather invisible bug from https://github.com/FAForever/fa/pull/6263 .
The logging when the `pcall` fails is disabled at the moment. Luckily, the errors are caught and registered by the c-debugger. The tables with unit references in them are cleaned up automagically by the garbage collector, but there can be a few ticks in between the unit dying and the unit being collected. In those few ticks it can generate various errors.
```
@c:\programdata\faforever\replaydata\gamedata\lua.nx2\lua\aibrains\components\storagemanagerbraincomponent.lua 179
CObject:.?AVCAiBrain@Moho@@, CFunc, "EconMidMassStore", "EconMidEnergyStore"
@c:\programdata\faforever\replaydata\gamedata\lua.nx2\lua\aibrains\components\storagemanagerbraincomponent.lua 187
CObject:.?AVCAiBrain@Moho@@, "EconMidEnergyStore", …
```
=> Add guards to verify that the unit instance still exists

changelog/snippets/fix.6345.md, lua/sim/weapons/DefaultProjectileWeapon.lua, lua/sim/weapons/uef/TIFCarpetBombWeapon.lua
Related to this [forum post](https://forum.faforever.com/topic/7889/improve-area-attack-and-reclaim-orders-6095-bug) and [this Discord post](https://discord.com/channels/197033481883222026/1261072611904061471).
Weapons now properly use the `AttackGroundTries` field because of https://github.com/FAForever/fa/pull/6277. For the average unit this is fine, but for bombers and specifically bombers with multiple projectiles per salvo it introduced an unusual problem: the first projectile would aim at the current target. All remaining projectiles may aim at the next target. This doesn't apply to all bombers, but in particular the UEF Tech 1 bomber (Scorcher) fell victim to this bug. 
When the bug happens we end up in an unstable state. To the user this would show as:
- (1) A bomber with a weapon …
=> Fix a bug that could freeze up a weapon and even the simulation

docs/development-start-here.md, docs/development-start-here/lua-debugger.md, docs/development-start-here/lua-setup.md, docs/development-start-here/lua-syntax.md, docs/development.md
Improves the documentation by separating out the topics into separate pages that are all clearly marked as introductionary.
=> Improve the 'start here' documentation

changelog/snippets/features.6363.md, lua/SimUtils.lua
Resolves #6361.
- Changes the categories for structure transfer from T4s and T3 Arty to all units. 
- Adjusts the stats of the wreckage created when a unit rebuild fails so that the wreckage has the full mass of the failed unit.
Spawn a paragon and some t3 engineers (they dont shoot) then build any unfinished structure or unit from a factory and run the console command to transfer the units to the opposite of the current focused army:
```lua
SimLua 
local units = ArmyBrains[GetFocusArmy()]:GetListOfUnits(categories.ALLUNITS)
local SimUtils = import('/lua/SimUtils.lua')
local target = GetFocusArmy() == 2 and {1} or {2}
ForkThread(SimUtils.TransferUnfinishedUnitsAfterDeath, units, target, false)
```
All structures get shared properly, and unbuilt units in factories turn into wrecks of the …
=> Transfer all unbuilt units on death

changelog/snippets/fix.6364.md, lua/sim/units/CommandUnit.lua
Select an ACU and an SACU then enable auto OC, it will crash:
```
ACCESS_VIOLATION: Read from 0x00000090
EAX: 0x00000000, EBX: 0x00000000, ECX: 0x00000090, EDX: 0x77B1F5F0
ESI: 0x00000000, EDI: 0x00000000, EBP: 0x55F4EBD8, ESP: 0x55F4EBB8
Stacktrace: 0x00000090 ntdll.dll+0x000AF5D0 ntdll.dll+0x000AF59F ntdll.dll+0x0006D3FE 0x00909148 0x00A824C0 ntdll.dll+0x0007A9CA KERNELBASE.dll+0x001589FE
LUA Main thread
@c:\programdata\faforever\gamedata\lua.nx2\lua\simcallbacks.lua 54
"AutoOvercharge", Table, Table, 1218.323608, Func:@c:\programdata\faforever\gamedata\lua.nx2\lua\simcallbacks.lua 117
@c:\programdata\faforever\gamedata\lua.nx2\lua\simcallbacks.lua 58
Table, Table, CFunc, Table, 12, CObject:.?AVUnit@Moho@@ ID:418 BpName:url0301_cloak …
```
=> Fix crash when enabling auto OC on non-sera SACU

.github/workflows/changelog.yaml, .github/workflows/docs-build.yml, docs/changelog.md, docs/changelogs/fafbeta.md, docs/changelogs/fafdevelop.md
Extends the changelog workflow to generate a workflow from a specific reference (branch/tag). This allows us to generate a changelog from `deploy/fafdevelop` or `deploy/fafbeta`. As we build the pages, we can then update the pages dynamically.
=> Setup for automatically generating changelogs of deployment branches

.github/workflows/changelog.yaml, .github/workflows/docs-build.yml
The scripts may not live in the same Git reference as the snippets. We now always retrieve the scripts from `develop`, while we retrieve the snippets from the designated branch.
We need to do a little string manipulation because artifacts do not support `/` in the file paths. In practice [expressions](https://docs.github.com/en/actions/learn-github-actions/expressions) in GitHub only allows you to add to strings, but it does not allow you to remove things from it. Ideally we'd use [startsWith](https://docs.github.com/en/actions/learn-github-actions/expressions#startswith) in combination with removing the first seven characters. But we can't, so now we have this odd and extensive if expression 😃 !
=> Separate the scripts and the data of the changelog generation workflow

.github/workflows/changelog.yaml, .github/workflows/docs-build.yml, .github/workflows/scripts/changelog-combine.sh, test-draft.sh
Removes the `deploy/` from the reference if it exists. In general, the reference (indirectly) used as part of a file name and that can't contain the character `/`.
=> Finalize the automagic changelogs for the deployment branches

docs/patches.md
Relative URLs are a little shaky because the base url is different between a development (no base url, therefore `/`) and a production environment (base url is `/fa`). This was a little tricky to understand since I did not know what to search for. It turns out that Jekyll has a [filter](https://jekyllrb.com/docs/liquid/filters/) for this called `relative_url`, which manages all of this for you.
=> Apply the relative URL filter for relative URLs in the documentation

docs/_posts/2024-08-03-3811.md
=> Slightly improve the formatting of 2024-08-03-3811.md

.github/workflows/docs-build.yml, .github/workflows/scripts/changelog-links.sh
Closes #6376
This PR updates the docs-build.yml workflow to update md files that include PR references.
It will loop through all files in the
docs/patches
docs/_posts
directories and rewrite any PR references using the #xxxxx expression and add the PR link.
The script takes 4 parameters. This is so it can be used with other repositories / environments in the future.
FOLDER_NAME - Where the md files are located
ORG_NAME - The github org name
REPO_NAME - The repository name
BASE_HOSTNAME - github.com
=> feat : Update docs-build to include PR link rewrites

.github/workflows/deploy-faf.yaml, .github/workflows/deploy-fafbeta.yaml, .github/workflows/deploy-fafdevelop.yaml, lua/globalInit.lua, lua/shared/components/DebugComponent.lua, lua/version.lua
Embed the hash and game type into the game by processing the files just before we deploy them. For now we can log this information to make it easier to understand for the developerat what commit a replay was. In the future we can use the same data to inform the host that a new game version is available and that he should restart.
I ran the bash scripts manually by copying them into a bash interpreter.
Users always experience a (short) duration of desyncs when a release happens. And in general, users are unaware of the exact version that resides on the FAF Develop and FAF Beta Balance game types
=> Add information about the game type and commit hash to the game

changelog/snippets/other.6399.md, engine/Sim/Projectile.lua
Document the support for method chaining of the projectile engine methods. I noticed this behavior as I was working on #6398.
I called every function and checked the output of the log with logging the instance. If the references match then the function supports method chaining.
```
LOG(self) -- returns memory reference
LOG("ChangeDetonateAboveHeight", self:ChangeDetonateAboveHeight(0)) -- returns nil
LOG("SetLifetime", self:SetLifetime(10)) -- returns memory reference
```
=> Update annotations of engine projectile methods

changelog/snippets/fix.6398.md, lua/sim/Projectile.lua
If you pass in an invalid value to `SetBallisticAcceleration` then the simulation will freeze up. This is a bug in the engine, but we can 'fix' it in Lua by simply error'ing out if we see such a value.
Ran a game and tested/confirmed that regular values are untouched and all variants of invalid values are caught.
Possibly related to:
- https://forum.faforever.com/topic/8022/replays-of-games-stuck-in-infinite-loop/1
=> Fix being able to pass through invalid ballistic values

.github/workflows/deploy-faf.yaml, .github/workflows/deploy-fafbeta.yaml, .github/workflows/deploy-fafdevelop.yaml
By experience I know that multiple deployments in quick succession tend to not end up deploying. A commit to any of the `deploy/` branches is sufficient to trigger the deployment. The mistake is trivial to make as I just did it by accident:
Which resulted in:
With these changes the workflows should cancel when they detect there are concurrent workflows.
=> Prevent simultaneous deployments across all branches

lua/globalInit.lua, lua/ui/game/score.lua, lua/ui/game/tooltip.lua, lua/ui/lobby/lobby.lua
Displays the game version information in the lobby and in the (default) scoreboard.
Launch the game and review the information that is displayed.
This should make it much more trivial for developers to understand at what commit a replay is running. It intentionally does **not** include the generated commit by the deployment branches, see also #6401 .
Note that these values default to 'unknown' as you develop. They are populated in the deployment workflows, see also:
-- - https://github.com/FAForever/fa/blob/develop/.github/workflows/deploy-faf.yaml
-- - https://github.com/FAForever/fa/blob/develop/.github/workflows/deploy-fafbeta.yaml
-- - https://github.com/FAForever/fa/blob/develop/.github/workflows/deploy-fafdevelop.yaml
=> Display game version information to the user

changelog/snippets/fix.6404.md, lua/SimUtils.lua
Fix the duplication of upgrading units on transfer. `IsUpgrade` seems to be the most correct way to check for a unit being an upgrade from what I've found in the repo. It is set here in `Unit.OnStartBuild` (`built.IsUpgrade`):
https://github.com/FAForever/fa/blob/2158d74b7d63e0e65ae17d1b71b6b81a1a5e458f/lua/sim/Unit.lua#L2814-L2824
Use this console command to inspect the unit data:
```lua
SimLua 
local units = ArmyBrains[GetFocusArmy()]:GetListOfUnits(categories.ALLUNITS)
for _, unit in units do
LOG('Unit: ', unit, unit.Blueprint.BlueprintId, 'DefWorkOrd: ', unit:GetCurrentDefaultWorkOrder(), 'Unitbeingbuilt: ', unit.UnitBeingBuilt, 'originalBuilder: ', unit.originalBuilder)
LOG('Am I being upgraded?', unit.originalBuilder and not unit.originalBuilder.Dead and …
```
=> Filter out upgrade units from being rebuilt on transfer

docs/_sass/color_schemes/faf.scss
As per the title. Currently, h2 has a higher weight than h1, which looks a bit odd.
=> Github.io changelog: increase the font-weight of the level 1 heading

changelog/snippets/fix.6432.md, lua/aibrain.lua
Reported on [Discord](https://discord.com/channels/197033481883222026/1277749416878669925). Replay [23190625](https://replay.faforever.com/23190625).
```
WARNING: Error running lua script: ...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(498): bad argument #1 to `getn' (table expected, got no value)
[C]: in function `getn'
...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(498): in function <...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua:479>
...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(526): in function `TransferUnitsToHighestBrain'
...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua(608): in function <...aforever\replaydata\gamedata\lua.nx2\lua\aibrain.lua:440>
```
The game tried to transfer units to a defeated player which causes the …
=> Fix error when full share transfers units to a dead player

changelog/snippets/fix.6447.md, lua/RuleInit.lua, lua/globalInit.lua
`repr` cannot be used in `blueprints.lua` due to upvaluing `string.match` before it exists.
Reported on [Discord](https://discord.com/channels/197033481883222026/832710161847287819/1284328122103103578):
```
warning: Problem Blueprints Loading: modded files from "Endgame Prime" mod: /mods/endgameprime/effects/emitters/cybran_teleport_charge_01_emit.bp:
warning: ...mdata\faforever\gamedata\lua.nx5\lua\system\repr.lua(68): attempt to call upval match' (a nil value)
warning: stack traceback:
warning:         ...mdata\faforever\gamedata\lua.nx5\lua\system\repr.lua(68): in function <...mdata\faforever\gamedata\lua.nx5\lua\system\repr.lua:67>
warning:         ...mdata\faforever\gamedata\lua.nx5\lua\system\repr.lua(195): in function putValue'
warning: …
```
=> Initialize utils before repr in RuleInit

changelog/snippets/fix.6430.md, projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
The `HasImpacted = true` line was not added back in during the refactor in #4517.
Add back the line.
The CZAR no longer gives errors after hitting an underwater unit with the depth charges.
=> Fix an OnImpact error for CZAR depth charges

changelog/snippets/other.6431.md, projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
Adds water vision to CZAR's depth charge on impact so that it makes sense alongside the normal vision it gives on impact.
Underwater units get revealed when hit by the depth charge.
=> Add water vision to CZAR depth charge on impact

changelog/snippets/fix.6433.md, units/UAS0201/UAS0201_unit.bp
Add the necessary category for the range ring to show up normally (without UI mods).
Spawn a destro and make sure the ring exists.
#3438 changed depth charge's range category to indirect fire.
=> Add `OVERLAYINDIRECTFIRE` to Aeon destroyer so depth charge's range ring appears

changelog/snippets/fix.6446.md, lua/ui/game/commandmode.lua, lua/userInit.lua
Reported on [Discord](https://discord.com/channels/197033481883222026/408556023180296193/1283069284548870310). 
With sufficient lag, the unpause thread checks the upgrading unit's focus before "assist to upgrade"'s upgrade order gets through. This means the upgrading unit's focus is `nil`, same as the engineer's, so an unpause order is sent at the moment. This unpause order is processed after the upgrade and pause orders of "assist to upgrade", causing the unit to upgrade -> pause -> unpause.
Replicable easily by using `net_Lag 3000` in the console. Make sure to remove the guards in `userInit.lua` not allowing that command to work. Just assist a mass extractor with any engineer and that much lag. It will upgrade, pause, and unpause.
- Check if the target focus is `nil` before comparing it …
=> Fix the "assist to upgrade" and "assist to unpause" settings conflicting and not pausing upgraded units during lag

changelog/snippets/fix.6418.md, lua/armordefinition.lua
Deathnuke and Overcharge
OC armor doesn't do anything with FAF's OC, but it's good to have for consistency
Fixes #6362.
Adds the `Overcharge` and `Deathnuke` resistances to TMD armor, as they are also structures.
ACU no longer blows up TMD, and deals 80 damage instead.
FAF's OC overrides any damage dealt with the structure damage blueprint property, so it cannot be tested.
=> Add structure armor resistances to TMD armor

changelog/snippets/fix.6419.md, lua/system/blueprints-units.lua
The reclaim tower mod adds a unit with the engineer station category and behavior based on its build range but does not specify a guard scan radius. Although guard scan radius defaults to 25, it seems that engineer station mods write in their guard scan radius just like base game engineer stations, so displaying the true build range instead of the assist range when the stat is missing seems to be better for compatibility with the reclaim tower mods without affecting engi station mods.
Used the Reclaim Tower mod and checked that air staging radius equals max build distance in the blueprint viewer.
=> Add nil check for GuardScanRadius in build range overlay

changelog/snippets/fix.6416.md, lua/sim/AdjacencyBuffs.lua
Fixes a [Discord bug report](https://discord.com/channels/197033481883222026/1265682067874775071) where Salvation fire rate wasn't decreased when T1 pgens were not present. This was caused by the fire rate being increased from `0.31` to `10/31` (which equals `0.323`).
Spawn 2 salvations, one with full adjacency and one with only t3 pgen adjacency. Hold fire, target ground, then pause, enable firing, and then confirm that the salvation with t1 pgens fires after 25 ticks stepped, and the one without pgens after 26 ticks.
=> Fix Salvation fire rate not being reduced when missing T1 pgens

changelog/snippets/fix.6429.md, units/UAL0401/UAL0401_Script.lua
The claws' aim is being disrupted by the walk animation. That makes up a small amount of erratic movement for units that are being tractored, although that mainly comes from the claws just rotating while they have no target due to tractoring one at the moment. Here is the aim problem demonstrated with lasers:
https://github.com/user-attachments/assets/95662165-f350-4eca-96b3-faa12619816f
Disable the left/right `B02` bones from being animated while the tractor claws fire since they are the pitch bone of the tractor claws.
The bones are the elbows of the GC's arms:
I tested with replacing the tractor claws with lasers and walking into an Othuum (claws wont fire at T4s), and making sure it doesn't start missing.
https://github.com/user-attachments/assets/08907f54-44dc-4a1f-b040-0dfb364864ce …
=> Fix GC claw aim being disrupted by walking

.github/workflows/auto-draft-pr.yaml
First of possibly many workflows to help us automate project management
=> Add a workflow to automatically convert pull requests to draft

changelog/snippets/fix.6471.md, units/XSB5101/XSB5101_unit.bp
The Seraphim wall now orientates towards the terrain as intended.
Create a line of walls across a cliff and inspect their orientation.
While reviewing https://github.com/FAForever/fa/pull/6438 I noticed that the Seraphim wall refuses to orientate to the terrain.
=> Fix xsb5101 not orientating to the terrain as intended

changelog/snippets/balance.6469.md, units/XRL0302/XRL0302_unit.bp
Unlike other Tech 2 units, the Fire Beetle only takes up one clamp on transports. This makes it possible to load the same quantities of Fire Beetles and Tech 1 units into transports. To ensure that the Fire Beetle does not slow transports down excessively, its `TransportSpeedReduction` stat is reduced to match that of Tech 1 units.
**Fire Beetle: T2 Mobile Bomb (XRL0302):**
- TransportSpeedReduction: 0.3 --> 0.15
=> Reduce the `TransportSpeedReduction` stat of the Fire Beetle

changelog/snippets/other.6463.md, lua/keymap/keyactions.lua, lua/selfdestruct.lua, lua/ui/game/confirmunitdestroy.lua
Removes the hotkey, UI and sim capabilities to kill all of your units at a click of a button. As requested by the moderators on [Discord](https://discord.com/channels/197033481883222026/1288427189313994823).
Ran the game and went on a rampage. All appears good.
In addition, I've checked whether campaign/coop maps use this functionality and they do not.
=> Remove the hotkey to kill all your units

changelog/snippets/other.6474.md, engine/User.lua, lua/system/utils.lua, lua/ui/lobby/autolobby.lua, lua/ui/uimain.lua, scripts/LaunchFAInstances.ps1
By using `/players` in combination with `/hostgame`, the game can be launched on LAN into the auto lobby, which automatically launches the lobby once all players are connected. This allows rapidly testing multiplayer in a local environment by launching multiple instances with a script and hosting/joining as needed.
Guards are added for the arguments used in the auto lobby as it is now more accessible since `/hostgame` is simpler than `/gpgnet`.
The powershell script added to the scripts folder in this PR launches multiple FA instances into the auto lobby and successfully starts everything. The faction launch argument can be omitted and the game launches too.
[scripts/LaunchFAInstances.ps1](https://github.com/FAForever/fa/blob/cd7c660d57b014b72c1e941a615680b95d4e968b/scripts/LaunchFAInstanc …
=> Implement command line launch of the auto lobby for LAN games

changelog/snippets/sections/other.6458.md, lua/sim/CollisionBeam.lua, lua/sim/Projectile.lua, lua/sim/weapon.lua
This is the table passed from weapons to projectiles so that the projectiles know their damage-dealing behavior
Started from `GetDamageTableInternal` and manually traced wherever the data was passed and used.
Also checked that my explanation of the metatable was correct by checking the projectile's vs weapon's `debug.allocatedsize()` of the damage table (40 vs 360 bytes) on the Aeon ACU's main gun.
I noticed that `CollideFriendly`'s functionality is broken. There is also an unused `CollideFriendlyShield` field that could be cleaned up.
=> Annotate the damage data passed from weapons to projectiles

changelog/snippets/fix.6436.md, lua/sim/Unit.lua
After #6436 contrails began to be able to trigger the movement fx warnings. I'm not sure for what reason.
```
warning: *No movement effect groups defined for unit 	"ura0102"	, Effect groups with bone lists must be defined to play movement effects. Add these to the Display.MovementEffects.	Air	.Effects table in unit blueprint.
```
Prevents the warning if the movement effects table is only used for contrail effects or footfall effects.
Fly a Cybran interceptor (ura0102) at max speed and confirm that the warning no longer appears.
=> Fix movement effects warning spam due to contrails

changelog/snippets/fix.6494.md, lua/system/blueprints-units.lua
Validate that the unit has a `Physics` table before assigning the `TransportSpeedReduction` stat. This allows us to better test changes without reloading the game.
Tested by removing the `Physics` table of a unit while having the `EnableDiskWatch` command line argument enabled.
=> Fix a crash when the `EnableDiskWatch` command line argument is enabled

changelog/snippets/balance.6466.md, engine/Core/Blueprints/UnitBlueprint.lua, units/XSL0401/XSL0401_unit.bp
Ythotha can walk backwards (with 2.5 speed at that) which is obviously overpowered and also looks very weird.
https://github.com/user-attachments/assets/0f12a23d-e2c9-4ee6-8391-00605244a5e6
Set its reverse speed to 0 so it cannot walk backwards.
Spawn it and confirm it cannot walk backwards when given move orders near close behind it.
```
CreateUnitAtMouse('xsl0401', 0,    0.00,    0.00,  0)
```
`BackUpDistance` gets a default value from the engine, but I'm not sure how it is calculated, so I didn't add a comment in the annotation about it.
=> Fix Ythotha being able to move backwards

changelog/snippets/other.6526.md, lua/system/repr.lua
A value of 1 is a little inaccessible. Often you are dealing with tables-in-tables. The second parameter that represents the configuration is a little difficult to find however. With this change, we make the default what you want on average.
=> Bump the default depth for recursive printing to 3

changelog/snippets/fix.6507.md, lua/sim/Projectile.lua
Fix an issue where the blueprint field `ProjectilesToDeflect` of a depth charge was ignored. It would always default to the value `3`.
In the following test case I increased the redirect count of the depth charge of the UEF Destroyer to 10.
https://github.com/user-attachments/assets/68fa6e63-9c84-4a6e-a36b-d62aae46c0dd
=> Fix depth charges not applying the `ProjectilesToDeflect` blueprint field

changelog/snippets/fix.6536.md, engine/Core/Blueprints/UnitBlueprint.lua, lua/system/blueprints-weapons.lua
Fixes a bug where most weapons got 1.0 tracking radius because they were set to 1.05 but floored to 1.0.
Spawn a unit and see that it does aim at targets at 1.05x its range.
- I was investigating why T3 mobile artillery wasn't unpacking when targets were outside on the edge of its range in reponse to this [Discord suggestion](https://discord.com/channels/197033481883222026/1306178958357823510) for a manual pack/unpack for T3 mobile artillery when I found out that the tracking radius wasn't applying for any units. It still doesn't apply for T3 mobile arty because of `NeedsUnpack = true`. Working around that engine AI logic adds lots of conditionals to the lua which is buggy, and deploying when targets are nearby is possibly undesired anyway.
=> Remove rounding in weapon tracking radius sanitization

changelog/snippets/other.6485.md, effects/mesh.fx, effects/terrain.fx
Depends on #6452, so the diff will be misleading until that one is merged.
Now every shader is capable of using the new, better way of calculating the water absorption. The only requirement is that the light multiplier is bigger than 2.1. This is good, because the mesh shader doesn't know what terrain shader is in use and has worked like this before. This could lead to unfitting results, if the light multiplier was big enough, but a terrain shader was used that only supported the legacy water calculation. This is now fixed.
I also made the decals able to use pbr light calculations. Now they behave consistently like the ground they are on. (Also the map editor does this automatically and we can't prevent it, so it helps the editor produce results that are consistent with the game.)
We …
=> Shader rework

changelog/snippets/balance.6383.md, units/URA0401/URA0401_unit.bp
The SR has four air-to-ground weapons: two bolters, which are the more dominant weapons, and two rocket packs, which are often overlooked. In the current release, only the bolters have area of effect damage, the rocket packs have none at all. 
From a design perspective, this is suboptimal since the rockets have a decently large explosion effect. The Renegade uses the same projectile with similar effects and has an area of effect radius of 3. It is also not intuitive, because it could be reasonably assumed that the rocket packs perform similarly to either the Renegade or the other air-to-ground weapons of the SR. Balance wise, it results in the rocket packs underperforming against smaller targets, such as Titans.
**Soul Ripper: Experimental Gunship (URA0401)**:
- Iridium Rocket Pack (x2): …
=> Enable the SR's Iridium Rocket Pack to deal damage in an area of effect

changelog/snippets/features.6424.md, lua/ui/game/unitviewDetail.lua
This is only a small UI tweak for units without a special `armorType` like, for example, the Striker. The current `armorType` portion of uvd.lua looks like this for these units:
```
Armor Type: Normal          (% of damage taken)
Normal - 100.0
```
This is the new output:
```
Armor Type: Normal
```
Both `(% of damage taken)` and `Normal - 100.0` do not provide the player with any relevant information, so they can be hidden.
Only affects units without a special `armorType`.
=> UVD: Remove unnecessary UI elements when the selected unit does not have a special `armorType`

changelog/fix.6547.md, lua/sim/NavGenerator.lua
Reported by @maudlin27 on the AI Discord, see also:
- https://discord.com/channels/619646141306503181/941273132818391100/1289285154145046623
Generated and unexplored maps temporarily set the playable area to 4. This confuses the navigational mesh. When the playable area is too small we instead opt to ignore it. This solution is not ideal.
=> Do not use the script-defined playable area when it is tiny

changelog/snippets/features.6479.md, lua/ui/lobby/autolobby/AutolobbyInterface.lua
Hides the map preview for now.
Requires functionality such as:
- https://github.com/FAForever/server/pull/1028
=> Hide the map preview for now

changelog/snippets/fix.6456.md, lua/sim/units/FactoryUnit.lua
Fixes #5625. UEF and Cybran air factories have an animation that locks the unit's orientation, interfering with the rolloff rotation. The changes move the rolloff rotation to happen after the animation finishes.
Spawn factories, give a rally point on one side, order an engineer, and then change the rally point to the other side before the engineer finishes building and see that it now gets rotated correctly in the UEF and Cybran factories.
```
CreateUnitAtMouse('xab1401', 0,    0.14,   -8.65, -0.00000)
CreateUnitAtMouse('xsb0302', 0,   -4.04,    2.16,  0.00000)
CreateUnitAtMouse('ueb0302', 0,   11.96,    2.16,  0.00000)
CreateUnitAtMouse('urb0302', 0,    3.96,    2.16,  0.00000)
CreateUnitAtMouse('uab0302', 0,  -12.04,    2.16,  0.00000)
```
=> Move `RollOfUnit()` to after the "finished building" animation

changelog/snippets/feature.6557.md, lua/ui/game/orders.lua
- Silos without engineering suites (SML, TML, SML subs, Sera battleship) will pause missile construction instead of cancelling (and wasting progress) when issued a hard stop command mid-build.
- Silos with engineering suites (ACUs and SACUs) are unchanged, and will cancel missiles under construction when issued a hard-stop. This is to prevent a situation where you want to construct something with the unit but don't want to spend additional resources on constructing a missile at the same time.
- Code changes: `Stop` is moved below `ClearCommands` to prevent LLS errors/be next to soft stop. Unnecessary local redefinition of `units` at the beginning of `Stop` and `SoftStop` is removed.
Spawn the following units and issue soft- and hard-stop commands. SACUs and ACUs will cancel missile orders …
=> Prevent siloes from cancelling missiles when issued a hard-stop command

changelog/snippets/fix.6436.md, lua/sim/Unit.lua, units/URL0208/URL0208_script.lua, units/XEL0306/XEL0306_unit.bp
- Add an exception for the warning condition in case there is a Treads table in the movement effects layer group, similar to #6480.
- Fix Spearhead's treads since I noticed it
Look at the spearhead's treads and make sure they work and aren't disconnected visually.
Checked all blueprints that could trigger the warning using this command:
```lua
UI_Lua 
for i,v in __blueprints do
if type(i) == 'number' then continue end
local me = v.Display.MovementEffects
local t = {"Land","Seabed","Sub","Water","Air","Orbital"}
for _, l in t do
local mel = me[l]
if mel and not mel.Effects then
LOG(string.format('%-7s %-12s %-20s %-20s', v.FactionCategory, v.TechCategory, LOC(v.Description), LOC(v.General.UnitName) or ''))
for i, _ in mel do
LOG(i)
end
end
end
end
```
<details> <summary> Output only has …
=> Fix movement effect warning spam due to Spearhead (XEL0306)

docs/_posts/2024-11-29-3814.md, lua/ui/lobby/autolobby.lua, lua/ui/lobby/changelogData.lua, lua/version.lua, mod_info.lua
Hosts of matchmaker games got the following error: `warning: GPGNET: Error processing gpg.net command CreateLobby: Attempting to lookup the RType for class Moho::CGpgNetInterface before it is registered.`
According to the debugger, the log statement was at fault.
=> Fix matchmaker games not launching

docs/_posts/2024-11-29-3815.md, lua/ui/lobby/autolobby.lua, lua/ui/lobby/autolobby/AutolobbyController.lua, lua/ui/lobby/autolobby/components/AutolobbyServerCommunicationsComponent.lua, lua/ui/lobby/changelogData.lua, lua/version.lua, mod_info.lua
Apparently sending anything else then `Launching` from the lobby code messes with the server state. My mistake for trying to be a smart-ass about it.
Tested together with @lL1l1 through the test client. We documented the procedure, see also https://github.com/FAForever/fa/pull/6567/commits/4debd629b23ec7511baad136ecd7991dcf6c1fdc .
=> Fix autolobby sending invalid game states to the server

changelog/snippets/fix.6546.md, lua/UserSync.lua, lua/sim/Unit.lua, lua/sim/weapons/DefaultProjectileWeapon.lua
An exploit that @clyfordv's mod discovered, where you can be notified of enemy billy nuke launches because the launch data is synced despite not having a VO line play.
Fixes the exploit by adding the VO's condition from `Unit.NukeCreatedAtUnit` to the launch data sync condition. Allies still get pings for billy nukes.
Log the data that is synced when a nuke launches:
- Allies/yourself/observers receive data + location data of billy nukes and nukes
- When switching to an enemy army before launching the nuke, you receive data only for nukes and no data at all for billy nukes.
There is currently no visual indicator for strategic launches by default, but it can be modded in.
Effectively a continuation of the anti-cheat logic in https://github.com/FAForever/fa/pull/5582.
=> Fix billy nuke launches being synced to UI

changelog/snippets/fix.6569.md, engine/User/CLobby.lua, lua/ui/lobby/autolobby/AutolobbyController.lua, lua/ui/lobby/autolobby/components/AutolobbyArguments.lua, scripts/LaunchFAInstances.ps1
Extends https://github.com/FAForever/fa/pull/6479 by implementing the details of https://github.com/FAForever/fa/pull/6160. I'm not sure how I forgot about this - the rating and divisions are also not part of the checklist. 
Extended the launch script made by @lL1l1 to include (sub)divisions. Launch the game via the script. Observe the divisions in the scoreboard.
And similar for clan tags with [8e2b159](https://github.com/FAForever/fa/pull/6569/commits/8e2b159414680e2c1be02ab68909b82eb0f58765):
Discussion on [Discord](https://discord.com/channels/197033481883222026/1312271501776388146) whether we should show this data by default to players.
=> Expose player ratings and divisions to the session

.vscode/settings.json, changelog/snippets/features.6576.md, lua/ui/game/worldview.lua
Preserves the settings of the primary world camera when switching to/from split view.
Start up the game and switch to/from split view.
https://github.com/user-attachments/assets/24cb0417-1aa6-4368-b85c-b48fbdacc453
=> Preserve the world camera when switching to/from split view

changelog/snippets/fix.6544.md, lua/SimUtils.lua
Fixes a bug where transferring units (Seraphim SACU) enables their enhancement-disabled weapons (Seraphim SACU TML) despite the enhancement not being built.
1. Spawn a Seraphim SACU without any upgrades.
2. Transfer it to another team.
3. It should not start building a missile. You also should not be able to order it to fire a missile by selecting a TML along with the SACU to be able to give the launch and build orders.
- In contrast, a missile preset is able to load and fire missiles without any workaround.
The overcharge weapon seems to not re-enable itself without these changes anyway, I'm not sure why.
=> Fix unit transfer enabling enhancement-locked weapons

changelog/snippets/fix.6583.md, effects/mesh.fx
Fixes #5381.
Not sure if the changes need comments, as I have no experience with the shaders.
Spawn rambo preset SACUs underwater, the shield mesh shouldn't show up above the water. Spawning multiple in one spot makes it easier to see.
Before:
After:
=> Fix personal shields reflecting above the water surface

changelog/snippets/balance.6415.md, projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_proj.bp
Adds the category used on strat bombs to Ahwassa's bomb so it ignores collisions with ASF.
Strat bombers already set a precedent for ASF not being able to block bomber snipes, due to the bombers frequently having a one-opportunity type of situation where every bomb matters and can decide the game. Being able to block an even larger and more impactful Ahwassa bomb makes no sense with this precedent, both balance-wise and aesthetically. Ahwassa also doesn't get any meaningful reward for doing so due to the old 10% damage vs ASF armor and the newer explosion delay.
Flying a bunch of ASF under the ahwassa when it bombs doesn't explode the bomb prematurely.
=> Make Ahwassa bomb ignore ASF collisions

changelog/snippets/fix.6605.md, loc/US/strings_db.lua
Fix the description of the Cybran SACU's gun range upgrade.
The description matches the difference in the code:
https://github.com/FAForever/fa/blob/738fe61c91ebc148193b007107806477ec732907/units/URL0301/URL0301_unit.bp#L321-L323
https://github.com/FAForever/fa/blob/738fe61c91ebc148193b007107806477ec732907/units/URL0301/URL0301_unit.bp#L607-L608
~~- [ ] Changes are annotated, including comments where useful~~
=> Fix the description of the Cybran SACU's gun range upgrade

changelog/snippets/fix.6629.md, units/UEL0401/UEL0401_script.lua
Since the instigator is used in a thread, and threads start 1 tick later, it can be passed from OnKilled and then get destroyed.
Replay: https://replay.faforever.com/24087043 Right side fatboy for south team at 29:00 errors out when dying
Error:
```
warning: Error running lua script: ...\gamedata\units.nx2\units\uel0401\uel0401_script.lua(263): Game object has been destroyed
[C]: in function `GetPositionXYZ'
...\gamedata\units.nx2\units\uel0401\uel0401_script.lua(263): in function <...\gamedata\units.nx2\units\uel0401\uel0401_script.lua:253>
```
- Check if the instigator was destroyed before calling `GetPositionXYZ` on it. I didn't opt for using `Unit.Dead` because this code won't run often and `.Dead` is true after dying, which is before C-object destruction.
- Running …
=> Check if instigator is destroyed in Fatboy `DeathThread`

changelog/snippets/fix.6617.md, engine/User.lua, lua/keymap/keyactions.lua, lua/ui/game/orders.lua, lua/userInit.lua
`IssueUnitCommand` was being given a `UserUnit` instead of a `UserUnit[]` in the new behavior from #6557, causing the following error:
```
WARNING: Error running HandleEvent script in CScriptObject at 19c8a700: ...rs\colon3\documents\github\fa\lua\ui\game\orders.lua(332): Expected a game object. (Did you call with '.' instead of ':'?)
[C]: in function `IssueUnitCommand'
...rs\colon3\documents\github\fa\lua\ui\game\orders.lua(332): in function `Stop'
...rs\colon3\documents\github\fa\lua\ui\game\orders.lua(355): in function `OnClick'
...ers\colon3\documents\github\fa\lua\maui\checkbox.lua(143): in function `HandleEvent'
...rs\colon3\documents\github\fa\lua\ui\game\orders.lua(1303): in function <...rs\colon3\documents\github\fa\lua\ui\game\orders.lua:1281>
```
- Like was …
=> Fix error with new stop command pausing silos

docs/development/developmentEnviroment.md, setup/setup-english.md
Adds some tips that I've personally used to the development environment/setup doc.
=> Add new unit-related development tips

changelog/snippets/fix.6602.md, engine/Sim/CPlatoon.lua, lua/sim/FactoryBuilderManager.lua, lua/sim/PlatoonFormManager.lua
This PR removed unused code from the Skirmish AI factory and platoon former manager.
The personality function calls were present in both the factory manager and platoonformer manager.
In the factory manager they created a ptnsize variable that is unused.
In the platoonformer manager that are used twice in CanFormPlatoon and FormPlatoon as the platoon count parameter. I validated that in the default AI this is always returning 1. So I've removed the function calls and replaced with a static integer of 1.
Tested that this change has no bearing on the AI functionality, nor does it cause a desync when comparing an replay with and without the changes indicating it is doing nothing out of what has already been analyzed.
The functions that are being modified are used by the AI multiple times per …
=> Fix : Remove unused personality calls in default skirmish AI code

changelog/snippets/fix.6630.md, lua/sim/Unit.lua, lua/utilities.lua
Initially reported on [Discord](https://discord.com/channels/197033481883222026/1323915745104625714) that ACUs would sometimes not spawn facing the correct direction after the release with https://github.com/FAForever/fa/pull/6438.
This is because the math used in the `QuatFromXZDirection(dx, dz)` function did not properly account for signs, and was giving the wrong output when `dx` was negative. ACUs on the right side of the map have a negative `dx` when rotating towards the middle of the map.
- Accounts for the sign of -dx
- Explain the mathematics more thoroughly
- Account for the division by zero case as it would print `Unit ual0001 is attempting to move to an invalid coord` to the log about the unit moving to an invalid coord when `SetOrientation({0, 1.#INF, 0, 1.#INF}, true)` …
=> Fix `QuatFromXZDirection` for negative dx inputs causing ACUs to spawn the wrong direction

changelog/snippets/other.6600.md, engine/User.lua, engine/User/CUIWorldView.lua, lua/ui/controls/worldview.lua, lua/ui/game/multihead.lua, lua/ui/game/worldview.lua
Annotates the functionality related to world views. Documents to some degree how secondary worldviews (that run on secondary adapters) work. 
Not necessary, these are just changes to annotations.
In preparation of a feature for HintHunter to toggle the split screen.
=> Annotate some of the functionality related to worldviews

changelog/snippets/other.6626.md, lua/ScenarioFramework.lua, lua/SimSync.lua, lua/enhancementcommon.lua, lua/sim/Unit.lua, lua/ui/game/construction.lua, lua/ui/notify/enhancementqueue.lua
Annotate the data about how enhancements are synced.
- Logging the enhancement queue functions
- Looking for warnings related to the annotations.
- The `EnhQueueData` class is declared in construction.lua as it is difficult to find how it gets put into the common enhancement table otherwise.
- Giving the Sync table a class brings up new undefined field warnings to solve for other sync features in the future
=> Annotate sync of enhancements

effects/terrain.fx
There are several changes here:
- I noticed that we actually disabled being able to scale the slot that is supposed to store the macrotexture. This makes sense when only thinking about the scenario where you provide a custom map-wide texture. Then the user does not have to worry about providing the right scaling to make the texture fit neatly over the whole map. However, there are some gpg macrotextures that are supposed to tile. If we don't provide the ability to control the scale of this texture we are artificially limiting mapmakers, so I added this ability again.
- I reworked the naming scheme because I noticed that the previous naming scheme was too complicated and made it hard to remember what is what.
- I found a usage for previously unused texture channels in the Terrain003 (old …
=> Rework shader names and add biplanar shader

changelog/snippets/fix.6572.md, lua/sim/weapons/DefaultProjectileWeapon.lua
Bombers miss when moving vertically because bombs inherit launcher XYZ momentum rotated onto the XZ plane, but the Lua calculation assumes only launcher XZ momentum is inherited.
Add a few lines fixing the XZ momentum used by the Lua calcuation.
Order a bomber to attack somewhere where it will be changing altitude, it should be perfectly accurate now. The easiest way is to groundfire in front of a landed bomber. You can also groundfire the peak of a mountain.
Left: no fix. Right: fixed
https://github.com/user-attachments/assets/1cc9f317-dfdd-4961-8bb2-5bdb1e8951d1
The engine still calculates the bomb drop zone independently for firing the bomb, and may not let the bomb fire at all. You can use `ai_RenderBombDropZone` to see the drop zone.
Bombs still have a speed limit in the projectile …
=> Fix bombers missing during vertical movement

lua/sim/Unit.lua
The ven diagram of when this error can trigger and when Unit.UnitId is undefined is a circle
=> Added fallback to self.UnitId in error message

changelog/snippets/fix.6532.md, lua/shield.lua, lua/sim/Projectile.lua
If multiple projectiles hit a target in the same tick, they will all impact it regardless of the target's HP.
For example, 6 TML (36000 damage) placed in a line will all impact a 13000 HP shield if they hit on the same tick. In general, any line/concave formation of units could be susceptible to this bug.
This is because collisions are checked for all projectiles before any impact scripts are run, so the usual `OnCollisionCheck` `if self.DisallowCollisions then return false end` doesn't work if `DisallowCollisions` is adjusted due to damage taken from impacts.
- Check `DisallowCollisions` in the `OnImpact` function of the projectile, so that projectiles have an up-to-date status on the entity's collision as HP gets adjusted due to previous impacts.
- Add the `DisallowCollisions` boolean …
=> Fix excess projectiles in the same tick impacting entities that die that tick

changelog/snippets/fix.6543.md, lua/sim/Unit.lua
This bit of code runs for all units and causes them to wait while dead before being destroyed, making them block damage when they shouldn't:
https://github.com/FAForever/fa/blob/9948335f0fe0699dead4f1e0070f08ebcfdd9fcc/lua/sim/Unit.lua#L1982-L1994
This code does the same, but makes up a much more significant portion of the wait time (0-0.5 seconds vs 0.1)
https://github.com/FAForever/fa/blob/9948335f0fe0699dead4f1e0070f08ebcfdd9fcc/lua/sim/Unit.lua#L1921-L1924
For a practical example, spawn a line of hives and an enemy monkeylord. The monkeylord's laser will be blocked while the dead hive is going through its explosion FX.
- add `DisallowCollisions = true` to `OnKilled` as that is the entry point for all the issues that arise with collisions after death (`DeathThreadDestructionWaitTime`, …
=> Disable collisions with dead units consistently

changelog/snippets/balance.6448.md, lua/sim/Unit.lua, lua/sim/units/AirUnit.lua, projectiles/ShieldCollider/ShieldCollider_script.lua
Air units do not instantly die (get `Unit:Destroy()` called); they wait until they impact the ground. Since the unit is not destroyed, it still has collision while falling through the air. Units undergoing a death animation should not have collision, this is already the case for land units like the Megalith and Monkeylord.
Adds `self.DisallowCollisions = true` in the `OnKilled` override function used by air units.
Spawn a UEF SAM and an enemy Cybran spy plane in front of the SAM. The SAM shouldn't waste all 6 shots (1200 damage) on the spy plane (700 hp), 2 shots should pass through. 
Make sure that the SAM doesn't kill the spy plane before all 6 shots are fired, or else it will cancel the volley early and you won't see 2 remaining shots.
This increases the effectiveness of SAMs against …
=> Fix air units colliding with projectiles after death

changelog/snippets/fix.6645.md, lua/sim/Unit.lua, lua/sim/commands/distribute-queue.lua
There is a random error when using distribute queue in normal games.
```
warning: Error running sim lua callback function 'DistributeOrders':
UnitScript:GetCommandQueue invalid UnitCommandQueue
[C]: in function `GetCommandQueue'
...\lua.nx2\lua\sim\unit.lua(4987): in function `GetCommandQueue'
...\lua.nx2\lua\sim\commands\distribute-queue.lua(77): in function `DistributeOrders'
...\lua.nx2\lua\simcallbacks.lua(569): in function `fn'
...\lua.nx2\lua\simcallbacks.lua(58): in function <...\lua.nx2\lua\simcallbacks.lua:54>
```
The debug setup reveals the following information:
```
warning: unit getcqueue errored:	url0301_rambo	41	dead, destroyed:	true	false
warning: UnitScript:GetCommandQueue invalid UnitCommandQueue
warning: stack traceback:
warning:         [C]: ?
warning: …
```
=> Fix error when using distribute queue on dying unit

changelog/snippets/fix.6636.md, changelog/snippets/graphics.6636.md, lua/EffectUtilities.lua, lua/EffectUtilitiesOpti.lua, lua/sim/units/cybran/CAirFactoryUnit.lua, lua/sim/units/cybran/CLandFactoryUnit.lua, lua/sim/units/cybran/CSeaFactoryUnit.lua
When a Cybran air factory dies while building the following error occurs:
```
warning: Error running lua script: ...\fa\lua\effectutilities.lua(345): attempt to loop over field `BuildEffectBones' (a nil value)
...\fa\lua\effectutilities.lua(345): in function <...\fa\lua\effectutilities.lua:341>
...\fa\lua\sim\units\cybran\cairfactoryunit.lua(62): in function <...\fa\lua\sim\units\cybran\cairfactoryunit.lua:56>
```
The error occurs because the wrong blueprint value is passed to the function, and it occurs after the factory dies because the function is stuck in a loop before the erroring code runs. The loop can be traced to b7169abb53cc97fed8c2ebdaebf9c1c16a9854d4 (10 years ago) where the Cybran naval factory build beams which are forked in a thread were added to land/air …
=> Fix error when Cybran air factories die while building

changelog/snippets/features.6643.md, engine/User.lua, lua/ui/game/gamemain.lua, lua/ui/game/pause.lua, lua/ui/game/tabs.lua
Related to:
- https://forum.faforever.com/topic/8648/suggesting-rule-change-make-immediately-unpausing-after-a-player-asked-for-a-pause-against-the-rules/1
Introduces a small delay before user A can resume the session after a pause initiated by user B. At all times, user B can resume immediately. A chat message is posted when a user pauses the session, attempts to resume the session and when the session is resumed.
Launched the game directly into the match maker lobby with the [LaunchScripts](https://github.com/FAForever/fa/blob/develop/scripts/LaunchFAInstances.ps1) made by @lL1l1 .
=> Add a delay to the pause feature

changelog/snippets/fix.6647.md, lua/ui/globals/InternalSaveGame.lua, lua/userInit.lua
According to @4z0t there's a possible buffer overflow in this function. This function is exposed to UI mods. It would technically allow a UI mod to run arbitrary code when the UI mod is enabled.
=> Add a guard to prevent a buffer overflow when saving a game

changelog/snippets/graphics.6621.md, effects/terrain.fx
The map editor will be able to automatically generate the map info texture with all the channels, so there is no reason not to use the higher resolution water texture.
=> Make Terrain000 use the water channel in the map info texture

changelog/snippets/fix.6608.md, lua/ui/game/tooltip.lua, lua/ui/lobby/ModsManager.lua
The mod manager is using some custom logic for the tooltips and its was not scaling the width of the tooltip causing text overflow on couple of the elements.
=> Fix text overflow in fixed width tooltips when using UI scaling

changelog/snippets/fix.6646.md, lua/ui/game/chat.lua
This refers to the sound when you receive a message. The sound plays in replays. I personally find it to be an annoying sound, but this is of course subjective.
=> Remove the chat sound when watching a replay

changelog/snippets/other.6679.md, lua/ui/game/commandmode.lua
Remove import of `WorldView.lua` in `CommandMode.lua` which is imported inside `WorldView.lua` causing circular dependency of these 2 modules.
=> Resolve circular dependency of WorldView and CommandMode

changelog/snippets/fix.6684.md, lua/ui/dialogs/console.lua
- search results are now sorted alphabetically
- clicking on an item doesnt steal the focus from the Edit, so UP/DOWN keys can be used to keep moving through the list
- the item list correctly follows the focus item and wraps around if needed
=> Console improvements

effects/terrain.fx
It is time for another stab at the terrain shader file. I gathered some new insights on what is important to produce the best results possible, partly from looking at BAR maps, partly from looking at maps from @sting-2 and these insights are the basis for the following changes.
The way to achieve the best quality seems have a huge (4-8k) map-wide albedo texture and to interpolate it with the other stratums that provide details. This way the map albedo texture can break up the texture repetition and provide much more color variation than you could by just tiling 8 regular textures.
The mapwide normal should ideally also be huge. To justify thse file sizes we need compression. Until now we stored the shadows, water depth and map normals all in one texture. Compressing these leads to severe …
=> Yet another shader rework

changelog/snippets/fix.6681.md, lua/ui/game/construction.lua, lua/ui/game/gamemain.lua
Initializing/altering objects during loading of a module is a bad habbit, especially if it is from another module. In this case it can cause error and game freeze if UI mod tries to access `construction.lua` before UI is created.
Queue dragging works as normal.
=> Don't initialize/alter objects during module loading in `Construction.lua`

changelog/snippets/fix.6701.md, lua/SimUtils.lua
First reported by @4z0t.
Units currently building in an external factory are attached indirectly, so the engine's usual army transfer behavior for standard factories doesn't destroy those units, and instead the unbuilt units are spawned as damaged units. In other words you can have an unit building in an external factory, transfer it to another player, and the unbuilt unit would respawn as a built but damaged unit for the other army.
https://github.com/user-attachments/assets/80bf1d32-a947-4927-bbb1-676e7b69f894
In the SimUtils transfer function, before using the engine `ChangeUnitArmy` function, destroy the building unit in the external factory if it exists. All user transfers go through here, as well as all the share on death type of transfers. Some scenario or AI utils don't, but they …
=> Fix exploit that spawns partially built units out of external factories on transfer

changelog/snippets/graphics.6683.md, effects/terrain.fx
Two small additions to the recent PR #6683.
_1)_ The specular color channels now control more behavior in the Terrain200 shaders. The green channel controls the contrast increase of the heightmaps that are used for texture blending. The blue and alpha channels store the values of the rotation matrix. This makes the rotation angle adjustable which could be beneficial in some cases.
The editor will not expose these values for now. Instead it will provide reasonable defaults. I plan to do it this way to give people time to first learn the important features of the new shaders. Then when they need more control I can expose these values. By doing this change now in the fa shaders and having the editor provide good default values, we ensure that all maps using Terrain200 shaders have reasonable …
=> Shader improvement

changelog/snippets/fix.6702.md, lua/defaultcomponents.lua, units/UEL0401/UEL0401_script.lua
First reported by @4z0t.
When a `BuildMobile` order is cancelled, `OnStopBuild` is called with an unbuilt unit. Carriers will put the unbuilt unit into their storage at that point because there are no checks for this scenario. Fatboy places the unbuilt unit on the ground. A `BuildMobile` order can be issued to factories trivially using UI mods. Thankfully it isn't a huge exploit because the unbuilt units are still unbuilt when they come out of storage.
https://github.com/user-attachments/assets/ccb41d39-8dd9-4bdd-b69d-0805989da310
After deployment:
- Carriers (Czar and all navy): Destroy unbuilt units in `OnStopBuildWithStorage` in the external factory component.
- Fatboy: Destroy unbuilt units in the `OnStopBuild` functions.
Spawn a carrier, select the external factory, and then issue a …
=> Fix unbuilt units staying around when issued with BuildMobile to external factories and cancelled

engine/Sim/CAiBrain.lua, engine/Sim/CAiPersonality.lua, engine/Sim/CPlatoon.lua, lua/AI/OpAI/BaseManager.lua, lua/AI/OpAI/BaseManagerPlatoonThreads.lua, lua/AI/OpAI/ReactiveAI.lua, lua/AI/aiutilities.lua, lua/ScenarioFramework.lua, lua/ScenarioPlatoonAI.lua, lua/SimObjectives.lua, lua/aibrain.lua, lua/aibrains/campaign-ai.lua, lua/cinematics.lua, lua/dataInit.lua, lua/platoon.lua, lua/scenariotriggers.lua, lua/sim/ScenarioUtilities.lua, lua/sim/Unit.lua, lua/sim/units/CommandUnit.lua, lua/sim/weapon.lua
Added more annotations and fixed incorrect ones.
=> Improve annotations

changelog/snippets/other.6703.md, engine/User.lua
Proper annotation for `IsObserver()`. According to engine it doesn't take any arguments.
=> Update annotation for `IsObserver()`

changelog/snippets/fix.6700.md, lua/sim/units/FactoryUnit.lua
You can do "OnStopBuild" with an unfinished unit by cancelling a `BuildMobile` order on the ground. This gets the factory locked up since there is no way to remove the unfinished unit.
Destroy unbuilt units in FactoryUnit.OnStopBuild
An unfinished unit no longer remains in the factory after the mobile build order is cancelled.
Copy-paste command for testing:
```
CreateUnitAtMouse('urb0301', 0,    0.00,    0.00, -0.00000)
ForkThread(function() 
WaitTicks(10) 
ConExecute('UI_SelectByCategory +nearest FACTORY CYBRAN TECH3')
import('/lua/ui/game/commandmode.lua').StartCommandMode('build', {name = 'url0303'}) 
end)
```
=> Fix unbuilt units not being destroyed in factories when mobile build orders are cancelled

changelog/snippets/fix.6689.md, lua/ui/game/construction.lua
If a unit in the queue was dragged in front of the same type of unit it would invisibly get stacked, thus getting the unit stuck in that position until it was moved away to an index which doesn't have the same unit type behind it.
Another way to think about it is that the stacking happening while the unit is being dragged desyncs the visual position of the item being dragged (the unit icon) and the actual position being dragged to (the drag indicator shown on the corners of the item).
https://github.com/user-attachments/assets/c5aa7070-be99-4301-b275-61becf6ba314
Disable stacking of same-id queue items while dragging is enabled.
The item being dragged does not get stuck when dragged around. Make sure you enable the draggable build queue game option when testing this. …
=> Fix dragging in build queue getting stuck when two similar items are next to each other

changelog/snippets/fix.6654.md, lua/ui/controls.lua, lua/ui/game/orders.lua, lua/ui/game/tooltip.lua
https://github.com/FAForever/fa/pull/6173 broke the mouse exit behavior because it didn't update all usages of the tooltip, under the incorrect assumption that the create function would return a Control that can be destroyed by the rest of the code like usual.
Update the remaining code for the order button tooltips to use the Tooltip class correctly.
Mouse over order buttons then move the mouse away and the tooltips should disappear. Previously the order button tooltips would only disappear when a new tooltip was created.
=> Fix order button tooltips not disappearing on mouse exit

changelog/snippets/other.6652.md, lua/ui/game/commandmode.lua
Annotate these less often used and weird command modes.
- `ping` mode:
- does not get cancelled by right click like other modes
- passes data from `StartCommandMode` to `EndCommandMode` on left/right click without any modifications
- `buildanchored` mode: restrictive, inaccurate, and unpolished version of `build` mode.
- check the engine for 'ping' string to be a command mode. If any other string is used in `StartCommandMode` the engine will give a warning (`CUIActionHandler::GetLeftMouseButtonAction got invalid commandMode: %s`), which can be used to find where all the strings are checked (func at `0x0081F7B0`).
- log the `IsCancel` param and click around with various command modes.
- Test `buildanchored` mode with multiple/single ACUs building a factory and a T1 pd.
```lua …
```
=> Annotate `ping` and `buildanchored` commandmode

changelog/snippets/fix.6709.md, engine/Core/Blueprints/UnitBlueprint.lua, lua/sim/Unit.lua, lua/sim/units/cybran/CConstructionStructureUnit.lua, units/XRB0104/XRB0104_unit.bp, units/XRB0204/XRB0204_unit.bp
Hives are a unique unit in that they have the `REPAIR` category/capability and an upgrade they can build. This allows them to build their upgrades through UI tricks (issue a repair on a wreck of the upgrade then move the order) or UI scripts:
The engine doesn't distinguish between buildable units and upgradeable units so this has to be fixed in Lua.
- Add `UpgradeOnlyCategory` to `UnitBlueprint.Economy`, which is a table of `UnparsedCategory` just like `BuildableCategory`, and if any categories are found inside the table they are not allowed to be built through `BuildMobile`.
With the following script a level 1 hive cannot build level 2 hives.
```
import("/lua/ui/game/commandmode.lua").StartCommandMode('build', {name = 'xrb0204'})
```
With the following script a level 2 hive cannot build …
=> Fix Hives building their upgrades as a separate unit

changelog/snippets/other.6662.md, lua/sim/Unit.lua, lua/sim/weapon.lua
When turret setup fails it does not give very clear information because the error messages are vague or the stack trace is incorrect due to bone validation itself erroring. Most commonly this occurs when developing mods.
- Refactors turret validation so the issues are clear.
- Change turret setup failure from `error` to `return`.
- Change Unit:ValidateBone so it doesn't error there, and instead just returns `false`.
- Fix ValidateBone not dealing with nil bones, a common case when turrets are setup incorrectly (forgetting a bone).
- Format weapon.lua
Remove bones for a unit's turret setup and check the new warning message.
=> Refactor weapon turret setup validation

changelog/snippets/other.6587.md, engine/Core/Blueprints/UnitBlueprint.lua, engine/Core/Blueprints/WeaponBlueprint.lua, units/UAS0302/UAS0302_Script.lua, units/UAS0302/UAS0302_unit.bp
- Improve descriptions for blueprint fields that say "used by" by adding the unit ID or class name
- Annotate SinkLower ("used by" megalith and monkeylord)
- Remove Omen's non-functional weapon opening animations
- Placed a monkeylord on a mountain peak to see what SinkLower does.
- Imported Omen's weapon animations into blender and noticed that they don't work because there are bones missing from the mesh.
=> Improve comments for unit-specific blueprint fields
